### ISSUE TITLE
ipv6 multicast addresses vanish after iface down/up sequence

### ISSUE THREAD

**Issue by eyuval** [zephyrproject-rtos/zephyr#37028] opened 2021-07-18 14:26 UTC
When performing a iface down/iface up sequence from the net shell,  the allnodes multicast address and the solicited multicast address have vanished at the end.  I am not versed enough in ipv6 and don't know if this the correct behaviour, but it surprised me. I am running zephyr 2.5

Steps to reproduce:
1. net iface 1
2. check there are the allnodes mcast and a solicited mcast address
3. net iface down 1
4. check all mcast addresses have vanished
5. net iface up 1
6. The mcast addresses have not returned to their previous state. They have vanished

**Comment by jukkar** [comment] 2021-07-20 13:58
We leave the multicast group when interface goes down on purpose, after all the device is not able to receive multicast traffic any longer. https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/ip/net_if.c#L4038
You need to re-join the group in you application if the interface comes back up.
Closing as this is not a bug.

**Closed by jukkar** 2021-07-20 13:58 UTC
Labels: bug
