### ISSUE TITLE
pip3 is unable to build wheel for cmsis-pack-manager as part of the requirements.txt on Fedora 37.

### ISSUE THREAD

**Issue by jo5huajohn** [zephyrproject-rtos/zephyr#52308] opened 2022-11-16 19:36 UTC
I'm not sure where to report this since pip says it's not a pip issue, so please let me know if I should report it somewhere else.

**Describe the bug**
Running `pip3 install --user -r ~/zephyrproject/zephyr/scripts/requirements.txt` returns the following error:

>   Building wheel for cmsis-pack-manager (pyproject.toml) ... error
  error: subprocess-exited-with-error
 × Building wheel for cmsis-pack-manager (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [288 lines of output]

**To Reproduce**
1. west init ~/zephyrproject
2. cd ~/zephyrproject
3. west update
4. west zephyr-export
5. pip3 install --user -r ~/zephyrproject/zephyr/scripts/requirements.txt

**Expected behavior**
A pip3 command runs successfully and the repo is ready to use.

**Impact**
Unable to build applications with Zephyr.

**Logs and console output**
```
pip3 install --user -r zephyr/scripts/requirements.txt
Ignoring windows-curses: markers 'sys_platform == "win32"' don't match your environment
Ignoring python-magic-bin: markers 'sys_platform == "win32"' don't match your environment
Collecting pyelftools>=0.27
  Using cached pyelftools-0.29-py2.py3-none-any.whl (174 kB)
Requirement already satisfied: PyYAML>=5.1 in /home/joshua/.local/lib/python3.11/site-packages (from -r zephyr/scripts/requirements-base.txt (line 11)) (6.0)
Requirement already satisfied: pykwalify in /home/joshua/.local/lib/python3.11/site-packages (from -r zephyr/scripts/requirements-base.txt (line 14)) (1.8.0)
Collecting canopen
  Using cached canopen-2.0.0-py3-none-any.whl (59 kB)
Requirement already satisfied: packaging in /usr/lib/python3.11/site-packages (from -r zephyr/scripts/requirements-base.txt (line 18)) (21.3)
Collecting progress
  Using cached progress-1.6-py3-none-any.whl
Collecting psutil
  Using cached psutil-5.9.4-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (280 kB)
Collecting pylink-square
  Using cached pylink_square-0.14.3-py2.py3-none-any.whl (82 kB)
Collecting anytree
  Using cached anytree-2.8.0-py2.py3-none-any.whl (41 kB)
Collecting intelhex
  Using cached intelhex-2.3.0-py2.py3-none-any.whl (50 kB)
Requirement already satisfied: west>=0.10.1 in /home/joshua/.local/lib/python3.11/site-packages (from -r zephyr/scripts/requirements-base.txt (line 30)) (0.14.0)
Requirement already satisfied: colorama in /home/joshua/.local/lib/python3.11/site-packages (from -r zephyr/scripts/requirements-build-test.txt (line 7)) (0.4.6)
Requirement already satisfied: ply>=3.10 in /usr/lib/python3.11/site-packages (from -r zephyr/scripts/requirements-build-test.txt (line 10)) (3.11)
Collecting gcovr>=4.2
  Using cached gcovr-5.2-py2.py3-none-any.whl (81 kB)
Collecting coverage
  Using cached coverage-6.5.0-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (217 kB)
Collecting pytest
  Using cached pytest-7.2.0-py3-none-any.whl (316 kB)
Collecting mypy
  Using cached mypy-0.991-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.1 MB)
Collecting mock>=4.0.1
  Using cached mock-4.0.3-py3-none-any.whl (28 kB)
Collecting breathe>=4.34
  Using cached breathe-4.34.0-py3-none-any.whl (92 kB)
Collecting sphinx!=5.2.0.post0,~=5.0
  Using cached sphinx-5.3.0-py3-none-any.whl (3.2 MB)
Collecting sphinx_rtd_theme~=1.0
  Using cached sphinx_rtd_theme-1.1.1-py2.py3-none-any.whl (2.8 MB)
Collecting sphinx-tabs
  Using cached sphinx_tabs-3.4.1-py3-none-any.whl (10.0 kB)
Collecting sphinxcontrib-svg2pdfconverter
  Using cached sphinxcontrib_svg2pdfconverter-1.2.1-py3-none-any.whl (8.1 kB)
Collecting pygments>=2.9
  Using cached Pygments-2.13.0-py3-none-any.whl (1.1 MB)
Collecting sphinx-notfound-page
  Using cached sphinx_notfound_page-0.8.3-py2.py3-none-any.whl (8.5 kB)
Collecting sphinx-copybutton
  Using cached sphinx_copybutton-0.5.1-py3-none-any.whl (13 kB)
Collecting pyserial
  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)
Collecting pyocd>=0.29.0
  Using cached pyocd-0.34.2-py3-none-any.whl (13.4 MB)
Collecting tabulate
  Using cached tabulate-0.9.0-py3-none-any.whl (35 kB)
Collecting cbor>=1.0.0
  Using cached cbor-1.0.0-py3-none-any.whl
Collecting gitlint
  Using cached gitlint-0.18.0-py2.py3-none-any.whl (22 kB)
Collecting junit2html
  Using cached junit2html-30.1.3-py3-none-any.whl (15 kB)
Collecting clang-format>=1.13x
  Using cached clang_format-15.0.4-py2.py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.5 MB)
Collecting lpc_checksum
  Using cached lpc_checksum-3.0.0-py3-none-any.whl (5.1 kB)
Requirement already satisfied: Pillow in /usr/lib64/python3.11/site-packages (from -r zephyr/scripts/requirements-extras.txt (line 19)) (9.2.0)
Collecting imgtool>=1.9
  Using cached imgtool-1.9.0-py3-none-any.whl (27 kB)
Collecting grpcio-tools
  Using cached grpcio_tools-1.50.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
Collecting PyGithub
  Using cached PyGithub-1.57-py3-none-any.whl (297 kB)
Collecting graphviz
  Using cached graphviz-0.20.1-py3-none-any.whl (47 kB)
Collecting python-magic
  Using cached python_magic-0.4.27-py2.py3-none-any.whl (13 kB)
Requirement already satisfied: lxml in /usr/lib64/python3.11/site-packages (from -r zephyr/scripts/requirements-compliance.txt (line 6)) (4.9.1)
Collecting junitparser>=2
  Using cached junitparser-2.8.0-py2.py3-none-any.whl (11 kB)
Collecting pylint
  Using cached pylint-2.15.5-py3-none-any.whl (508 kB)
Requirement already satisfied: docopt>=0.6.2 in /home/joshua/.local/lib/python3.11/site-packages (from pykwalify->-r zephyr/scripts/requirements-base.txt (line 14)) (0.6.2)
Requirement already satisfied: python-dateutil>=2.8.0 in /usr/lib/python3.11/site-packages (from pykwalify->-r zephyr/scripts/requirements-base.txt (line 14)) (2.8.2)
Requirement already satisfied: ruamel.yaml>=0.16.0 in /home/joshua/.local/lib/python3.11/site-packages (from pykwalify->-r zephyr/scripts/requirements-base.txt (line 14)) (0.17.21)
Collecting python-can>=3.0.0
  Using cached python_can-4.0.0-py3-none-any.whl (235 kB)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/lib/python3.11/site-packages (from packaging->-r zephyr/scripts/requirements-base.txt (line 18)) (3.0.9)
Collecting future
  Using cached future-0.18.2-py3-none-any.whl
Requirement already satisfied: six in /usr/lib/python3.11/site-packages (from pylink-square->-r zephyr/scripts/requirements-base.txt (line 21)) (1.16.0)
Requirement already satisfied: setuptools in /usr/lib/python3.11/site-packages (from west>=0.10.1->-r zephyr/scripts/requirements-base.txt (line 30)) (62.6.0)
Collecting jinja2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting attrs>=19.2.0
  Using cached attrs-22.1.0-py2.py3-none-any.whl (58 kB)
Collecting iniconfig
  Using cached iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting pluggy<2.0,>=0.12
  Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting typing-extensions>=3.10
  Using cached typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting mypy-extensions>=0.4.3
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting docutils>=0.12
  Using cached docutils-0.19-py3-none-any.whl (570 kB)
Collecting sphinxcontrib-applehelp
  Using cached sphinxcontrib_applehelp-1.0.2-py2.py3-none-any.whl (121 kB)
Collecting sphinxcontrib-devhelp
  Using cached sphinxcontrib_devhelp-1.0.2-py2.py3-none-any.whl (84 kB)
Collecting sphinxcontrib-jsmath
  Using cached sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl (5.1 kB)
Collecting sphinxcontrib-htmlhelp>=2.0.0
  Using cached sphinxcontrib_htmlhelp-2.0.0-py2.py3-none-any.whl (100 kB)
Collecting sphinxcontrib-serializinghtml>=1.1.5
  Using cached sphinxcontrib_serializinghtml-1.1.5-py2.py3-none-any.whl (94 kB)
Collecting sphinxcontrib-qthelp
  Using cached sphinxcontrib_qthelp-1.0.3-py2.py3-none-any.whl (90 kB)
Collecting snowballstemmer>=2.0
  Using cached snowballstemmer-2.2.0-py2.py3-none-any.whl (93 kB)
Requirement already satisfied: babel>=2.9 in /usr/lib/python3.11/site-packages (from sphinx!=5.2.0.post0,~=5.0->-r zephyr/scripts/requirements-doc.txt (line 4)) (2.10.3)
Collecting alabaster<0.8,>=0.7
  Using cached alabaster-0.7.12-py2.py3-none-any.whl (14 kB)
Collecting imagesize>=1.3
  Using cached imagesize-1.4.1-py2.py3-none-any.whl (8.8 kB)
Requirement already satisfied: requests>=2.5.0 in /usr/lib/python3.11/site-packages (from sphinx!=5.2.0.post0,~=5.0->-r zephyr/scripts/requirements-doc.txt (line 4)) (2.28.1)
Collecting docutils>=0.12
  Using cached docutils-0.17.1-py2.py3-none-any.whl (575 kB)
Collecting sphinx-tabs
  Using cached sphinx_tabs-3.4.0-py3-none-any.whl (10.0 kB)
Collecting jinja2
  Using cached Jinja2-3.0.3-py3-none-any.whl (133 kB)
Collecting capstone<5.0,>=4.0
  Using cached capstone-4.0.2-py2.py3-none-manylinux1_x86_64.whl (2.1 MB)
Collecting cmsis-pack-manager<1.0,>=0.4.0
  Using cached cmsis-pack-manager-0.4.0.tar.gz (43 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting intervaltree<4.0,>=3.0.2
  Using cached intervaltree-3.1.0-py2.py3-none-any.whl
Collecting libusb-package<2.0,>=1.0
  Using cached libusb_package-1.0.26.0-cp311-cp311-linux_x86_64.whl
Collecting natsort<9.0,>=8.0.0
  Using cached natsort-8.2.0-py3-none-any.whl (37 kB)
Collecting prettytable<4.0,>=2.0
  Using cached prettytable-3.5.0-py3-none-any.whl (26 kB)
Collecting pyusb<2.0,>=1.2.1
  Using cached pyusb-1.2.1-py3-none-any.whl (58 kB)
Collecting gitlint-core[trusted-deps]==0.18.0
  Using cached gitlint_core-0.18.0-py2.py3-none-any.whl (70 kB)
Requirement already satisfied: Click>=8 in /usr/lib/python3.11/site-packages (from gitlint-core[trusted-deps]==0.18.0->gitlint->-r zephyr/scripts/requirements-extras.txt (line 7)) (8.1.3)
Collecting arrow>=1
  Using cached arrow-1.2.3-py3-none-any.whl (66 kB)
Collecting sh>=1.13.0
  Using cached sh-1.14.3.tar.gz (62 kB)
  Preparing metadata (setup.py) ... done
Collecting Click>=8
  Using cached click-8.0.3-py3-none-any.whl (97 kB)
Collecting arrow>=1
  Using cached arrow-1.2.1-py3-none-any.whl (63 kB)
Collecting sh>=1.13.0
  Using cached sh-1.14.2-py2.py3-none-any.whl (40 kB)
Collecting cbor2
  Using cached cbor2-5.4.3-cp311-cp311-linux_x86_64.whl
Collecting cryptography>=2.4.2
  Using cached cryptography-38.0.3-cp36-abi3-manylinux_2_28_x86_64.whl (4.2 MB)
Collecting protobuf<5.0dev,>=4.21.6
  Using cached protobuf-4.21.9-cp37-abi3-manylinux2014_x86_64.whl (408 kB)
Collecting grpcio>=1.50.0
  Using cached grpcio-1.50.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.7 MB)
Collecting deprecated
  Using cached Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Collecting pyjwt>=2.4.0
  Using cached PyJWT-2.6.0-py3-none-any.whl (20 kB)
Collecting pynacl>=1.4.0
  Using cached PyNaCl-1.5.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (856 kB)
Collecting dill>=0.2
  Using cached dill-0.3.6-py3-none-any.whl (110 kB)
Collecting platformdirs>=2.2.0
  Using cached platformdirs-2.5.4-py3-none-any.whl (14 kB)
Collecting astroid<=2.14.0-dev0,>=2.12.12
  Using cached astroid-2.12.12-py3-none-any.whl (264 kB)
Collecting isort<6,>=4.2.5
  Using cached isort-5.10.1-py3-none-any.whl (103 kB)
Collecting mccabe<0.8,>=0.6
  Using cached mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)
Collecting tomlkit>=0.10.1
  Using cached tomlkit-0.11.6-py3-none-any.whl (35 kB)
Collecting lazy-object-proxy>=1.4.0
  Using cached lazy_object_proxy-1.8.0-cp311-cp311-linux_x86_64.whl
Collecting wrapt<2,>=1.14
  Using cached wrapt-1.14.1-cp311-cp311-linux_x86_64.whl
Requirement already satisfied: pytz>=2015.7 in /usr/lib/python3.11/site-packages (from babel>=2.9->sphinx!=5.2.0.post0,~=5.0->-r zephyr/scripts/requirements-doc.txt (line 4)) (2022.6)
Collecting appdirs<2.0,>=1.4
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting milksnake<1.0,>=0.1.5
  Using cached milksnake-0.1.5-py2.py3-none-any.whl (9.6 kB)
Requirement already satisfied: cffi>=1.12 in /usr/lib64/python3.11/site-packages (from cryptography>=2.4.2->imgtool>=1.9->-r zephyr/scripts/requirements-extras.txt (line 22)) (1.15.1)
Collecting sortedcontainers<3.0,>=2.0
  Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.1-py3-none-any.whl
Collecting wcwidth
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting msgpack~=1.0.0
  Using cached msgpack-1.0.4-cp311-cp311-linux_x86_64.whl
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/lib/python3.11/site-packages (from requests>=2.5.0->sphinx!=5.2.0.post0,~=5.0->-r zephyr/scripts/requirements-doc.txt (line 4)) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.11/site-packages (from requests>=2.5.0->sphinx!=5.2.0.post0,~=5.0->-r zephyr/scripts/requirements-doc.txt (line 4)) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.11/site-packages (from requests>=2.5.0->sphinx!=5.2.0.post0,~=5.0->-r zephyr/scripts/requirements-doc.txt (line 4)) (1.26.12)
Requirement already satisfied: pycparser in /usr/lib/python3.11/site-packages (from cffi>=1.12->cryptography>=2.4.2->imgtool>=1.9->-r zephyr/scripts/requirements-extras.txt (line 22)) (2.20)
Building wheels for collected packages: cmsis-pack-manager
  Building wheel for cmsis-pack-manager (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for cmsis-pack-manager (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [288 lines of output]
      /usr/lib/python3.11/site-packages/setuptools/config/setupcfg.py:463: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running bdist_wheel
      running build
      running build_py
      creating build/lib
      creating build/lib/cmsis_pack_manager
      copying cmsis_pack_manager/pack_manager.py -> build/lib/cmsis_pack_manager
      copying cmsis_pack_manager/_version.py -> build/lib/cmsis_pack_manager
      copying cmsis_pack_manager/_native__ffi.py -> build/lib/cmsis_pack_manager
      copying cmsis_pack_manager/_native.py -> build/lib/cmsis_pack_manager
      copying cmsis_pack_manager/__init__.py -> build/lib/cmsis_pack_manager
          Updating crates.io index
         Compiling libc v0.2.137
         Compiling autocfg v1.1.0
         Compiling cfg-if v1.0.0
         Compiling cfg-if v0.1.10
         Compiling log v0.4.17
         Compiling futures v0.1.31
         Compiling byteorder v1.4.3
         Compiling semver-parser v0.7.0
         Compiling either v1.8.0
         Compiling maybe-uninit v2.0.0
         Compiling lazy_static v1.4.0
         Compiling cc v1.0.76
         Compiling scopeguard v1.1.0
         Compiling proc-macro2 v1.0.47
         Compiling unicode-ident v1.0.5
         Compiling fnv v1.0.7
         Compiling quote v1.0.21
         Compiling syn v1.0.103
         Compiling tinyvec_macros v0.1.0
         Compiling rand_core v0.4.2
         Compiling lock_api v0.3.4
         Compiling unicode-bidi v0.3.8
         Compiling tinyvec v1.6.0
         Compiling semver v0.9.0
         Compiling autocfg v0.1.8
         Compiling spin v0.5.2
         Compiling memchr v2.5.0
         Compiling version_check v0.9.4
         Compiling rustc_version v0.2.3
         Compiling once_cell v1.16.0
         Compiling crossbeam-utils v0.7.2
         Compiling slab v0.4.7
         Compiling smallvec v0.6.14
         Compiling memoffset v0.5.6
         Compiling crossbeam-epoch v0.8.2
         Compiling untrusted v0.7.1
         Compiling matches v0.1.9
         Compiling parking_lot_core v0.6.2
         Compiling parking_lot v0.9.0
         Compiling rand_core v0.3.1
         Compiling serde_derive v1.0.147
         Compiling itoa v0.4.8
         Compiling unicase v2.6.0
         Compiling indexmap v1.9.1
         Compiling serde v1.0.147
         Compiling adler v1.0.2
         Compiling rand_chacha v0.1.1
         Compiling unicode-normalization v0.1.22
         Compiling rand_pcg v0.1.2
         Compiling gimli v0.26.2
         Compiling miniz_oxide v0.5.4
         Compiling iovec v0.1.4
         Compiling num_cpus v1.14.0
         Compiling bytes v0.4.12
         Compiling net2 v0.2.38
         Compiling time v0.1.44
         Compiling tokio-sync v0.1.8
         Compiling failure_derive v0.1.8
         Compiling percent-encoding v2.2.0
         Compiling ring v0.16.20
         Compiling tokio-executor v0.1.10
         Compiling mio v0.6.23
         Compiling tokio-io v0.1.13
         Compiling crossbeam-queue v0.2.3
         Compiling http v0.1.21
         Compiling idna v0.1.5
         Compiling tokio-current-thread v0.1.7
         Compiling tokio-timer v0.2.13
         Compiling backtrace v0.3.66
         Compiling hashbrown v0.12.3
         Compiling httparse v1.8.0
         Compiling crossbeam-deque v0.7.4
         Compiling tokio-codec v0.1.2
         Compiling tokio-threadpool v0.1.18
         Compiling percent-encoding v1.0.1
         Compiling unicode-xid v0.2.4
         Compiling tokio-buf v0.1.1
         Compiling string v0.2.1
         Compiling idna v0.3.0
         Compiling form_urlencoded v1.1.0
         Compiling tokio-reactor v0.1.12
         Compiling mio-uds v0.6.8
         Compiling url v1.7.2
         Compiling object v0.29.0
         Compiling hyper v0.12.36
         Compiling rand v0.6.5
         Compiling num-traits v0.2.15
         Compiling base64 v0.10.1
         Compiling tokio-uds v0.2.7
         Compiling tokio-fs v0.1.7
         Compiling tokio-udp v0.1.6
         Compiling tokio-tcp v0.1.4
         Compiling crc32fast v1.3.2
         Compiling try-lock v0.2.3
         Compiling tokio v0.1.22
         Compiling rustc-demangle v0.1.21
         Compiling serde_json v1.0.87
         Compiling want v0.2.0
         Compiling url v2.3.1
         Compiling mime_guess v2.0.4
         Compiling idna v0.2.3
         Compiling h2 v0.1.26
         Compiling http-body v0.1.0
         Compiling futures-cpupool v0.1.8
         Compiling rand_os v0.1.3
         Compiling sct v0.6.1
         Compiling webpki v0.21.4
         Compiling addr2line v0.17.0
         Compiling rand_isaac v0.1.1
         Compiling rand_xorshift v0.1.1
         Compiling rand_hc v0.1.0
         Compiling num-integer v0.1.45
         Compiling rand_jitter v0.1.4
         Compiling encoding_rs v0.8.31
         Compiling ryu v1.0.11
         Compiling rustls v0.16.0
         Compiling itoa v1.0.4
         Compiling webpki-roots v0.17.0
         Compiling publicsuffix v1.5.6
         Compiling ct-logs v0.6.0
         Compiling cookie v0.12.0
         Compiling try_from v0.3.2
         Compiling dtoa v0.4.8
         Compiling mime v0.3.16
         Compiling crossbeam-utils v0.8.12
         Compiling flate2 v1.0.24
         Compiling quick-xml v0.17.2
         Compiling dirs-sys v0.3.7
         Compiling iana-time-zone v0.1.53
         Compiling scoped-tls v0.1.2
         Compiling tokio-core v0.1.18
         Compiling minidom v0.12.0
         Compiling dirs v4.0.0
         Compiling termcolor v1.1.3
         Compiling unicode-width v0.1.10
         Compiling uuid v0.7.4
         Compiling textwrap v0.11.0
         Compiling xdg v2.4.1
         Compiling atty v0.2.14
         Compiling crossbeam-channel v0.5.6
         Compiling vec_map v0.8.2
         Compiling bitflags v1.3.2
         Compiling chrono v0.4.23
         Compiling ansi_term v0.12.1
         Compiling strsim v0.8.0
         Compiling app_dirs v1.2.1
         Compiling synstructure v0.12.6
         Compiling clap v2.34.0
         Compiling pbr v1.0.4
         Compiling tokio-rustls v0.10.3
         Compiling simplelog v0.8.0
         Compiling ctor v0.1.26
         Compiling hyper-rustls v0.17.1
         Compiling failure v0.1.8
         Compiling serde_urlencoded v0.5.5
         Compiling cookie_store v0.7.0
         Compiling reqwest v0.9.24
         Compiling cmsis-pack v0.3.0 (/tmp/pip-install-c1qkro4b/cmsis-pack-manager_a3eb0efd558f4809933816beffb1a4aa/rust/cmsis-pack)
      warning: fields `name`, `description` and `doc` are never read
         --> cmsis-pack/src/pdsc/component.rs:160:5
          |
      159 | pub struct Bundle {
          |            ------ fields in this struct
      160 |     name: String,
          |     ^^^^
      ...
      164 |     description: String,
          |     ^^^^^^^^^^^
      165 |     doc: String,
          |     ^^^
          |
          = note: `#[warn(dead_code)]` on by default
          = note: `Bundle` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
      
         Compiling cmsis-cli v0.3.0 (/tmp/pip-install-c1qkro4b/cmsis-pack-manager_a3eb0efd558f4809933816beffb1a4aa/rust/cmsis-cli)
      warning: `cmsis-pack` (lib) generated 1 warning
         Compiling cmsis-cffi v0.3.0 (/tmp/pip-install-c1qkro4b/cmsis-pack-manager_a3eb0efd558f4809933816beffb1a4aa/rust/cmsis-cffi)
      warning: unused return value of `std::mem::replace` that must be used
         --> cmsis-cffi/src/pack_index.rs:145:13
          |
      145 |             mem::replace(boxed.borrow_mut(), next_state);
          |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          |
          = note: `#[warn(unused_must_use)]` on by default
          = note: if you don't need the old value, you can just assign the new value directly
      
      warning: unused return value of `std::mem::replace` that must be used
         --> cmsis-cffi/src/pack_index.rs:191:13
          |
      191 |             mem::replace(boxed.borrow_mut(), next_state);
          |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          |
          = note: if you don't need the old value, you can just assign the new value directly
      
      warning: `cmsis-cffi` (lib) generated 2 warnings
          Finished release [optimized] target(s) in 44.92s
      copying dylib libcmsis_cffi.so
      Traceback (most recent call last):
        File "/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/setuptools/build_meta.py", line 244, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
          self.run_setup()
        File "/usr/lib/python3.11/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 66, in <module>
          setup(
        File "/usr/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 177, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
          dist.run_commands()
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.11/site-packages/setuptools/command/build.py", line 24, in run
          super().run()
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-r1q_p4_3/overlay/lib/python3.11/site-packages/milksnake/setuptools_ext.py", line 88, in run
          func(base_path=base_path, inplace=False)
        File "/tmp/pip-build-env-r1q_p4_3/overlay/lib/python3.11/site-packages/milksnake/setuptools_ext.py", line 276, in build_cffi
          ffi = make_ffi()
                ^^^^^^^^^^
        File "/tmp/pip-build-env-r1q_p4_3/overlay/lib/python3.11/site-packages/milksnake/setuptools_ext.py", line 262, in make_ffi
          from milksnake.ffi import make_ffi
        File "/tmp/pip-build-env-r1q_p4_3/overlay/lib/python3.11/site-packages/milksnake/ffi.py", line 8, in <module>
          _directive_re = re.compile(r'^\s*#.*?$(?m)')
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib64/python3.11/re/__init__.py", line 227, in compile
          return _compile(pattern, flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib64/python3.11/re/__init__.py", line 294, in _compile
          p = _compiler.compile(pattern, flags)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib64/python3.11/re/_compiler.py", line 743, in compile
          p = _parser.parse(p, flags)
              ^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib64/python3.11/re/_parser.py", line 980, in parse
          p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib64/python3.11/re/_parser.py", line 455, in _parse_sub
          itemsappend(_parse(source, state, verbose, nested + 1,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib64/python3.11/re/_parser.py", line 841, in _parse
          raise source.error('global flags not at the start '
      re.error: global flags not at the start of the expression at position 9
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cmsis-pack-manager
Failed to build cmsis-pack-manager
ERROR: Could not build wheels for cmsis-pack-manager, which is required to install pyproject.toml-based projects
```

**Environment (please complete the following information):**
 - OS: Linux, Fedora 37.
 - Toolchain: NA
 - Commit SHA or Version used: 3.2.99

**Additional context**
Add any other context that could be relevant to your issue, such as pin setting,
target configuration, ...

**Comment by nordicjm** [comment] 2022-11-17 09:02
Duplicate of https://github.com/zephyrproject-rtos/zephyr/issues/51951

**Closed by nordicjm** 2022-11-17 09:02 UTC
Labels: bug
