### ISSUE TITLE
samples/net/sockets small bugs

### ISSUE THREAD

**Issue by maksimdrachov** [zephyrproject-rtos/zephyr#36659] opened 2021-07-01 08:01 UTC
**Describe the bug**
Some examples contain some small bugs.

_**samples/net/sockets/pocket
samples/net/sockets/tcp**_
![Screenshot 2021-07-01 at 09 56 51](https://user-images.githubusercontent.com/39975120/124087840-b1cb5b80-da52-11eb-9201-6d01281ddcff.png)
```
CONFIG_ENTROPY_GENERATOR=y
CONFIG_TEST_RANDOM_GENERATOR=y
```
needs to be added to prj.conf for it to work

_**samples/net/sockets/echo_client**_
Doesn't work, can't figure out how to fix.
![image](https://user-images.githubusercontent.com/39975120/124087015-e68ae300-da51-11eb-978b-579b756d30c9.png)

**To Reproduce**
1. cd ~/zephyrproject/zephyr/samples/net/sockets/NAME-EXAMPLE
2. west build -b nucleo_f756zg
3. See error

**Expected behavior**
A successful build

**Impact**
Annoyance, but can be easily fixed in the case of the first two.
Don't have a lot of experience with Zephyr, so need someone else to take a look at the third one.

**Logs and console output**

**Environment (please complete the following information):**
 - OS: MacOS
 - Toolchain Zephyr
 - Commit SHA or Version used
```
VERSION_MAJOR = 2
VERSION_MINOR = 6
PATCHLEVEL = 99
VERSION_TWEAK = 0
EXTRAVERSION =
```

**Comment by nashif** [comment] 2021-07-06 17:23
Can you please submit a PR to fix those small issues?

**Comment by rlubos** [comment] 2021-07-12 09:32
I'm not able to reproduce the third failure (the `echo_client` one), perhaps you need to run a clean build?

**Comment by rlubos** [comment] 2021-07-26 15:01
#36860 with a fix for the first two problems was merged. As the third one doesn't seem to be reproducible, I'm closing the issue. Please reopen if it still persists somehow (but as mentioned earlier it likely just needs a clean build).

**Closed by rlubos** 2021-07-26 15:01 UTC
Labels: area: Networking, bug, priority: low
