### ISSUE TITLE
[Coverity CID :186842] Memory - illegal accesses in /drivers/interrupt_controller/plic.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#8699] opened 2018-07-03 05:44 UTC
Static code scan issues seen in File: /drivers/interrupt_controller/plic.c
 Category: Memory - illegal accesses
 Function: plic_irq_handler
 Component: Drivers
 CID: 186842
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by agross-linaro** [comment] 2018-07-05 20:53
It seems to me like there are some missing #idfefs around the irq +=  RISCV_MAX_GENERIC_IRQ; keying off of CONFIG_RISCV_HAS_PLIC.  However there might be issues with the PLIC_IRQS count.  With coverity thinking this only has 32 IRQS, it appears the failing platform is the one without the HAS_PLIC configured.

**Comment by nashif** [comment] 2018-07-31 17:08
@kgugala can you please have a look?

**Comment by nashif** [comment] 2018-08-14 17:12
@kgugala ping

**Comment by kgugala** [comment] 2018-08-29 09:20
@nashif sorry for stalling this, I was on holidays. I'll take a look on that.

**Comment by ceolin** [comment] 2018-08-31 20:35
guys, this is not a bug. The invalid memory access that coverity is complaining will never happen because ``_irq_spurious(NULL);`` will be called first and this function never returns

```
...
_NanoFatalErrorHandler(_NANO_ERR_SPURIOUS_INT, &_default_esf);
```

Question, should I add a return after this so any static analyzer will complain or we can just close this issue (here and in coverity)

**Comment by nashif** [comment] 2018-08-31 20:38
lets close.. mark it as invalid in coverity please.

**Closed by nashif** 2018-08-31 20:38 UTC
Labels: Coverity, area: Drivers, bug, priority: medium
