### ISSUE TITLE
Multiple tests are failing on sam_e70_xplained once the cache is enabled

### ISSUE THREAD

**Issue by spoorthik** [zephyrproject-rtos/zephyr#9689] opened 2018-08-28 09:45 UTC
Due to commit c090776 multiple tests are failing on sam_e70_xplained.

**Comment by spoorthik** [comment] 2018-08-28 09:47
Refer: https://github.com/zephyrproject-rtos/zephyr/issues/9684, https://github.com/zephyrproject-rtos/zephyr/issues/9683, https://github.com/zephyrproject-rtos/zephyr/issues/9682, https://github.com/zephyrproject-rtos/zephyr/issues/9680, https://github.com/zephyrproject-rtos/zephyr/issues/9677 for execution logs.

**Comment by tgorochowik** [comment] 2018-08-28 10:30
That probably won't be very helpful, but if the original MPU/cache patches from #8185 are applied to the  `zephyr-v1.12.0` tag - the tests pass (and the cache works) (I remembered it to work and I just verified that).

So probably one of the recent MPU changes is causing all of this, not enabling the caches itself (but of course enabling them does trigger this bug).

**Comment by nashif** [comment] 2018-08-28 18:05
merged now

**Closed by nashif** 2018-08-28 18:05 UTC
Labels: bug, priority: high

**Comment by aurel32** [comment] 2018-11-02 15:33
I have tried to re-enable the caches on the current git code, and I am not able to reproduce all those issues. @spoorthik, can you try to re-apply the patch enabling the caches to check it is also fixed on your side?

**Comment by aurel32** [comment] 2018-11-02 15:45
I forgot to say I **do** reproduce the issue with the commit just before the revert.

**Comment by aurel32** [comment] 2018-11-03 21:56
@spoorthik, thanks for the test. I ran exactly the same thing, but I don't have the issue. I believe you are still interested to the cache enabled by default on the SAM E70 platform. I have therefore just opened the issue #11069 to discuss that, that is probably better than here.
