### ISSUE TITLE
Bluetooth: host: central connection context leak

### ISSUE THREAD

**Issue by joerchan** [zephyrproject-rtos/zephyr#50427] opened 2022-09-20 14:18 UTC
**Describe the bug**
I've been seeing this issue with the zephyr host. I am using NCS (2c8ef25e7) and the two samples for direction finding.
The connection context for the central part is left in an incomplete state when the connection is timed out.

**To Reproduce**
 `west build -b nrf52833dk_nrf52833 ../zephyr/samples/bluetooth/direction_finding_peripheral -d peripheral -- -DCONFIG_BT_LL_SW_SPLIT=y`
and
`west build -b nrf52833dk_nrf52833 ../zephyr/samples/bluetooth/direction_finding_central -d central -- -DCONFIG_BT_LL_SW_SPLIT=y`
 
Flashing both samples, and resetting the peripheral side using the RESET button on the DK the central eventually runs into a problem where it is unable to create the connection.

```
[01:13:22.249,298] <wrn> bt_conn: Found valid connection in disconnected state
[01:13:22.566,467] <wrn> b[DEVICE]: 17:5D:F5:1E:99:7D (random), AD evt type 3, AD data len 31, RSSI -82
[DEVICE]: D8:9A:D6:93:B8:0E (random), AD evt type 0, AD data len 8, RSSI -30
[AD]: 1 data_len 1
[AD]: 39 data_len 3
Create conn failed (err -22)
```

**Impact**
Connection context is leaking, creating a new connection is no longer possible when this happens.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.13.1
 - Commit SHA or Version used: NCS (2c8ef25e7)

**Comment by carlescufi** [comment] 2022-09-22 11:29
Downgrading to Low because it is not easily reproducible.

**Comment by kruithofa** [comment] 2022-11-16 12:12
Closing since it is unreproducible

**Comment by jusleht** [comment] 2023-01-16 07:34
Reproduced this with nrf5340 with 3.2.0, confirm, renders connection creation impossible.

**Comment by jusleht** [comment] 2023-01-16 08:25
We have old peripheral, Suunto hr belt, with which issue is reproduced 100%. We run our host app on top of nrf sdk 2.2.0. Unfortunately I cant share the code (corporate owned), but 
[suunto_hr_belt.zip](https://github.com/zephyrproject-rtos/zephyr/files/10423803/suunto_hr_belt.zip)
attached is the ellisys capture of the scenario. What seems to happen is we get after disconnect an extra measurement which likely causes the issue in host.

**Comment by jusleht** [comment] 2023-01-16 08:47
I forgot to mention, we use the softdevice controller in this case.

**Comment by jori-nordic** [comment] 2023-01-16 09:16
> I forgot to mention, we use the softdevice controller in this case.

That's interesting, could you try using the Zephyr LL to see if it still reproduces the issue?

Would it be possible to share the stack logs after enabling 
```
CONFIG_BT_DEBUG_LOG=y
CONFIG_BT_DEBUG_CONN=y
```

**Comment by jusleht** [comment] 2023-01-16 11:12
[rtt_capture.txt](https://github.com/zephyrproject-rtos/zephyr/files/10425176/rtt_capture.txt)

Here is debug_log & debug_conn trace with the softdevice. I'll try to see if I can make a build with LL_SPLIT, although it might not even be possible because we use mpsl etc on netcore that need to be ripped out

**Comment by jori-nordic** [comment] 2023-01-18 09:56
Turns out it was a missing unref in the application code. Closing ticket.

**Closed by jori-nordic** 2023-01-18 09:56 UTC
Labels: bug, priority: low, area: Bluetooth, area: Bluetooth Host

**Comment by joerchan** [comment] 2023-01-18 10:24
In @jusleht case maybe? I was using the zephyr samples.
But it is OK to close anyway, as I can't reproduce this anymore.
