### ISSUE TITLE
sanitycheck failures on lpcxpresso54114_m4: Error: Aborting due to non-whitelisted Kconfig warning

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#11859] opened 2018-12-05 01:26 UTC
**Describe the bug**
I'm seeing build failures on some cases for lpcxpresso54114_m4

**To Reproduce**
$ sanitycheck -i

**Expected behavior**
All tests pass

**Impact**
This may be breaking our CI builds

**Screenshots or console output**
```
lpcxpresso54114_m4        samples/subsys/ipc/ipm_mcux/test                   FAILED: build_error
--------------sanity-out/lpcxpresso54114_m4/samples/subsys/ipc/ipm_mcux/test/build.log--------------
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.7.1", minimum required is "3.4") 
-- Selected BOARD lpcxpresso54114_m4
Zephyr version: 1.13.99
Parsing Kconfig tree in /projects/zephyr/Kconfig
Loading /projects/zephyr/boards/arm/lpcxpresso54114/lpcxpresso54114_m4_defconfig as base
Merging /projects/zephyr/samples/subsys/ipc/ipm_mcux/prj.conf
Merging /projects/zephyr/sanity-out/lpcxpresso54114_m4/samples/subsys/ipc/ipm_mcux/test/overlay.conf
CMake Warning at /projects/zephyr/cmake/toolchain.cmake:33 (message):
  ZEPHYR_GCC_VARIANT is deprecated, please use ZEPHYR_TOOLCHAIN_VARIANT
  instead
Call Stack (most recent call first):
  /projects/zephyr/cmake/app/boilerplate.cmake:260 (include)
  CMakeLists.txt:9 (include)


-- Loading /projects/zephyr/boards/arm/lpcxpresso54114/lpcxpresso54114_m4.dts as base
-- Overlaying /projects/zephyr/dts/common/common.dts
lpcxpresso54114_m4.dts_compiled: Warning (simple_bus_reg): /soc/gpio@0: simple-bus unit address format error, expected "4008c000"
lpcxpresso54114_m4.dts_compiled: Warning (simple_bus_reg): /soc/gpio@1: simple-bus unit address format error, expected "4008c000"
lpcxpresso54114_m4.dts_compiled: Warning (unique_unit_address): /soc/flash@0: duplicate unit-address (also used in node /soc/gpio@0)
/projects/zephyr/scripts/dts/extract_dts_includes.py:496: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  and isinstance(merge_dct[k], collections.Mapping)):
extract_dts_includes.py: Merge of 'category': 'required'  overwrites 'optional'.
-- Cache files will be written to: /home/apboie/.cache/zephyr
-- The C compiler identification is GNU 6.2.0
-- The CXX compiler identification is GNU 6.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /opt/zephyr-sdk/sysroots/x86_64-pokysdk-linux/usr/bin/arm-zephyr-eabi/arm-zephyr-eabi-gcc
-- Performing Test toolchain_is_ok
-- Performing Test toolchain_is_ok - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /projects/zephyr/sanity-out/lpcxpresso54114_m4/samples/subsys/ipc/ipm_mcux/test
make[1]: Entering directory '/projects/zephyr/sanity-out/lpcxpresso54114_m4/samples/subsys/ipc/ipm_mcux/test'
make[2]: Entering directory '/projects/zephyr/sanity-out/lpcxpresso54114_m4/samples/subsys/ipc/ipm_mcux/test'
make[3]: Entering directory '/projects/zephyr/sanity-out/lpcxpresso54114_m4/samples/subsys/ipc/ipm_mcux/test'
Scanning dependencies of target kobj_types_h_target
make[3]: Leaving directory '/projects/zephyr/sanity-out/lpcxpresso54114_m4/samples/subsys/ipc/ipm_mcux/test'
make[3]: Entering directory '/projects/zephyr/sanity-out/lpcxpresso54114_m4/samples/subsys/ipc/ipm_mcux/test'
[  0%] Generating include/generated/kobj-types-enum.h, include/generated/otype-to-str.h
make[3]: Leaving directory '/projects/zephyr/sanity-out/lpcxpresso54114_m4/samples/subsys/ipc/ipm_mcux/test'
make[3]: Entering directory '/projects/zephyr/sanity-out/lpcxpresso54114_m4/samples/subsys/ipc/ipm_mcux/test'
[  0%] Built target kobj_types_h_target
Scanning dependencies of target syscall_macros_h_target
make[3]: Leaving directory '/projects/zephyr/sanity-out/lpcxpresso54114_m4/samples/subsys/ipc/ipm_mcux/test'
make[3]: Entering directory '/projects/zephyr/sanity-out/lpcxpresso54114_m4/samples/subsys/ipc/ipm_mcux/test'
make[3]: Entering directory '/projects/zephyr/sanity-out/lpcxpresso54114_m4/samples/subsys/ipc/ipm_mcux/test'
[  1%] Generating include/generated/syscall_macros.h
Scanning dependencies of target syscall_list_h_target
make[3]: Leaving directory '/projects/zephyr/sanity-out/lpcxpresso54114_m4/samples/subsys/ipc/ipm_mcux/test'
make[3]: Entering directory '/projects/zephyr/sanity-out/lpcxpresso54114_m4/samples/subsys/ipc/ipm_mcux/test'
[  2%] Generating misc/generated/syscalls.json
make[3]: Leaving directory '/projects/zephyr/sanity-out/lpcxpresso54114_m4/samples/subsys/ipc/ipm_mcux/test'
[  3%] Generating include/generated/syscall_dispatch.c, include/generated/syscall_list.h
make[3]: Leaving directory '/projects/zephyr/sanity-out/lpcxpresso54114_m4/samples/subsys/ipc/ipm_mcux/test'
make[3]: Entering directory '/projects/zephyr/sanity-out/lpcxpresso54114_m4/samples/subsys/ipc/ipm_mcux/test'
[  3%] Built target syscall_macros_h_target
[  4%] Built target syscall_list_h_target
Scanning dependencies of target driver_validation_h_target
make[3]: Leaving directory '/projects/zephyr/sanity-out/lpcxpresso54114_m4/samples/subsys/ipc/ipm_mcux/test'
make[3]: Entering directory '/projects/zephyr/sanity-out/lpcxpresso54114_m4/samples/subsys/ipc/ipm_mcux/test'
[  5%] Generating include/generated/driver-validation.h
make[3]: Leaving directory '/projects/zephyr/sanity-out/lpcxpresso54114_m4/samples/subsys/ipc/ipm_mcux/test'
[  5%] Built target driver_validation_h_target
make[3]: Entering directory '/projects/zephyr/sanity-out/lpcxpresso54114_m4/samples/subsys/ipc/ipm_mcux/test'
Scanning dependencies of target ipm_mcux_remote
make[3]: Leaving directory '/projects/zephyr/sanity-out/lpcxpresso54114_m4/samples/subsys/ipc/ipm_mcux/test'
make[3]: Entering directory '/projects/zephyr/sanity-out/lpcxpresso54114_m4/samples/subsys/ipc/ipm_mcux/test'
[  5%] Creating directories for 'ipm_mcux_remote'
[  6%] No download step for 'ipm_mcux_remote'
[  7%] No patch step for 'ipm_mcux_remote'
[  8%] No update step for 'ipm_mcux_remote'
[  9%] Performing configure step for 'ipm_mcux_remote'
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.7.1", minimum required is "3.4") 
-- Selected BOARD qemu_x86
Zephyr version: 1.13.99

warning: IPM_MCUX (defined at drivers/ipm/Kconfig:21) was assigned the value 'y' but got the value
'n'. You can check symbol information (including dependencies) in the 'menuconfig' interface (see
the Application Development Primer section of the manual), or in the Kconfig reference at
http://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_IPM_MCUX.html (which is updated
regularly from the master branch). See the 'Setting configuration values' section of the Board
Porting Guide as well.

warning: PRINTK (defined at subsys/debug/Kconfig:105) was assigned the value 'n' but got the value
'y'. You can check symbol information (including dependencies) in the 'menuconfig' interface (see
the Application Development Primer section of the manual), or in the Kconfig reference at
http://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_PRINTK.html (which is updated
regularly from the master branch). See the 'Setting configuration values' section of the Board
Porting Guide as well.

/projects/zephyr/samples/subsys/ipc/ipm_mcux/remote/prj.conf:5: warning: attempt to assign the value "n" to the undefined symbol PLATFORM_SPECIFIC_INIT
Parsing Kconfig tree in /projects/zephyr/Kconfig
Loading /projects/zephyr/boards/x86/qemu_x86/qemu_x86_defconfig as base
Merging /projects/zephyr/samples/subsys/ipc/ipm_mcux/remote/prj.conf

Error: Aborting due to non-whitelisted Kconfig warning
'/projects/zephyr/samples/subsys/ipc/ipm_mcux/remote/prj.conf:5: warning: attempt to assign the
value "n" to the undefined symbol PLATFORM_SPECIFIC_INIT'. Note: If this warning doesn't point to an
actual problem, you can add it to the whitelist at the top of
/projects/zephyr/scripts/kconfig/kconfig.py.

CMake Error at /projects/zephyr/cmake/kconfig.cmake:159 (message):
  command failed with return code: 1
Call Stack (most recent call first):
  /projects/zephyr/cmake/app/boilerplate.cmake:259 (include)
  CMakeLists.txt:8 (include)


-- Configuring incomplete, errors occurred!
make[3]: *** [CMakeFiles/ipm_mcux_remote.dir/build.make:106: ipm_mcux_remote-prefix/src/ipm_mcux_remote-stamp/ipm_mcux_remote-configure] Error 1

```

**Comment by galak** [comment] 2018-12-08 14:34
Is there some other setting you've got in the env or something.  I'm not able to reproduce this.

**Comment by galak** [comment] 2018-12-11 16:16
ping

**Comment by andrewboie** [comment] 2019-01-03 22:59
> Is there some other setting you've got in the env or something. I'm not able to reproduce this.

Nothing special on my end that I'm aware of.
I can trivially reproduce this with "sanitycheck -i"

**Comment by andrewboie** [comment] 2019-01-03 23:03
Actually, I have BOARD=qemu_x86 in my environment.
I notice:

```
Loading /projects/zephyr/boards/x86/qemu_x86/qemu_x86_defconfig as base
Merging /projects/zephyr/samples/subsys/ipc/ipm_mcux/remote/prj.conf
```

That doesn't look right.
Having BOARD set in environment has never interfered with sanitycheck before, any idea why it is breaking these two tests?

**Comment by galak** [comment] 2019-01-15 20:07
This is most likely because we set BOARD in `samples/subsys/ipc/openamp/CMakeLists.txt`  

We have:

`set(BOARD lpcxpresso54114_m4)`

**Comment by galak** [comment] 2019-01-30 19:34
Going to close this as it seems like a usage error.  Feel free to re-open.

**Closed by galak** 2019-01-30 19:34 UTC
Labels: bug, priority: low
