### ISSUE TITLE
Compiling tests/drivers/can/api shows warning

### ISSUE THREAD

**Issue by talih0** [zephyrproject-rtos/zephyr#70390] opened 2024-03-18 19:11 UTC
**Describe the bug**
When compiling CAN api test tests/drivers/can/api there's a warning message:

![image](https://github.com/zephyrproject-rtos/zephyr/assets/17433307/b14d79c2-cf0f-4071-af82-2dd3c0b63ec8)

The issue only appears to happen when CONFIG_CAN_STATS=y

**To Reproduce**
1. west build -p -b mimxrt1064_evk tests/drivers/can/api/

**Expected behavior**
No warning messages.

**Environment (please complete the following information):**
 - Linux
 - Toolchain Zephyr-SDK 0.16.5
 - Commit SHA d921659d6a4ffa9d47896c23f9292c238c183d19 (origin/main)

**Comment by henrikbrixandersen** [comment] 2024-03-18 21:24
I am unable to reproduce the above on current `main` (3fd545b05b45ec62a67b426ce809c804c86b8593):

```
$ west build -p -b mimxrt1064_evk tests/drivers/can/api/
-- west build: making build dir /home/brix/Projects/zephyrproject/zephyr/build pristine
-- west build: generating a build system
Loading Zephyr default modules (Zephyr base).
-- Application: /home/brix/Projects/zephyrproject/zephyr/tests/drivers/can/api
-- CMake version: 3.28.1
-- Found Python3: /home/brix/Projects/zephyrproject/venv/bin/python3 (found suitable version "3.10.12", minimum required is "3.8") found components: Interpreter 
-- Cache files will be written to: /home/brix/.cache/zephyr
-- Zephyr version: 3.6.99 (/home/brix/Projects/zephyrproject/zephyr)
-- Found west (found suitable version "1.2.0", minimum required is "0.14.0")
-- Board: mimxrt1064_evk, identifier: mimxrt1064
-- ZEPHYR_TOOLCHAIN_VARIANT not set, trying to locate Zephyr SDK
-- Found host-tools: zephyr 0.16.5 (/opt/zephyr-sdk/0.16.5)
-- Found toolchain: zephyr 0.16.5 (/opt/zephyr-sdk/0.16.5)
-- Found Dtc: /opt/zephyr-sdk/0.16.5/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.6.0", minimum required is "1.4.6") 
-- Found BOARD.dts: /home/brix/Projects/zephyrproject/zephyr/boards/nxp/mimxrt1064_evk/mimxrt1064_evk.dts
-- Generated zephyr.dts: /home/brix/Projects/zephyrproject/zephyr/build/zephyr/zephyr.dts
-- Generated devicetree_generated.h: /home/brix/Projects/zephyrproject/zephyr/build/zephyr/include/generated/devicetree_generated.h
-- Including generated dts.cmake file: /home/brix/Projects/zephyrproject/zephyr/build/zephyr/dts.cmake
Parsing /home/brix/Projects/zephyrproject/zephyr/Kconfig
Loaded configuration '/home/brix/Projects/zephyrproject/zephyr/boards/nxp/mimxrt1064_evk/mimxrt1064_evk_defconfig'
Merged configuration '/home/brix/Projects/zephyrproject/zephyr/tests/drivers/can/api/prj.conf'
Configuration saved to '/home/brix/Projects/zephyrproject/zephyr/build/zephyr/.config'
Kconfig header saved to '/home/brix/Projects/zephyrproject/zephyr/build/zephyr/include/generated/autoconf.h'
-- Found GnuLd: /opt/zephyr-sdk/0.16.5/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd (found version "2.38") 
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /opt/zephyr-sdk/0.16.5/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc
Load components for MIMXRT1064:
driver_common component is included.
driver_reset component is included.
device_CMSIS component is included.
CMSIS_Include_core_cm component is included.
device_system component is included.
driver_flexcan component is included.
driver_lpuart component is included.
driver_igpio component is included.
driver_cache_armv7_m7 component is included.
-- Using ccache: /usr/bin/ccache
-- Configuring done (9.8s)
-- Generating done (0.3s)
-- Build files have been written to: /home/brix/Projects/zephyrproject/zephyr/build
-- west build: building application
[  1%] Generating misc/generated/syscalls.json, misc/generated/struct_tags.json
[  2%] Built target parse_syscalls_target
[  3%] Generating include/generated/kobj-types-enum.h, include/generated/otype-to-str.h, include/generated/otype-to-size.h
[  3%] Built target kobj_types_h_target
[  4%] Generating include/generated/syscall_dispatch.c, include/generated/syscall_list.h
[  4%] Built target syscall_list_h_target
[  4%] Generating include/generated/driver-validation.h
[  4%] Built target driver_validation_h_target
[  4%] Building C object zephyr/CMakeFiles/offsets.dir/arch/arm/core/offsets/offsets.c.obj
[  4%] Built target offsets
[  5%] Generating include/generated/offsets.h
[  5%] Built target offsets_h
[  5%] Generating include/generated/version.h
-- Zephyr version: 3.6.99 (/home/brix/Projects/zephyrproject/zephyr), build: v3.6.0-1180-g3fd545b05b45
[  5%] Built target version_h
[  5%] Built target zephyr_generated_headers
[  6%] Building C object CMakeFiles/app.dir/src/common.c.obj
[  6%] Building C object CMakeFiles/app.dir/src/classic.c.obj
[  7%] Building C object CMakeFiles/app.dir/src/transceiver.c.obj
[  7%] Building C object CMakeFiles/app.dir/src/utilities.c.obj
[  8%] Building C object CMakeFiles/app.dir/src/canfd.c.obj
[  9%] Building C object CMakeFiles/app.dir/src/stats.c.obj
[  9%] Linking C static library app/libapp.a
[  9%] Built target app
[ 10%] Building C object zephyr/CMakeFiles/zephyr.dir/lib/heap/heap.c.obj
[ 10%] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/cbprintf_packaged.c.obj
[ 11%] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/printk.c.obj
[ 13%] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/sem.c.obj
[ 13%] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/thread_entry.c.obj
[ 14%] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/cbprintf_complete.c.obj
[ 14%] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/assert.c.obj
[ 15%] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/mutex.c.obj
[ 15%] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/user_work.c.obj
[ 16%] Building C object zephyr/CMakeFiles/zephyr.dir/lib/utils/dec.c.obj
[ 16%] Building C object zephyr/CMakeFiles/zephyr.dir/lib/utils/hex.c.obj
[ 17%] Building C object zephyr/CMakeFiles/zephyr.dir/lib/utils/rb.c.obj
[ 17%] Building C object zephyr/CMakeFiles/zephyr.dir/lib/utils/timeutil.c.obj
[ 18%] Building C object zephyr/CMakeFiles/zephyr.dir/lib/utils/bitarray.c.obj
[ 18%] Building C object zephyr/CMakeFiles/zephyr.dir/misc/generated/configs.c.obj
[ 19%] Building C object zephyr/CMakeFiles/zephyr.dir/soc/nxp/imxrt/imxrt10xx/soc.c.obj
[ 20%] Building C object zephyr/CMakeFiles/zephyr.dir/soc/nxp/imxrt/mpu_regions.c.obj
[ 20%] Building C object zephyr/CMakeFiles/zephyr.dir/subsys/logging/log_minimal.c.obj
[ 21%] Building C object zephyr/CMakeFiles/zephyr.dir/subsys/mem_mgmt/mem_attr.c.obj
[ 21%] Building C object zephyr/CMakeFiles/zephyr.dir/subsys/stats/stats.c.obj
[ 22%] Building C object zephyr/CMakeFiles/zephyr.dir/subsys/tracing/tracing_none.c.obj
[ 22%] Linking C static library libzephyr.a
[ 22%] Built target zephyr
[ 22%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/main_weak.c.obj
[ 23%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/banner.c.obj
[ 23%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/busy_wait.c.obj
[ 25%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/device.c.obj
[ 25%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/errno.c.obj
[ 26%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/fatal.c.obj
[ 27%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/init.c.obj
[ 27%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/kheap.c.obj
[ 28%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/mem_slab.c.obj
[ 28%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/float.c.obj
[ 29%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/thread.c.obj
[ 29%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/version.c.obj
[ 30%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/priority_queues.c.obj
[ 30%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/sched.c.obj
[ 31%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/idle.c.obj
[ 31%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/mailbox.c.obj
[ 32%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/msg_q.c.obj
[ 32%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/mutex.c.obj
[ 33%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/queue.c.obj
[ 33%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/sem.c.obj
[ 34%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/stack.c.obj
[ 35%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/system_work_q.c.obj
[ 35%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/work.c.obj
[ 36%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/condvar.c.obj
[ 36%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/spinlock_validate.c.obj
[ 38%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/xip.c.obj
[ 38%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/timeout.c.obj
[ 39%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/timer.c.obj
[ 39%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/mempool.c.obj
[ 40%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/futex.c.obj
[ 40%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/mem_domain.c.obj
[ 41%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/userspace_handler.c.obj
[ 41%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/userspace.c.obj
[ 42%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/dynamic_disabled.c.obj
[ 43%] Linking C static library libkernel.a
[ 43%] Built target kernel
[ 43%] Building C object zephyr/arch/common/CMakeFiles/isr_tables.dir/isr_tables.c.obj
[ 44%] Linking C static library libisr_tables.a
[ 44%] Built target isr_tables
[ 45%] Building C object zephyr/arch/common/CMakeFiles/arch__common.dir/sw_isr_common.c.obj
[ 45%] Linking C static library libarch__common.a
[ 45%] Built target arch__common
[ 46%] Building C object zephyr/arch/arch/arm/core/CMakeFiles/arch__arm__core.dir/fatal.c.obj
[ 46%] Building C object zephyr/arch/arch/arm/core/CMakeFiles/arch__arm__core.dir/nmi.c.obj
[ 47%] Building ASM object zephyr/arch/arch/arm/core/CMakeFiles/arch__arm__core.dir/nmi_on_reset.S.obj
[ 47%] Building C object zephyr/arch/arch/arm/core/CMakeFiles/arch__arm__core.dir/tls.c.obj
[ 48%] Building ASM object zephyr/arch/arch/arm/core/CMakeFiles/arch__arm__core.dir/userspace.S.obj
[ 48%] Linking C static library libarch__arm__core.a
[ 48%] Built target arch__arm__core
[ 50%] Building ASM object zephyr/arch/arch/arm/core/cortex_m/CMakeFiles/arch__arm__core__cortex_m.dir/exc_exit.S.obj
[ 50%] Building C object zephyr/arch/arch/arm/core/cortex_m/CMakeFiles/arch__arm__core__cortex_m.dir/fault.c.obj
[ 51%] Building ASM object zephyr/arch/arch/arm/core/cortex_m/CMakeFiles/arch__arm__core__cortex_m.dir/fault_s.S.obj
[ 52%] Building C object zephyr/arch/arch/arm/core/cortex_m/CMakeFiles/arch__arm__core__cortex_m.dir/fpu.c.obj
[ 52%] Building ASM object zephyr/arch/arch/arm/core/cortex_m/CMakeFiles/arch__arm__core__cortex_m.dir/reset.S.obj
[ 53%] Building C object zephyr/arch/arch/arm/core/cortex_m/CMakeFiles/arch__arm__core__cortex_m.dir/scb.c.obj
[ 53%] Building C object zephyr/arch/arch/arm/core/cortex_m/CMakeFiles/arch__arm__core__cortex_m.dir/thread_abort.c.obj
[ 54%] Building ASM object zephyr/arch/arch/arm/core/cortex_m/CMakeFiles/arch__arm__core__cortex_m.dir/vector_table.S.obj
[ 54%] Building C object zephyr/arch/arch/arm/core/cortex_m/CMakeFiles/arch__arm__core__cortex_m.dir/swap.c.obj
[ 55%] Building ASM object zephyr/arch/arch/arm/core/cortex_m/CMakeFiles/arch__arm__core__cortex_m.dir/swap_helper.S.obj
[ 55%] Building C object zephyr/arch/arch/arm/core/cortex_m/CMakeFiles/arch__arm__core__cortex_m.dir/irq_manage.c.obj
[ 56%] Building C object zephyr/arch/arch/arm/core/cortex_m/CMakeFiles/arch__arm__core__cortex_m.dir/prep_c.c.obj
[ 56%] Building C object zephyr/arch/arch/arm/core/cortex_m/CMakeFiles/arch__arm__core__cortex_m.dir/thread.c.obj
[ 57%] Building ASM object zephyr/arch/arch/arm/core/cortex_m/CMakeFiles/arch__arm__core__cortex_m.dir/cpu_idle.S.obj
[ 57%] Building C object zephyr/arch/arch/arm/core/cortex_m/CMakeFiles/arch__arm__core__cortex_m.dir/irq_init.c.obj
[ 58%] Building ASM object zephyr/arch/arch/arm/core/cortex_m/CMakeFiles/arch__arm__core__cortex_m.dir/isr_wrapper.S.obj
[ 59%] Building ASM object zephyr/arch/arch/arm/core/cortex_m/CMakeFiles/arch__arm__core__cortex_m.dir/__aeabi_read_tp.S.obj
[ 59%] Building C object zephyr/arch/arch/arm/core/cortex_m/CMakeFiles/arch__arm__core__cortex_m.dir/cache.c.obj
[ 60%] Linking C static library libarch__arm__core__cortex_m.a
[ 60%] Built target arch__arm__core__cortex_m
[ 60%] Building C object zephyr/arch/arch/arm/core/mpu/CMakeFiles/arch__arm__core__mpu.dir/arm_core_mpu.c.obj
[ 61%] Building C object zephyr/arch/arch/arm/core/mpu/CMakeFiles/arch__arm__core__mpu.dir/arm_mpu.c.obj
[ 61%] Linking C static library libarch__arm__core__mpu.a
[ 61%] Built target arch__arm__core__mpu
[ 63%] Building C object zephyr/lib/libc/picolibc/CMakeFiles/lib__libc__picolibc.dir/libc-hooks.c.obj
[ 63%] Linking C static library liblib__libc__picolibc.a
[ 63%] Built target lib__libc__picolibc
[ 63%] Building C object zephyr/lib/libc/common/CMakeFiles/lib__libc__common.dir/source/stdlib/abort.c.obj
[ 64%] Building C object zephyr/lib/libc/common/CMakeFiles/lib__libc__common.dir/source/stdlib/malloc.c.obj
[ 64%] Linking C static library liblib__libc__common.a
[ 64%] Built target lib__libc__common
[ 64%] Building C object zephyr/boards/nxp/mimxrt1064_evk/CMakeFiles/boards__nxp__mimxrt1064_evk.dir/home/brix/Projects/zephyrproject/modules/hal/nxp/mcux/mcux-sdk/boards/evkmimxrt1064/xip/evkmimxrt1064_flexspi_nor_config.c.obj
[ 65%] Building C object zephyr/boards/nxp/mimxrt1064_evk/CMakeFiles/boards__nxp__mimxrt1064_evk.dir/home/brix/Projects/zephyrproject/modules/hal/nxp/mcux/mcux-sdk/boards/evkmimxrt1064/dcd.c.obj
[ 65%] Linking C static library libboards__nxp__mimxrt1064_evk.a
[ 65%] Built target boards__nxp__mimxrt1064_evk
[ 65%] Building C object zephyr/subsys/testsuite/ztest/CMakeFiles/subsys__testsuite__ztest.dir/src/ztest.c.obj
[ 66%] Building C object zephyr/subsys/testsuite/ztest/CMakeFiles/subsys__testsuite__ztest.dir/src/ztest_error_hook.c.obj
[ 66%] Building C object zephyr/subsys/testsuite/ztest/CMakeFiles/subsys__testsuite__ztest.dir/src/ztest_rules.c.obj
[ 67%] Building C object zephyr/subsys/testsuite/ztest/CMakeFiles/subsys__testsuite__ztest.dir/src/ztest_defaults.c.obj
[ 67%] Linking C static library libsubsys__testsuite__ztest.a
[ 67%] Built target subsys__testsuite__ztest
[ 68%] Building C object zephyr/drivers/cache/CMakeFiles/drivers__cache.dir/cache_handlers.c.obj
[ 68%] Linking C static library libdrivers__cache.a
[ 68%] Built target drivers__cache
[ 69%] Building C object zephyr/drivers/can/CMakeFiles/drivers__can.dir/can_common.c.obj
[ 69%] Building C object zephyr/drivers/can/CMakeFiles/drivers__can.dir/can_mcux_flexcan.c.obj
[ 70%] Building C object zephyr/drivers/can/CMakeFiles/drivers__can.dir/can_handlers.c.obj
[ 70%] Linking C static library libdrivers__can.a
[ 70%] Built target drivers__can
[ 71%] Building C object zephyr/drivers/clock_control/CMakeFiles/drivers__clock_control.dir/clock_control_mcux_ccm.c.obj
[ 71%] Linking C static library libdrivers__clock_control.a
[ 71%] Built target drivers__clock_control
[ 72%] Building C object zephyr/drivers/console/CMakeFiles/drivers__console.dir/uart_console.c.obj
[ 73%] Linking C static library libdrivers__console.a
[ 73%] Built target drivers__console
[ 73%] Building C object zephyr/drivers/gpio/CMakeFiles/drivers__gpio.dir/gpio_mcux_igpio.c.obj
[ 75%] Building C object zephyr/drivers/gpio/CMakeFiles/drivers__gpio.dir/gpio_handlers.c.obj
[ 75%] Linking C static library libdrivers__gpio.a
[ 75%] Built target drivers__gpio
[ 76%] Building C object zephyr/drivers/memc/CMakeFiles/drivers__memc.dir/memc_nxp_flexram.c.obj
[ 76%] Linking C static library libdrivers__memc.a
[ 76%] Built target drivers__memc
[ 77%] Building C object zephyr/drivers/pinctrl/CMakeFiles/drivers__pinctrl.dir/common.c.obj
[ 77%] Building C object zephyr/drivers/pinctrl/CMakeFiles/drivers__pinctrl.dir/pinctrl_imx.c.obj
[ 78%] Linking C static library libdrivers__pinctrl.a
[ 78%] Built target drivers__pinctrl
[ 78%] Building C object zephyr/drivers/serial/CMakeFiles/drivers__serial.dir/uart_mcux_lpuart.c.obj
[ 79%] Building C object zephyr/drivers/serial/CMakeFiles/drivers__serial.dir/uart_handlers.c.obj
[ 80%] Linking C static library libdrivers__serial.a
[ 80%] Built target drivers__serial
[ 80%] Building C object zephyr/drivers/timer/CMakeFiles/drivers__timer.dir/sys_clock_init.c.obj
[ 81%] Building C object zephyr/drivers/timer/CMakeFiles/drivers__timer.dir/cortex_m_systick.c.obj
[ 81%] Linking C static library libdrivers__timer.a
[ 81%] Built target drivers__timer
[ 81%] Building C object modules/hal_nxp/hal_nxp/CMakeFiles/..__modules__hal__nxp.dir/mcux/mcux-sdk/devices/MIMXRT1064/drivers/fsl_clock.c.obj
[ 82%] Building C object modules/hal_nxp/hal_nxp/CMakeFiles/..__modules__hal__nxp.dir/mcux/mcux-sdk/drivers/common/fsl_common.c.obj
[ 82%] Building C object modules/hal_nxp/hal_nxp/CMakeFiles/..__modules__hal__nxp.dir/mcux/mcux-sdk/drivers/common/fsl_common_arm.c.obj
[ 83%] Building C object modules/hal_nxp/hal_nxp/CMakeFiles/..__modules__hal__nxp.dir/mcux/mcux-sdk/devices/MIMXRT1064/system_MIMXRT1064.c.obj
[ 83%] Building C object modules/hal_nxp/hal_nxp/CMakeFiles/..__modules__hal__nxp.dir/mcux/mcux-sdk/drivers/flexcan/fsl_flexcan.c.obj
[ 84%] Building C object modules/hal_nxp/hal_nxp/CMakeFiles/..__modules__hal__nxp.dir/mcux/mcux-sdk/drivers/lpuart/fsl_lpuart.c.obj
[ 84%] Building C object modules/hal_nxp/hal_nxp/CMakeFiles/..__modules__hal__nxp.dir/mcux/mcux-sdk/drivers/igpio/fsl_gpio.c.obj
[ 85%] Building C object modules/hal_nxp/hal_nxp/CMakeFiles/..__modules__hal__nxp.dir/mcux/mcux-sdk/drivers/cache/armv7-m7/fsl_cache.c.obj
[ 85%] Linking C static library lib..__modules__hal__nxp.a
[ 85%] Built target ..__modules__hal__nxp
[ 85%] Generating app_smem_unaligned linker section
[ 85%] Built target app_smem_unaligned_linker
[ 85%] Generating linker_zephyr_pre0.cmd
[ 85%] Built target linker_zephyr_pre0_script
[ 86%] Building C object zephyr/CMakeFiles/zephyr_pre0.dir/misc/empty_file.c.obj
[ 86%] Linking C executable zephyr_pre0.elf
Logical command for additional byproducts on target: zephyr_pre0
[ 86%] Built target zephyr_pre0
[ 86%] Generating kobject_prebuilt_hash.gperf
[ 86%] Built target kobj_prebuilt_hash_list
[ 86%] Generating kobject_prebuilt_hash_preprocessed.c
[ 86%] Built target kobj_prebuilt_hash_output_src_pre
[ 88%] Generating kobject_prebuilt_hash.c
[ 88%] Building C object zephyr/CMakeFiles/kobj_prebuilt_hash_output_lib.dir/kobject_prebuilt_hash.c.obj
[ 88%] Built target kobj_prebuilt_hash_output_lib
[ 89%] Generating include/generated/linker-kobject-prebuilt-data.h
[ 89%] Built target kobject_linker
[ 90%] Generating app_smem_aligned linker section
[ 90%] Built target app_smem_aligned_linker
[ 91%] Generating linker_zephyr_pre1.cmd
[ 91%] Built target linker_zephyr_prebuilt_script_target
[ 92%] Building C object zephyr/CMakeFiles/zephyr_pre1.dir/misc/empty_file.c.obj
[ 93%] Linking C executable zephyr_pre1.elf
Logical command for additional byproducts on target: zephyr_pre1
[ 93%] Built target zephyr_pre1
[ 93%] Generating kobject_hash.gperf
[ 93%] Built target kobj_hash_list
[ 94%] Generating kobject_hash_preprocessed.c
[ 94%] Built target kobj_hash_output_src_pre
[ 95%] Generating kobject_hash.c
[ 95%] Building C object zephyr/CMakeFiles/kobj_hash_output_lib.dir/kobject_hash.c.obj
[ 95%] Built target kobj_hash_output_lib
[ 96%] Generating kobject_hash_renamed.o
[ 96%] Built target kobj_hash_output_obj_renamed
[ 97%] Generating linker.cmd
[ 97%] Built target linker_zephyr_final_script_target
[ 98%] Generating isr_tables.c, isr_tables_vt.ld, isr_tables_swi.ld
[ 98%] Building C object zephyr/CMakeFiles/zephyr_final.dir/misc/empty_file.c.obj
[100%] Building C object zephyr/CMakeFiles/zephyr_final.dir/isr_tables.c.obj
[100%] Linking C executable zephyr.elf
Memory region         Used Size  Region Size  %age Used
           FLASH:      126296 B         4 MB      3.01%
             RAM:       15672 B        32 MB      0.05%
            ITCM:          0 GB       128 KB      0.00%
            DTCM:          0 GB       128 KB      0.00%
           OCRAM:          0 GB       256 KB      0.00%
          OCRAM2:          0 GB       512 KB      0.00%
        IDT_LIST:          0 GB        32 KB      0.00%
Generating files from /home/brix/Projects/zephyrproject/zephyr/build/zephyr/zephyr.elf for board: mimxrt1064_evk
[100%] Built target zephyr_final
[100%] Built target check_init_priorities
```

Do you have any custom changes, Kconfig options, environment variables, ... set?

**Comment by talih0** [comment] 2024-03-18 21:51
I had a default Kconfig option in my .west/config file. It should be reproducible with:

west build -p -b mimxrt1064_evk tests/drivers/can/api/ -- -DCONFIG_COMPILER_SAVE_TEMPS=y

**Comment by henrikbrixandersen** [comment] 2024-03-18 22:03
> I had a default Kconfig option in my .west/config file. It should be reproducible with:
> 
> 
> 
> west build -p -b mimxrt1064_evk tests/drivers/can/api/ -- -DCONFIG_COMPILER_SAVE_TEMPS=y

Okay. The issue is likely of the same nature as what was fixed in https://github.com/zephyrproject-rtos/zephyr/pull/54308, then.

**Comment by henrikbrixandersen** [comment] 2024-03-19 14:30
Same problem exists in `include/zephyr/drivers/i2c.h` when `CONFIG_I2C_STATS` is enabled.

**Comment by henrikbrixandersen** [comment] 2024-03-19 14:50
@talih0 Please try the proposed fix in https://github.com/zephyrproject-rtos/zephyr/pull/70439

**Closed** 2024-04-05 10:20 UTC
Labels: bug, priority: low, area: CAN
