### ISSUE TITLE
fatfs update to latest upstream version

### ISSUE THREAD

**Issue by lowlander** [zephyrproject-rtos/zephyr#28096] opened 2020-09-06 14:31 UTC
Zephyr currently uses version R0.12b (September 4, 2016) but upstream ( http://elm-chan.org/fsw/ff/00index_e.html ) already has R0.14 (October 14, 2019) plus some additional patches.

**Comment by nashif** [comment] 2021-05-28 20:55
duplicate of #34557

**Closed by nashif** 2021-05-28 20:55 UTC
Labels: Enhancement, area: File System
