### ISSUE TITLE
up_squared: tests/kernel/timer/timer_api failed.

### ISSUE THREAD

**Issue by chen-png** [zephyrproject-rtos/zephyr#32688] opened 2021-02-26 02:10 UTC
**To Reproduce**
1. west build -b up_squared -p auto tests/kernel/timer/timer_api
2. west flash ~/up_squared.sh
3. see error

**Logs and console output**
Booting Zephyr OS build zephyr-v2.5.0-487-g0ba94379381f
Running test suite timer_api

START - test_time_conversions
PASS - test_time_conversions

START - test_timer_duration_period
PASS - test_timer_duration_period

START - test_timer_restart
PASS - test_timer_restart

START - test_timer_period_0
PASS - test_timer_period_0

START - test_timer_expirefn_null
PASS - test_timer_expirefn_null
......
START - test_timer_user_data
PASS - test_timer_user_data

START - test_timer_remaining
PASS - test_timer_remaining

**START - test_timeout_abs
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/timer/timer_api/src/main.c:725: test_timeout_abs: (cap_ticks + rem_ticks + 1 == exp_ticks) || (rem_ticks + cap2_ticks + 1 == exp_ticks) || (INEXACT_MS_CONVERT && (cap_ticks + rem_ticks == exp_ticks)) || (INEXACT_MS_CONVERT && (rem_ticks + cap2_ticks == exp_ticks)) is false
FAIL - test_timeout_abs**

START - test_sleep_abs
PASS - test_sleep_abs

Test suite timer_api failed.

PROJECT EXECUTION FAILED

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: zephyr-sdk-0.12.2
 - Commit ID: 0ba94379381f

**Comment by nashif** [comment] 2021-02-26 14:14
duplicate of #32697

**Closed by nashif** 2021-02-26 14:14 UTC
Labels: area: Tests, bug
