### ISSUE TITLE
samples/arch/smp/pktqueue does not compile for esp32

### ISSUE THREAD

**Issue by Rhvarrier** [zephyrproject-rtos/zephyr#55833] opened 2023-03-15 20:21 UTC
**Describe the bug**
samples/arch/smp/pktqueue does not compile for esp32.
I get the following error 

**To Reproduce**
1. Start python virtual environment for west and source the needed environment variable
2. Run `west build -b esp32 zephyr/samples/arch/smp/pktqueue -p`

**Expected behavior**
The sample should compile without error

**Impact**
I cannot try SMP support on ESP32 even if it seems supported

**Logs and console output**
`xtensa-espressif_esp32_zephyr-elf/bin/ld.bfd: zephyr/zephyr_pre0.elf section `bss' will not fit in region `dram0_0_seg'
xtensa-espressif_esp32_zephyr-elf/bin/../lib/gcc/xtensa-espressif_esp32_zephyr-elf/12.1.0/../../../../xtensa-espressif_esp32_zephyr-elf/bin/ld.bfd: DRAM segment data does not fit.
xtensa-espressif_esp32_zephyr-elf/bin/../lib/gcc/xtensa-espressif_esp32_zephyr-elf/12.1.0/../../../../xtensa-espressif_esp32_zephyr-elf/bin/ld.bfd: section noinit VMA [000000003ffe5230,000000003fff722f] overlaps section bss VMA [000000003ffb0310,000000003ffffcc7]
xtensa-espressif_esp32_zephyr-elf/bin/../lib/gcc/xtensa-espressif_esp32_zephyr-elf/12.1.0/../../../../xtensa-espressif_esp32_zephyr-elf/bin/ld.bfd: region dram0_0_seg overflowed by 146120 bytes
`

**Additional context**
I'm getting the same error when compiling zephyr/samples/arch/smp/pi. However I'm able to build and flash hello-world and blinky samples

**Comment by nordicjm** [comment] 2023-03-16 08:21
The application is too big to fit to flash, it specifically has `platform_exclude: esp32`, therefore this is not a bug, closing.

**Closed by nordicjm** 2023-03-16 08:21 UTC
Labels: bug
