### ISSUE TITLE
sam_e70b_xplained: Mutlitple tests in tests/kernel/mem_protect are failing. 

### ISSUE THREAD

**Issue by yerabolu** [zephyrproject-rtos/zephyr#42705] opened 2022-02-10 19:29 UTC
**Describe the bug**
kernel.memory_protection.kernel.memory_protection.alloc_kobjects
kernel.memory_protection.kernel.memory_protection.thread_alloc_out_of_idx
kernel.memory_protection.kernel.memory_protection.kobj_create_out_of_memory
kernel.memory_protection.kernel.memory_protection.kobject_perm_error
kernel.memory_protection.kernel.memory_protection.kobject_free_error
kernel.memory_protection.kernel.memory_protection.all_kobjects_str

**To Reproduce**
1. twister -p sam_e70b_xplained --device-testing --device-serial /dev/ttyACM0 -T tests/kernel/mem_protect/ 
2. see error

**Logs and console output**
```
*** Booting Zephyr OS build v3.0.0-rc2-22-g32c4bd3b684a  ***
Running test suite memory_protection_test_suite
===================================================================
START - test_permission_inheritance
E: ***** MPU FAULT *****
E:   Data Access Violation
E:   MMFAR Address: 0x20401454
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000001
E: r3/a4:  0x20401454 r12/ip:  0x0040ca8f r14/lr:  0x004006ad
E:  xpsr:  0x21000000
E: Faulting instruction address (r15/pc): 0x0040072a
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x20400c10 (unknown)
Caught system error -- reason 0 1
fatal error expected as part of test case
PASS - test_permission_inheritance in 0.40 seconds
===================================================================
START - test_inherit_resource_pool
PASS - test_inherit_resource_pool in 0.1 seconds
===================================================================
START - test_mem_domain_setup
PASS - test_mem_domain_setup in 0.1 seconds
===================================================================
START - test_mem_domain_valid_access
PASS - test_mem_domain_valid_access in 0.1 seconds
===================================================================
START - test_mem_domain_invalid_access
E: ***** MPU FAULT *****
E:   Data Access Violation
E:   MMFAR Address: 0x204008e0
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x0000000a r12/ip:  0x0040cf61 r14/lr:  0x0040cf6d
E:  xpsr:  0x61000000
E: Faulting instruction address (r15/pc): 0x004020ac
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x20401098 (child_thread)
Caught system error -- reason 0 1
fatal error expected as part of test case
E: ***** MPU FAULT *****
E:   Data Access Violation
E:   MMFAR Address: 0x204008c0
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x0040cf61 r14/lr:  0x0040cf6d
E:  xpsr:  0x61000000
E: Faulting instruction address (r15/pc): 0x00402110
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x20401098 (child_thread)
Caught system error -- reason 0 1
fatal error expected as part of test case
PASS - test_mem_domain_invalid_access in 0.81 seconds
===================================================================
START - test_mem_domain_no_writes_to_ro
E: ***** MPU FAULT *****
E:   Data Access Violation
E:   MMFAR Address: 0x204008c0
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x000000c8
E: r3/a4:  0x204008c0 r12/ip:  0x0040cf61 r14/lr:  0x0040cf6d
E:  xpsr:  0x21000000
E: Faulting instruction address (r15/pc): 0x00401f68
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x20401098 (child_thread)
Caught system error -- reason 0 1
fatal error expected as part of test case
PASS - test_mem_domain_no_writes_to_ro in 0.41 seconds
===================================================================
START - test_mem_domain_remove_add_partition
E: ***** MPU FAULT *****
E:   Data Access Violation
E:   MMFAR Address: 0x204008e0
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x0000000a r12/ip:  0x0040cf61 r14/lr:  0x0040cf6d
E:  xpsr:  0x61000000
E: Faulting instruction address (r15/pc): 0x004020ac
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x20401098 (child_thread)
Caught system error -- reason 0 1
fatal error expected as part of test case
PASS - test_mem_domain_remove_add_partition in 0.41 seconds
===================================================================
START - test_mem_domain_api_supervisor_only
E: ***** MPU FAULT *****
E:   Data Access Violation
E:   MMFAR Address: 0x20401abf
E: r0/a1:  0x20401574  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x20401abf r12/ip:  0x0040cf61 r14/lr:  0x00402015
E:  xpsr:  0x61000000
E: Faulting instruction address (r15/pc): 0x0040a870
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x20401098 (child_thread)
Caught system error -- reason 0 1
fatal error expected as part of test case
E: ***** MPU FAULT *****
E:   Data Access Violation
E:   MMFAR Address: 0x20409454
E: r0/a1:  0x204016e8  r1/a2:  0x2040944c  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x0040cf61 r14/lr:  0x0040aa09
E:  xpsr:  0x21000000
E: Faulting instruction address (r15/pc): 0x0040a712
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x20401098 (child_thread)
Caught system error -- reason 0 1
fatal error expected as part of test case
E: ***** MPU FAULT *****
E:   Data Access Violation
E:   MMFAR Address: 0x20401aac
E: r0/a1:  0x20401aac  r1/a2:  0x20409470  r2/a3:  0x00000000
E: r3/a4:  0x00000020 r12/ip:  0x0040cf61 r14/lr:  0x0040ab19
E:  xpsr:  0x21000000
E: Faulting instruction address (r15/pc): 0x004067e4
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x20401098 (child_thread)
Caught system error -- reason 0 1
fatal error expected as part of test case
E: ***** MPU FAULT *****
E:   Data Access Violation
E:   MMFAR Address: 0x20401aac
E: r0/a1:  0x20401aac  r1/a2:  0x20400fe0  r2/a3:  0x00000000
E: r3/a4:  0x00000020 r12/ip:  0x0040cf61 r14/lr:  0x0040ad65
E:  xpsr:  0x21000000
E: Faulting instruction address (r15/pc): 0x004067e4
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x20401098 (child_thread)
Caught system error -- reason 0 1
fatal error expected as part of test case
PASS - test_mem_domain_api_supervisor_only in 0.162 seconds
===================================================================
START - test_mem_domain_boot_threads
PASS - test_mem_domain_boot_threads in 0.1 seconds
===================================================================
START - test_mem_domain_migration
spin thread entry
migrate to new domain
set test completion
spin thread completed
PASS - test_mem_domain_migration in 0.8 seconds
===================================================================
START - test_mem_part_overlap
E: partition 0x20409464 base 204008c0 (size 32) overlaps existing base 204008c0 (size 32)
E: invalid partition 0x20409464
PASS - test_mem_part_overlap in 0.11 seconds
===================================================================
START - test_mem_domain_init_fail
E: NULL k_mem_partition provided
E: invalid partition index 1 ((nil))
PASS - test_mem_domain_init_fail in 0.7 seconds
===================================================================
START - test_mem_domain_remove_part_fail
E: no matching partition found
PASS - test_mem_domain_remove_part_fail in 0.3 seconds
===================================================================
START - test_mem_part_add_error_null
E: NULL k_mem_partition provided
E: invalid partition (nil)
PASS - test_mem_part_add_error_null in 0.6 seconds
===================================================================
START - test_mem_part_add_error_zerosize
E: zero sized partition at 0x20409458 with base 0x204008a0
E: invalid partition 0x20409458
PASS - test_mem_part_add_error_zerosize in 0.9 seconds
===================================================================
START - test_mem_part_error_wraparound
E: invalid partition 0x204057c4, wraparound detected. base 0xfffff800 size 2048
E: invalid partition 0x204057c4
PASS - test_mem_part_error_wraparound in 0.10 seconds
===================================================================
START - test_mem_part_remove_error_zerosize
E: no matching partition found
PASS - test_mem_part_remove_error_zerosize in 0.3 seconds
===================================================================
START - test_mem_part_assign_bss_vars_zero
PASS - test_mem_part_assign_bss_vars_zero in 0.1 seconds
===================================================================
START - test_mem_part_auto_determ_size
PASS - test_mem_part_auto_determ_size in 0.1 seconds
===================================================================
START - test_kobject_access_grant
E: ***** MPU FAULT *****
E:   Data Access Violation
E:   MMFAR Address: 0x20401544
E: r0/a1:  0x00000000  r1/a2:  0x20401544  r2/a3:  0xffffffff
E: r3/a4:  0xffffffff r12/ip:  0x0040cf61 r14/lr:  0x0040cf6d
E:  xpsr:  0x21000000
E: Faulting instruction address (r15/pc): 0x00400e40
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x20401150 (test_kobject_access_grant)
Caught system error -- reason 0 1
fatal error expected as part of test case
PASS - test_kobject_access_grant in 0.42 seconds
===================================================================
START - test_kobject_access_grant_error
PASS - test_kobject_access_grant_error in 0.1 seconds
===================================================================
START - test_kobject_access_grant_error_user_null
E: (nil) is not a valid generic
E: address is not a known kernel object
E: syscall z_vrfy_k_object_access_grant failed check: object (nil) access denied
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00000000
E:  xpsr:  0x00000000
E: Faulting instruction address (r15/pc): 0x0000ffff
E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
E: Current thread: 0x20401150 (test_kobject_access_grant_error)
Caught system error -- reason 3 1
fatal error expected as part of test case
PASS - test_kobject_access_grant_error_user_null in 0.48 seconds
===================================================================
START - test_kobject_access_grant_error_user
E: (nil) is not a valid k_thread
E: address is not a known kernel object
E: syscall z_vrfy_k_object_access_grant failed check: access denied
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00000000
E:  xpsr:  0x00000000
E: Faulting instruction address (r15/pc): 0x0000ffff
E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
E: Current thread: 0x20401150 (test_kobject_access_grant_error)
Caught system error -- reason 3 1
fatal error expected as part of test case
PASS - test_kobject_access_grant_error_user in 0.47 seconds
===================================================================
START - test_kobject_access_all_grant_error
E: ***** MPU FAULT *****
E:   Data Access Violation
E:   MMFAR Address: 0x20409644
E: r0/a1:  0x20409644  r1/a2:  0x20409604  r2/a3:  0x00000000
E: r3/a4:  0x00000004 r12/ip:  0x0040cf61 r14/lr:  0x0040db05
E:  xpsr:  0x01000000
E: Faulting instruction address (r15/pc): 0x00400186
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x20401150 (test_kobject_access_all_grant_e)
Caught system error -- reason 0 1
fatal error expected as part of test case
PASS - test_kobject_access_all_grant_error in 0.42 seconds
===================================================================
START - test_syscall_invalid_kobject
E: 0x20409574 is not a valid k_sem
E: address is actually a k_mutex
E: syscall z_vrfy_k_sem_take failed check: access denied
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00000000
E:  xpsr:  0x00000000
E: Faulting instruction address (r15/pc): 0x0000ffff
E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
E: Current thread: 0x20401150 (test_syscall_invalid_kobject)
Caught system error -- reason 3 1
fatal error expected as part of test case
PASS - test_syscall_invalid_kobject in 0.46 seconds
===================================================================
START - test_thread_without_kobject_permission
E: thread 0x20401150 (9) does not have permission on k_sem 0x204095d4
E: permission bitmap
E: 00 00 00 00             |....    
E: syscall z_vrfy_k_sem_give failed check: access denied
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00000000
E:  xpsr:  0x00000000
E: Faulting instruction address (r15/pc): 0x0000ffff
E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
E: Current thread: 0x20401150 (test_thread_without_kobject_per)
Caught system error -- reason 3 1
fatal error expected as part of test case
PASS - test_thread_without_kobject_permission in 0.51 seconds
===================================================================
START - test_kobject_revoke_access
E: thread 0x20400cc8 (3) does not have permission on k_sem 0x204095d4
E: permission bitmap
E: 00 00 00 00             |....    
E: syscall z_vrfy_k_sem_give failed check: access denied
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00000000
E:  xpsr:  0x00000000
E: Faulting instruction address (r15/pc): 0x00000007
E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
E: Current thread: 0x20400cc8 (unknown)
Caught system error -- reason 3 1
fatal error expected as part of test case
PASS - test_kobject_revoke_access in 0.49 seconds
===================================================================
START - test_kobject_grant_access_kobj
PASS - test_kobject_grant_access_kobj in 0.1 seconds
===================================================================
START - test_kobject_grant_access_kobj_invalid
E: thread 0x20400cc8 (3) does not have permission on k_thread 0x20400d80
E: permission bitmap
E: 00 00 00 00             |....    
E: syscall z_vrfy_k_object_access_grant failed check: access denied
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00000000
E:  xpsr:  0x00000000
E: Faulting instruction address (r15/pc): 0x00000007
E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
E: Current thread: 0x20400cc8 (unknown)
Caught system error -- reason 3 1
fatal error expected as part of test case
PASS - test_kobject_grant_access_kobj_invalid in 0.50 seconds
===================================================================
START - test_kobject_release_from_user
E: thread 0x20400cc8 (3) does not have permission on k_sem 0x204095d4
E: permission bitmap
E: 00 02 00 00             |....    
E: syscall z_vrfy_k_sem_give failed check: access denied
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00000000
E:  xpsr:  0x00000000
E: Faulting instruction address (r15/pc): 0x00000007
E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
E: Current thread: 0x20400cc8 (unknown)
Caught system error -- reason 3 1
fatal error expected as part of test case
PASS - test_kobject_release_from_user in 0.49 seconds
===================================================================
START - test_kobject_invalid
PASS - test_kobject_invalid in 0.1 seconds
===================================================================
START - test_kobject_access_all_grant
PASS - test_kobject_access_all_grant in 0.1 seconds
===================================================================
START - test_thread_has_residual_permissions
E: thread 0x20400cc8 (3) does not have permission on k_sem 0x204095d4
E: permission bitmap
E: 00 02 00 00             |....    
E: syscall z_vrfy_k_sem_take failed check: access denied
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00000000
E:  xpsr:  0x00000000
E: Faulting instruction address (r15/pc): 0x00000007
E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
E: Current thread: 0x20400cc8 (unknown)
Caught system error -- reason 3 1
fatal error expected as part of test case
PASS - test_thread_has_residual_permissions in 0.49 seconds
===================================================================
START - test_kobject_access_grant_to_invalid_thread
E: thread 0x20401150 (9) does not have permission on k_thread 0x20400f28
E: permission bitmap
E: 00 00 00 00             |....    
E: syscall test_kobject_access_grant_to_invalid_thread failed check: access denied
PASS - test_kobject_access_grant_to_invalid_thread in 0.19 seconds
===================================================================
START - test_kobject_access_invalid_kobject
E: thread 0x20401150 (9) does not have permission on k_sem 0x20401484
E: permission bitmap
E: 00 00 00 00             |....    
E: syscall z_vrfy_k_sem_take failed check: access denied
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00000000
E:  xpsr:  0x00000000
E: Faulting instruction address (r15/pc): 0x0000ffff
E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
E: Current thread: 0x20401150 (test_kobject_access_invalid_kob)
Caught system error -- reason 3 1
fatal error expected as part of test case
PASS - test_kobject_access_invalid_kobject in 0.51 seconds
===================================================================
START - test_access_kobject_without_init_access
E: thread 0x20401150 (9) does not have permission on k_sem 0x20401474
E: permission bitmap
E: 00 00 00 00             |....    
E: syscall z_vrfy_k_sem_take failed check: access denied
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00000000
E:  xpsr:  0x00000000
E: Faulting instruction address (r15/pc): 0x0000ffff
E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
E: Current thread: 0x20401150 (test_access_kobject_without_ini)
Caught system error -- reason 3 1
fatal error expected as part of test case
PASS - test_access_kobject_without_init_access in 0.51 seconds
===================================================================
START - test_access_kobject_without_init_with_access
E: 0x20401464 used before initialization
E: syscall z_vrfy_k_sem_take failed check: access denied
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00000000
E:  xpsr:  0x00000000
E: Faulting instruction address (r15/pc): 0x00000007
E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
E: Current thread: 0x20400cc8 (unknown)
Caught system error -- reason 3 1
fatal error expected as part of test case
PASS - test_access_kobject_without_init_with_access in 0.41 seconds
===================================================================
START - test_kobject_reinitialize_thread_kobj
E: thread 0x20400cc8 (3) does not have permission on k_thread 0x20400d80
E: permission bitmap
E: 00 00 00 00             |....    
E: syscall z_vrfy_k_thread_create failed check: access denied
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00000000
E:  xpsr:  0x00000000
E: Faulting instruction address (r15/pc): 0x00000007
E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
E: Current thread: 0x20400cc8 (unknown)
Caught system error -- reason 3 1
fatal error expected as part of test case
PASS - test_kobject_reinitialize_thread_kobj in 0.50 seconds
===================================================================
START - test_create_new_thread_from_user
PASS - test_create_new_thread_from_user in 0.1 seconds
===================================================================
START - test_new_user_thread_with_in_use_stack_obj
E: 0x20406800 z_thread_stack_element in use
E: syscall z_vrfy_k_thread_create failed check: bad stack object
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00000000
E:  xpsr:  0x00000000
E: Faulting instruction address (r15/pc): 0x00000007
E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
E: Current thread: 0x20400cc8 (unknown)
Caught system error -- reason 3 1
fatal error expected as part of test case
PASS - test_new_user_thread_with_in_use_stack_obj in 0.42 seconds
===================================================================
START - test_create_new_thread_from_user_no_access_stack
E: thread 0x20400cc8 (3) does not have permission on z_thread_stack_element 0x20406a00
E: permission bitmap
E: 00 00 00 00             |....    
E: syscall z_vrfy_k_thread_create failed check: bad stack object
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00000000
E:  xpsr:  0x00000000
E: Faulting instruction address (r15/pc): 0x00000007
E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
E: Current thread: 0x20400cc8 (unknown)
Caught system error -- reason 3 1
fatal error expected as part of test case
PASS - test_create_new_thread_from_user_no_access_stack in 0.51 seconds
===================================================================
START - test_create_new_thread_from_user_invalid_stacksize
SKIP - test_create_new_thread_from_user_invalid_stacksize in 0.1 seconds
===================================================================
START - test_create_new_thread_from_user_huge_stacksize
SKIP - test_create_new_thread_from_user_huge_stacksize in 0.1 seconds
===================================================================
START - test_create_new_supervisor_thread_from_user
E: syscall z_vrfy_k_thread_create failed check: options & K_USER
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00000000
E:  xpsr:  0x00000000
E: Faulting instruction address (r15/pc): 0x00000007
E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
E: Current thread: 0x20400cc8 (unknown)
Caught system error -- reason 3 1
fatal error expected as part of test case
PASS - test_create_new_supervisor_thread_from_user in 0.38 seconds
===================================================================
START - test_create_new_essential_thread_from_user
E: syscall z_vrfy_k_thread_create failed check: !(options & K_ESSENTIAL)
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00000000
E:  xpsr:  0x00000000
E: Faulting instruction address (r15/pc): 0x00000007
E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
E: Current thread: 0x20400cc8 (unknown)
Caught system error -- reason 3 1
fatal error expected as part of test case
PASS - test_create_new_essential_thread_from_user in 0.39 seconds
===================================================================
START - test_create_new_higher_prio_thread_from_user
E: syscall z_vrfy_k_thread_create failed check: z_is_prio_lower_or_equal(prio, _current->base.prio)
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00000000
E:  xpsr:  0x00000000
E: Faulting instruction address (r15/pc): 0x00000007
E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
E: Current thread: 0x20400cc8 (unknown)
Caught system error -- reason 3 1
fatal error expected as part of test case
PASS - test_create_new_higher_prio_thread_from_user in 0.42 seconds
===================================================================
START - test_create_new_invalid_prio_thread_from_user
E: syscall z_vrfy_k_thread_create failed check: _is_valid_prio(prio, NULL)
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00000000
E:  xpsr:  0x00000000
E: Faulting instruction address (r15/pc): 0x00000007
E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
E: Current thread: 0x20400cc8 (unknown)
Caught system error -- reason 3 1
fatal error expected as part of test case
PASS - test_create_new_invalid_prio_thread_from_user in 0.39 seconds
===================================================================
START - test_mark_thread_exit_uninitialized
PASS - test_mark_thread_exit_uninitialized in 0.1 seconds
===================================================================
START - test_mem_part_assert_add_overmax
E: no free partition slots available
PASS - test_mem_part_assert_add_overmax in 0.4 seconds
===================================================================
START - test_kobject_init_error
E: bad object type 255 requested
E: bad object type 55 requested
E: forbidden object type 'k_futex' requested
PASS - test_kobject_init_error in 0.10 seconds
===================================================================
START - test_alloc_kobjects
E: ***** BUS FAULT *****
E:   Precise data bus error
E:   BFAR Address: 0x1d0ef3c
E: r0/a1:  0x01d0ef3c  r1/a2:  0x0040d307  r2/a3:  0x00000000
E: r3/a4:  0x00000020 r12/ip:  0x20402bd0 r14/lr:  0x0040b875
E:  xpsr:  0x21000000
E: Faulting instruction address (r15/pc): 0x004067e4
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x20401150 (test_alloc_kobjects)
Caught system error -- reason 0 0
fatal error was unexpected, aborting
```

**Environment (please complete the following information):**
 - OS: Fedora
 - Toolchain - SDK 13.2
 - Commit SHA: 32c4bd3b684a

**Comment by dleach02** [comment] 2022-02-15 18:00
@yerabolu, I am not able to reproduce this on the frdm_k64f. How repeatable is this for you?

**Comment by yerabolu** [comment] 2022-02-15 19:13
@dleach02 : i am able to reproduce it, but the reproducibility rate is very low. Failure happens randomly. So far i have run it 10 times and test failed 2 times.

**Comment by dleach02** [comment] 2022-02-15 21:39
@hakehuang, this is called out against an Atmel part but the reporter also noted it occurring on k64f.

**Comment by dleach02** [comment] 2022-02-15 22:20
Ok. I'm seeing the failure(s)

**Comment by dleach02** [comment] 2022-02-16 05:37
yeah, I see the same one

**Comment by hakehuang** [comment] 2022-02-16 06:07
@dleach02 mimxrt595_evk_cm33 also fails at this test and with different log.
[log.txt](https://github.com/zephyrproject-rtos/zephyr/files/8077193/log.txt)

**Comment by hakehuang** [comment] 2022-02-16 07:13
> @dleach02 mimxrt595_evk_cm33 also fails at this test and with different log. [log.txt](https://github.com/zephyrproject-rtos/zephyr/files/8077193/log.txt)
and it is ok at my frdm_k64 board log as linked
[frdm_k64f_log.txt](https://github.com/zephyrproject-rtos/zephyr/files/8077555/frdm_k64f_log.txt)

my board is using openocd debugger, and the board revision is 
70028163 rev E
SCH-28163 REV F

**Comment by dleach02** [comment] 2022-02-17 05:30
This is randomly failing because of uninitialized data in an allocated K_OBJ_MSGQ. The test cases are doing a k_object_alloc(K_OBJ_MSGQ) but not following up the alloc with a k_msgq_init() to ensure that the fields are initialized appropriately. 

The test cases here are expecting fatal errors so after a fatal error it kills the thread which will cause the logic to walk through the k_objects to remove the thread ID references to any objects. In unref_check(), if the kernel object has no threads referencing it AND it is an allocated object, the code will free the object back to its respective heap.  In the case of a k_msg object, the k_msgq_cleanup() function will further check msgq->flags to determine if the buffer_start pointer points to an allocated buffer and if it does it will k_free() buffer_start back to its heap. 

Problem with uninitialized data is that the msgq->flags and msgq->buffer_start will have random RAM values and randomly it may attempt to free the buffer_start pointer to invalid memory or unaligned memory so the k_free() function will sometimes fault when doing this clean up.

The fix for this is likely to change the test suite to ensure allocated kernel objects are initialized. Per the documentation of k_object_alloc():

> The object will be returned in an uninitialized state, with the calling thread being granted permission on it

A kludge fix to verify this was to memset() the kernel object to zero in the allocation function. Not sure we want to incur that overhead since the documentation says the object returned is uninitialized.

**Comment by dleach02** [comment] 2022-02-17 15:25
@yerabolu can you test my PR #42913 on your system. 

I figured out the root issue and can see that it is a random type of failure.

**Comment by dleach02** [comment] 2022-02-21 03:07
> Found the same issue on reel_board.

Yeah, this will randomly occur on any board. Uninitialized memory has a way of doing this ;-)

**Closed** 2022-02-22 01:43 UTC
Labels: bug, priority: low, area: ARM, platform: NXP, platform: Atmel
