### ISSUE TITLE
usb mass storage : config waits for Vendor ID and Product ID from user during building

### ISSUE THREAD

**Issue by akhileshupadhyay** [zephyrproject-rtos/zephyr#4606] opened 2017-10-27 13:49 UTC
While building application for usb mass storage, config is expecting user to pass Vendor ID and Product id. Build keeps waiting until provided with IDs. This creates blockage for automation. 

=================================
Below logs appear during building:

````
Merging prj.conf
#
# configuration written to .config
#
make[1]: Entering directory 'ZEPHYR_BASE'
make[2]: Entering directory 'ZEPHYR_BASE/samples/subsys/usb/mass/outdir/quark_se_c1000_devboard'
  GEN     ./Makefile
scripts/kconfig/conf --silentoldconfig Kconfig
.config:434:warning: symbol value '' invalid for USB_DEVICE_VID
.config:435:warning: symbol value '' invalid for USB_DEVICE_PID
*
* Restart config...
*
*
* USB device stack
*
USB device stack (USB_DEVICE_STACK) [Y/n/?] y
  Sets log level for the USB device stack (SYS_LOG_USB_LEVEL) [1] 1
  USB Vendor ID (USB_DEVICE_VID) [] (NEW)

````

Steps to reproduce:

1. cd   $ZEPHYR_BASE
2. source  zephyr-env.sh
3. cd   $ZEPHYR_BASE/samples/subsys/usb/mass
4. make  BOARD=quark_se_c1000_devboard

Work around:
````
Pass USB_DEVICE_VID and USB_DEVICE_PID to boards/x86/quark_se_c1000_devboard/Kconfig.defconfig
````

**Comment by finikorg** [comment] 2017-10-27 14:49
We do not have VENDOR_ID and PRODUCT_ID assigned for this board, however if you know uark_se_c1000_devboard default values we can put them to this defconfig. BTW, do not you use sanitycheck for automatic build?

**Comment by nashif** [comment] 2017-10-27 16:28
@finikorg this is breaking sanitycheck and we do need to have some default values added in this case, same as with tinyTILE.

**Comment by nashif** [comment] 2017-10-27 16:33
ok, I mixed this up with another issue we had with IDs, but in this case for the arduino 101, they all share the same ID like the tinyTILE, so this needs to be set somewhere, in this case probably in the test framework testing the usb

**Comment by finikorg** [comment] 2017-11-01 09:00
I consider this not a bug but feature. Until we get proper Vendor ID we cannot invent those values and put to the project configuration files. Automation issues are resolved in sample.yaml configurations.

**Comment by jfischer-phytec-iot** [comment] 2017-11-02 10:43
currently it is desired behavior

**Comment by kumarvikash1** [comment] 2017-11-29 05:09
As discussed above, Now VID & PID values are being provided from test framework only. Specific VID & PID will be profided by user, if any. 

We can close this issue as FIXED.

**Comment by carlescufi** [comment] 2018-01-23 18:37
Can we close this as @kumarvikash1 mentioned, or do we need to add any required changes now that there is a "default" Zephyr PID/VID?

**Comment by finikorg** [comment] 2018-02-01 09:47
Closed as fixed

**Closed** 2018-02-01 09:47 UTC
Labels: area: USB, bug, priority: medium
