### ISSUE TITLE
up_squared: tests/kernel/threads/thread_stack/kernel.threads.thread_stack

### ISSUE THREAD

**Issue by KamilxPaszkiet** [zephyrproject-rtos/zephyr#66143] opened 2023-12-05 10:32 UTC
**Describe the bug**
`tests/kernel/threads/thread_stack/kernel.threads.thread_stack`
timeout.

**To Reproduce**
twister --device-testing --hardware-map up2.map -s tests/kernel/threads/thread_stack/kernel.threads.thread_stack -vv

**Logs and console output**
```
DEBUG   - DEVICE: *** Booting Zephyr OS build zephyr-v3.5.0-2629-gd70e8d5a8f91 ***
DEBUG   - DEVICE: E: ACPI get table failed: 5
DEBUG   - DEVICE: Running TESTSUITE userspace_thread_stack
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_idle_stack
DEBUG   - DEVICE: hi! bye!
DEBUG   - DEVICE: E: Page fault at address 0x10 (error code 0x2)
DEBUG   - DEVICE: E: Linear address not present in page tables
DEBUG   - DEVICE: E: Access violation: supervisor thread not allowed to write
DEBUG   - DEVICE: E: PTE: not present
DEBUG   - DEVICE: E: RAX: 0x0000000000000000 RBX: 0x0000000000000000 RCX: 0x0000000000000001 RDX: 0x0000000000000001
DEBUG   - DEVICE: E: RSI: 0x0000000000000001 RDI: 0x0000000000000000 RBP: 0x00000000005bb1a0 RSP: 0x00000000005bb180
DEBUG   - DEVICE: E:  R8: 0x0000000000000000  R9: 0x0000000000000000 R10: 0x0000000000000000 R11: 0x0000000000bd6008
DEBUG   - DEVICE: E: R12: 0x0000000000000000 R13: 0x0000000000000000 R14: 0x00000000005bb1f8 R15: 0x0000000000100409
DEBUG   - DEVICE: E: RSP: 0x00000000005bb180 RFLAGS: 0x0000000000010246 CS: 0x0018 CR3: 0x0000000000e17000
DEBUG   - DEVICE: E: RIP: 0x000000000010a0b5
DEBUG   - DEVICE: E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
DEBUG   - DEVICE: E: Current thread: 0x121000 (unknown)
DEBUG   - DEVICE: E: Halting system
```
**Environment:**
- OS: Linux
- Toolchain: zephyr-sdk-0.16.3
- zephyr-v3.5.0-2629-gd70e8d5a8f91

**Comment by MaureenHelm** [comment] 2023-12-05 17:31
Duplicate of #65722

**Closed by MaureenHelm** 2023-12-05 17:31 UTC
Labels: bug, area: X86, platform: up_squared
