### ISSUE TITLE
west install error

### ISSUE THREAD

**Issue by AbramQuerashi** [zephyrproject-rtos/zephyr#27580] opened 2020-08-14 11:14 UTC
**Describe the bug**
What have you tried to diagnose or workaround this issue?

I tried to install zephyr and while installing west i got the below error.

pip3 install --user -U west
WARNING: The directory '/home/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: The directory '/home/biju/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting west

**To Reproduce**
pip3 install --user -U west

**Comment by mbolivar-nordic** [comment] 2020-08-17 17:59
This appears to be a pip misconfiguration. What operating system are you using?

**Comment by mbolivar-nordic** [comment] 2020-08-17 18:00
Closing this one as a duplicate of https://github.com/zephyrproject-rtos/zephyr/issues/27580, which is filed in the correct repository and has more information.

**Closed by mbolivar-nordic** 2020-08-17 18:00 UTC
Labels: bug
