### ISSUE TITLE
Tests: unittest with new ZTEST API

### ISSUE THREAD

**Issue by kruithofa** [zephyrproject-rtos/zephyr#47420] opened 2022-07-06 15:42 UTC
**Describe the bug**
unittests do not use a prj.conf file, so it is not possible to set CONFIG_NEW_ZTEST_API to yes, and as a result the new API can not be used.

an example is the unittest in tests/ztest/base where the CMakeLists.txt file specifies to use the deprecated ztest API for unittesting

for the unittest for the Bluetooth LLCP we have a workaround for setting kconfig values by specifying them in an include file: tests/bluetooth/controller/mock_ctrl/include/kconfig.h
Adding CONFIG_NEW_ZTEST_API=y  to this file does not work, but gives a compile error ' fatal error: syscalls/ztest_test_new.h: No such file or directory', presumably because this file is auto-generated

**To Reproduce**
1. add the line '#define CONFIG_NEW_ZTEST_API y' to the file tests/bluetooth/controller/mock_ctrl/include/kconfig.h
2. go to the folder tests/bluetooth/controller/ctrl_api
3. run twister: 'twister -v -T .'
4. see that the build fails

**Expected behavior**

**Impact**
Can not use the new API for unit testing

**Logs and console output**

**Environment (please complete the following information):**
Running on Linux

**Additional context**

**Comment by yperess** [comment] 2022-07-06 16:38
@kruithofa OK, so the issue is that `unittest` doesn't have Kconfig support and is manually compiling the ztest library from source. I'm working on a fix for this.

**Closed** 2022-07-07 16:22 UTC
Labels: bug, priority: medium, area: Test Framework

**Comment by spbnick** [comment] 2023-02-26 16:37
I just tried copying the [`prj.conf` from the "integration" test suite sample](https://github.com/zephyrproject-rtos/zephyr/blob/eead89e7f22dcb2e507cb2083c5ad8383cead038/samples/subsys/testsuite/integration/prj.conf), and got the same error. Removing the `CONFIG_ZTEST=y` from my `prj.conf` fixed this. Although, I'm not sure if I would be able to write my tests now (never did that before) :man_shrugging:

**Comment by spbnick** [comment] 2023-02-26 16:47
Nope, my app can't find `zephyr/ztest.h` now, and I have no idea how would even do that, because I couldn't even find that file myself :see_no_evil: The documentation didn't help me. I'll go ask on Discord.
