### ISSUE TITLE
"make clean" removes include directory

### ISSUE THREAD

**Issue by therealprof** [zephyrproject-rtos/zephyr#8444] opened 2018-06-18 08:16 UTC
Recently calling `make clean` in a build directory of an example (here a subdirectory of the example code) removes the whole include directory:
```
# git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    ../../../../include/adc.h
	deleted:    ../../../../include/aio_comparator.h
	deleted:    ../../../../include/arch/arc/arch.h
	deleted:    ../../../../include/arch/arc/v2/addr_types.h
	deleted:    ../../../../include/arch/arc/v2/arcv2_irq_unit.h
	deleted:    ../../../../include/arch/arc/v2/asm_inline.h
...
```

**Comment by SebastianBoe** [comment] 2018-06-18 08:48
Closing as duplicate of #8380

**Closed by SebastianBoe** 2018-06-18 08:48 UTC
