### ISSUE TITLE
shell/usb cdc_acm: shell does not work on CDC_ACM

### ISSUE THREAD

**Issue by alexanderwachter** [zephyrproject-rtos/zephyr#32581] opened 2021-02-23 15:48 UTC
The shell is not responding on USB CDC_ACM after #31880 got merged.
However, the USB serial device is still working.

I'm on a custom board with an stm32g4.
Reverting the commit from 31880 brings the shell back.

**Comment by jfischer-no** [comment] 2021-02-23 16:26
`CONFIG_SHELL_BACKEND_SERIAL_INIT_PRIORITY=51` is a possible workaround.

**Comment by pabigot** [comment] 2021-02-23 16:28
Yes, this is at least partly due to `device_get_binding()` now returning null on devices that have not been initialized.  We're going to need runtime equivalent to `DEVICE_DT_GET()` that looks up things by name regardless of whether they're ready to be used.

@galak again we should perhaps slow down on removing label properties.

**Comment by pabigot** [comment] 2021-02-23 16:45
FWIW, I can't manage to get `samples/subsys/shell/shell_module` to run on a CDC ACM before *or* after #31880 was merged, even with updating the init priority.  If anybody can provide clear instructions I'd appreciate it.

**Comment by jfischer-no** [comment] 2021-02-23 16:55
> FWIW, I can't manage to get `samples/subsys/shell/shell_module` to run on a CDC ACM before _or_ after #31880 was merged, even with updating the init priority. If anybody can provide clear instructions I'd appreciate it.

I found an old patch that adds shell support to console sample, #32586

**Comment by pabigot** [comment] 2021-02-23 18:18
I'm going to call this a configuration error, and so the issue is a question, not a bug or a regression.

The shell UART back end initializes in `POST_KERNEL` at `CONFIG_SHELL_BACKEND_SERIAL_INIT_PRIORITY` which defaults to 0.

Most UART devices initialize in `PRE_KERNEL_1` at `CONFIG_SHELL_BACKEND_SERIAL_INIT_PRIORITY` which defaults to 50.

So everything just works as long as serial devices are initialized in an earlier init level.

But CDC ACM device initializes at `POST_KERNEL` at `CONFIG_SHELL_BACKEND_SERIAL_INIT_PRIORITY` which defaults to 50.

So the correct fix, if using CDC ACM for shell, is to increase `CONFIG_SHELL_BACKEND_SERIAL_INIT_PRIORITY` to at least 51 as @jfischer-no identified.

I don't see any obvious way to detect the situation and change the default.

FWIW, the solution prototyped in #32587 also makes it work, but for the same reason that it worked until `device_is_ready()` got fixed:  the device is successfully retrieved before initialization but the operations performed on it appear to either be delayed until the device is ready, or are robust if invoked before the device has been initialized.

Making shell_uart robust in the face of UART devices that can be started late or turned off is a much larger task.

**Comment by alexanderwachter** [comment] 2021-02-24 07:21
I can confirm that setting `CONFIG_SHELL_BACKEND_SERIAL_INIT_PRIORITY=51` solves the problem. Thanks @pabigot @jfischer-no

**Closed** 2021-02-24 11:13 UTC
Labels: area: Shell, area: USB, question
