### ISSUE TITLE
"PWM" on teensy41

### ISSUE THREAD

**Issue by Chethan-TS** [zephyrproject-rtos/zephyr#78050] opened 2024-09-05 11:35 UTC
**unable to configure PWM on teensy 4.1**

i am trying the "samples/basic/servo_motor" example for teensy41 board, below have attached the overlay for teensy41 but when i build the same i get error.

below is the error:

chethan@Chethan:~/GCB_rnd/BLDC/teensy_pwm_test/servo_motor$ west build -p always -b teensy41
-- west build: making build dir /home/chethan/GCB_rnd/BLDC/teensy_pwm_test/servo_motor/build pristine
-- west build: generating a build system
Loading Zephyr default modules (Zephyr base).
-- Application: /home/chethan/GCB_rnd/BLDC/teensy_pwm_test/servo_motor
-- CMake version: 3.29.6
-- Found Python3: /usr/bin/python3 (found suitable version "3.10.12", minimum required is "3.8") found components: Interpreter
-- Cache files will be written to: /home/chethan/.cache/zephyr
-- Zephyr version: 3.5.0 (/home/chethan/zephyrproject/zephyr)
-- Found west (found suitable version "1.2.0", minimum required is "0.14.0")
-- Board: teensy41
-- ZEPHYR_TOOLCHAIN_VARIANT not set, trying to locate Zephyr SDK
-- Found host-tools: zephyr 0.16.5 (/home/chethan/zephyr-sdk-0.16.5-1)
-- Found toolchain: zephyr 0.16.5 (/home/chethan/zephyr-sdk-0.16.5-1)
-- Found Dtc: /home/chethan/zephyr-sdk-0.16.5-1/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.6.0", minimum required is "1.4.6")
-- Found BOARD.dts: /home/chethan/zephyrproject/zephyr/boards/arm/teensy4/teensy41.dts
-- Found devicetree overlay: /home/chethan/GCB_rnd/BLDC/teensy_pwm_test/servo_motor/app.overlay
-- Generated zephyr.dts: /home/chethan/GCB_rnd/BLDC/teensy_pwm_test/servo_motor/build/zephyr/zephyr.dts
-- Generated devicetree_generated.h: /home/chethan/GCB_rnd/BLDC/teensy_pwm_test/servo_motor/build/zephyr/include/generated/devicetree_generated.h
-- Including generated dts.cmake file: /home/chethan/GCB_rnd/BLDC/teensy_pwm_test/servo_motor/build/zephyr/dts.cmake
Parsing /home/chethan/zephyrproject/zephyr/Kconfig
Loaded configuration '/home/chethan/zephyrproject/zephyr/boards/arm/teensy4/teensy41_defconfig'
Merged configuration '/home/chethan/GCB_rnd/BLDC/teensy_pwm_test/servo_motor/prj.conf'
Configuration saved to '/home/chethan/GCB_rnd/BLDC/teensy_pwm_test/servo_motor/build/zephyr/.config'
Kconfig header saved to '/home/chethan/GCB_rnd/BLDC/teensy_pwm_test/servo_motor/build/zephyr/include/generated/autoconf.h'
-- Found GnuLd: /home/chethan/zephyr-sdk-0.16.5-1/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd (found version "2.38")
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /home/chethan/zephyr-sdk-0.16.5-1/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc
Load components for MIMXRT1062:
driver_common component is included.
driver_reset component is included.
device_CMSIS component is included.
CMSIS_Include_core_cm component is included.
device_system component is included.
driver_lpi2c component is included.
driver_lpspi component is included.
driver_lpuart component is included.
driver_igpio component is included.
driver_pwm component is included.
driver_cache_armv7_m7 component is included.
-- Configuring done (4.2s)
-- Generating done (0.1s)
-- Build files have been written to: /home/chethan/GCB_rnd/BLDC/teensy_pwm_test/servo_motor/build
-- west build: building application
[1/136] Preparing syscall dependency handling

[2/136] Generating include/generated/version.h
-- Zephyr version: 3.5.0 (/home/chethan/zephyrproject/zephyr), build: zephyr-v3.5.0
[129/136] Building C object CMakeFiles/app.dir/src/main.c.obj
FAILED: CMakeFiles/app.dir/src/main.c.obj 
ccache /home/chethan/zephyr-sdk-0.16.5-1/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc -DBOARD_FLASH_SIZE="CONFIG_FLASH_SIZE*1024" -DCPU_MIMXRT1062DVJ6A -DKERNEL -DNDEBUG -DPICOLIBC_INTEGER_PRINTF_SCANF -DXIP_BOOT_HEADER_DCD_ENABLE=1 -DXIP_BOOT_HEADER_ENABLE=1 -DXIP_EXTERNAL_FLASH -D_FORTIFY_SOURCE=1 -D_POSIX_C_SOURCE=200809 -D__LINUX_ERRNO_EXTENSIONS__ -D__PROGRAM_START -D__ZEPHYR__=1 -I/home/chethan/zephyrproject/zephyr/include -I/home/chethan/GCB_rnd/BLDC/teensy_pwm_test/servo_motor/build/zephyr/include/generated -I/home/chethan/zephyrproject/zephyr/soc/arm/nxp_imx/rt -I/home/chethan/zephyrproject/modules/hal/cmsis/CMSIS/Core/Include -I/home/chethan/zephyrproject/zephyr/modules/cmsis/. -I/home/chethan/zephyrproject/modules/hal/nxp/mcux/mcux-sdk/devices/MIMXRT1062 -I/home/chethan/zephyrproject/modules/hal/nxp/mcux/mcux-sdk/devices/MIMXRT1062/drivers -I/home/chethan/zephyrproject/modules/hal/nxp/mcux/mcux-sdk/devices/MIMXRT1062/xip -I/home/chethan/zephyrproject/modules/hal/nxp/mcux/mcux-sdk/drivers/common -I/home/chethan/zephyrproject/modules/hal/nxp/mcux/mcux-sdk/drivers/lpi2c -I/home/chethan/zephyrproject/modules/hal/nxp/mcux/mcux-sdk/drivers/lpspi -I/home/chethan/zephyrproject/modules/hal/nxp/mcux/mcux-sdk/drivers/lpuart -I/home/chethan/zephyrproject/modules/hal/nxp/mcux/mcux-sdk/drivers/igpio -I/home/chethan/zephyrproject/modules/hal/nxp/mcux/mcux-sdk/drivers/pwm -I/home/chethan/zephyrproject/modules/hal/nxp/mcux/mcux-sdk/drivers/cache/armv7-m7 -I/home/chethan/zephyrproject/zephyr/modules/hal_nxp/. -fno-strict-aliasing -Os -imacros /home/chethan/GCB_rnd/BLDC/teensy_pwm_test/servo_motor/build/zephyr/include/generated/autoconf.h -fno-printf-return-value -fno-common -g -gdwarf-4 -fdiagnostics-color=always -mcpu=cortex-m7 -mthumb -mabi=aapcs -mfp16-format=ieee --sysroot=/home/chethan/zephyr-sdk-0.16.5-1/arm-zephyr-eabi/arm-zephyr-eabi -imacros /home/chethan/zephyrproject/zephyr/include/zephyr/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-pointer-sign -Wpointer-arith -Wexpansion-to-defined -Wno-unused-but-set-variable -Werror=implicit-int -fno-pic -fno-pie -fno-asynchronous-unwind-tables -ftls-model=local-exec -fno-reorder-functions --param=min-pagesize=0 -fno-defer-pop -fmacro-prefix-map=/home/chethan/GCB_rnd/BLDC/teensy_pwm_test/servo_motor=CMAKE_SOURCE_DIR -fmacro-prefix-map=/home/chethan/zephyrproject/zephyr=ZEPHYR_BASE -fmacro-prefix-map=/home/chethan/zephyrproject=WEST_TOPDIR -ffunction-sections -fdata-sections --specs=picolibc.specs -std=c99 -MD -MT CMakeFiles/app.dir/src/main.c.obj -MF CMakeFiles/app.dir/src/main.c.obj.d -o CMakeFiles/app.dir/src/main.c.obj -c /home/chethan/GCB_rnd/BLDC/teensy_pwm_test/servo_motor/src/main.c
In file included from /home/chethan/zephyrproject/zephyr/include/zephyr/toolchain/gcc.h:98,
                 from /home/chethan/zephyrproject/zephyr/include/zephyr/toolchain.h:50,
                 from /home/chethan/zephyrproject/zephyr/include/zephyr/kernel_includes.h:23,
                 from /home/chethan/zephyrproject/zephyr/include/zephyr/kernel.h:17,
                 from /home/chethan/GCB_rnd/BLDC/teensy_pwm_test/servo_motor/src/main.c:11:
/home/chethan/zephyrproject/zephyr/include/zephyr/device.h:85:41: error: '__device_dts_ord_DT_N_ALIAS_pwm1_P_pwms_IDX_0_PH_ORD' undeclared here (not in a function)
   85 | #define DEVICE_NAME_GET(dev_id) _CONCAT(__device_, dev_id)
      |                                         ^~~~~~~~~
/home/chethan/zephyrproject/zephyr/include/zephyr/toolchain/common.h:137:26: note: in definition of macro '_DO_CONCAT'
  137 | #define _DO_CONCAT(x, y) x ## y
      |                          ^
/home/chethan/zephyrproject/zephyr/include/zephyr/device.h:85:33: note: in expansion of macro '_CONCAT'
   85 | #define DEVICE_NAME_GET(dev_id) _CONCAT(__device_, dev_id)
      |                                 ^~~~~~~
/home/chethan/zephyrproject/zephyr/include/zephyr/device.h:212:37: note: in expansion of macro 'DEVICE_NAME_GET'
  212 | #define DEVICE_DT_NAME_GET(node_id) DEVICE_NAME_GET(Z_DEVICE_DT_DEV_ID(node_id))
      |                                     ^~~~~~~~~~~~~~~
/home/chethan/zephyrproject/zephyr/include/zephyr/device.h:229:34: note: in expansion of macro 'DEVICE_DT_NAME_GET'
  229 | #define DEVICE_DT_GET(node_id) (&DEVICE_DT_NAME_GET(node_id))
      |                                  ^~~~~~~~~~~~~~~~~~
/home/chethan/zephyrproject/zephyr/include/zephyr/drivers/pwm.h:258:24: note: in expansion of macro 'DEVICE_DT_GET'
  258 |                 .dev = DEVICE_DT_GET(DT_PWMS_CTLR_BY_IDX(node_id, idx)),       \
      |                        ^~~~~~~~~~~~~
/home/chethan/zephyrproject/zephyr/include/zephyr/drivers/pwm.h:326:34: note: in expansion of macro 'PWM_DT_SPEC_GET_BY_IDX'
  326 | #define PWM_DT_SPEC_GET(node_id) PWM_DT_SPEC_GET_BY_IDX(node_id, 0)
      |                                  ^~~~~~~~~~~~~~~~~~~~~~
/home/chethan/GCB_rnd/BLDC/teensy_pwm_test/servo_motor/src/main.c:16:40: note: in expansion of macro 'PWM_DT_SPEC_GET'
   16 | static const struct pwm_dt_spec pwm1 = PWM_DT_SPEC_GET(DT_ALIAS(pwm1));
      |                                        ^~~~~~~~~~~~~~~
In file included from /home/chethan/zephyrproject/zephyr/include/zephyr/arch/arm/arch.h:20,
                 from /home/chethan/zephyrproject/zephyr/include/zephyr/arch/cpu.h:19,
                 from /home/chethan/zephyrproject/zephyr/include/zephyr/kernel_includes.h:37:
/home/chethan/zephyrproject/zephyr/include/zephyr/devicetree.h:237:32: error: 'DT_N_ALIAS_pwm1_P_pwms_IDX_0_VAL_channel' undeclared here (not in a function)
  237 | #define DT_ALIAS(alias) DT_CAT(DT_N_ALIAS_, alias)
      |                                ^~~~~~~~~~~
/home/chethan/zephyrproject/zephyr/include/zephyr/devicetree.h:4272:9: note: in definition of macro 'DT_CAT7'
 4272 |         a1 ## a2 ## a3 ## a4 ## a5 ## a6 ## a7
      |         ^~
/home/chethan/zephyrproject/zephyr/include/zephyr/devicetree/pwms.h:136:9: note: in expansion of macro 'DT_PHA_BY_IDX'
  136 |         DT_PHA_BY_IDX(node_id, pwms, idx, cell)
      |         ^~~~~~~~~~~~~
/home/chethan/zephyrproject/zephyr/include/zephyr/devicetree/pwms.h:208:9: note: in expansion of macro 'DT_PWMS_CELL_BY_IDX'
  208 |         DT_PWMS_CELL_BY_IDX(node_id, idx, channel)
      |         ^~~~~~~~~~~~~~~~~~~
/home/chethan/zephyrproject/zephyr/include/zephyr/drivers/pwm.h:259:28: note: in expansion of macro 'DT_PWMS_CHANNEL_BY_IDX'
  259 |                 .channel = DT_PWMS_CHANNEL_BY_IDX(node_id, idx),               \
      |                            ^~~~~~~~~~~~~~~~~~~~~~
/home/chethan/zephyrproject/zephyr/include/zephyr/drivers/pwm.h:326:34: note: in expansion of macro 'PWM_DT_SPEC_GET_BY_IDX'
  326 | #define PWM_DT_SPEC_GET(node_id) PWM_DT_SPEC_GET_BY_IDX(node_id, 0)
      |                                  ^~~~~~~~~~~~~~~~~~~~~~
/home/chethan/GCB_rnd/BLDC/teensy_pwm_test/servo_motor/src/main.c:16:40: note: in expansion of macro 'PWM_DT_SPEC_GET'
   16 | static const struct pwm_dt_spec pwm1 = PWM_DT_SPEC_GET(DT_ALIAS(pwm1));
      |                                        ^~~~~~~~~~~~~~~
/home/chethan/zephyrproject/zephyr/include/zephyr/devicetree.h:237:25: note: in expansion of macro 'DT_CAT'
  237 | #define DT_ALIAS(alias) DT_CAT(DT_N_ALIAS_, alias)
      |                         ^~~~~~
/home/chethan/GCB_rnd/BLDC/teensy_pwm_test/servo_motor/src/main.c:16:56: note: in expansion of macro 'DT_ALIAS'
   16 | static const struct pwm_dt_spec pwm1 = PWM_DT_SPEC_GET(DT_ALIAS(pwm1));
      |                                                        ^~~~~~~~
/home/chethan/zephyrproject/zephyr/include/zephyr/devicetree.h:237:32: error: 'DT_N_ALIAS_pwm1_P_pwms_IDX_0_VAL_period' undeclared here (not in a function)
  237 | #define DT_ALIAS(alias) DT_CAT(DT_N_ALIAS_, alias)
      |                                ^~~~~~~~~~~
/home/chethan/zephyrproject/zephyr/include/zephyr/devicetree.h:4272:9: note: in definition of macro 'DT_CAT7'
 4272 |         a1 ## a2 ## a3 ## a4 ## a5 ## a6 ## a7
      |         ^~
/home/chethan/zephyrproject/zephyr/include/zephyr/devicetree/pwms.h:136:9: note: in expansion of macro 'DT_PHA_BY_IDX'
  136 |         DT_PHA_BY_IDX(node_id, pwms, idx, cell)
      |         ^~~~~~~~~~~~~
/home/chethan/zephyrproject/zephyr/include/zephyr/devicetree/pwms.h:249:9: note: in expansion of macro 'DT_PWMS_CELL_BY_IDX'
  249 |         DT_PWMS_CELL_BY_IDX(node_id, idx, period)
      |         ^~~~~~~~~~~~~~~~~~~
/home/chethan/zephyrproject/zephyr/include/zephyr/drivers/pwm.h:260:27: note: in expansion of macro 'DT_PWMS_PERIOD_BY_IDX'
  260 |                 .period = DT_PWMS_PERIOD_BY_IDX(node_id, idx),                 \
      |                           ^~~~~~~~~~~~~~~~~~~~~
/home/chethan/zephyrproject/zephyr/include/zephyr/drivers/pwm.h:326:34: note: in expansion of macro 'PWM_DT_SPEC_GET_BY_IDX'
  326 | #define PWM_DT_SPEC_GET(node_id) PWM_DT_SPEC_GET_BY_IDX(node_id, 0)
      |                                  ^~~~~~~~~~~~~~~~~~~~~~
/home/chethan/GCB_rnd/BLDC/teensy_pwm_test/servo_motor/src/main.c:16:40: note: in expansion of macro 'PWM_DT_SPEC_GET'
   16 | static const struct pwm_dt_spec pwm1 = PWM_DT_SPEC_GET(DT_ALIAS(pwm1));
      |                                        ^~~~~~~~~~~~~~~
/home/chethan/zephyrproject/zephyr/include/zephyr/devicetree.h:237:25: note: in expansion of macro 'DT_CAT'
  237 | #define DT_ALIAS(alias) DT_CAT(DT_N_ALIAS_, alias)
      |                         ^~~~~~
/home/chethan/GCB_rnd/BLDC/teensy_pwm_test/servo_motor/src/main.c:16:56: note: in expansion of macro 'DT_ALIAS'
   16 | static const struct pwm_dt_spec pwm1 = PWM_DT_SPEC_GET(DT_ALIAS(pwm1));
      |                                                        ^~~~~~~~
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /usr/bin/cmake --build /home/chethan/GCB_rnd/BLDC/teensy_pwm_test/servo_motor/build
chethan@Chethan:~/GCB_rnd/BLDC/teensy_pwm_test/servo_motor$ 

``````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````

i would be grateful if someone assist me on the same. 
[overlay.txt](https://github.com/user-attachments/files/16892925/overlay.txt)


* Page: `amples/basic/servo_motor`
* Version: 3.5.0

**Comment by henrikbrixandersen** [comment] 2024-09-10 10:51
> * Version: 3.5.0

Zephyr version 3.5.0 is no longer supported. Can you reproduce this on either v3.7.0 or current `main` branch?

**Comment by bdkrae** [comment] 2024-09-10 20:20
With current `main` branch the overlay file `teensy41.overlay` for `samples/basic/servo_motor` should look something like this:

```
/ {
	servo: servo {
		compatible = "pwm-servo";
		pwms = <&flexpwm2_pwm2 1 PWM_MSEC(20) PWM_POLARITY_NORMAL>;
		min-pulse = <PWM_USEC(700)>;
		max-pulse = <PWM_USEC(2500)>;
	};
};

&pinctrl {
	pinmux_flexpwm_ch1: pinmux_flexpwm_ch1 {
		group0 {
			pinmux = <&iomuxc_gpio_b0_11_flexpwm2_pwmb2>;
			drive-strength = "r0-7";
			slew-rate = "fast";
			nxp,speed = "200-mhz";
		};
	};
};

&flexpwm2_pwm2 {
	status = "okay";
	pinctrl-0 = <&pinmux_flexpwm_ch1>;
	pinctrl-names = "default";
	nxp,prescaler = <64>;
};
```

FlexPWM peripheral is not active per default for teensy board, so you have to do that in this file. Also you need a pinmapping, in this example its mapped to `gpio_b0_11` which you will find on boards `pin 9`.

**Comment by mmahadevan108** [comment] 2024-09-25 18:36
@Chethan-TS did you get a chance to try the suggestion from @bdkrae

**Comment by Chethan-TS** [comment] 2024-09-26 04:39
thanks for the response @bdkrae .

yes, @mmahadevan108 i did try with the current **main** branch . in his particular overlay, flexpwm2_pwmb2 has been used and it worked well and fine for the above mentioned example , when i try to use other available pwm's only few worked.

i do not know the reason, it would be helpful it i get clarification on the same.

 
![T4 1-Cardlike](https://github.com/user-attachments/assets/7d961bdc-a47b-482f-840d-89b4d316363a)

**Comment by bdkrae** [comment] 2024-09-30 19:50
Here is an extended example for `teensy41.overlay`. Maybe this helps to clarify the principle. If you still experience problems please provide more details on which pins it fails.

```
/ {
	servo: servo {
		compatible = "pwm-servo";
		// pwms = <&flexpwm2_pwm0 1 PWM_MSEC(20) PWM_POLARITY_NORMAL>; // flexpwm2 ch0 output B -> teensy pin 33
		// pwms = <&flexpwm2_pwm0 0 PWM_MSEC(20) PWM_POLARITY_NORMAL>; // flexpwm2 ch0 output A -> teensy pin 4
		// pwms = <&flexpwm2_pwm2 0 PWM_MSEC(20) PWM_POLARITY_NORMAL>; // flexpwm2 ch2 output A -> teensy pin 6
		// pwms = <&flexpwm4_pwm2 1 PWM_MSEC(20) PWM_POLARITY_NORMAL>; // flexpwm4 ch2 output B -> teensy pin 3
		pwms = <&flexpwm3_pwm1 1 PWM_MSEC(20) PWM_POLARITY_NORMAL>; // flexpwm3 ch1 output B -> teensy pin 28
		min-pulse = <PWM_USEC(700)>;
		max-pulse = <PWM_USEC(2500)>;
	};
};

&pinctrl {
    pinmux_flexpwm2_ch0: pinmux_flexpwm2_ch0 {
        group0 {
            pinmux = <&iomuxc_gpio_emc_06_flexpwm2_pwma0>, //output A
                    <&iomuxc_gpio_emc_07_flexpwm2_pwmb0>; //output B
            drive-strength = "r0-7";
            slew-rate = "fast";
            nxp,speed = "200-mhz";
        };
    };
	pinmux_flexpwm2_ch2: pinmux_flexpwm2_ch2 {
		group0 {
			pinmux = <&iomuxc_gpio_b0_10_flexpwm2_pwma2>, //output A
                    <&iomuxc_gpio_b0_11_flexpwm2_pwmb2>; //output B
			drive-strength = "r0-7";
			slew-rate = "fast";
			nxp,speed = "200-mhz";
		};
	};
	pinmux_flexpwm4_ch2: pinmux_flexpwm4_ch2 {
		group0 {
			pinmux = <&iomuxc_gpio_emc_04_flexpwm4_pwma2>, //output A
                    <&iomuxc_gpio_emc_05_flexpwm4_pwmb2>; //output B
			drive-strength = "r0-7";
			slew-rate = "fast";
			nxp,speed = "200-mhz";
		};
	};
	pinmux_flexpwm3_ch1: pinmux_flexpwm3_ch1 {
		group0 {
			pinmux = <&iomuxc_gpio_emc_32_flexpwm3_pwmb1>; //output A
			drive-strength = "r0-7";
			slew-rate = "fast";
			nxp,speed = "200-mhz";
		};
	};
};

&flexpwm2_pwm0 {
	status = "okay";
	pinctrl-0 = <&pinmux_flexpwm2_ch0>;
	pinctrl-names = "default";
	nxp,prescaler = <64>;
};

&flexpwm2_pwm2 {
	status = "okay";
	pinctrl-0 = <&pinmux_flexpwm2_ch2>;
	pinctrl-names = "default";
	nxp,prescaler = <64>;
};

&flexpwm4_pwm2 {
	status = "okay";
	pinctrl-0 = <&pinmux_flexpwm4_ch2>;
	pinctrl-names = "default";
	nxp,prescaler = <64>;
};

&flexpwm3_pwm1 {
	status = "okay";
	pinctrl-0 = <&pinmux_flexpwm3_ch1>;
	pinctrl-names = "default";
	nxp,prescaler = <64>;
};
```

**Comment by mmahadevan108** [comment] 2024-11-06 23:31
@Chethan-TS , can we close this issue?

**Comment by henrikbrixandersen** [comment] 2024-12-29 10:33
Closing due to lack of response.

**Closed** 2024-12-29 10:33 UTC
Labels: bug, priority: low, area: PWM
