### ISSUE TITLE
Enable flash_shell on all platforms with a flash_driver

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#14994] opened 2019-03-28 16:17 UTC
There's an old PR for doing this here:

PR #13702

We probably need a mix of board support and Kconfig to determine if the sample is valid.

**Comment by de-nordic** [comment] 2022-07-21 14:18
@galak The #13702 has been merged, so the issue is solved?

**Comment by de-nordic** [comment] 2024-02-23 12:34
Seems to be solved at lest since https://github.com/zephyrproject-rtos/zephyr/commit/a8d3c8e142e2a4a8ec9fb52bf0aa42ee2c7fd7cc
prior to v2.5.0-rc1, closing.

**Closed by de-nordic** 2024-02-23 12:34 UTC
Labels: Enhancement, area: Flash, area: Shell
