### ISSUE TITLE
unexpected eof in qemu_cortex and mps2

### ISSUE THREAD

**Issue by 1xlibiao** [zephyrproject-rtos/zephyr#49004] opened 2022-08-12 09:00 UTC
**Describe the bug**
The tests/subsys/logging/log_backend_init falied on qemu_cortex and mps2.

**Observed for**
 - qemu_cortex_m0
 - qemu_cortex_m3
 - mps2_an385
 - mps3_an547
 - mps2_an521
 
 **To Reproduce**

1. have qemu_cortex_m0 or mps2
2. go to your zephyr dir
3. use twister -p qemu_cortex_m0 -T tests/subsys/logging/log_backend_init -vv 
4. see error:
**tests/subsys/logging/log_backend_init/logging.log_backend_initialization FAILED unexpected eof (qemu 0.269s)**

**Logs and console output**
```
INFO    - /__w/zephyr/zephyr/twister-out/qemu_cortex_m3/tests/subsys/logging/log_backend_init/logging.log_backend_initialization/handler.log
INFO    - 114/462 qemu_cortex_m0            
tests/subsys/logging/log_backend_init/logging.log_backend_initialization FAILED unexpected eof (qemu 0.269s)
INFO    - /__w/zephyr/zephyr/twister-out/qemu_cortex_m0/tests/subsys/logging/log_backend_init/logging.log_backend_initialization/handler.log
ERROR   - *** Booting Zephyr OS build zephyr-v3.1.0-3289-g0066254f5650  ***
Running TESTSUITE log_backend_init
===================================================================
START - test_log_backends_initialization
 PASS - test_log_backends_initialization in 2.217 seconds
===================================================================
TESTSUITE log_backend_init succeeded
===================================================================
RunID: ca515[183](https://github.com/zephyrproject-rtos/zephyr/runs/7760052717?check_suite_focus=true#step:12:184)eafc8f3faad76f3742dcb209
PROJECT EXECUTION SUCCESSFUL

```

**Advice**
Comment out the LOG_PANIC() of 943 lines https://github.com/zephyrproject-rtos/zephyr/blob/f5378424f7f492a8ae0d173a015bc1186fcc7127/subsys/testsuite/ztest/src/ztest_new.c#L943

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain - SDK 14.1
 - Commit SHA  https://github.com/zephyrproject-rtos/zephyr/pull/48848

**Comment by nashif** [comment] 2022-08-23 21:46
The log is showing a successful run, so I am not sure what the issue is.

**Comment by 1xlibiao** [comment] 2022-08-24 02:05
> The log is showing a successful run, so I am not sure what the issue is.

log error update

**Comment by mengxianglinx** [comment] 2022-08-24 08:38
Not aware of why "LOG_PANIC()" in ztest_new.c, but that need all log_backend implement "panic" interface, if not, access to NULL pointer will cause crash,  "unexpected eof" will come up.

**Comment by hwang37** [comment] 2022-09-06 23:16
@1xlibiao @mengxianglinx  could you continue updating and working on this bug?

**Comment by mengxianglinx** [comment] 2022-09-07 02:20
By implementing panic() interface for log_backend, the "unexpected eof" issue of some qemu platform disappears. close it.

**Closed by mengxianglinx** 2022-09-07 02:20 UTC
Labels: bug, priority: low, area: ARM, area: Logging
