### ISSUE TITLE
samples: drivers: mbox: samples/drivers/mbox/sample.drivers.mbox.real_hw fails at nrf5340

### ISSUE THREAD

**Issue by nordic-piks** [zephyrproject-rtos/zephyr#72712] opened 2024-05-14 07:01 UTC
**Describe the bug**
The samples/drivers/mbox/sample.drivers.mbox.real_hw

Observed for
- nrf5340dk/nrf5340/cpuapp

**To Reproduce**
1. have nrf5340dk/nrf5340/cpuapp connected
2. go to your zephyr dir
3. call ./scripts/twister -T samples/drivers/mbox -p nrf5340dk/nrf5340/cpuapp --device-testing --device-serial /dev/ttyACM0 -v --inline-logs
4. See console output with error

**Expected behavior**
Valid console output

**Impact**
Not clear

**Logs and console output**
```
[2024-05-13T17:47:11.912Z] *** Booting Zephyr OS build v3.6.0-3768-g961959fc5f2b ***
[2024-05-13T17:47:11.912Z] Hello from APP
[2024-05-13T17:47:11.912Z] Pong (on channel 0)
[2024-05-13T17:47:11.912Z] Ping (on channel 1)
[2024-05-13T17:47:11.912Z] Pong (on channel 0)
[2024-05-13T17:47:11.912Z] Ping (on channel 1)
[2024-05-13T17:47:11.912Z] Ping (on channel 1)
[2024-05-13T17:47:11.912Z] Pong (on channel 0)
[2024-05-13T17:47:11.912Z] Ping (on channel 1)
[2024-05-13T17:47:11.912Z] Pong (on channel 0)
[2024-05-13T17:47:11.912Z] Ping (on channel 1)
[2024-05-13T17:47:11.912Z] Ping (on channel 1)
[2024-05-13T17:47:11.912Z] Pong (on channel 0)
[2024-05-13T17:47:11.912Z] Ping (on channel 1)
[2024-05-13T17:47:11.912Z] Pong (on channel 0)
```
But there is expected (from sample.yaml):
```
        - "Ping \\(on channel 0\\)"
        - "Pong \\(on channel 0\\)"
        - "Ping \\(on channel 1\\)"
        - "Pong \\(on channel 1\\)"
```
So there is missing ping on channel 0 and pong on channel 1

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Toolchain Zephyr SDK 0.16.5
 - Commit SHA or Version used: v3.6.0-3768-g961959fc5f2b

**Comment by gmarull** [comment] 2024-07-11 13:49
Duplicate of https://github.com/zephyrproject-rtos/zephyr/issues/70307

**Closed by gmarull** 2024-07-11 13:49 UTC
Labels: bug, priority: low, platform: nRF
