### ISSUE TITLE
get_maintainer.py is broken

### ISSUE THREAD

**Issue by mbolivar-nordic** [zephyrproject-rtos/zephyr#37586] opened 2021-08-10 19:02 UTC
**Describe the bug**

This can't be used to get the maintainer for a path.

**To Reproduce**

`$ ./scripts/get_maintainer.py path .`

This reports an error about some random line in the MAINTAINERS.yml file. If you fix the error and run it again, you will get another error. This keeps happening for many lines in the file, so either we've just never used this script and it doesn't actually work or the file is malformed.

**Comment by mbolivar-nordic** [comment] 2021-08-10 19:04
@nashif you're listed in CODEOWNERS for get_maintainer.py; am I just holding it wrong?

**Comment by mbolivar-nordic** [comment] 2021-08-10 19:08
Concrete example: 

```
$ ./scripts/get_maintainer.py path drivers/i2c/i2c_tca9546a.c 
./scripts/get_maintainer.py: error: /home/mbolivar/zp/zephyr/MAINTAINERS.yml: glob pattern 'arch/arm/aarch32/' in 'files' in area 'ARM arch' does not match any files
```

**Comment by aescolar** [comment] 2021-08-11 11:47
Duplicate of #32531 :)

**Closed** 2021-08-11 11:54 UTC
Labels: bug, TSC, Meta
