### ISSUE TITLE
rb_tree misbehaves with multiple nodes that compare equal

### ISSUE THREAD

**Issue by cjswright** [zephyrproject-rtos/zephyr#66245] opened 2023-12-06 21:07 UTC
**Describe the bug**

I am using the rbtree to manage tasks in a scheduler where tasks are sorted by deadline, and it's possible that two tasks have the same deadline.

The rbtree rb_remove() implementation appears to not be robust to items being inserted that compare the same.

Code:
```c
struct rbnode *node;

node = rb_get_min(&queue);

if (node == NULL)
	break;

rb_remove(&queue, node);
if (rb_contains(&queue, node))
	k_panic();

```

If the RB tree has several nodes inserted where lessthan_fn(a, b) == lessthan_fn(b, a) == false, i.e. a == b, then the rb_remove does not work and the k_panic() above can hit. I reliably hit the issue with four nodes inserted which all compare equal.

I'm testing this on ARM on nRF5340, but I believe the bug should be present on any system.

My compare function, with workaround that resolves the issue:
```c
typedef struct msg_queue_msg_t
{
	struct rbnode rbnode;
	uint32_t deadline;
} msg_queue_msg_t;

bool 
lessthan_fn(struct rbnode *a, struct rbnode *b)
{
	struct msg_queue_msg_t *a_c = CONTAINER_OF(a, msg_queue_msg_t, rbnode);
	struct msg_queue_msg_t *b_c = CONTAINER_OF(b, msg_queue_msg_t, rbnode);

	/* Workaround for rbtree not robust to nodes comparing equal */
	if (a_c->deadline == b_c->deadline)
		return a < b;

	return a_c->deadline < b_c->deadline;
}

```

I did some sleuthing and it appears the issue is in the find_and_stack() function, which uses a binary search to find the node to remove.

**Expected behavior**
Some options (not mutually exclusive)
1) find_and_stack() should detect that two nodes are equal and do a more thorough search of the tree than assuming that lessthan_fn == false must mean that the child is in the right tree. Has some impact on performance in degenerate cases where every node in the tree compares equal.
2) the rbtree implementation could detect that two nodes compare equal and tiebreak itself, comparing the pointer values as I have in my compare function above. It would need to do this on every call to lessthan_fn.
3) rbtree detects that two nodes compare equal and asserts
4) documentation is updated to explain that the lessthan_fn must resolve tie breaks

**Impact**
Low, have workaround/solution

**Environment (please complete the following information):**
 - OS: Linux
 - West, simple blinky example from NRF Connect SDK
 - SHA: zephyr 1687aaaac2

**Comment by peter-mitsis** [comment] 2023-12-12 02:48
In the red/black tree documentation (https://docs.zephyrproject.org/latest/kernel/data_structures/rbtree.html#balanced-red-black-tree), it states in reference to the behaviour of the _lessthan_fn_ ...

> Note that “equal” is not allowed, nodes within a tree must have a single fixed order for the algorithm to work correctly.

Based upon the existing documentation, and a brief review of a couple of its uses in Zephyr, I am leaning towards taking no further action and closing this issue.

**Comment by cjswright** [comment] 2023-12-12 03:31
Okay, yes, I didn't see that.

It'd be nice I think if this was clear in the documentation for rb_lessthan_t, but I'm okay as well if you'd rather close it.

**Comment by andyross** [comment] 2023-12-12 04:36
Yeah, not a bug.  You can't write a binary tree without a well-defined order, the binary search doesn't work (or it could be made to do so, but it's no longer O(logN) so you'd fail your exam).

**Closed by andyross** 2023-12-12 04:36 UTC
Labels: bug, area: Kernel
