### ISSUE TITLE
How to make Zephyr as a ble mesh provisioner ?

### ISSUE THREAD

**Issue by rahul30694** [zephyrproject-rtos/zephyr#17726] opened 2019-07-23 11:28 UTC
**Describe the bug**
What have you tried to diagnose or workaround this issue?

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=board\_xyz
3. make

**Expected behavior**

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Screenshots or console output**
If applicable, add a screenshot (drag-and-drop an image), or console logs
(cut-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue.

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Additional context**

**Comment by carlescufi** [comment] 2019-07-23 11:37
Duplicate of #17727

**Closed by carlescufi** 2019-07-23 11:37 UTC
Labels: bug
