### ISSUE TITLE
error: initializer element is not constant .attr = K_MEM_PARTITION_P_RX_U_RX

### ISSUE THREAD

**Issue by alexisc67** [zephyrproject-rtos/zephyr#31008] opened 2020-12-26 09:21 UTC
**Describe the bug**
Find an error when building a basic sample Blinky for the Thingy:52.
Here is the error:
zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c:77:3: error: initializer element is not constant
   .attr = K_MEM_PARTITION_P_RX_U_RX,
   ^
zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c:77:3: error: (near initialization for 'static_regions[0].attr')

**To Reproduce**
1. Run in the command line: west build -p auto -b thingy52_nrf52832 samples/basic/blinky

**Expected behavior**
Complete build

**Impact**
showstopper

**Logs and console output**
zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c:77:3: error: initializer element is not constant
   .attr = K_MEM_PARTITION_P_RX_U_RX,
   ^
zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c:77:3: error: (near initialization for 'static_regions[0].attr')

**Environment (please complete the following information):**
 - MacOS
 - Toolchain GNUARMEMB
 - Zephyr version: 2.4.99

**Additional context**
![image](https://user-images.githubusercontent.com/12430569/103148830-2223b800-4764-11eb-9c06-e169b1569f37.png)

**Comment by pabigot** [comment] 2020-12-26 15:04
Which version of ARM embedded are you using?  I'm unable to reproduce this on Linux at current master head 4ca7942411 with either gcc-arm-none-eabi-9-2020-q2-update or gcc-arm-none-eabi-10-2020-q4-major.

**Comment by ioannisg** [comment] 2021-01-04 10:18
will take a look

**Comment by ioannisg** [comment] 2021-01-25 08:58
@alexisc67 I cannot reproduce this either, at current master (7b9b3cfe5a129580ec97c40e7a98d2fab07fa78c)

**Comment by carlescufi** [comment] 2021-01-26 18:20
Unable to reproduce, closing. Feel free to reopen if this is still an issue.

**Closed by carlescufi** 2021-01-26 18:20 UTC
Labels: area: Memory Protection, bug, priority: medium
