### ISSUE TITLE
tunslip6: main: open: No such file or directory

### ISSUE THREAD

**Issue by lorepieri8** [zephyrproject-rtos/zephyr#15706] opened 2019-04-27 00:05 UTC
**Describe the bug**
Trying to follow https://docs.zephyrproject.org/1.13.0/subsystems/networking/qemu_setup.html in docker (Ubuntu 18.04) I fail to complete step 2 without errors.

**To Reproduce**
1. In terminal 2, ./loop-socat.sh
2. In terminal 3, sudo ./loop-slip-tap.sh

**Expected behavior**
Unknown. (Not specified in the link above)

EDIT: 
In a Digital Ocean linux instance I get:
```
********SLIP started on ``/tmp/slip.dev''
slipfd and inslip reopened
ip neigh flush dev tap0
Cannot find device "tap0"
opened tap device ``/dev/tap0''
ifconfig tap0 up
ip -6 route add 2001:db8::/64 dev tap0
ip -6 addr add 2001:db8::2/64 dev tap0
ip route add 192.0.2.0/24 dev tap0
ip addr add 192.0.2.2/24 dev tap0
ifconfig tap0

tap0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.0.2.2  netmask 255.255.255.0  broadcast 0.0.0.0
        inet6 2001:db8::2  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::c437:baff:fe5f:5f78  prefixlen 64  scopeid 0x20<link>
        ether c6:37:ba:5f:5f:78  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Screenshots or console output**

Infinite loop of:

```
********SLIP started on ``/tmp/slip.dev''
slipfd and inslip reopened
ip neigh flush dev tap0
Cannot find device "tap0"
tunslip6: main: open: No such file or directory
```

**Environment (please complete the following information):**
 - OS: docker, Ubuntu 18.04

**Additional info**
The same procedure works on a Digital Ocean linux instance. So I suspect that docker is missing some packages.

**Comment by jukkar** [comment] 2019-05-01 16:53
Instead of SLIP, you might want to try real Ethernet driver like e1000 in QEMU. See https://docs.zephyrproject.org/1.14.0/guides/networking/networking_with_host.html and  https://docs.zephyrproject.org/1.14.0/guides/networking/qemu_eth_setup.html#networking-with-eth-qemu for details.

This issue seems to be related to docker instead of zephyr, so removing the bug label.

**Comment by nashif** [comment] 2019-05-07 12:10
leave it as a bug please, if it is not a bug in zephyr, it should be closed instead or filed in the right place.

**Comment by lorepieri8** [comment] 2019-05-08 10:39
@jukkar 

On Digital Ocena I get

```
root@lorenzoPractice:~/zephyr_networking/net-tools# ./net-setup.sh
Using ./zeth.conf configuration file.
Creating zeth
RTNETLINK answers: File exists
```

while on Docker:

```
root@3e5b46fa1a8b:/net-tools# ./net-setup.sh 
Using ./zeth.conf configuration file.
Creating zeth
open: No such file or directory
Cannot find device "zeth"
Cannot find device "zeth"
Cannot find device "zeth"
Cannot find device "zeth"
Cannot find device "zeth"
```

**Comment by jukkar** [comment] 2019-05-13 20:59
Perhaps you have something incorrectly setup in the docker image so that the `ip tuntap add zeth mode tap` fails. Can you try to run it manually and see what errors it will print.
Closing this one for now as this does not seem to be related to issue in zephyr.

**Closed by jukkar** 2019-05-13 20:59 UTC
Labels: area: Networking, bug

**Comment by lorepieri8** [comment] 2019-05-17 18:52
@jukkar 
It was indeed some networking capability missing in docker. Using

`docker run --cap-add=NET_ADMIN --device /dev/net/tun:/dev/net/tun  -it f69f013e46ef /bin/bash`

where `f69f013e46ef` is the CONTAINER ID will fix it.

**Comment by ouaaliw** [comment] 2024-02-29 11:35
ip tuntap add zeth mode tap
open: No such file or directory  
i am using WSL, i didn't understand this error. maybe because of the kernel limitation of WSL!!
