### ISSUE TITLE
importing zscilib into existing zephyr project

### ISSUE THREAD

**Issue by Ananyaaynana** [zephyrproject-rtos/zephyr#57152] opened 2023-04-22 18:31 UTC
I am trying to include the zscilib module in my project. In the west.yml file of my app directory I have added under name-whitelist "-zscilib" to import the module.

This is the west.yml file of my application.
`# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: libresolar
      url-base: https://github.com/LibreSolar
    - name: thingset
      url-base: https://github.com/ThingSet
    - name: throwtheswitch
      url-base: https://github.com/ThrowTheSwitch
  projects:
    - name: zephyr
      remote: libresolar
      revision: v3.2-branch
      import:
        name-whitelist:
          - cmsis
          - edtt
          - hal_espressif
          - hal_stm32
          - tinycrypt
          - zscilib
    - name: oled-display-library
      remote: libresolar
      revision: 523b26c103de56714fcda655702d600870a671bc
      path: modules/oled-display
    - name: thingset-zephyr-sdk
      remote: thingset
      revision: adb1accd280ef91668bd592233dde3e42195e9b9
      path: thingset-zephyr-sdk
      import:
        name-whitelist:
          - thingset-device-library
    - name: unity
      remote: throwtheswitch
      revision: 74cde089e65c3435ce9aa87d5c69f4f16b7f6ade
      path: modules/unity`

In the Kconfig.zscilib file I have changed the default value from "n" to "y".

`
config ZSL
	bool "Zephyr scientific library support"
	default y
	help
	  This option enables the zephyr scientific library.

if ZSL

config ZSL_SINGLE_PRECISION
	bool "Use single-precision floats."
	default y
	help
	  Enabling this option will cause all zsl functions to use single
	  precision (32-bit) floating point values, rather than the default of
	  double-precision (64-bits).

config ZSL_PLATFORM_OPT
	int "Platform optimisations"
	default 0
	range 0 2
	help
	  Platform used for optimised assembly functions where possible.
	  0 None
	  1 ARM Thumb (GNU)
	  2 ARM Thumb2 (GNU)

config ZSL_VECTOR_INLINE
	bool "Use inline vector functions."
	default y
	help
	  Enabling this option will cause common vector functions to use inline
	  versions, avoiding the overhead of function calls at the expense of
	  a larger firmware image.

config ZSL_MATRIX_INLINE
	bool "Use inline matrix functions."
	default y
	help
	  Enabling this option will cause common matrix functions to use inline
	  versions, avoiding the overhead of function calls at the expense of
	  a larger firmware image.
	
config ZSL_BOUNDS_CHECKS
	bool "Enable bounds checking in functions."
	default y
	help
	  Enabling this option will cause common functions to ensure that requested
	  data is within the bounds of the vector, matrix, etc. object. This should
	  generally always be enabled for safety reasons, but you may wish to
	  disable it in exceptional circumstances for performance reasons.

	  Note that the performance gains from enabling inline functions will
	  generally be greater than the benefit of disabling bounds checks, and
	  with far less risk associated with the decision.

	  EXTREME CARE should be taken when disabling this option since it can
	  easily lead to stack corruption and critical firmware failures. This
	  should only be disabled as a final option, and only on known-good
	  and thoroughly tested code.

config ZSL_SHELL
	bool "Enable the 'zsl' shell command and core shell support"
	default y
	depends on SHELL
	help
	  Enabling this option will make the 'zsl' shell command available, and
	  enable general zscilib shell support.

config ZSL_SHELL_CLR
	bool "Enable the 'color' shell command"
	default y
	depends on ZSL_SHELL
	help
	  Enabling this option will make the 'color' shell command available.

config ZSL_SHELL_ORIENT
	bool "Enable the 'orient' shell command"
	default y
	depends on ZSL_SHELL
	help
	  Enabling this option will make the 'orient' shell command available.

config ZSL_CLR_RGBF_BOUND_CAP
	bool "Limit RGB float values to the 0.0..1.0 range"
	default y

endif`

In the menuconfig I am not able to enable this module as there is no zscilib module option available in "modules-->" in the menuconfig.

I have cloned the zscilib modules in the modules folder. The folder tree of my project is:
west-workspace
    ---bms-firmware
    ---modules
    ---thingset zephyr-sdk
    ---tools
    ---zephyr

In the prj.conf file of my app I have included the command "CONFIG_ZSL = y"

When I run a west build using the command on the terminal:
>>west build -b bms_c1
 I am getting this error:
`/home/ananya/west-workspace3/bms-firmware/app/prj.conf:32: warning: attempt to assign the value 'y' to the undefined symbol ZSL
Parsing /home/ananya/west-workspace3/bms-firmware/app/Kconfig
Loaded configuration '/home/ananya/west-workspace3/bms-firmware/boards/riscv/bms_c1/bms_c1_defconfig'
Merged configuration '/home/ananya/west-workspace3/bms-firmware/app/prj.conf'
Merged configuration '/home/ananya/west-workspace3/bms-firmware/app/boards/bms_c1.conf'

error: Aborting due to Kconfig warnings

CMake Error at /home/ananya/west-workspace3/zephyr/cmake/modules/kconfig.cmake:326 (message):
  command failed with return code: 1
Call Stack (most recent call first):
  /home/ananya/west-workspace3/zephyr/cmake/modules/zephyr_default.cmake:108 (include)
  /home/ananya/west-workspace3/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
  /home/ananya/west-workspace3/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:97 (include_boilerplate)
  CMakeLists.txt:7 (find_package)

-- Configuring incomplete, errors occurred!
FAILED: build.ninja 
/usr/bin/cmake --regenerate-during-build -S/home/ananya/west-workspace3/bms-firmware/app -B/home/ananya/west-workspace3/bms-firmware/app/build
ninja: error: rebuilding 'build.ninja': subcommand failed
FATAL ERROR: command exited with status 1: /usr/bin/cmake --build /home/ananya/west-workspace3/bms-firmware/app/build
`
According to the zephyr documentary it is enough to enable the default value under "config ZSL" in the Kconfig file in the app directory and in prj.conf file "CONFIG_ZSL = y" should be added which I have done. I have followed all the steps yet I am getting this error. I am new to Zephyr. What am I missing here?

**Comment by nordicjm** [comment] 2023-04-24 06:40
> I have cloned the zscilib modules in the modules folder. The folder tree of my project is:

This is wrong, you do not clone modules, you use `west` for getting and updating modules, please read https://docs.zephyrproject.org/latest/develop/west/basics.html#west-update-basics and https://docs.zephyrproject.org/latest/develop/west/built-in.html#west-update and https://docs.zephyrproject.org/latest/develop/application/index.html for details.

Closing as user error, not a bug.

**Closed by nordicjm** 2023-04-24 06:40 UTC
