### ISSUE TITLE
bluetooth: audio: BAP Unicast Client only discovers 1 of each type of PAC record

### ISSUE THREAD

**Issue by Chris-StJohn-Bose** [zephyrproject-rtos/zephyr#80861] opened 2024-11-04 17:35 UTC
https://github.com/zephyrproject-rtos/zephyr/blob/23fb3b77a2b2cf53eff1697888f443236069b30c/subsys/bluetooth/audio/bap_unicast_client.c#L4405

PACS servers may have multiple PAC characteristic of each type source/sink:

> **PACS v1.0.1 Section 3.1**
> (..)
> When the server supports reception of audio data, the decision to expose all supported PAC records
> within a single Sink PAC characteristic or multiple Sink PAC characteristics is left to the implementation.
> 

`unicast_client_pac_discover_cb()` always returns `BT_GATT_ITER_STOP` so only the first one is found.

**Comment by Thalley** [comment] 2024-11-05 07:40
This looks like a duplicate of https://github.com/zephyrproject-rtos/zephyr/issues/70826. Can you confirm @Chris-StJohn-Bose ?

**Comment by Chris-StJohn-Bose** [comment] 2024-11-06 19:30
> This looks like a duplicate of #70826. Can you confirm @Chris-StJohn-Bose ?

Yes I think this is a duplicate @Thalley

**Comment by Thalley** [comment] 2024-11-06 19:40
Closing as duplicate then :)

**Closed by Thalley** 2024-11-06 19:40 UTC
Labels: Enhancement, area: Bluetooth, area: Bluetooth Audio

**Comment by Chris-StJohn-Bose** [comment] 2024-11-07 09:15
thanks @Thalley I'll submit a PR if I get around to fixing it and tag #70826

**Comment by Thalley** [comment] 2024-11-07 11:50
Sounds good. There are also some planned effort from @jthm-ot to make make the PACS client usable for the broadcast assistant as well, so just be aware that the PACS client will likely need to be moved out from the BAP unicast client and into a standalone client usable from both BAP Unicast Client and BAP Broadcast Assistant (or have it's own public API). It does not prevent the above from being added, but just be aware of any changes that may cause merge conflicts
