### ISSUE TITLE
Typo in lines 518 and 554 of subsys/bluetooth/shell/bt.c

### ISSUE THREAD

**Issue by spam-receiver** [zephyrproject-rtos/zephyr#59082] opened 2023-06-08 22:58 UTC
In https://github.com/zephyrproject-rtos/zephyr/commit/028e0a3c8d75fc5e2027f54dbb5a55aadbb1c490 I found:

518 static void static void discon**en**cted_set_new_default_conn_cb(struct bt_conn *conn, void *user_data)
554 bt_conn_foreach(BT_CONN_TYPE_LE, discon**en**cted_set_new_default_conn_cb, NULL);

I think it should be:

518 static void static void discon**ne**cted_set_new_default_conn_cb(struct bt_conn *conn, void *user_data)
554 bt_conn_foreach(BT_CONN_TYPE_LE, discon**ne**cted_set_new_default_conn_cb, NULL);

**Comment by alwa-nordic** [comment] 2023-06-14 10:12
@spam-receiver Thank you for raising this issue. Would you like to submit a PR that corrects this typo?

**Comment by nashif** [comment] 2023-06-14 13:05
@alwa-nordic  please do not remove the bug label, if this is not a bug, close it as a non-bug.

**Comment by spam-receiver** [comment] 2023-06-15 12:34
> @spam-receiver Thank you for raising this issue. Would you like to submit a PR that corrects this typo?

No, I accidentally found this typo.

**Closed** 2023-06-20 10:44 UTC
Labels: bug, priority: low, area: Bluetooth, area: Shell
