### ISSUE TITLE
Linker error with CONFIG_NET_TCP=y

### ISSUE THREAD

**Issue by tfir1981** [zephyrproject-rtos/zephyr#39655] opened 2021-10-22 10:27 UTC
**Describe the bug**
I am using the NUCLEO_F412ZG Board and i want to setup an MQTT-Application with an w5500 mac-phy. Adding step by step my Kconfig-Parameters, i get a linker error after adding CONFIG_NET_TCP.

```properties
CONFIG_MAIN_STACK_SIZE=4096

CONFIG_CPLUSPLUS=y
CONFIG_LIB_CPLUSPLUS=y
CONFIG_STD_CPP11=y
CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_NANO=n
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y

CONFIG_SPI=y

CONFIG_ETH_W5500=y

CONFIG_ETHERNET_LOG_LEVEL_DBG=y

CONFIG_NETWORKING=y
CONFIG_NET_SHELL=y
CONFIG_NET_L2_ETHERNET=y

CONFIG_ENTROPY_GENERATOR=y
CONFIG_TEST_RANDOM_GENERATOR=y

# Networking Config:
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_POSIX_NAMES=n
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=n
CONFIG_NET_TCP=y

# Enable the MQTT Lib
CONFIG_MQTT_LIB=y

# Network address config
CONFIG_NET_CONFIG_SETTINGS=y
# CONFIG_NET_CONFIG_NEED_IPV4=y
CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.0.2.1"
CONFIG_NET_CONFIG_PEER_IPV4_ADDR="192.0.2.2"
```

`CONFIG_MQTT_LIB` implicitly sets `CONFIG_NET_SOCKETS=y`. So far so good. Without `CONFIG_NET_TCP` build is fine. But after turning this switch to `y` i get the linker error below.
Finally i was studying the documentation of [BSD Socket](https://docs.zephyrproject.org/2.6.0/reference/networking/sockets.html) and found some hints concerning libc. 
I build up my Kconfg with the help of the zephyr-samples. So i think `CONFIG_NET_TCP` is necessary for mqtt comminication. 

**Expected behavior**
Build without errors.

**Impact**
showstopper: Cannot build Mqtt-Samples

**Logs and console output**
```bash
Linking .pio/build/my_eval_board/zephyr/firmware-pre.elf
/Project/.piocore/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.bfd: .piocore/packages/toolchain-gccarmnoneeabi/arm-none-eabi/lib/thumb/v7e-m+fp/hard/libc.a(lib_a-fini.o): in function `__libc_fini_array':
fini.c:(.text.__libc_fini_array+0x26): undefined reference to `_fini'
collect2: error: ld returned 1 exit status
*** [.pio/build/my_eval_board/zephyr/firmware-pre.elf] Error 1
```

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 20.04 LTS
 - Toolchain Zephyr 2.6.0 with PlatformIO

**Comment by tfir1981** [comment] 2021-11-01 08:46
Hi,

sorry, that i am so late. This is an DTS-Overlay for a W5500:

```
&spi1 {
	pinctrl-0 = <&spi1_sck_pa5 &spi1_miso_pa6 &spi1_mosi_pa7>;
	status = "okay";
  cs-gpios = <&gpiod 14 GPIO_ACTIVE_LOW>;

  test_spi_w5500: w5500@0 {
    compatible = "wiznet,w5500";
    label = "w5500";
    reg = <0>;
    spi-max-frequency = <0>;
    int-gpios = <&gpiod 15 GPIO_ACTIVE_LOW>;
    reset-gpios = <&gpiof 13 GPIO_ACTIVE_LOW>;
  };
};
```

**Comment by rlubos** [comment] 2021-11-02 10:14
@tfir1981 I've just tested `mqtt_publisher` sample with `nucleo_f412zg` board (Zephyr v2.6.0) with the following changes in the  `prj.conf` file:
```
CONFIG_ETH_W5500=y
CONFIG_SPI=y
```
and the DTS ovelray you've posted  - the sample built just fine, there were no linker error as you've posted. Perpahs it's some environmental issue on your side then? Are you using Zephyr SDK (I'm running Zephyr SDK v0.13.1)?

**Comment by tfir1981** [comment] 2021-11-02 12:05
Hi, thank you for resonse.
The problem is

`CONFIG_NET_TCP` needs `CONFIG_NEWLIB_LIBC_NANO` and
`CONFIG_NEWLIB_LIBC_FLOAT_PRINTF` needs `CONFIG_NEWLIB_LIBC` which i need, too.

The default sample code builds fine. But if you add some `snprintf` or `printf` calls you will get the linker error.

**Comment by rlubos** [comment] 2021-11-02 12:30
> `CONFIG_NET_TCP` needs `CONFIG_NEWLIB_LIBC_NANO`

Where would that requirement come from? I don't see any dependency in `CONFIG_NET_TCP`  to any libc configuration.

Anyway, I'm still not able to reproduce the issue locally. I've added the following to `prj.conf`:
```
CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_NANO=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y
```
and a `printf()` call to the sample and it still builds just fine for me.

**Comment by carlescufi** [comment] 2021-11-17 10:11
Given that this works as intended with vanilla Zephyr but only fails with PlatformIO, I will close this and suggest you open an issue in the PlatformIO bug tracker.

**Closed by carlescufi** 2021-11-17 10:11 UTC
Labels: bug, priority: low, area: Networking

**Comment by tfir1981** [comment] 2021-11-17 10:21
I found out, that the error is on west, too. I have to analyse the Problem later.
