### ISSUE TITLE
tests/benchmarks/timing_info/testcase.yaml#test failed @ nrf52_pca10040

### ISSUE THREAD

**Issue by inakypg** [zephyrproject-rtos/zephyr#1218] opened 2017-08-22 18:22 UTC
```
starting test - Time Measurement
Timing Results: Clock Frequency: 0 MHz
Context switch                             ***** MPU FAULT *****
  Executing thread ID (thread): 0x2000110c
  Faulting instruction address:  0x200024a8
  Instruction Access Violation
Fatal fault in ISR! Spinning...
```

gitrev 4e439653aaaf0c2ab8a4333cebb1e1385905354a

**Comment by nashif** [comment] 2017-08-23 01:52
@carlescufi  FYI

**Comment by youvedeep** [comment] 2017-08-23 04:43
Further there is another thread at GitHub where discussion about this is tracked.

**Comment by youvedeep** [comment] 2017-08-23 04:43
https://github.com/zephyrproject-rtos/zephyr/pull/1095

**Comment by carlescufi** [comment] 2017-08-23 08:12
@nashif I am following up in the #1095 thread, thanks!

**Comment by AdithyaBaglody** [comment] 2017-08-23 08:57
I feel the issue is with the AAPCS for ARM. if the scratch registers are saved it should be okay.

**Comment by nashif** [comment] 2017-08-31 19:13
fixed by #1095

**Closed by nashif** 2017-08-31 19:13 UTC
Labels: bug, priority: medium
