### ISSUE TITLE
bad logic in test_busy_wait of tests/kernel/context

### ISSUE THREAD

**Issue by vonhust** [zephyrproject-rtos/zephyr#25233] opened 2020-05-12 04:19 UTC
in` test_busy_wait`, `rv = k_sem_take(&reply_timeout, K_MSEC(timeout * 2));` is called with a timeout of 40 ms, then in `busy_wait_thread`, for non NIOS2 arch,   the cpu will busy wait > 40 ms,  it means the timeout  of  `reply_timeout`.  so

* k_sem_give(&reply_timeout) is useless, as `reply_timeout` is timeout. It will affect following tests
* `zassert_false(rv, " *** thread timed out waiting for " "k_busy_wait()");` is wrong, as `rv = k_sem_take(&reply_timeout, K_MSEC(timeout * 2));` will return an error code (< 0 )

**Comment by stephanosio** [comment] 2020-05-12 04:22
Duplicate of #25176 and #25194.

Already fixed in #25203.

**Closed** 2020-05-12 04:22 UTC
Labels: Duplicate, bug
