### ISSUE TITLE
Add more networking tests to net-tools test script

### ISSUE THREAD

**Issue by pfl** [zephyrproject-rtos/zephyr#22577] opened 2020-02-07 08:48 UTC
The networking sample test script in scripts/net/run-sample-tests.sh could be enhanced with simple smoke tests for the following features:
* DHCPv4
* IPv4 LL addressing
* DNS
* mDNS, LLMNR
* SNTP
* MQTT

All the features described above would need their respective sample applications to execute the functionality and then exit with a return value of zero if the test was successful and a non-zero one if not. This return value is then picked up by the script and success/failure is reported. 
Each of these features need proper configuration of the respective "server" component in the net-tools image, some may also require additional programs to be added to said image.

Also, if the script itself starts to get overwhelmingly big, consider rewriting it in Python or similar.

**Comment by carlescufi** [comment] 2023-11-15 10:20
Closing as duplicate of https://github.com/zephyrproject-rtos/zephyr/issues/29764

**Closed by carlescufi** 2023-11-15 10:20 UTC
Labels: Enhancement, area: Networking
