### ISSUE TITLE
Backport 'samples: subsys: mgmt: smp_svr: Fix dupicate fs mgmt registration' to 2.7

### ISSUE THREAD

**Issue by lairdjm** [zephyrproject-rtos/zephyr#44619] opened 2022-04-07 07:18 UTC
**Describe the bug**
This is a backport request for the upcoming zephyr 2.7 release to port a fix to the smp_svr sample application which causes an infinite loop when file management is enabled
Original PR: https://github.com/zephyrproject-rtos/zephyr/pull/43868

**Comment by mbolivar-nordic** [comment] 2022-04-12 16:43
Closing as dupe of https://github.com/zephyrproject-rtos/zephyr/issues/43858

**Closed by mbolivar-nordic** 2022-04-12 16:43 UTC
Labels: bug, backport v2.7-branch
