### ISSUE TITLE
call to bt_gatt_hids_init influences execution time of work queue

### ISSUE THREAD

**Issue by ppryga** [zephyrproject-rtos/zephyr#20632] opened 2019-11-12 15:14 UTC
**Describe the bug**
If an application registers gatt services for a first time the bt_gatt_init is called that at the end of the day leads to call to db_hash_store if CONFIG_BT_SETTINGS is enabled. 
That also leads to block of system work queue for a long time if settings are stored in flash.

**Expected behavior**
Is that correct to store the  hash every power up/reset of the application if the same services are registered once again?

**Impact**
It may cause decrease of a flash lifetime if device is restarted very often.
Can't run high frequency works in a system work queue because of lag provided by settins store of db hash.

**Comment by ppryga** [comment] 2019-11-12 22:58
I've added additional information about the issue in update section of description.

**Comment by Vudentz** [comment] 2019-12-13 02:24
I don't really get this one, the stack can only really tell if the services have changed by generating a hash and then proceed to compare to the stored one. As for calling db_hash_store doesn't setting_save_one actually checks if the value is the same and skip any IO, or that is not always the case, in which case we should probably compare to stored_hash before commiting anything.

**Comment by joerchan** [comment] 2019-12-13 09:11
> I don't really get this one, the stack can only really tell if the services have changed by generating a hash and then proceed to compare to the stored one. As for calling db_hash_store doesn't setting_save_one actually checks if the value is the same and skip any IO, or that is not always the case, in which case we should probably compare to stored_hash before commiting anything.

@Vudentz We had the same discussion here in a different issue and the conclusion there was that settings_save would not overwrite if the value was the same.
https://github.com/zephyrproject-rtos/zephyr/issues/20629#issuecomment-562073390

**Comment by mfiumara** [comment] 2020-02-11 22:52
This might be related to #22730.

**Comment by joerchan** [comment] 2020-02-12 09:56
> This might be related to #22730.

That's probably correct. The hash will have to calculated, but should not be stored if not changed.

**Comment by ppryga** [comment] 2020-05-06 09:49
@pdunaj  or @MarekPieta can you verify if the issue sill exist?

**Comment by mfiumara** [comment] 2020-05-06 13:52
@ppryga this is probably resolved in #22730. Could you retest with lastest master and see if the issue is still there?

**Comment by joerchan** [comment] 2020-05-07 09:17
Close this as I was told by @MarekPieta that the issue has been fixed.

**Closed by joerchan** 2020-05-07 09:17 UTC
Labels: area: Bluetooth, bug, priority: low
