### ISSUE TITLE
intel_adsp: tests/kernel/profiling/profiling_api/kernel.common.profiling fails

### ISSUE THREAD

**Issue by majunkier** [zephyrproject-rtos/zephyr#70489] opened 2024-03-20 12:42 UTC
**Describe the bug**
tested on intel_adsp/ boards (cavs25, ace15_mtpm ,ace20_lnl)

```
tests/kernel/profiling/profiling_api/kernel.common.profiling
```

test hangs despite initially promising results. Result is timeout.

**To Reproduce**
` twister --device-testing --hardware-map PATH-TO-HWMAP -s tests/kernel/profiling/profiling_api/kernel.common.profiling`

**Expected behavior**
Test should pass

**Logs and console output**
handler.log

```
*** Booting Zephyr OS build v3.6.0-1236-g8f4ac0d4ab45 ***
Running TESTSUITE profiling_api
I: 0x40042350 (idle 02):	unused 1952	usage 96 / 2048 (4 %)
===================================================================
I: 0x400422a8 (idle 01):	unused 1960	usage 88 / 2048 (4 %)
I: 0x400424f0 (sysworkq):	unused 696	usage 328 / 1024 (32 %)
I: 0x40042200 (idle 00):	unused 1960	usage 88 / 2048 (4 %)
I: 0x400423f8 (main):	unused 1576	usage 472 / 2048 (23 %)
START - test_call_stacks_analyze_main
from main thread:
I: 0x40042150 (test_call_stacks_analyze_main):	unused 1376	usage 416 / 1792 (23 %)
I: 0x40042350 (idle 02):	unused 1960	usage 88 / 2048 (4 %)
I: 0x400422a8 (idle 01):	unused 1848	usage 200 / 2048 (9 %)
I: 0x400424f0 (sysworkq):	unused 696	usage 328 / 1024 (32 %)
I: 0x40042200 (idle 00):	unused 1960	usage 88 / 2048 (4 %)
I: 0x400423f8 (main):	unused 1408	usage 640 / 2048 (31 %)
PASS - test_call_stacks_analyze_main in 0.002 seconds
===================================================================
TESTSUITE profiling_api succeeded
Running TESTSUITE profiling_api_1cpu
===================================================================
START - test_call_stacks_analyze_idle
from idle thread:
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Version used: v3.6.0-1236-g8f4ac0d4ab45

**Comment by nashif** [comment] 2024-03-20 13:29
duplicate of #70494

**Closed by nashif** 2024-03-20 13:29 UTC
Labels: bug, platform: Intel ADSP
