### ISSUE TITLE
twister: Mechanism to pass CLI args through to ztest executable

### ISSUE THREAD

**Issue by tristan-google** [zephyrproject-rtos/zephyr#52167] opened 2022-11-10 20:02 UTC
Individual test executables built with ztest have a number of useful settings that can be configured using CLI args. These include setting the seed for the test shuffler, filtering test suites and cases, adjusting the execution time, etc...:
 
```
$ twister-out/native_posix/.../.../zephyr/zephyr.exe -h
[-h] [--h] [--help] [-?] [-rt] [-no-rt] [-rt-drift=<dratio>] [-rt-ratio=<ratio>] 
[-rtc-offset=<time_offset>] [-rtc-reset] [-stop_at=<time>] [-flash=<path>] [-list] 
[-test=<suite::test>] [-color] [-no-color] [-force-color] [-testargs <arg>...]
```
 
Currently, Twister's own CLI has a `--seed` option that gets passed down to the tests, but there does not appear to be a mechanism for passing other arguments through to ztest. The best workaround is to run `./twister --build-only` and then invoke the resulting `zephyr.exe` executable(s) manually, but this defeats most of the benefits of having Twister.
 
Since ztest and twister are meant to be used together, I'd like to propose adding a mechanism to Twister to allow passing additional CLI args through to ztest binaries. One strategy is to add a separator flag like so: `./twister <twister args> [-- <ztest args>]` and forward everything following the double dash to the test binary. Alternatively, we could do it the way we handle extra CMake args: `./twister <twister args> -Z=<ztest_arg_name>=<ztest_arg_value>`. I don't think it's a good idea to add individual CLI options to Twister for each of the ztest options as this will be difficult to maintain going forward and because Twister already has a lot.

While the above is mostly intended for unit / native_posix tests running on the host via the BinaryHandler, the DeviceHandler could make use of the additional args by passing them in to `west flash` in case users wish to customize that call.

**Comment by nashif** [comment] 2022-11-18 13:19
duplicate of #41073

**Closed by nashif** 2022-11-18 13:19 UTC
Labels: Enhancement, area: Twister
