### ISSUE TITLE
fs/NVS: NVS is not compatible with flash memories which have 0x00 as erased 

### ISSUE THREAD

**Issue by nvlsianpu** [zephyrproject-rtos/zephyr#22063] opened 2020-01-21 14:46 UTC
**This is informative issue**, not a bu really
NVS design assumes 0xff as memory erased state. So it will doesn't work on devices which has 0x00 as erased byte state (e.g. some stm32 embedded. ~~and native_posix with the flash simulator~~ )

**To Reproduce**
~~Try NVS sample using native_posix target~~
[EDIT]: native_posix was fixed
Try NVS sample using a target which have 0x00 as erased byte flash value.

**Comment by carlescufi** [comment] 2020-01-21 18:08
FYI @Laczen

**Comment by Laczen** [comment] 2020-01-21 20:16
In general it would be good (and trivial) to add support in nvs for devices that use 0x00 as erase value. This however would not solve the problem with flash simulation on native posix. In the flash simulator on native posix the flash area is filled with 0x00 at start but is set to 0xff after erase. For the flash simulator on native posix it would be better to erase (set to 0xff) on creation of flash.bin.

**Comment by de-nordic** [comment] 2020-06-26 07:04
The solution https://github.com/zephyrproject-rtos/zephyr/pull/25947 does not seem to work correctly.

**Comment by Laczen** [comment] 2020-06-26 07:43
@de-nordic , might this be caused by line 417 in flash_simulator.c that initializes flash to 0xff ?

**Comment by de-nordic** [comment] 2020-06-26 10:20
> 
> 
> @de-nordic , might this be caused by line 417 in flash_simulator.c that initializes flash to 0xff ?

Thanks @Laczen! That may be the case, I will check this.

**Comment by de-nordic** [comment] 2020-06-26 12:16
> 
> > @de-nordic , might this be caused by line 417 in flash_simulator.c that initializes flash to 0xff ?
> 
There was a problem, but still this is not the root cause.

**Comment by Laczen** [comment] 2020-06-26 13:23
> > > @de-nordic , might this be caused by line 417 in flash_simulator.c that initializes flash to 0xff ?
> 
> There was a problem, but still this is not the root cause.

Do you have an idea where it fails?

**Comment by de-nordic** [comment] 2020-06-26 13:47
> 
> 
> > > > @de-nordic , might this be caused by line 417 in flash_simulator.c that initializes flash to 0xff ?
> > 
> > 
> > There was a problem, but still this is not the root cause.
> 
> Do you have an idea where it fails?

I narrowed it to `nvs_read_hist`, where it returns `-ENOENT`, due all conditions evaluating to 1.

I still do not understand operation of NVS good enough to write more on the subject.

**Comment by Laczen** [comment] 2020-06-26 14:30
@de-nordic, I am a bit puzzled, did you run the test before the merge ? -> I was looking at what would be different from your local test and the automated test.

**Comment by de-nordic** [comment] 2020-06-26 14:37
> 
> 
> @de-nordic, I am a bit puzzled, did you run the test before the merge ? -> I was looking at what would be different from your local test and the automated test.

Yes I did. I run both of the nvs tests each time I have updated something. I do not know why it did pass prior.

**Comment by Laczen** [comment] 2020-06-26 14:40
> > @de-nordic, I am a bit puzzled, did you run the test before the merge ? -> I was looking at what would be different from your local test and the automated test.
> 
> Yes I did. I run both of the nvs tests each time I have updated something. I do not know why it did pass prior.

OK, maybe it is in the 0x00 overlay file (< 0x00 > instead of <0x00> ?)

**Comment by de-nordic** [comment] 2020-06-26 14:44
I have printed out the values that are used for initialization of simulated flash and they are 0.
```
Booting from ROM..Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 6
Intitlizing to 0
*** Booting Zephyr OS build zephyr-v2.3.0-607-g16763ff9b6db  ***
Running test suite test_nvs
===================================================================
START - test_nvs_init
I: 5 Sectors of 1024 bytes
I: alloc wra: 0, 3f0
I: data wra: 0, 0
 PASS - test_nvs_init
===================================================================
START - test_nvs_write
I: 5 Sectors of 1024 bytes
I: alloc wra: 0, 3f0
I: data wra: 0, 0
wlk 3f0 3f0
wlk.id 0 1
wlk_ate.len 0
cnt 0 0
1
1
wlk 3e8 3e8
wlk.id 0 1
wlk_ate.len 0
cnt 0 0
1
1

    Assertion failed at WEST_TOPDIR/zephyr/tests/subsys/fs/nvs/src/main.c:100: execute_long_pattern_write: (len == sizeof(rd_buf) is false)
nvs_read unexpected failure: -2
 FAIL - test_nvs_write
```

**Comment by de-nordic** [comment] 2020-06-26 14:45
`Intitlizing to 0` comes from the flash driver.

**Comment by de-nordic** [comment] 2020-06-26 14:50
Same run but on the non-0x00 test:
```
ESC[0mSeaBIOS (version rel-1.12.1-0-ga5cab58-dirty-20200202_184651-8999447e980d-zephyr
)
Booting from ROM..Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 6
Intitlizing to ff
*** Booting Zephyr OS build zephyr-v2.3.0-607-g16763ff9b6db  ***
Running test suite test_nvs
===================================================================
START - test_nvs_init
I: 5 Sectors of 1024 bytes
I: alloc wra: 0, 3f0
I: data wra: 0, 0
 PASS - test_nvs_init
===================================================================
START - test_nvs_write
I: 5 Sectors of 1024 bytes
I: alloc wra: 0, 3f0
I: data wra: 0, 0
wlk 3f0 3f0
wlk.id ffff 1
wlk_ate.len ffff
cnt 0 0
1
0
wlk 3e8 3e8
wlk.id 1 1
wlk_ate.len 200
cnt 1 0
0
0
 PASS - test_nvs_write
```

**Comment by Laczen** [comment] 2020-06-26 15:28
@de-nordic, it seems that even the first write fails, in the flash_simulator there is a suspicious line at 261-262:

```
/* only pull bits to zero */
*(FLASH(offset + i)) &= *((uint8_t *)data + i);
```
shouldn't this be changed ?

**Comment by de-nordic** [comment] 2020-06-26 15:48
@Laczen Yes, you have identified the problem correctly. This is the line. NVS requires no changes. I will fix this and extend testcases for flash simulator.

**Comment by de-nordic** [comment] 2020-07-24 13:16
This issue has been solved, closing.

**Closed by de-nordic** 2020-07-24 13:16 UTC
Labels: Enhancement, area: File System, area: Flash, area: native port
