### ISSUE TITLE
Power management strategy of Zephyr can't work well on nRF52 boards.

### ISSUE THREAD

**Issue by Jiurifei** [zephyrproject-rtos/zephyr#12367] opened 2019-01-08 03:27 UTC
I am using the project which is located in `samples/subsys/power/power_mgr` to test the power consumption of my nRF52832/52840 board. When getting into `SYS_POWER_STATE_CPU_LPS ` or  `SYS_POWER_STATE_CPU_LPS_1 ` state(system on), the current is always about 290uA. While in deep sleep state(system off) , the current is normal and below 1uA. As we all know, nRF52x boards burned into Nordic SDK can work well. In which situation, the power consumption in idle state(system on) is around 2uA.

In order to solve this problem, I have turned off some peripherals which may lead to the increase of power consumption like UART0, and it indeed worked, but the current only reduced a little, around 20uA.
Obviously, it's not the main reason. So, I referred to the document of "Device Drivers and Device Model" of Zephyr project. I found that four standard drivers which were present on all supported boards. these are `Interrupt controller`  `Timer`  `Serial communication`  `Random number generator`. Which may produce extra power consumption? If so, whether means power management of Zephyr still needs enhancement?
I would appreciate it if anybody gives me some advice.

**Comment by Jiurifei** [comment] 2019-01-08 06:52
@ntavish Thank you for your suggestion! The sample you used is "center_hr" or "peripheral_hr"? Whether disabling UART is the only operation you did? And how did you disable your UART? 
Actually I have tried the method you told, but it didn't work well.

**Comment by ntavish** [comment] 2019-01-08 07:44
I tried peripheral_hr, I can't recall exactly which settings, but check if shell is enabled, or UART is being selected by something.

**Comment by Jiurifei** [comment] 2019-01-08 08:02
@ntavish the shell is disabled.  Indeed, some macros can have an effect on UART, such as "Use UART for console" which is under selection of console drivers. But even if I close some relevant macros then disable some peripherals, the power consumption is still too high. I have raised this before.#12150. And @JuricaResetar  has encountered the same question as mine.

**Comment by ntavish** [comment] 2019-01-08 10:12
Can you try blinky example, disable LEDs turning on. I am seeing around 5uA with that.

**Comment by ntavish** [comment] 2019-01-08 10:30
Can you try blinky example, disable LEDs turning on. I am seeing around 5uA with that.

**Comment by Jiurifei** [comment] 2019-01-08 11:46
@ntavish Thank you for your friendly help. I have experimented the example you told and turned off the leds just now, the current was about 167uA. Then I tried Zephyr's low power strategy, enabled the macro--`Device power management`  `low power state`   `deep sleep state`, the current increased, up to 310uA. 
Why this situation can occur? Could you tell me some details what you did?
BTW, the project I worked on is base on Zephyr 1.13.99.  the test  method I used follows nRF52832_PDK_user_ Guide, shows bleow:

![pic](https://user-images.githubusercontent.com/43055877/50828897-a618e580-137d-11e9-98e2-f626c8f5e45e.PNG)

**Comment by ntavish** [comment] 2019-01-08 12:00
I am using nordic's power profiler kit. Did you get under 10uA current for any Nordic power examples? 

Also could it be your equipment's current sensitivity in that low current range?

**Comment by Jiurifei** [comment] 2019-01-08 12:19
@ntavish yeah, I have used my board to run bt_app_uart example of Nordic. I disabled uart0 and increased the interval of broadcast to 1s. The average power consumption is around 10uA and current in idle state is 3uA. So, I really want to know how you achieve it!

**Comment by nordic-krch** [comment] 2019-01-08 13:21
fyi @pizi-nordic

**Comment by pizi-nordic** [comment] 2019-01-08 13:31
There is ongoing work to fix that (https://github.com/zephyrproject-rtos/zephyr/pull/12259).

**Comment by Jiurifei** [comment] 2019-01-09 03:48
@pizi-nordic I have browsed the PR you mentioned. In fact, what I am concerned is how to reduce the power consumption essentially rather than the logic of achieving power management, although it's important. So, when you finish the framework, could you please test the real current in different low power state to see whether it can hit the spot? 

Moreover, as a guiding function, k_sleep() can't work well in all of the examples, such as `zephyr/samples/bluetooth/mesh`. Not only logging thread can affect ticks, but also others I guess. Which leads to power management strategy failure that system can't choose a way to get into low power state correctly according to the inputting ticks. I think you may have a look.

**Comment by baw-serafin** [comment] 2019-01-14 15:10
@Jiurifei We ran in similar troubles. Sometime LPS / LPS_1 current is way to high. In discussion with nordic engineers I have understood, that the soc can not enter the desired internal state if some clocks are running.

For example I2C used to block LPS so there where some changes (https://github.com/zephyrproject-rtos/zephyr/commit/d1b3efd98ba02a177568dff6b8ef2fa513fa2bb2), but I believe not all things are fixed allready. If everything is correct. Zephyr can get as low as 2uA in LPS(_1?) but it never worked reliably enough for me so we choose to go with deep_sleep

**Comment by gmarull** [comment] 2022-11-17 12:37
Many changes have happened in PM since this PR, so I think it's time to close it. If you observe power usage issues on nRF, please, open a new issue with details on how to reproduce them.

**Closed by gmarull** 2022-11-17 12:37 UTC
Labels: Enhancement, area: Power Management
