### ISSUE TITLE
stty: standard input: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by wangnuannuan** [zephyrproject-rtos/zephyr#19739] opened 2019-10-10 09:43 UTC
**Describe the bug**
I am using jenkins to run the sanitycheck. The jenkins job run 4 stages in parallel and each stage run 1/4 of the tests. The error `stty: standard input: Inappropriate ioctl for device` always occurs during run time.
```

JOBS: 4
Cleaning output directory out-2nd-pass
29 tests selected, 0 tests discarded due to filters
stty: standard input: Inappropriate ioctl for device
 1/29 nsim_em_mpu_stack_guard   tests/application_development/gen_inc_file/buildsystem.include_file PASSED (nsim 4.898s)
 2/29 nsim_em_mpu_stack_guard   tests/application_development/cpp/misc.app_dev.cpp PASSED (build)
stty: standard input: Inappropriate ioctl for device
 3/29 nsim_em_mpu_stack_guard   tests/application_development/libcxx/misc.app_dev.libcxx PASSED (nsim 4.387s)
stty: standard input: Inappropriate ioctl for device
 4/29 nsim_em_mpu_stack_guard   tests/application_development/libcxx/misc.app_dev.libcxx.exceptions PASSED (nsim 5.155s)
stty: standard input: Inappropriate ioctl for device
 5/29 nsim_em_mpu_stack_guard   tests/benchmarks/sys_kernel/benchmark.kernel       PASSED (nsim 4.779s)
stty: standard input: Inappropriate ioctl for device
 6/29 nsim_em_mpu_stack_guard   tests/benchmarks/timing_info/benchmark.timing.default_kernel PASSED (nsim 5.131s)
stty: standard input: Inappropriate ioctl for device
 7/29 nsim_em_mpu_stack_guard   tests/cmsis_rtos_v1/portability.cmsis_rtos_v1      PASSED (nsim 6.363s)
stty: standard input: Inappropriate ioctl for device
 8/29 nsim_em_mpu_stack_guard   tests/benchmarks/timing_info/benchmark.timing.userspace PASSED (nsim 7.145s)
stty: standard input: Inappropriate ioctl for device
 9/29 nsim_em_mpu_stack_guard   tests/cmsis_rtos_v2/portability.cmsis_rtos_v2      PASSED (nsim 4.986s)
stty: standard input: Inappropriate ioctl for device
10/29 nsim_em_mpu_stack_guard   tests/crypto/rand32/crypto.rand32                  PASSED (nsim 4.757s)
stty: standard input: Inappropriate ioctl for device
11/29 nsim_em_mpu_stack_guard   tests/crypto/rand32/crypto.rand32.random_sw_systimer PASSED (nsim 4.287s)
stty: standard input: Inappropriate ioctl for device
12/29 nsim_em_mpu_stack_guard   tests/crypto/mbedtls/crypto.mbedtls                PASSED (nsim 107.395s)
stty: standard input: Inappropriate ioctl for device

```

**Comment by dleach02** [comment] 2019-10-14 19:31
@wangnuannuan, please provide target board this reproduced on, environment information, SDK version.

**Comment by wangnuannuan** [comment] 2019-10-16 01:42
- target board: arc nsim
- environment information: 
    - LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0- 
    - amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
    - Distributor ID:	CentOS
    - Description:	CentOS release 6.9 (Final)
    - Release:	6.9
    - Codename:	Final
- SDK version: 0.10.3
- python version: 3.7

**Comment by tgraydon** [comment] 2020-05-29 21:54
I am seeing this with Jenkins as well. I am using Jenkins to fire off a script that in turn runs sanitycheck. The scripts run fine at the command line, but this "Inappropriate ioctl for device" error spews when I run these scripts from Jenkins.

Preliminary investigation leads me to believe that this is because Jenkins is not really using a terminal for running scripts, and stty functions, like turning on and off echo, cause the system to start yelling about being a non-terminal device. 

I have skirted the issue by having Jenkins launch the scripts using the "script" shell command. i.e. script -q -c $WORKSPACE/my_script.sh $WORKSPACE/<my_script_out_log_file>

This does sort of muck up the script output when sanitycheck is running, because it is dumping everything to a file, so just output from sanitycheck failures gets thrown to the console log. Not pretty, but it does stop the incessant flow of the error message.  

So, at least in my scenario, this appears to be an issue with Jenkins, and is not actually related to sanitycheck. I do NOT see this when I run at the command line with the same exact scripts.

**Comment by abrodkin** [comment] 2020-06-04 11:26
@tgraydon that's interesting as we also seeing this only when running in Jenkins, so indeed it might be more of a Jenkins problem.

@oleg-nenashev is that a know issue? Is there a chance to get some feedback from Jenkins people?

**Comment by tgraydon** [comment] 2020-06-09 22:54
It appears to be more of an artifact from how Jenkins manages the console output. Shell scripts are expecting to input/output to an interactive shell/terminal, and Jenkins seems to be subverting that in some way. Hence, the same bash scripts I am running at the command line work perfectly on the same host, but Jenkins console shows ioctl device errors. 

Using the "script" command to launch the scripts from Jenkins and bypassing the interactive shell"fixes" the issue. Another thing we are looking at is setting Jenkins user to use a non-interactive shell. That may have implications to troubleshooting, though, if someone needs to log in as Jenkins user for any reason.

So anyway, not sure whether this is really a Jenkins issue per se, although it sure would be nice if it did the "right thing" with console output when running shell scripts.

**Comment by nashif** [comment] 2020-07-25 15:18
this is a jenkins issue, closing. Works fine in Zephyr CI.

**Closed by nashif** 2020-07-25 15:18 UTC
Labels: area: Sanitycheck, bug, priority: low
