### ISSUE TITLE
BLE notify characteristic not working

### ISSUE THREAD

**Issue by ujur007** [zephyrproject-rtos/zephyr#55853] opened 2023-03-16 11:21 UTC
**Is your feature request related to a problem? Please describe.**
I have recently installed the Zephyr SDK and have a sample nRF application where there is custom BLE characteristic with some interrupt callback for button pressed event. An LED on nRF5340-DK turns-on when Button is pressed. I wanted to create a customs characteristic which notify user when button/LED status has changed. 
Here the following is code for the callback for button press which works fine and LED always toggles on button press, however, notification does not work. 
Especially, there is nothing printed in this function on the serial console application.
I have not used the callback function for Notify characteristic. I saw it is not mandatory.

```
void btn_pressed(const struct device *dev, struct gpio_callback *cb, uint32_t pins){
    int err;
    gpio_pin_toggle_dt(&bpled);
    printk("Notify btn value");
    btn_val = btn_val + 1;
    if(conn){
        err = bt_gatt_notify(conn, &Buttonpress_characteristic.uuid, &btn_val, sizeof(btn_val));
    }
    else{
        printk("BLE is not connected");
    }
    if(err){
    printk("Error notify %d", err);
    }
}
```

**Describe the solution you'd like**
The BLE notification is enabled in mobile application and client-server connection works fine. All I wanted to see is how notify works.

**Describe alternatives you've considered**
I would try some example application with notify.

**Additional context**
I can drop .HEX file for app and net cores here if required.

**Comment by nordicjm** [comment] 2023-03-16 11:23
It does not work because you are trying to call a bluetooth function in an interrupt, this is not supported, use a workqueue or similar. Closing as not a bug.

**Closed by nordicjm** 2023-03-16 11:23 UTC
Labels: Feature Request

**Comment by ujur007** [comment] 2023-03-16 11:28
Ok. Thanks. 
Did not know that it can not work in interrupt. BTW, is that documented or it is kind of normal rule that interrupts are kept as short as possible?

**Comment by nordicjm** [comment] 2023-03-16 12:00
It's not the length that is the problem, it's the multitasking - if you're in an ISR, you cannot take a mutex or semaphore for example, so if you call a bluetooth function you'll find you're stuck in an infinite loop trying to take a mutex which can't be given. Not sure if it's documented on the bluetooth pages, @jori-nordic any ideas?

**Comment by ujur007** [comment] 2023-03-16 15:12
The st_ble_sensor app implements callback but not in main function, rather a separate function.
