### ISSUE TITLE
Flash: SFDP parameter address is not correct

### ISSUE THREAD

**Issue by marekmatej** [zephyrproject-rtos/zephyr#47970] opened 2022-07-18 17:42 UTC
---
name: SFDP parameter address parse error
about: ''
title: SFDP parameter address parse error
labels: bug
assignees: ''

---

If CONFIG_SPI_NOR_SFDP_RUNTIME is enabled, reading SFDP parameter table gives all 0xFF, which leads to flash miss-configuration.

Parameter Table Pointer from SFDP param. header represents the address of parameter table in dual-words, therefore it need to be converted to byte address by multiplying by 4.
https://github.com/zephyrproject-rtos/zephyr/blob/03912c23e380c9e36a7ce40cc061f58720f67e73/drivers/flash/spi_nor.c#L916

Example: on S25FL127S device that PTP is 0x448, which multiplied by 4 gives 0x1120, which is correct address of Parameter Table.

The issue makes runtime discovery of SFDP parameter impossible.

As workaround, multiply return value of the function by 4.
https://github.com/zephyrproject-rtos/zephyr/blob/9cb707b814af979f3c6d2342bdf19945691d3baf/drivers/flash/jesd216.h#L50

**Comment by henrikbrixandersen** [comment] 2022-07-19 13:54
Please use the bug report template when reporting a bug (you can copy it from here since you missed it in the first place: https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by nvlsianpu** [comment] 2022-09-15 10:41
> Parameter Table Pointer from SFDP param. header represents the address of parameter table in dual-words, therefore it need to be converted to byte address by multiplying by 4.

<b>NACK</b> According to the JESD216E SFDP specification: PTP is specified in byte unit and must be dword aligned.

I did test how SFDP readout works on nRF52840dk_nrf52840 (it has MX25R6435F serial flash) with qspi nor driver (using samples/drivers/jesd216). Procedure in the sample is the same as in spi_nor driver and it does work well (addressing is correct, ).

**Comment by nvlsianpu** [comment] 2022-09-15 15:55
I tested readout using spi-nor driver on nrf52840dk_nrf52840. It works well as well.
I open PR with configuration used by my: https://github.com/zephyrproject-rtos/zephyr/pull/50277

**Comment by nvlsianpu** [comment] 2022-09-15 16:05
According to S25FL127S specification it should behave the same.

I'm closing as can not to reproducer a bag here. JESD216 are addressed properly.

**Closed by nvlsianpu** 2022-09-15 16:05 UTC
Labels: bug, priority: low, area: Flash
