### ISSUE TITLE
Cannot build C++ sample projects on Windows

### ISSUE THREAD

**Issue by mrfuchs** [zephyrproject-rtos/zephyr#9940] opened 2018-09-12 12:52 UTC
Samples having set `CONFIG_CPLUSPLUS=y` in their prj.conf (e.g. zephyr\samples\cpp_synchronization) fail to build on Windows - at least when using the GNU Arm Embedded Toolchain.

Command Line:
`D:\test\zephyr\samples\cpp_synchronization>cmake -GNinja -Bbuild -H. -DBOARD=stm32f4_disco`

Output:
```
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
CMake Error at ../../CMakeLists.txt:11 (project):
  The CMAKE_CXX_COMPILER:

    C:/Program Files (x86)/GNU Tools Arm Embedded/7 2018-q2-update/bin/arm-none-eabi-g++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
```

It seems like the CMAKE_CXX_COMPILER variable is not allowed to end on "++" (...gcc works, but ...g++ does not). So I changed [gcc.cmake:52](https://github.com/zephyrproject-rtos/zephyr/blob/a7ddb1fb825e144cb0509a7b4302c3d23115a5f2/cmake/compiler/gcc.cmake#L52) to
`set(CMAKE_CXX_COMPILER "${cplusplus_compiler}.exe"     CACHE INTERNAL " " FORCE)`.

Resulting output:

```
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- The ASM compiler identification is GNU
-- Found assembler: C:/Program Files (x86)/GNU Tools Arm Embedded/7 2018-q2-update/bin/arm-none-eabi-gcc.exe
-- Performing Test toolchain_is_ok
-- Performing Test toolchain_is_ok - Success
-- Configuring done
-- Generating done
-- Build files have been written to: D:/test/zephyr/samples/cpp_synchronization/build
```

**Comment by SebastianBoe** [comment] 2018-09-12 13:31
Closing as duplicate of #9582

**Closed by SebastianBoe** 2018-09-12 13:31 UTC
