### ISSUE TITLE
tests/kernel/mbox/mbox_usage/testcase.yaml#kernel.mailbox crashes on ESP32

### ISSUE THREAD

**Issue by spoorthik** [zephyrproject-rtos/zephyr#9744] opened 2018-08-31 09:47 UTC
Execution log:

```
***** Booting Zephyr OS v1.13.0-rc2-1-g19b7eaa (delayed boot 1000ms) *****
Running test suite test_mbox
===================================================================
starting test - test_msg_receiver
PASS - test_msg_receiver
===================================================================
starting test - msg_receiver_unlimited
S ** FATAL EXCEPTION
 ** CPU 0 EXCCAUSE 28 PS 0x00060020 PC 0x40082a77 VADDR 0x00000044
 **  A0 0x80081191  SP 0x3ffb3350  A2 0x3ffb1664  A3 0x00000000
 **  A4 0x00000000  A5 0x3ffb1638  A6 0x3ffb14d4  A7 0x00000001
 **  A8 0x3ffb1638  A9 0x00000000 A10 0x00000001 A11 0x00000001
 ** A12 0x00000001 A13 0x3ffb1638 A14 0x00060e21 A15 0x00000001
 ** LBEG 0x00000000 LEND 0x00000000 LCOUNT 0x00000000
 ** SAR 0x00000008
Current thread ID = 0x00000000
Faulting instruction address = 0xdeaddead
Fatal fault in ISR! Spinning...
```
Latest commit on which issue is seen: 19b7eaaa65f6354a831f02372a9e79eab0198bc0

Steps to reproduce:

```
cd zephyr.git/tests/kernel/mbox/mbox_usage
mkdir build && cd build
cmake -DBOARD=esp32 .. 
make flash
```

**Comment by nashif** [comment] 2018-09-03 01:53
duplicate of #8283

**Closed by nashif** 2018-09-03 01:53 UTC
Labels: area: Xtensa, bug
