### ISSUE TITLE
get a run error "Fatal exception (28): LoadProhibited" while enable CONFIG_NEWLIB_LIBC=y

### ISSUE THREAD

**Issue by sam131208** [zephyrproject-rtos/zephyr#46093] opened 2022-05-28 10:42 UTC
**Describe the bug**
Get a run error "Fatal exception (28): LoadProhibited" while enable CONFIG_NEWLIB_LIBC=y. 

**To Reproduce**
1. modify samples/subsys/mgmt/mcumgr/smp_svr/overlay-bt.conf ,   delete CONFIG_MCUMGR_SMP_SHELL=y, add CONFIG_NEWLIB_LIBC=y
2. west build  -b esp32  samples/subsys/mgmt/mcumgr/smp_svr  --   -DOVERLAY_CONFIG=overlay-bt.conf
3. west flash

**Logs and console output**
=~=~=~=~=~=~=~=~=~=~=~= PuTTY log 2022.05.28 18:25:44 =~=~=~=~=~=~=~=~=~=~=~=
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff8598,len:4908
ho 0 tail 12 room 4
load:0x40093000,len:13804
load:0x4009b800,len:5976
entry 0x40093448
[esp32] [INF] Enabling RNG early entropy source...
[esp32] [INF] *** Booting MCUboot build v1.7.0-485-ge86f575 ***
[esp32] [INF] Primary image: magic=good, swap_type=0x1, copy_done=0x3, image_ok=0x1
[esp32] [INF] Scratch: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
[esp32] [INF] Boot source: primary slot
[esp32] [INF] Swap type: none
[esp32] [INF] Disabling RNG early entropy source...
[esp32] [INF] br_image_off = 0x10000
[esp32] [INF] ih_hdr_size = 0x20
[esp32] [INF] Loading image 0 - slot 0 from flash, area id: 1
[esp32] [INF] DRAM segment: start=0x58a6, size=0x1dcc, vaddr=0x3ffbdb60
[esp32] [INF] IRAM segment: start=0x7674, size=0x187dc, vaddr=0x40080000
[esp32] [INF] start=0x4009052c
Fatal exception (28): LoadProhibited
epc1=0x40096f6f, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000

Under is the zephyr.map file:
                0x0000000040096f64      0x11d /home/sam/zephyr-sdk-0.14.2/xtensa-espressif_esp32_zephyr-elf/xtensa-espressif_esp32_zephyr-elf/lib/./libc.a(lib_a-svfiprintf.o)
                                        0x121 (size before relaxing)
                0x0000000040096f64                __ssprint_r
 *fill*         0x0000000040097081        0x3 

**Environment (please complete the following information):**
 - OS: ubuntu
 - Toolchain: Zephyr SDK 0.14.2
 - zephyr ver 3.1 rc2

**Comment by sylvioalves** [comment] 2022-05-28 16:25
@sam131208 This error is happening due to a missing PR in zephyr's mcuboot:  https://github.com/mcu-tools/mcuboot/pull/1362`  
This should be already synced but it was not. I asked maintainers to take a look. This is same root cause for this: #45349.  
So I will close this as duplicated, ok?

**Closed by sylvioalves** 2022-05-28 16:25 UTC
Labels: bug, platform: ESP32, area: mcumgr
