### ISSUE TITLE
tests/net/trickle failed on frdm_k64f board

### ISSUE THREAD

**Issue by chen-png** [zephyrproject-rtos/zephyr#18508] opened 2019-08-20 00:57 UTC
**Describe the bug**
Running test suite test_trickle on frdm_k64f board, it failed with error message "test_trickle_2_wait: (cb_2_called is false)".

**To Reproduce**
1. west build -b=frdm_k64f  tests/net/trickle
2. west flash

**Screenshots or console output**
![image](https://user-images.githubusercontent.com/52983984/63309059-edaa1b80-c327-11e9-9bcf-22b55d462f36.png)

**Environment (please complete the following information):**
 - OS: Fedora28
 - Toolchain: Zephyr-sdk-0.10.2
 - Commit ID: 59bbf3a521

**Comment by ioannisg** [comment] 2019-08-23 13:42
@chen-png are you looking into this issue?

**Comment by ioannisg** [comment] 2019-08-23 14:35
Test fails also on sam_e70_xplained, so this is not platform-specific.

**Comment by nashif** [comment] 2019-08-23 18:06
duplicate of #18598

**Closed by nashif** 2019-08-23 18:06 UTC
Labels: bug, priority: medium
