### ISSUE TITLE
frdm_k64f：failed to run test case tests/subsys/modbus/modbus.rtu/server_setup_low_none

### ISSUE THREAD

**Issue by shaoanxli** [zephyrproject-rtos/zephyr#46158] opened 2022-06-01 08:04 UTC
**Describe the bug**
The test appears to be failing , and an interruption occurs  and log "W: Frame length error" while the test is judged to pass. When the length is greater than 256 and less than 4, such a log will output: "W: Frame length error ", and the length is 1 at this time. Could you please help to check if this is a issue or not?

The log prints here zephyr/subsys/modbus/modbus_serial.c:253.

**To Reproduce**
1. source zephyr-env.sh
2. west build -p always -b frdm_k64f tests/subsys/modbus/
3. Open another terminal and execute: picocom -b 115200 /dev/ttyACM0

**Expected behavior**
Should not see "W: Frame length error" in the result of test_server_setup_low_none.

**Impact**
Almost no impact.

**Logs and console output**
```
*** Booting Zephyr OS build v3.1.0-rc3-4-g2ef3fe7bca13  ***
Running TESTSUITE modbus_client_test
===================================================================
START - test_server_setup_low_none
I: RTU timeout 4010 us
PASS - test_server_setW: Frame length error
up_low_none in 0.3 seconds
===================================================================
START - test_client_setup_low_none
I: RTU timeout 4010 us
PASS - test_client_setup_low_none in 0.3 seconds
===================================================================

```

**Environment:**
OS: Linux,
Toolchain Zephyr SDK 0.14.1
Commit SHA or Version: 2ef3fe7bca13

**Comment by enjiamai** [comment] 2022-06-02 03:37
This is a known twister issue, has nothing to do with this test case. So close it.

**Comment by enjiamai** [comment] 2022-06-02 04:06
Except twister issue, one thing we want to ensure is:   is the "W: Frame length error"  happens in the report of the test_server_setup_low_none a normal behavior.

Could you please help to check if this is a issue or not? Thanks!

**Comment by jfischer-no** [comment] 2022-06-29 12:38
> Except twister issue, one thing we want to ensure is: is the "W: Frame length error" happens in the report of the test_server_setup_low_none a normal behavior.
> 
> Could you please help to check if this is a issue or not? Thanks!

Not an issue as long all test cases pass. "W: Frame length error" warning comes from the modbus subsystem, caused by test cases which intentionally send wrong frames.

**Closed by jfischer-no** 2022-06-29 12:38 UTC
Labels: bug, priority: low, area: modbus
