### ISSUE TITLE
error with 'west update' on Windows 10

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#21629] opened 2019-12-31 08:49 UTC
**Describe the bug**
```
PS C:\Users\andrew\projects\zephyr> west update
...
=== updating civetweb (modules\lib\civetweb):
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
...
ERROR: update failed for project civetweb
PS C:\Users\andrew\projects\zephyr>
```

**To Reproduce**

Set up windows 10 zephyr environment with chocolatey, and try to west init.

**Expected behavior**
No errors.

**Impact**
Unsure what depends on this.

**Comment by carlescufi** [comment] 2020-01-02 18:55
This seems to be a duplicate of #21426. See there for a workaround.

**Closed by carlescufi** 2020-01-02 18:55 UTC
Labels: bug
