### ISSUE TITLE
Nordic: remove default-enable of bluetooth capability

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#12215] opened 2018-12-21 17:38 UTC
As discussed in #12209 it's been discovered that (almost?) all Nordic-based boards have the following in their board defconfig:

```
# bluetooth
CONFIG_BT=y
CONFIG_BT_CTLR=y
```

This causes any application built for the boards to get roughly 30 KB of possibly unnecessary driver infrastructure.  It's particularly an issue when another transport mechanism (802.15.4 or OpenThreads) is desired instead.

Task is to review why this was done and, if there isn't a compelling explanation, remove this from all Nordic board defconfig files.

**Comment by carlescufi** [comment] 2018-12-21 19:59
I agree with getting this done, I will send a PR. Changed from bug to enhancement.

**Comment by SebastianBoe** [comment] 2018-12-27 13:45
This is a duplicate of https://github.com/zephyrproject-rtos/zephyr/issues/5454

I agree that boards should not be enabling large software stacks, like BT.

**Comment by pabigot** [comment] 2019-01-13 15:12
It would be good to get a fix in place before topic-counter goes in.  Default-enabling bluetooth causes any attempt to use `COUNTER_TIMER0` or `COUNTER_RTC0` to be rejected by cmake with an unhelpful diagnostic.  It took a while to figure out the cause was `CONFIG_BT=y`.

**Comment by carlescufi** [comment] 2019-02-07 17:09
@cvinayak @SebastianBoe how about we do it like the particle boards do:
https://github.com/zephyrproject-rtos/zephyr/blob/master/boards/arm/particle_xenon/Kconfig.defconfig#L46

That way we only enable the controller if Bluetooth is enabled.

**Closed** 2019-02-07 21:17 UTC
Labels: area: Boards, enhancement, nRF
