### ISSUE TITLE
bluetooth:eatt:Creating a credit based channel with insufficient authentication returns wrong response.

### ISSUE THREAD

**Issue by MSEEHenrik** [zephyrproject-rtos/zephyr#61407] opened 2023-08-11 08:26 UTC
Using **L2CAP_CREDIT_BASED_CONNECTION_REQ** to create and configure new L2CAP channels.
The device returns a  **L2CAP_CREDIT_BASED_CONNECTION_RSP** package with a result code.
If the link is not encrypted, a status reply with a result code of 0x000E is expected.

0x000E - All connections pending - authentication pending.

Zephyr generates a status reply with a result code of 0x0005.

0x0005 - Connection refused - insufficient authentication.

The behavior is described in Core Specification 5.4 | Vol 3, Part A, section 4.25 and 4.26.

Tests: This behavior is tested with qualification test **L2CAP/ECFC/BV-43-C**.

Target platform: nrf52840dk_nrf52840.

Kconfig flags:
CONFIG_BT_L2CAP_ECRED=y
CONFIG_BT_EATT=y
CONFIG_BT_EATT_MAX=5
CONFIG_BT_EATT_AUTO_CONNECT=y

**Comment by hermabe** [comment] 2023-08-11 10:09
The "pending" statuses are only relevant for BR/EDR and not available on LE, see errata ES-18351. Which TCRL are you on?

**Comment by MSEEHenrik** [comment] 2023-08-11 10:53
I'm using the latest TCRL - TCRL-2023-1.

**Comment by MariuszSkamra** [comment] 2023-08-18 09:54
ES-18351 is still not resolved (incorporated).
I pinged people in https://bluetooth.atlassian.net/browse/ES-18351.
There's a waiver that can be used: https://bluetooth.atlassian.net/browse/ES-22070 until the issue is resolved

**Comment by carlescufi** [comment] 2023-09-14 10:41
> ES-18351 is still not resolved (incorporated). I pinged people in https://bluetooth.atlassian.net/browse/ES-18351. There's a waiver that can be used: https://bluetooth.atlassian.net/browse/ES-22070 until the issue is resolved

@hermabe @MSEEHenrik if this is the case, can we close this issue?

**Comment by hermabe** [comment] 2023-09-14 11:12
> > ES-18351 is still not resolved (incorporated). I pinged people in https://bluetooth.atlassian.net/browse/ES-18351. There's a waiver that can be used: https://bluetooth.atlassian.net/browse/ES-22070 until the issue is resolved
> 
> @hermabe @MSEEHenrik if this is the case, can we close this issue?

Yes. There is a waiver available until next TCRL is out.

**Closed** 2023-09-14 12:36 UTC
Labels: bug, priority: low, area: Bluetooth, area: Bluetooth Qualification, area: Bluetooth Host

**Comment by MSEEHenrik** [comment] 2023-09-15 06:14
Yes - It can be closed.
