### ISSUE TITLE
tests: subsys: usb: device: usb.device hangs

### ISSUE THREAD

**Issue by nordic-piks** [zephyrproject-rtos/zephyr#52670] opened 2022-11-30 11:50 UTC
**Describe the bug**
The zephyr/tests/subsys/usb/device/usb.device hangs

Observed for
- nrf5340dk_nrf5340_cpuapp_ns

But test works fine for:
- nrf5340dk_nrf5340_cpuapp
- nrf52840dk_nrf52840

**To Reproduce**
1. have nrf5340dk_nrf5340_cpuapp_ns J-Link connected and **DO NOT** connect nRF USB
2. go to your zephyr dir
3. call ./scripts/twister -T tests/subsys/usb/device  -p nrf5340dk_nrf5340_cpuapp_ns --device-testing --device-serial /dev/ttyACM1 -v --inline-logs
4. See console output with error

**Expected behavior**
Valid console output

**Impact**
Not clear

**Logs and console output**
```
[2022-11-30T00:11:41.998Z] [0mERROR   - D: __usb_descriptor_start 0x20040124[0m
[2022-11-30T00:11:41.998Z] [0mD: __usb_descriptor_end 0x20040195[0m
[2022-11-30T00:11:41.998Z] [0mD: Configuration descriptor 0x20040136[0m
[2022-11-30T00:11:41.998Z] [0mD: Interface descriptor 0x2004013f[0m
[2022-11-30T00:11:41.998Z] [0mD: Endpoint descriptor 0x20040148[0m
[2022-11-30T00:11:41.998Z] [0mD: ep 0x81, mps 64, type 2[0m
[2022-11-30T00:11:41.998Z] [0mD: Fixing EP address 81 -> 81[0m
[2022-11-30T00:11:41.998Z] [0mD: endpoint 0x81[0m
[2022-11-30T00:11:41.998Z] [0mD: Now the wTotalLength is 25[0m
[2022-11-30T00:11:41.998Z] [0mD: idx_max 11, ascii_idx_max 5, buf 0x20040155[0m
[2022-11-30T00:11:41.998Z] [0mD: char R : 52, idx 5 -> 11[0m
[2022-11-30T00:11:41.998Z] [0mD: char Y : 59, idx 4 -> 9[0m
[2022-11-30T00:11:41.998Z] [0mD: char H : 48, idx 3 -> 7[0m
[2022-11-30T00:11:41.998Z] [0mD: char P : 50, idx 2 -> 5[0m
[2022-11-30T00:11:41.998Z] [0mD: char E : 45, idx 1 -> 3[0m
[2022-11-30T00:11:41.998Z] [0mD: char Z : 5a, idx 0 -> 1[0m
[2022-11-30T00:11:41.998Z] [0mD: idx_max 13, ascii_idx_max 6, buf 0x20040163[0m
[2022-11-30T00:11:41.998Z] [0mD: char V : 56, idx 6 -> 13[0m
[2022-11-30T00:11:41.998Z] [0mD: char E : 45, idx 5 -> 11[0m
[2022-11-30T00:11:41.998Z] [0mD: char D : 44, idx 4 -> 9[0m
[2022-11-30T00:11:41.998Z] [0mD: char - : 2d, idx 3 -> 7[0m
[2022-11-30T00:11:41.998Z] [0mD: char B : 42, idx 2 -> 5[0m
[2022-11-30T00:11:41.998Z] [0mD: char S : 53, idx 1 -> 3[0m
[2022-11-30T00:11:41.998Z] [0mD: char U : 55, idx 0 -> 1[0m
[2022-11-30T00:11:41.998Z] [0mD: Serial Number[0m
[2022-11-30T00:11:41.998Z] [0mD: 5d d9 94 a8 62 ee 8c 1d |]...b...[0m
[2022-11-30T00:11:41.998Z] [0mD: idx_max 31, ascii_idx_max 15, buf 0x20040173[0m
[2022-11-30T00:11:41.998Z] [0mD: char D : 44, idx 15 -> 31[0m
[2022-11-30T00:11:41.998Z] [0mD: char 1 : 31, idx 14 -> 29[0m
[2022-11-30T00:11:41.998Z] [0mD: char C : 43, idx 13 -> 27[0m
[2022-11-30T00:11:41.998Z] [0mD: char 8 : 38, idx 12 -> 25[0m
[2022-11-30T00:11:41.998Z] [0mD: char E : 45, idx 11 -> 23[0m
[2022-11-30T00:11:41.998Z] [0mD: char E : 45, idx 10 -> 21[0m
[2022-11-30T00:11:41.998Z] [0mD: char 2 : 32, idx 9 -> 19[0m
[2022-11-30T00:11:41.998Z] [0mD: char 6 : 36, idx 8 -> 17[0m
[2022-11-30T00:11:41.998Z] [0mD: char 8 : 38, idx 7 -> 15[0m
[2022-11-30T00:11:41.998Z] [0mD: char A : 41, idx 6 -> 13[0m
[2022-11-30T00:11:41.998Z] [0mD: char 4 : 34, idx 5 -> 11[0m
[2022-11-30T00:11:41.998Z] [0mD: char 9 : 39, idx 4 -> 9[0m
[2022-11-30T00:11:41.998Z] [0mD: char 9 : 39, idx 3 -> 7[0m
[2022-11-30T00:11:41.998Z] [0mD: char D : 44, idx 2 -> 5[0m
[2022-11-30T00:11:41.998Z] [0mD: char D : 44, idx 1 -> 3[0m
[2022-11-30T00:11:41.998Z] [0mD: char 5 : 35, idx 0 -> 1[0m
[2022-11-30T00:11:41.998Z] [0m*** Booting Zephyr OS build zephyr-v3.2.0-2064-g7c8264277a93 ***[0m
[2022-11-30T00:11:41.998Z] [0mRunning TESTSUITE device_usb[0m
[2022-11-30T00:11:41.998Z] [0m===================================================================[0m
[2022-11-30T00:11:41.998Z] [0mD: lock usb_enable_lock mutex[0m
[2022-11-30T00:11:41.998Z] [0mD: set cb, ep: 0x81[0m
[2022-11-30T00:11:41.998Z] [0mD: EP enable: 0x00[0m
[2022-11-30T00:11:41.998Z] [0mD: EP enable: 0x80[0m
[2022-11-30T00:11:41.998Z] [0mD: unlock usb_enable_lock mutex[0m
[2022-11-30T00:11:41.998Z] [0mSTART - test_usb_dc_api[0m
[2022-11-30T00:11:41.998Z] [0mPASS - test_usb_dc_api in 0.001 seconds[0m
[2022-11-30T00:11:41.998Z] [0m===================================================================[0m
[2022-11-30T00:11:41.998Z] [0mSTART - test_usb_dc_api_invalid[0m
[2022-11-30T00:11:41.998Z] [0mD: ep_write: ep 0x20, len 1[0m
[2022-11-30T00:11:41.998Z] [0mD: ep_read: ep 0x20, maxlen 1[0m
[2022-11-30T00:11:41.998Z] [0mPASS - test_usb_dc_api_invalid in 0.013 seconds[0m
[2022-11-30T00:11:41.998Z] [0m===================================================================[0m
[2022-11-30T00:11:41.998Z] [0mSTART - test_usb_dc_api_read_write[0m
[2022-11-30T00:11:41.998Z] [0mD: ep_read: ep 0x20, maxlen 1[0m
[2022-11-30T00:11:41.998Z] [0mD: ep_write: ep 0x20, len 1[0m
[2022-11-30T00:11:41.998Z] [0mPASS - test_usb_dc_api_read_write in 0.013 seconds[0m
[2022-11-30T00:11:41.998Z] [0m===================================================================[0m
[2022-11-30T00:11:41.998Z] [0mSTART - test_usb_deconfig[0m
[2022-11-30T00:11:41.998Z] [0mPASS - test_usb_deconfig in 0.001 seconds[0m
[2022-11-30T00:11:41.998Z] [0m===================================================================[0m
[2022-11-30T00:11:41.998Z] [0mSTART - test_usb_disable[0m
[2022-11-30T00:11:41.998Z] [0mD: EP disable: 0x00[0m
[2022-11-30T00:11:41.998Z] [0mD: EP disable: 0x80[0m
[2022-11-30T00:11:41.998Z] [0m[0m
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Toolchain Zephyr SDK 0.15.1
 - Commit SHA or Version used: zephyr-v3.2.0-2064-g7c8264277a93

**Comment by desowin** [comment] 2022-12-02 07:45
I cannot reproduce this. Note that I had to use `/dev/ttyACM1` instead of `/dev/ttyACM0`, because the output appears only on the second serial port. 
```
[tmon@tmon-laptop zephyr]$ git log -1 --format=%H
7c8264277a9377cd41f8dfe3a777bb897015b562
[tmon@tmon-laptop zephyr]$ ./scripts/twister -T tests/subsys/usb/device -p nrf5340dk_nrf5340_cpuapp_ns --device-testing --device-serial /dev/ttyACM1 -v --inline-logs
ZEPHYR_BASE unset, using "/home/tmon/zephyrproject/zephyr"
Renaming output directory to /home/tmon/zephyrproject/zephyr/twister-out.4
INFO    - Using Ninja..
INFO    - Zephyr version: zephyr-v3.2.0-2064-g7c8264277a93
INFO    - Using 'zephyr' toolchain.
INFO    - Building initial testsuite list...
INFO    - Writing JSON report /home/tmon/zephyrproject/zephyr/twister-out/testplan.json

Device testing on:

| Platform                    | ID   | Serial device   |
|-----------------------------|------|-----------------|
| nrf5340dk_nrf5340_cpuapp_ns |      | /dev/ttyACM1    |

INFO    - JOBS: 12
INFO    - Adding tasks to the queue...
INFO    - Added initial list of jobs to queue
INFO    - 1/1 nrf5340dk_nrf5340_cpuapp_ns zephyr/tests/subsys/usb/device/usb.device          PASSED (device 16.129s)

INFO    - 1 test scenarios (1 test instances) selected, 0 configurations skipped (0 by static filter, 0 at runtime).
INFO    - 1 of 1 test configurations passed (100.00%), 0 failed, 0 skipped with 0 warnings in 27.31 seconds
INFO    - In total 5 test cases were executed, 0 skipped on 1 out of total 518 platforms (0.19%)
INFO    - 1 test configurations executed on platforms, 0 test configurations were only built.

Hardware distribution summary:

| Board                       | ID   |   Counter |
|-----------------------------|------|-----------|
| nrf5340dk_nrf5340_cpuapp_ns |      |         1 |
INFO    - Saving reports...
INFO    - Writing JSON report /home/tmon/zephyrproject/zephyr/twister-out/twister.json
INFO    - Writing xunit report /home/tmon/zephyrproject/zephyr/twister-out/twister.xml...
INFO    - Writing xunit report /home/tmon/zephyrproject/zephyr/twister-out/twister_report.xml...
INFO    - Run completed
```

```
2022-12-02 08:30:38,353 - twister - INFO - Using Ninja..
2022-12-02 08:30:38,369 - twister - INFO - Zephyr version: zephyr-v3.2.0-2064-g7c8264277a93
2022-12-02 08:30:38,372 - twister - DEBUG - Running cmake script /home/tmon/zephyrproject/zephyr/cmake/verify-toolchain.cmake
2022-12-02 08:30:38,372 - twister - DEBUG - Calling cmake: /usr/bin/cmake -DFORMAT=json -P /home/tmon/zephyrproject/zephyr/cmake/verify-toolchain.cmake
2022-12-02 08:30:38,709 - twister - DEBUG - Finished running  /home/tmon/zephyrproject/zephyr/cmake/verify-toolchain.cmake
2022-12-02 08:30:38,709 - twister - INFO - Using 'zephyr' toolchain.
2022-12-02 08:30:38,783 - twister - DEBUG - Reading test case configuration files under /home/tmon/zephyrproject/zephyr/tests/subsys/usb/device...
2022-12-02 08:30:38,783 - twister - DEBUG - Found possible testsuite in /home/tmon/zephyrproject/zephyr/tests/subsys/usb/device
2022-12-02 08:30:38,785 - twister - DEBUG - Reading platform configuration files under /home/tmon/zephyrproject/zephyr/boards...
2022-12-02 08:30:39,128 - twister - DEBUG - Reading platform configuration files under /home/tmon/zephyrproject/zephyr/scripts/pylib/twister/boards...
2022-12-02 08:30:39,129 - twister - DEBUG - platform filter: ['nrf5340dk_nrf5340_cpuapp_ns']
2022-12-02 08:30:39,129 - twister - DEBUG -     arch_filter: None
2022-12-02 08:30:39,129 - twister - DEBUG -      tag_filter: None
2022-12-02 08:30:39,129 - twister - DEBUG -     exclude_tag: None
2022-12-02 08:30:39,129 - twister - INFO - Building initial testsuite list...
2022-12-02 08:30:39,129 - twister - INFO - Writing JSON report /home/tmon/zephyrproject/zephyr/twister-out/testplan.json
2022-12-02 08:30:39,135 - twister - INFO - JOBS: 12
2022-12-02 08:30:39,135 - twister - INFO - Adding tasks to the queue...
2022-12-02 08:30:39,135 - twister - DEBUG - adding nrf5340dk_nrf5340_cpuapp_ns/zephyr/tests/subsys/usb/device/usb.device
2022-12-02 08:30:39,136 - twister - INFO - Added initial list of jobs to queue
2022-12-02 08:30:39,136 - twister - DEBUG - Launch process 0
2022-12-02 08:30:39,136 - twister - DEBUG - Launch process 1
2022-12-02 08:30:39,137 - twister - DEBUG - Launch process 2
2022-12-02 08:30:39,138 - twister - DEBUG - Launch process 3
2022-12-02 08:30:39,139 - twister - DEBUG - Running cmake on /home/tmon/zephyrproject/zephyr/tests/subsys/usb/device for nrf5340dk_nrf5340_cpuapp_ns
2022-12-02 08:30:39,140 - twister - DEBUG - Calling cmake: /usr/bin/cmake -B/home/tmon/zephyrproject/zephyr/twister-out/nrf5340dk_nrf5340_cpuapp_ns/zephyr/tests/subsys/usb/device/usb.device -DTC_RUNID=6823661a5af2e5762eb7e45936f2f632 -DEXTRA_CFLAGS=-Werror '-DEXTRA_AFLAGS=-Werror -Wa,--fatal-warnings' -DEXTRA_LDFLAGS=-Wl,--fatal-warnings -DEXTRA_GEN_DEFINES_ARGS=--edtlib-Werror -GNinja -S/home/tmon/zephyrproject/zephyr/tests/subsys/usb/device -DBOARD=nrf5340dk_nrf5340_cpuapp_ns
2022-12-02 08:30:39,140 - twister - DEBUG - Launch process 4
2022-12-02 08:30:39,141 - twister - DEBUG - Launch process 5
2022-12-02 08:30:39,142 - twister - DEBUG - Launch process 6
2022-12-02 08:30:39,144 - twister - DEBUG - Launch process 7
2022-12-02 08:30:39,145 - twister - DEBUG - Launch process 8
2022-12-02 08:30:39,147 - twister - DEBUG - Launch process 9
2022-12-02 08:30:39,148 - twister - DEBUG - Launch process 10
2022-12-02 08:30:39,149 - twister - DEBUG - Launch process 11
2022-12-02 08:30:40,878 - twister - DEBUG - Finished building /home/tmon/zephyrproject/zephyr/tests/subsys/usb/device for nrf5340dk_nrf5340_cpuapp_ns
2022-12-02 08:30:40,880 - twister - DEBUG - build test: nrf5340dk_nrf5340_cpuapp_ns/zephyr/tests/subsys/usb/device/usb.device
2022-12-02 08:30:40,880 - twister - DEBUG - Building /home/tmon/zephyrproject/zephyr/tests/subsys/usb/device for nrf5340dk_nrf5340_cpuapp_ns
2022-12-02 08:30:48,517 - twister - DEBUG - Determine test cases for test instance: nrf5340dk_nrf5340_cpuapp_ns/zephyr/tests/subsys/usb/device/usb.device
2022-12-02 08:30:48,517 - twister - DEBUG - zephyr.symbols found: /home/tmon/zephyrproject/zephyr/twister-out/nrf5340dk_nrf5340_cpuapp_ns/zephyr/tests/subsys/usb/device/usb.device/zephyr/zephyr.symbols
2022-12-02 08:30:48,517 - twister - DEBUG - Determine test cases for test suite: usb.device
2022-12-02 08:30:48,517 - twister - DEBUG - Test instance nrf5340dk_nrf5340_cpuapp_ns/zephyr/tests/subsys/usb/device/usb.device already has 5 cases.
2022-12-02 08:30:48,519 - twister - DEBUG - run test: nrf5340dk_nrf5340_cpuapp_ns/zephyr/tests/subsys/usb/device/usb.device
2022-12-02 08:30:48,519 - twister - DEBUG - Using serial device /dev/ttyACM1 @ 115200 baud
2022-12-02 08:30:49,530 - twister - DEBUG - Flash command: ['ninja', '-C', '/home/tmon/zephyrproject/zephyr/twister-out/nrf5340dk_nrf5340_cpuapp_ns/zephyr/tests/subsys/usb/device/usb.device', 'flash']
2022-12-02 08:31:02,257 - twister - DEBUG - ninja: Entering directory `/home/tmon/zephyrproject/zephyr/twister-out/nrf5340dk_nrf5340_cpuapp_ns/zephyr/tests/subsys/usb/device/usb.device'
[0/1] Flashing nrf5340dk_nrf5340_cpuapp_ns
-- west flash: rebuilding
[0/20] Performing build step for 'tfm'
ninja: no work to do.
[2/3] Performing install step for 'tfm'
-- Install configuration: "MinSizeRel"
[3/3] Completed 'tfm'
-- west flash: using runner nrfjprog
Using board 1050033908
-- runners.nrfjprog: Flashing file: /home/tmon/zephyrproject/zephyr/twister-out/nrf5340dk_nrf5340_cpuapp_ns/zephyr/tests/subsys/usb/device/usb.device/tfm_merged.hex

[ ######               ]   0.000s | Erase file - Check image                                                           

[ ##                   ]   0.000s | Check image validity - Initialize device info                                      

[ #####                ]   0.000s | Check image validity - Check region 0 settings                                     

[ ########             ]   0.000s | Check image validity - block 1 of 5                                                

[ ###########          ]   0.027s | Check image validity - block 2 of 5                                                

[ ##############       ]   0.017s | Check image validity - block 3 of 5                                                

[ #################### ]   0.043s | Check image validity - Finished                                                    

[ #############        ]   0.000s | Erase file - Erasing                                                               

[ ####                 ]   0.000s | Erasing non-volatile memory - block 1 of 4                                         

[ ########             ]   1.113s | Erasing non-volatile memory - block 2 of 4                                         

[ ############         ]   3.391s | Erasing non-volatile memory - block 3 of 4                                         

[ #################### ]   0.000s | Erasing non-volatile memory - Erase successful                                     

[ #################### ]   7.438s | Erase file - Done erasing                                                          

[ ######               ]   0.000s | Program file - Checking image                                                      

[ ##                   ]   0.000s | Check image validity - Initialize device info                                      

[ #####                ]   0.000s | Check image validity - Check region 0 settings                                     

[ ########             ]  10.529s | Check image validity - block 1 of 5                                                

[ ###########          ]   5.753s | Check image validity - block 2 of 5                                                

[ ##############       ]   3.117s | Check image validity - block 3 of 5                                                

[ #################### ]   0.010s | Check image validity - Finished                                                    

[ #############        ]   0.000s | Program file - Programming                                                         

[ ####                 ]   0.000s | Programming image - block 1 of 4                                                   

[ ########             ]   0.231s | Programming image - block 2 of 4                                                   

[ ############         ]   0.738s | Programming image - block 3 of 4                                                   

[ #################### ]   0.000s | Programming image - Write successful                                               

[ #################### ]   1.587s | Program file - Done programming                                                    

[ ######               ]   0.000s | Verify file - Check image                                                          

[ ##                   ]   0.000s | Check image validity - Initialize device info                                      

[ #####                ]   0.000s | Check image validity - Check region 0 settings                                     

[ ########             ]  12.841s | Check image validity - block 1 of 5                                                

[ ###########          ]   7.015s | Check image validity - block 2 of 5                                                

[ ##############       ]   3.798s | Check image validity - block 3 of 5                                                

[ #################### ]   0.000s | Check image validity - Finished                                                    

[ #############        ]   0.000s | Verify file - Verifying                                                            

[ ####                 ]   0.000s | Verifying image - block 1 of 4                                                     

[ ########             ]   0.214s | Verifying image - block 2 of 4                                                     

[ ############         ]   0.737s | Verifying image - block 3 of 4                                                     

[ #################### ]   0.000s | Verifying image - Verify successful                                                

[ #################### ]   1.583s | Verify file - Done verifying                                                       
Applying pin reset.
-- runners.nrfjprog: Board with serial number 1050033908 flashed successfully.

2022-12-02 08:31:05,006 - twister - DEBUG - DEVICE: D: __usb_descriptor_start 0x20040124
2022-12-02 08:31:05,016 - twister - DEBUG - DEVICE: D: __usb_descriptor_end 0x20040195
2022-12-02 08:31:05,020 - twister - DEBUG - DEVICE: D: Configuration descriptor 0x20040136
2022-12-02 08:31:05,030 - twister - DEBUG - DEVICE: D: Interface descriptor 0x2004013f
2022-12-02 08:31:05,033 - twister - DEBUG - DEVICE: D: Endpoint descriptor 0x20040148
2022-12-02 08:31:05,042 - twister - DEBUG - DEVICE: D: ep 0x81, mps 64, type 2
2022-12-02 08:31:05,045 - twister - DEBUG - DEVICE: D: Fixing EP address 81 -> 81
2022-12-02 08:31:05,053 - twister - DEBUG - DEVICE: D: endpoint 0x81
2022-12-02 08:31:05,056 - twister - DEBUG - DEVICE: D: Now the wTotalLength is 25
2022-12-02 08:31:05,067 - twister - DEBUG - DEVICE: D: idx_max 11, ascii_idx_max 5, buf 0x20040155
2022-12-02 08:31:05,070 - twister - DEBUG - DEVICE: D: char R : 52, idx 5 -> 11
2022-12-02 08:31:05,079 - twister - DEBUG - DEVICE: D: char Y : 59, idx 4 -> 9
2022-12-02 08:31:05,081 - twister - DEBUG - DEVICE: D: char H : 48, idx 3 -> 7
2022-12-02 08:31:05,084 - twister - DEBUG - DEVICE: D: char P : 50, idx 2 -> 5
2022-12-02 08:31:05,093 - twister - DEBUG - DEVICE: D: char E : 45, idx 1 -> 3
2022-12-02 08:31:05,095 - twister - DEBUG - DEVICE: D: char Z : 5a, idx 0 -> 1
2022-12-02 08:31:05,106 - twister - DEBUG - DEVICE: D: idx_max 13, ascii_idx_max 6, buf 0x20040163
2022-12-02 08:31:05,116 - twister - DEBUG - DEVICE: D: char V : 56, idx 6 -> 13
2022-12-02 08:31:05,119 - twister - DEBUG - DEVICE: D: char E : 45, idx 5 -> 11
2022-12-02 08:31:05,121 - twister - DEBUG - DEVICE: D: char D : 44, idx 4 -> 9
2022-12-02 08:31:05,130 - twister - DEBUG - DEVICE: D: char - : 2d, idx 3 -> 7
2022-12-02 08:31:05,133 - twister - DEBUG - DEVICE: D: char B : 42, idx 2 -> 5
2022-12-02 08:31:05,142 - twister - DEBUG - DEVICE: D: char S : 53, idx 1 -> 3
2022-12-02 08:31:05,145 - twister - DEBUG - DEVICE: D: char U : 55, idx 0 -> 1
2022-12-02 08:31:05,146 - twister - DEBUG - DEVICE: D: Serial Number
2022-12-02 08:31:05,156 - twister - DEBUG - DEVICE: D: 54 c9 5e ba d9 f4 5c 93 |T.^...\.
2022-12-02 08:31:05,168 - twister - DEBUG - DEVICE: D: idx_max 31, ascii_idx_max 15, buf 0x20040173
2022-12-02 08:31:05,170 - twister - DEBUG - DEVICE: D: char 3 : 33, idx 15 -> 31
2022-12-02 08:31:05,180 - twister - DEBUG - DEVICE: D: char 9 : 39, idx 14 -> 29
2022-12-02 08:31:05,182 - twister - DEBUG - DEVICE: D: char C : 43, idx 13 -> 27
2022-12-02 08:31:05,192 - twister - DEBUG - DEVICE: D: char 5 : 35, idx 12 -> 25
2022-12-02 08:31:05,194 - twister - DEBUG - DEVICE: D: char 4 : 34, idx 11 -> 23
2022-12-02 08:31:05,204 - twister - DEBUG - DEVICE: D: char F : 46, idx 10 -> 21
2022-12-02 08:31:05,207 - twister - DEBUG - DEVICE: D: char 9 : 39, idx 9 -> 19
2022-12-02 08:31:05,209 - twister - DEBUG - DEVICE: D: char D : 44, idx 8 -> 17
2022-12-02 08:31:05,219 - twister - DEBUG - DEVICE: D: char A : 41, idx 7 -> 15
2022-12-02 08:31:05,221 - twister - DEBUG - DEVICE: D: char B : 42, idx 6 -> 13
2022-12-02 08:31:05,230 - twister - DEBUG - DEVICE: D: char E : 45, idx 5 -> 11
2022-12-02 08:31:05,233 - twister - DEBUG - DEVICE: D: char 5 : 35, idx 4 -> 9
2022-12-02 08:31:05,242 - twister - DEBUG - DEVICE: D: char 9 : 39, idx 3 -> 7
2022-12-02 08:31:05,245 - twister - DEBUG - DEVICE: D: char C : 43, idx 2 -> 5
2022-12-02 08:31:05,247 - twister - DEBUG - DEVICE: D: char 4 : 34, idx 1 -> 3
2022-12-02 08:31:05,256 - twister - DEBUG - DEVICE: D: char 5 : 35, idx 0 -> 1
2022-12-02 08:31:05,269 - twister - DEBUG - DEVICE: *** Booting Zephyr OS build zephyr-v3.2.0-2064-g7c8264277a93 ***
2022-12-02 08:31:05,272 - twister - DEBUG - DEVICE: Running TESTSUITE device_usb
2022-12-02 08:31:05,284 - twister - DEBUG - DEVICE: ===================================================================
2022-12-02 08:31:05,294 - twister - DEBUG - DEVICE: D: lock usb_enable_lock mutex
2022-12-02 08:31:05,296 - twister - DEBUG - DEVICE: D: USB detected
2022-12-02 08:31:05,309 - twister - DEBUG - DEVICE: D: set cb, D: USB D: SUSPEND state detected
2022-12-02 08:31:05,315 - twister - DEBUG - DEVICE: Powered
2022-12-02 08:31:05,316 - twister - DEBUG - DEVICE: D: USB Suspend state
2022-12-02 08:31:05,317 - twister - DEBUG - DEVICE: ep: 0x81
2022-12-02 08:31:05,319 - twister - DEBUG - DEVICE: D: EP enable: 0x00
2022-12-02 08:31:05,328 - twister - DEBUG - DEVICE: D: EP enable: 0x80
2022-12-02 08:31:05,330 - twister - DEBUG - DEVICE: D: unlock usb_enable_lock mutex
2022-12-02 08:31:05,339 - twister - DEBUG - DEVICE: START - test_usb_dc_api
2022-12-02 08:31:05,343 - twister - DEBUG - DEVICE: PASS - test_usb_dc_api in 0.001 seconds
2022-12-02 08:31:05,356 - twister - DEBUG - DEVICE: ===================================================================
2022-12-02 08:31:05,366 - twister - DEBUG - DEVICE: START - test_usb_dc_api_invalid
2022-12-02 08:31:05,368 - twister - DEBUG - DEVICE: D: ep_write: ep 0x20, len 1
2022-12-02 08:31:05,378 - twister - DEBUG - DEVICE: D: ep_read: ep 0x20, maxlen 1
2022-12-02 08:31:05,389 - twister - DEBUG - DEVICE: PASS - test_usb_dc_api_invalid in 0.013 seconds
2022-12-02 08:31:05,402 - twister - DEBUG - DEVICE: ===================================================================
2022-12-02 08:31:05,405 - twister - DEBUG - DEVICE: START - test_usb_dc_api_read_write
2022-12-02 08:31:05,415 - twister - DEBUG - DEVICE: D: ep_read: ep 0x20, maxlen 1
2022-12-02 08:31:05,417 - twister - DEBUG - DEVICE: D: ep_write: ep 0x20, len 1
2022-12-02 08:31:05,429 - twister - DEBUG - DEVICE: PASS - test_usb_dc_api_read_write in 0.013 seconds
2022-12-02 08:31:05,442 - twister - DEBUG - DEVICE: ===================================================================
2022-12-02 08:31:05,444 - twister - DEBUG - DEVICE: START - test_usb_deconfig
2022-12-02 08:31:05,452 - twister - DEBUG - DEVICE: D: USBD Reset
2022-12-02 08:31:05,454 - twister - DEBUG - DEVICE: D: USB detected
2022-12-02 08:31:05,456 - twister - DEBUG - DEVICE: PASS - tesD: USB Powered
2022-12-02 08:31:05,467 - twister - DEBUG - DEVICE: t_usb_deconfig D: SUSPEND state detected
2022-12-02 08:31:05,469 - twister - DEBUG - DEVICE: D: USB Suspend state
2022-12-02 08:31:05,477 - twister - DEBUG - DEVICE: in 0.010 seconds
2022-12-02 08:31:05,490 - twister - DEBUG - DEVICE: ===================================================================
2022-12-02 08:31:05,492 - twister - DEBUG - DEVICE: START - test_usb_disable
2022-12-02 08:31:05,501 - twister - DEBUG - DEVICE: D: EP disable: 0x00
2022-12-02 08:31:05,503 - twister - DEBUG - DEVICE: D: EP disable: 0x80
2022-12-02 08:31:05,514 - twister - DEBUG - DEVICE: PASS - test_usb_disable in 0.011 seconds
2022-12-02 08:31:05,527 - twister - DEBUG - DEVICE: ===================================================================
2022-12-02 08:31:05,529 - twister - DEBUG - DEVICE: TESTSUITE device_usb succeeded
2022-12-02 08:31:05,529 - twister - DEBUG - DEVICE: 
2022-12-02 08:31:05,540 - twister - DEBUG - DEVICE: ------ TESTSUITE SUMMARY START ------
2022-12-02 08:31:05,540 - twister - DEBUG - DEVICE: 
2022-12-02 08:31:05,556 - twister - DEBUG - DEVICE: SUITE PASS - 100.00% [device_usb]: pass = 5, fail = 0, skip = 0, total = 5 duration = 0.048 seconds
2022-12-02 08:31:05,568 - twister - DEBUG - DEVICE: - PASS - [device_usb.test_usb_dc_api] duration = 0.001 seconds
2022-12-02 08:31:05,582 - twister - DEBUG - DEVICE: - PASS - [device_usb.test_usb_dc_api_invalid] duration = 0.013 seconds
2022-12-02 08:31:05,602 - twister - DEBUG - DEVICE: - PASS - [device_usb.test_usb_dc_api_read_write] duration = 0.013 seconds
2022-12-02 08:31:05,615 - twister - DEBUG - DEVICE: - PASS - [device_usb.test_usb_deconfig] duration = 0.010 seconds
2022-12-02 08:31:05,627 - twister - DEBUG - DEVICE: - PASS - [device_usb.test_usb_disable] duration = 0.011 seconds
2022-12-02 08:31:05,628 - twister - DEBUG - DEVICE: 
2022-12-02 08:31:05,631 - twister - DEBUG - DEVICE: ------ TESTSUITE SUMMARY END ------
2022-12-02 08:31:05,631 - twister - DEBUG - DEVICE: 
2022-12-02 08:31:05,644 - twister - DEBUG - DEVICE: ===================================================================
2022-12-02 08:31:05,654 - twister - DEBUG - DEVICE: RunID: 6823661a5af2e5762eb7e45936f2f632
2022-12-02 08:31:05,657 - twister - DEBUG - DEVICE: PROJECT EXECUTION SUCCESSFUL
2022-12-02 08:31:05,659 - twister - DEBUG - run status: nrf5340dk_nrf5340_cpuapp_ns/zephyr/tests/subsys/usb/device/usb.device passed
2022-12-02 08:31:05,660 - twister - INFO - 1/1 nrf5340dk_nrf5340_cpuapp_ns zephyr/tests/subsys/usb/device/usb.device          [32mPASSED[39m (device 16.129s)
2022-12-02 08:31:05,664 - twister - INFO - 1 test scenarios (1 test instances) selected, 0 configurations skipped (0 by static filter, 0 at runtime).
2022-12-02 08:31:05,664 - twister - DEBUG - --------------------------------
2022-12-02 08:31:05,664 - twister - DEBUG - Total test suites: 1
2022-12-02 08:31:05,664 - twister - DEBUG - Total test cases: 5
2022-12-02 08:31:05,664 - twister - DEBUG - Executed test cases: 5
2022-12-02 08:31:05,664 - twister - DEBUG - Skipped test cases: 0
2022-12-02 08:31:05,664 - twister - DEBUG - Completed test suites: 1
2022-12-02 08:31:05,664 - twister - DEBUG - Passing test suites: 1
2022-12-02 08:31:05,664 - twister - DEBUG - Failing test suites: 0
2022-12-02 08:31:05,664 - twister - DEBUG - Skipped test suites: 0
2022-12-02 08:31:05,664 - twister - DEBUG - Skipped test suites (runtime): 0
2022-12-02 08:31:05,664 - twister - DEBUG - Skipped test suites (filter): 0
2022-12-02 08:31:05,664 - twister - DEBUG - Errors: 0
2022-12-02 08:31:05,664 - twister - DEBUG - --------------------------------
2022-12-02 08:31:05,664 - twister - INFO - [32m1 of 1[39m test configurations passed (100.00%), [39m0[39m failed, 0 skipped with [39m0[39m warnings in 27.31 seconds
2022-12-02 08:31:05,664 - twister - INFO - In total 5 test cases were executed, 0 skipped on 1 out of total 518 platforms (0.19%)
2022-12-02 08:31:05,664 - twister - INFO - [32m1[39m test configurations executed on platforms, [31m0[39m test configurations were only built.
2022-12-02 08:31:05,665 - twister - INFO - Saving reports...
2022-12-02 08:31:05,665 - twister - INFO - Writing JSON report /home/tmon/zephyrproject/zephyr/twister-out/twister.json
2022-12-02 08:31:05,665 - twister - INFO - Writing xunit report /home/tmon/zephyrproject/zephyr/twister-out/twister.xml...
2022-12-02 08:31:05,666 - twister - INFO - Writing xunit report /home/tmon/zephyrproject/zephyr/twister-out/twister_report.xml...
2022-12-02 08:31:05,666 - twister - DEBUG - usb.device.usb_deconfig: No status
2022-12-02 08:31:05,666 - twister - DEBUG - usb.device.usb_deconfig: No status
2022-12-02 08:31:05,666 - twister - INFO - Run completed
```

**Comment by desowin** [comment] 2022-12-02 11:22
The very important detail is to have nRF USB not connected. If nRF USB is connected, everything works as expected.

**Comment by desowin** [comment] 2022-12-02 12:34
This is duplicate of #52703. That is, the actual root cause is the same, only the way the bug exhibits itself is different (hang on nRF530 DK vs "Illegal use of the EPSR" on nRF52840 DK)

**Closed by desowin** 2022-12-02 12:34 UTC
Labels: bug, Duplicate, priority: low, area: USB, platform: nRF, area: Tests
