### ISSUE TITLE
wifi simple_link driver build error

### ISSUE THREAD

**Issue by tbursztyka** [zephyrproject-rtos/zephyr#27634] opened 2020-08-18 07:01 UTC
**Describe the bug**
build error

**To Reproduce**
west build -b cc3235sf_launchxl samples/net/sockets/http_get

**Expected behavior**
no error

**Logs and console output**
See for yourself while building the sample.

**Comment by jukkar** [comment] 2020-08-18 07:47
Duplicate of #27587

**Closed by jukkar** 2020-08-18 07:47 UTC
Labels: bug
