### ISSUE TITLE
tests/kernel/common: test_bitfield: test_bitfield: (b1 not equal to (1 << bit))

### ISSUE THREAD

**Issue by cinlyooi-intel** [zephyrproject-rtos/zephyr#15019] opened 2019-03-29 11:55 UTC
**Describe the bug**
Assertion occured at test_bitfield(), i.e.

test_bitfield: (b1 not equal to (1 << bit))

Observed for both test cases `kernel.common` and `kernel.common.misra`

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=altera_max10
3. make
4. make run

**Screenshots or console output**
```
***** Booting Zephyr OS v1.14.0-rc3-2-gf5a4a698ec17 (delayed boot 3000ms) *****
Running test suite common
===================================================================
starting test - test_verify_bootdelay
PASS - test_verify_bootdelay
===================================================================
starting test - test_irq_offload
PASS - test_irq_offload
===================================================================
starting test - test_byteorder_memcpy_swap
PASS - test_byteorder_memcpy_swap
===================================================================
starting test - test_byteorder_mem_swap
PASS - test_byteorder_mem_swap
===================================================================
starting test - test_atomic
PASS - test_atomic
===================================================================
starting test - test_bitfield
twiddling bits....

    Assertion failed at /home/cinlyooi/tests/zephyr.git/tests/kernel/common/src/bitfield.c:43: test_bitfield: (b1 not equal to (1 << bit))
sys_set_bit failed on bit 0

FAIL - test_bitfield
===================================================================
starting test - test_printk
22 113 10000 32768 40000 22
p 112 -10000 -32768 -40000 -22
0xcafebabe 0x0000beef
0x1 0x01 0x0001 0x00000001 0x0000000000000001
0x1 0x 1 0x   1 0x       1
42 42 0042 00000042
-42 -42 -042 -0000042
42 42   42       42
42 42 0042 00000042
255     42    abcdef  0x0000002a      42
ERR -1 ERR ffffffffffffffff
PASS - test_printk
===================================================================
starting test - test_slist
PASS - test_slist
===================================================================
starting test - test_dlist
PASS - test_dlist
===================================================================
starting test - test_intmath
PASS - test_intmath
===================================================================
starting test - test_timeout_order
thread 0 synced on timer 0
thread 1 synced on timer 1
thread 2 synced on timer 2
PASS - test_timeout_order
===================================================================
starting test - test_clock_uptime
PASS - test_clock_uptime
===================================================================
starting test - test_clock_cycle
PASS - test_clock_cycle
===================================================================
starting test - test_version
PASS - test_version
===================================================================
starting test - test_multilib
PASS - test_multilib
===================================================================
starting test - test_thread_context
PASS - test_thread_context
===================================================================
Test suite common failed.
===================================================================

```
**Environment (please complete the following information):**
 - OS: fedora29
 - Toolchain: zephyr
 - Commit SHA or Version used: f5a4a698ec17e6a78299966a1a3fe73c3404b78d

**Comment by nashif** [comment] 2019-03-29 12:27
duplicate of #7909

**Closed by nashif** 2019-03-29 12:27 UTC
Labels: area: Kernel, area: Tests, bug
