### ISSUE TITLE
Ninja: Running sanitycheck has byproducts outside of sanity-out

### ISSUE THREAD

**Issue by SebastianBoe** [zephyrproject-rtos/zephyr#5725] opened 2018-01-18 14:10 UTC
Running sanitycheck with ninja will dirty the repo with untracked files.

e.g. tests/net/arp/test/

All files should be written to sanity-out.

**Comment by nashif** [comment] 2018-01-18 14:27
I have noticed this, but was never able to reproduce it, is there a simple way to reproduce this?

**Comment by SebastianBoe** [comment] 2018-01-19 07:33
Run it from my machine? ;)

Will take a closer look.

**Comment by nashif** [comment] 2018-07-13 17:51
have not see this issue and can't reproduce, closing

**Closed by nashif** 2018-07-13 17:51 UTC
Labels: area: Build System, area: Testing, bug, priority: low
