### ISSUE TITLE
Cannot calculate CAN SJW timing parameter

### ISSUE THREAD

**Issue by pfayolle** [zephyrproject-rtos/zephyr#61077] opened 2023-08-02 14:32 UTC
**Describe the bug**
No CAN API function actually sets the SJW timing parameter.

I am using a board based on a STM32H7, and trying to calculate CAN timing parameters to achieve a bus speed of 500Kbps.
I am on the v3.4 branch.

I tried:
- using the can_calc_timing function, but it does not update the SJW attribute of the can_timing structure.
- using the can_set_bitrate, but it explicitly sets SJW to 0 at the end of the function.

**To Reproduce**
Trying to set the bitrate or CAN timings to achieve a particular bus speed at runtime.

**Expected behavior**
The SJW attribute should be set to the proper value, allowing the can_set_timing call to succeed afterwards and have valid communications with other devices.

For a 500Kbs, and a 87.5% sampling point, I expect to have:
- prescaler = 1
- sjw = 128
- prop-seg = 0
- phase-seg1 = 167
- phase-seg2 = 24

If I use these values I can communicate properly with another CAN device that uses a 500Kbps bus speed.

**Impact**
This prevents changing the bus speed to arbitrary values at runtime, and forces the me to hard code the values.

**Comment by henrikbrixandersen** [comment] 2023-08-07 12:35
> * using the can_calc_timing function, but it does not update the SJW attribute of the can_timing structure.

That's expected. The CAN timing calculation functions do not alter the SJW as this is independent of the other bit timing parameters.

> * using the can_set_bitrate, but it explicitly sets SJW to 0 at the end of the function.

If by `0` you mean `CAN_SJW_NO_CHANGE` (which is defined to zero), then yes. Again, this is the expected behavior (see above). This allows the driver to use the hardcoded SJW value specified at build-time (see https://github.com/zephyrproject-rtos/zephyr/blob/a5895d6464e4e6b3f348ae51fb7ee037473a0365/drivers/can/can_mcan.c#L216 for an example implementation of this, as used on the STM32H7).

It is definitely possible to change the SJW at runtime. See https://github.com/zephyrproject-rtos/zephyr/blob/a5895d6464e4e6b3f348ae51fb7ee037473a0365/drivers/can/can_shell.c#L395 for an example of how the CAN shell module allows setting the SJW along with the bitrate.

**Comment by henrikbrixandersen** [comment] 2023-08-14 09:14
@pfayolle I am closing this issue since setting the SJW timing parameter at runtime _is_ supported. Please reopen if you see things differently.

**Closed by henrikbrixandersen** 2023-08-14 09:14 UTC
Labels: bug, priority: low, area: CAN
