### ISSUE TITLE
tests/benchmarks/timing_info failures on nrf52[840]_pca100040[56]

### ISSUE THREAD

**Issue by inakypg** [zephyrproject-rtos/zephyr#1279] opened 2017-08-28 21:40 UTC
Toolchain: ZEPHYR_GCC_VARIANT=zephyr
Repo: https://github.com/zephyrproject-rtos/zephyr.git 1f46eb66d8e13708b65e80ee4db4e9de05b14bf6 master          
Board: nrf52840_pca10056 

Summary:

```
eval failed: found expected (for failure) `(USAGE FAULT|[Ff]atal fault in )` in console `jfsotc03/nrf52840-33:default` at 1.60s
console output: ***** delaying boot 1000ms (per build configuration) *****
console output: ***** MPU FAULT *****
console output:   Executing thread ID (thread): 0x200010c0
console output:   Faulting instruction address:  0x200024c0
console output:   Instruction Access Violation
console output: Fatal fault in ISR! Spinning...

```
Detailed output:

```
build passed: 'mkdir -p /home/jenkins/workspace/zephyr-master-tcf-v0.11-branch/LABEL/verify/SHARD/2-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/tcf.runci-170828-0531-72-hZMhkH/tfse/outdir-tfse-ibg4-nrf52840_pca10056; rm -f /home/jenkins/workspace/zephyr-master-tcf-v0.11-branch/LABEL/verify/SHARD/2-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/tcf.runci-170828-0531-72-hZMhkH/tfse/outdir-tfse-ibg4-nrf52840_pca10056/.config' @/home/jenkins/workspace/zephyr-master-tcf-v0.11-branch/LABEL/verify/SHARD/2-3/ZEPHYR_GCC_VARIANT/zephyr/tcf.git/tcfl/app_zephyr.py:125
build passed: 'make -j -C /home/jenkins/workspace/zephyr-master-tcf-v0.11-branch/LABEL/verify/SHARD/2-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/tests/benchmarks/timing_info/ EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" KCPPFLAGS=-DTC_RUNID=ci-170828-0531-72:ibg4 BOARD=nrf52840_pca10056 ARCH=arm  O=/home/jenkins/workspace/zephyr-master-tcf-v0.11-branch/LABEL/verify/SHARD/2-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/tcf.runci-170828-0531-72-hZMhkH/tfse/outdir-tfse-ibg4-nrf52840_pca10056 initconfig' @/home/jenkins/workspace/zephyr-master-tcf-v0.11-branch/LABEL/verify/SHARD/2-3/ZEPHYR_GCC_VARIANT/zephyr/tcf.git/tcfl/app_zephyr.py:167
build output: Using /home/jenkins/workspace/zephyr-master-tcf-v0.11-branch/LABEL/verify/SHARD/2-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/boards/arm/nrf52840_pca10056/nrf52840_pca10056_defconfig as base
build output: Merging prj.conf
build output: Merging /home/jenkins/workspace/zephyr-master-tcf-v0.11-branch/LABEL/verify/SHARD/2-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/tcf.runci-170828-0531-72-hZMhkH/tfse/outdir-tfse-ibg4-nrf52840_pca10056/boot_config.conf
build output: .config:27:warning: symbol value '2048# Config file automatically generated by TCF's:' invalid for MAIN_STACK_SIZE
build output: #
build output: # configuration written to .config
build output: #
build passed: 'make -j -C /home/jenkins/workspace/zephyr-master-tcf-v0.11-branch/LABEL/verify/SHARD/2-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/tests/benchmarks/timing_info EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" KCPPFLAGS=-DTC_RUNID=ci-170828-0531-72:ibg4 BOARD=nrf52840_pca10056 ARCH=arm  O=/home/jenkins/workspace/zephyr-master-tcf-v0.11-branch/LABEL/verify/SHARD/2-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/tcf.runci-170828-0531-72-hZMhkH/tfse/outdir-tfse-ibg4-nrf52840_pca10056' @/home/jenkins/workspace/zephyr-master-tcf-v0.11-branch/LABEL/verify/SHARD/2-3/ZEPHYR_GCC_VARIANT/zephyr/tcf.git/tcfl/app_zephyr.py:197
build passed  type:nrf52840_pca10056
deployed (try 1/4) set([(u'kernel-arm', u'/home/jenkins/workspace/zephyr-master-tcf-v0.11-branch/LABEL/verify/SHARD/2-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/tcf.runci-170828-0531-72-hZMhkH/tfse/outdir-tfse-ibg4-nrf52840_pca10056/zephyr.hex')])
deploy (1 tries) passed
deploy passed  type:nrf52840_pca10056
Reset
eval failed: found expected (for failure) `(USAGE FAULT|[Ff]atal fault in )` in console `jfsotc03/nrf52840-33:default` at 1.60s
console output: ***** delaying boot 1000ms (per build configuration) *****
console output: ***** MPU FAULT *****
console output:   Executing thread ID (thread): 0x200010c0
console output:   Faulting instruction address:  0x200024c0
console output:   Instruction Access Violation
console output: Fatal fault in ISR! Spinning...

```

**Comment by nashif** [comment] 2017-08-28 23:54
duplicate of #1218

**Closed** 2017-08-28 23:56 UTC
