### ISSUE TITLE
logging: syst: sample failure

### ISSUE THREAD

**Issue by gmarull** [zephyrproject-rtos/zephyr#51074] opened 2022-10-07 12:01 UTC
**Describe the bug**

```
ERROR   - SYS-T RAW DATA: 020A7F0B480000000000000000002A2A2A20426F6F74696E67205A6570687972204F53206275696C64202573202573202A2A2A0A007A65706879722D76332E322E302D3330382D673632303863623562633936380000
SYS-T RAW DATA: 230A0601040000000000000000002B6E0000
SYS-T RAW DATA: 330A060104000000000000000000126E0000
SYS-T RAW DATA: 430A060104000000000000000000FC6D0000
SYS-T RAW DATA: 730A060104000100000000000000E56D0000

INFO    - /__w/zephyr/zephyr/twister-out/qemu_cortex_m0/samples/subsys/logging/syst/sample.logger.syst.catalog.deferred_cpp/handler.log
```

**To Reproduce**

```
./scripts/twister -T samples/subsys/logging/syst -p qemu_cortex_m0
```

**Expected behavior**

Sample/test passes

**Impact**

Blocking CI

**Logs and console output**

See above

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK 0.15.0
 - Commit SHA or Version used: 916e04e0ef3c129ae9837cdc05c13ea427650a12

**Additional context**

Observed in https://github.com/zephyrproject-rtos/zephyr/pull/50987

**Comment by stephanosio** [comment] 2022-10-07 12:02
Duplicate of #50941

**Closed by stephanosio** 2022-10-07 12:02 UTC
Labels: bug, priority: high, area: Logging
