### ISSUE TITLE
Tests: Crypto: rand32 faults on nrf51_pca10028 and nrf52_pca10040

### ISSUE THREAD

**Issue by spoorthik** [zephyrproject-rtos/zephyr#8199] opened 2018-06-06 07:24 UTC
**Test location:** tests/crypto/rand32/

**Test identifier:** crypto.rand32.random_hw_xoroshiro.rand32

**Configuration file:** prj_hw_random_xoroshiro.conf

**Execution log:**
On nrf51_pca10028:

```
***** HARD FAULT *****
Executing thread ID (thread): 0x00000000
Faulting instruction address: 0xf3efb662
Fatal fault in ISR! Spinning...

```

On nrf52_pca10040:

```
***** MPU FAULT *****
Executing thread ID (thread): 0x00000000
Faulting instruction address: 0x20000cc0
Data Access Violation
Address: 0x9
Fatal fault in essential thread! Spinning...
```
**Latest Commit on which the test fails:** 265f502b8e48ba3299bfbbef7814cbab196af0b3

**Comment by ManojSubbarao** [comment] 2018-06-11 03:44
@punitvara what is the status?

**Comment by punitvara** [comment] 2018-06-11 06:41
Asked for feedback on PR @ManojSubbarao

**Comment by punitvara** [comment] 2018-08-29 10:38
Updated justification for PR and reopened. @ManojSubbarao

**Comment by carlescufi** [comment] 2018-09-01 21:13
CC @pizi-nordic @ioannisg 

I believe the issue is the following:

The function that initializes the xoroshiro rng is called here:
https://github.com/zephyrproject-rtos/zephyr/blob/master/kernel/init.c#L495
This is before the scheduler has been initialized through a call to `_sched_init()`.

The xoroshiro init function (`xoroshiro128_initialize`) then calls `entropy_get_entropy`:
https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/random/rand32_xoroshiro128.c#L61
which in turn calls the `entropy_nrf5_get_entropy()` function in:
https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/entropy/entropy_nrf5.c#L241

This uses semaphores, and those are not functional before the scheduler has been initialized. So the possible fixes I see are:

1) Do not call `entropy_get_entropy` from  `xoroshiro128_initialize` at all
2) Instead call the early-boot `z_early_boot_rand32_get()` which is available even before the scheduler is up:
https://github.com/zephyrproject-rtos/zephyr/blob/master/kernel/init.c#L395

**Comment by AdithyaBaglody** [comment] 2018-09-03 05:30
@carlescufi is there a specific reason why we should continue to keep xoroshiro in pre_kernel_2? 
I see that this particular bug can be resolved just by moving it to post_kernel where the scheduler is up and the interrupts are enabled. 
The approach you said makes total sense if we have a specific need for the subsystem xoroshiro to be up and running before the kernel itself.  AFAIK we don't usually have subsystems running before the kernel unless there is a specific need.

**Comment by carlescufi** [comment] 2018-09-03 08:51
@AdithyaBaglody no, no specific reason at all. I have no issues with moving xoroshiro to post kernel. In fact, can you please send a PR for that?

**Comment by AdithyaBaglody** [comment] 2018-09-03 09:28
@carlescufi Please have a look at #8207

**Comment by carlescufi** [comment] 2018-09-03 10:01
@AdithyaBaglody I approved it, but I think you might break something when moving the init from PRE_KERNEL to POST_KERNEL, see Anas' comment in your PR.
Instead I suggest we go with option 2)

**Comment by AdithyaBaglody** [comment] 2018-09-03 10:33
@carlescufi oh I didn't see that. 
But now I am looking into that PR #7767. If I am not mistaken, it was created as a precursor to stack randomization. And then we ended up using the early_boot_rand32 API which only used the entropy drivers. 
@nashif @lpereira Can you please help me out here as to what exactly the PR fixed

**Comment by carlescufi** [comment] 2018-09-03 11:28
@nashif btw I think we could downgrade this from Medium to Low, since it's unlikely that the xoroshiro RNG will be used with our hardware

**Comment by nashif** [comment] 2018-09-03 14:15
@carlescufi you probably want to disable this test on nrf then

**Comment by lpereira** [comment] 2018-09-03 14:56
@AdithyaBaglody #7767 fixed the initialization order for entropy drivers and randomization libraries. Some randomization libraries require entropy at initialization (such as xoroshiro128+), and entropy drivers were not being initialized before the libraries. That's what that old PR is doing.

However, as @carlescufi mentions, some entropy drivers will use semaphores, and the system initialization must progress further before they can be used.

Maybe the xoroshiro initialization can be changed to do something similar to what `z_early_boot_rand32_get()` does , testing if `entropy_get_entropy_isr()` is supported first, and, if not supported, using `entropy_get_entropy()`?  This will fix the initialization in nRF boards, which is one of the few platforms implementing the `..._isr()` variant.

Initializing the random number generators before `POST_KERNEL` is necessary because the stack canary (`__stack_chk_guard`) *must* be initialized very early in the boot process; otherwise, the check will fail further along, and this will cause the system to panic.

**Comment by AdithyaBaglody** [comment] 2018-09-04 09:44
@lpereira I was looking at the code and I didn't find any references to the xoroshiro related code.
 Inside the init.c we have 
https://github.com/zephyrproject-rtos/zephyr/blob/master/kernel/init.c#L395
which is called from 
https://github.com/zephyrproject-rtos/zephyr/blob/master/kernel/init.c#L498

which will be used for stack pointer randomization.
This function (z_early_boot_rand32_get) for a NRF board will exit on 
https://github.com/zephyrproject-rtos/zephyr/blob/master/kernel/init.c#L418

the next place where this rand function would be used is in 
https://github.com/zephyrproject-rtos/zephyr/blob/master/kernel/thread.c#L296 ->  https://github.com/zephyrproject-rtos/zephyr/blob/master/kernel/thread.c#L263

Here the code will again goto z_early_boot_rand32_get(). Note this is post_kernel

So in this sequence I don't see a need for the xoroshiro to be at pre_kernel_2.


> Moving the initialization of the stack canary to this level 

Not at all saying this. I am only concerned with the xoroshiro subsystem initialization. 

>Maybe the xoroshiro initialization can be changed to do something similar to what z_early_boot_rand32_get()

Yep this is possible and I tested it and it is working. I have a patch ready for this. But my main concern is as explained above

**Comment by lpereira** [comment] 2018-09-04 14:17
Thanks for making the patch and confirming my theory works, @AdithyaBaglody!

Random number generator libraries, such as xoroshiro128+, will implement sys_rand32_get(). Their initialization are marked with a call to the SYS_INIT() macro. You don't call it directly.

**Comment by AdithyaBaglody** [comment] 2018-09-04 14:38
>Random number generator libraries, such as xoroshiro128+, will implement sys_rand32_get(). Their initialization are marked with a call to the SYS_INIT() macro. You don't call it directly.

I understand this is done during pre_kernel_2. But what I am trying to say here is that, the code that is needed by the kernel will never use the APIs from the subsystem xoroshiro directly.

So my point is, there is no need to change the code when we can just move the initialization to post_kernel.

**Comment by lpereira** [comment] 2018-09-04 18:01
It will, yes, please read the code carefully: sys_rand32_get() -- which might be the xoroshiro implementation -- might be called by the early boot RNG function depending on the configuration.  And, in some cases, if these things fail to obtain a semaphore, a very predictable value (the cycle counter, which is often a small number during early boot), will be used instead.

So, no, *please* don't change the initialization to POST_KERNEL. It's wrong.  **It'll break things.** It'll seem it's working when in fact it's **silently** thwarting the stack canaries.

You've made a patch fixing things; it just needs to be tweaked slightly, to not rely on `entropy_get_entropy_isr()` if not supported by the platform.  Once you do that, things should work just fine in every architecture.

**Comment by dleach02** [comment] 2018-09-04 20:31
Just note that moving initialization to POST_KERNEL is an architectural statement on when sys_rand32_get() can be used (probably still should have some documentation on this). 

Option 2 would address this problem since the root problem is that the NRF entropy function has semaphores and the path through z_early_boot_rand32_get() would instead use the NRF ISR entropy routine.

**Closed** 2018-09-05 17:04 UTC
Labels: area: Crypto / RNG, bug, nRF, priority: low
