### ISSUE TITLE
[Coverity CID: 183066] Error handling issues in /tests/kernel/mbox/mbox_api/src/test_mbox_api.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#6666] opened 2018-03-19 10:38 UTC
Static code scan issues seen in File: /tests/kernel/mbox/mbox_api/src/test_mbox_api.c
 Category: Error handling issues
 Function: tmbox_get
 Component: Tests
 CID: 183066
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by spoorthik** [comment] 2018-05-30 06:35
The issue is already fixed in the latest version of code base. This can be closed.

**Comment by mandarcthorat1** [comment] 2019-03-22 10:23
The problem is detected again by latest coverity scan. Please have a look

**Comment by ceolin** [comment] 2019-03-23 01:37
#14857

**Closed** 2019-03-26 00:09 UTC
Labels: Coverity, area: Tests, bug, priority: low
