### ISSUE TITLE
[Coverity CID :190997]Integer handling issues in /lib/os/printk.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#13828] opened 2019-02-27 10:54 UTC
Static code scan issues seen in File: /lib/os/printk.c
 Category: Integer handling issues
 Function: _vprintk
 Component: Other
 CID: 190997
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by galak** [comment] 2019-02-27 13:52
Closing duplicate of #13843

**Closed by galak** 2019-02-27 13:52 UTC
Labels: Coverity, area: Other, bug
