### ISSUE TITLE
WS2812 SPI LED driver with DMA on nrf52 bad SPI data

### ISSUE THREAD

**Issue by clementlgl** [zephyrproject-rtos/zephyr#33505] opened 2021-03-19 14:20 UTC
**Describe the bug**
I'm trying to make the WS2812 LED example work on nrf52dk_nrf52832.

WS2812 LED driver does not work properly on nrf52. When I use the SPI DMA driver (nordic,nrf-spi), a low level is maintained on the line for a few µS in the middle of the frame (see diagram below) and the LEDs do not support it.

![SPIM](https://user-images.githubusercontent.com/33811740/111792895-02181680-88c5-11eb-9878-65163e623973.png)

**Expected behavior**
If I use the standard SPI driver (nrf-spi) the bits are less regular but there is no low level maintained several microseconds in the middle of the frame. And it works :tada: 

![SPI](https://user-images.githubusercontent.com/33811740/111793330-7357c980-88c5-11eb-9d37-af97493d367a.png)

I think the problem comes from the SPI driver in DMA mode, have you ever had this problem?

**To Reproduce**
1. west build -b nrf52dk_nrf52832 -p auto samples/drivers/led_ws2812/
2. west flash

**Impact**
The LEDs don't work and using the spi driver without DMA is not a good solution.

**Environment**
 - OS: Ubuntu 18.04
 - Toolchain zephyr 0.12.3

**Comment by peterniebert** [comment] 2021-03-20 06:34
I would defintely say that this is not caused by a bug of zephyr, rather it is a design issue in nRF SOCs

I have observed the same thing some time ago independently in the context of mBed OS. Some not obvious change in the processor state must cause this pause. Or maybe, it is a priority issue on the bus?
You might try to place the buffer in a predefined memory page that is not used by anything else?

 Maybe this should be discussed with engineers at devzone? 

On the other hand, most WS2812 like LEDs now accept pauses of this dimension so it should not be a problem with modern LEDs. The downside is that reset times are now in the low 100s of us, which may negatively affect the frame rate. So you could still solve the problem by changing to modern LEDs.

**Comment by peterniebert** [comment] 2021-03-20 07:19
Reset times:

Take a look here: https://datasheet.lcsc.com/szlcsc/2006151006_Worldsemi-WS2812B-B_C114586.pdf
"RESET time>280μs, it won't cause wrong reset while interruption, its upports the lower frequency and inexpensive MCU."

**Comment by clementlgl** [comment] 2021-03-22 08:32
Thank you @peterniebert, 

Indeed I tried with LEDs bought more recently and it works well. My other strip is too old ... 

If it's a SOC bug it's a shame but I think we can close this issue. I also use Mbed OS and I will try on it.

Thanks for the link to the  WS2812 PDF, I had read it too quickly but I had not thought of an evolution of the WS2812 and that the LEDs of my old strip were old !

Thanks for your help

**Comment by carlescufi** [comment] 2021-03-23 17:11
Closing this since it doesn't seem to be a Zephyr issue. @anangl please reopen if you think this is an actual bug.

**Closed by carlescufi** 2021-03-23 17:11 UTC
Labels: area: SPI, bug, platform: nRF, priority: low
