### ISSUE TITLE
NXP: Enabling frdm_k64f usb host controller leads CI fail because frdm_k64f + max3421e is default used in CI

### ISSUE THREAD

**Issue by MarkWangChinese** [zephyrproject-rtos/zephyr#70013] opened 2024-03-11 01:44 UTC
**Describe the bug**
When implementing https://github.com/zephyrproject-rtos/zephyr/pull/68232, find: Enabling frdm_k64f usb host controller leads CI fail because frdm_k64f + max3421e is default used in CI

**Comment by hakehuang** [comment] 2024-05-23 04:05
@MarkWangChinese  please follow the community style to report issue. and this is not a bug but a feature enhance/missing

**Comment by decsny** [comment] 2024-06-25 18:21
I am going to close this because it doesn't seem to be reporting a bug and don't know what the meaning is. If there is a bug please edit the original message to follow the reporting template and then you can reopen this issue.

**Closed by decsny** 2024-06-25 18:21 UTC
Labels: bug, priority: low, area: USB, platform: NXP
