### ISSUE TITLE
[Coverity CID :203434]Control flow issues in /drivers/timer/xlnx_psttc_timer.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18365] opened 2019-08-17 20:39 UTC
Static code scan issues seen in File: /drivers/timer/xlnx_psttc_timer.c
 Category: Control flow issues
 Function: xttc_calculate_interval
 Component: Drivers
 CID: 203434
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by aescolar** [comment] 2019-08-18 09:25
@bbolen this code came from your PR #9316 from this commit 4ef9d4b , could you take a look at it?

![image](https://user-images.githubusercontent.com/32480799/63222629-d560c200-c1aa-11e9-97e1-4bf42bfb2309.png)

**Comment by bbolen** [comment] 2019-08-19 00:47
Yes, I'll take a look.

**Comment by galak** [comment] 2019-08-19 13:43
@bbolen looks like not a bug, but will let you look in more detail.

**Comment by LeiW000** [comment] 2019-08-21 05:27
We should ignore it in coverity. It is possible that "TIMER_INPUT_CLKHZ" is defined with a very large number by user in qemu_cortex_r5.dts.

I have updated "CID 203434" in coverity to ignore it. So, I think we can close the issue now.

**Closed** 2019-08-21 05:30 UTC
Labels: Coverity, area: Drivers, bug, priority: medium
