### ISSUE TITLE
frdm_k64f: tests/drivers/adc/adc_dma/drivers.adc.dma - CPU exeption

### ISSUE THREAD

**Issue by KamilxPaszkiet** [zephyrproject-rtos/zephyr#69977] opened 2024-03-08 14:49 UTC
**Describe the bug**
CPU exeption on `tests/drivers/adc/adc_dma/drivers.adc.dma` test.

**Logs and console output**
```
DEBUG   - DEVICE: *** Booting Zephyr OS build v3.6.0-646-g9412ad306f64 ***
DEBUG   - DEVICE: Running TESTSUITE adc_dma
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_adc_asynchronous_call
DEBUG   - DEVICE: E: ***** BUS FAULT *****
DEBUG   - DEVICE: E:   Instruction bus error
DEBUG   - DEVICE: E:   NXP MPU error, port 3
DEBUG   - DEVICE: E:     Mode: Supervisor, Instruction Address: 0x200023c0
DEBUG   - DEVICE: E:     Type: Read, Master: 0, Regions: 0x8400
DEBUG   - DEVICE: E: r0/a1:  0x0000a0cc  r1/a2:  0x0000ad52  r2/a3:  0x0000abc2
DEBUG   - DEVICE: E: r3/a4:  0x200023c0 r12/ip:  0x00000008 r14/lr:  0x0000091b
DEBUG   - DEVICE: E:  xpsr:  0x20000000
DEBUG   - DEVICE: E: Faulting instruction address (r15/pc): 0x200023c0
DEBUG   - DEVICE: E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
DEBUG   - DEVICE: E: Current thread: 0x200006c0 (test_adc_asynchronous_call)
DEBUG   - DEVICE: E: Halting system
```
**To Reproduce**
```
twister --device-testing --hardware-map map.yaml -s tests/drivers/adc/adc_dma/drivers.adc.dma -vv
```

- OS: Linux
- Toolchain: zephyr-sdk-0.16.5
- v3.6.0-646-g9412ad306f64

**Comment by decsny** [comment] 2024-05-02 16:49
might be related to #72080

**Comment by dleach02** [comment] 2024-05-30 20:46
Please try to reproduce with the sha listed (9412ad306f64)

**Comment by decsny** [comment] 2024-06-04 02:29
closing because the listed testcase doesn't exist and the nearest likely one (tests/drivers/adc/adc_api/drivers.adc.dma_nxp_kinetis) is passing, reopen if you still have an issue

**Closed by decsny** 2024-06-04 02:29 UTC
Labels: bug, priority: low, area: ADC, platform: NXP, platform: NXP Drivers
