### ISSUE TITLE
Arduino Nano 33 BLE sense constantly resetting.

### ISSUE THREAD

**Issue by bkalthoff** [zephyrproject-rtos/zephyr#33352] opened 2021-03-15 16:19 UTC
**Describe the bug**
After building and flashing the hello_world sample the board constantly resets over and over.
I've tried using different the master branch of zephyr and the v2.5 branch but to no avail.
I also tried different version of bossac, one that I built from source and one that came with the arduino IDE.
Flashing with the arduino IDE does not cause constant resetting. I have yet to try on building and flashing on another machine.

I am getting a warning when building. See warning further down.

**To Reproduce**
1. west build -p -b arduino_nano_33_ble samples/hello_world
2. west flash --bossac="/path/to/bossac"
3. sudo dmesg
4. Check if USB constantly disconnecting and reconnecting.

**dmesg output**

```
[ 9152.530787] usb 1-10: new full-speed USB device number 113 using xhci_hcd
[ 9152.689489] usb 1-10: New USB device found, idVendor=2341, idProduct=005a, bcdDevice= 0.11
[ 9152.689490] usb 1-10: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 9152.689491] usb 1-10: Product: Arduino Nano 33 BLE
[ 9152.689492] usb 1-10: Manufacturer: Arduino
[ 9152.689492] usb 1-10: SerialNumber: 0000000000000000A5048AA7799337A8
[ 9152.690955] cdc_acm 1-10:1.0: ttyACM0: USB ACM device
[ 9152.725168] usb 1-10: USB disconnect, device number 113
[ 9153.054786] usb 1-10: new full-speed USB device number 114 using xhci_hcd
[ 9153.213407] usb 1-10: New USB device found, idVendor=2341, idProduct=005a, bcdDevice= 0.11
[ 9153.213408] usb 1-10: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 9153.213409] usb 1-10: Product: Arduino Nano 33 BLE
[ 9153.213410] usb 1-10: Manufacturer: Arduino
[ 9153.213410] usb 1-10: SerialNumber: 0000000000000000A5048AA7799337A8
[ 9153.214946] cdc_acm 1-10:1.0: ttyACM0: USB ACM device
[ 9153.243920] usb 1-10: USB disconnect, device number 114
[ 9153.566790] usb 1-10: new full-speed USB device number 115 using xhci_hcd
[ 9153.725412] usb 1-10: New USB device found, idVendor=2341, idProduct=005a, bcdDevice= 0.11
[ 9153.725413] usb 1-10: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 9153.725414] usb 1-10: Product: Arduino Nano 33 BLE
[ 9153.725414] usb 1-10: Manufacturer: Arduino
[ 9153.725415] usb 1-10: SerialNumber: 0000000000000000A5048AA7799337A8
[ 9153.727355] cdc_acm 1-10:1.0: ttyACM0: USB ACM device
[ 9153.762748] usb 1-10: USB disconnect, device number 115
```

**cmake warning**
```
CMake Warning at ../../subsys/usb/CMakeLists.txt:22 (message):
  CONFIG_USB_DEVICE_VID has default value 0x2FE3.

  This value is only for testing and MUST be configured for USB products.


CMake Warning at ../../subsys/usb/CMakeLists.txt:28 (message):
  CONFIG_USB_DEVICE_PID has default value 0x100.

  This value is only for testing and MUST be configured for USB products.
  ```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain (Zephyr SDK)
 - Board https://store.arduino.cc/arduino-nano-33-ble-sense
 - V2.5 branch and Master branch

**Comment by bkalthoff** [comment] 2021-03-15 21:05
Found success when using UART and finally got some output. Guessing that the cdc_acm driver isn't working correctly.

**Comment by galak** [comment] 2021-03-16 21:56
> Found success when using UART and finally got some output. Guessing that the cdc_acm driver isn't working correctly.

When you say using UART, what do you mean?

@saltyJeff  can you look at this bug?

**Comment by bkalthoff** [comment] 2021-03-16 23:15
> > Found success when using UART and finally got some output. Guessing that the cdc_acm driver isn't working correctly.
> 
> When you say using UART, what do you mean?
> 
> @saltyJeff can you look at this bug?

I managed to get serial output through the tx/rx pins, but not the usb. I tried on two different machines, same issue.

**Comment by carlescufi** [comment] 2021-03-23 17:32
@jfischer-no could you try to shed some light here?

**Comment by jfischer-no** [comment] 2021-03-23 17:40
I do not think this is related to USB device support as it works fine on different nRF52840 based boards.
I also do think it is not a bug but configuration issue. Please check `samples/subsys/shell/shell_module ` build with overlay-usb.conf and `samples/subsys/usb/console`.

**Comment by jfischer-no** [comment] 2021-03-24 08:53
Is it related to #33523?

**Comment by Stefan-Schmidt** [comment] 2021-05-05 13:53
For me it was very much related. I have seen the same resetting behavior and the root was indeed the double offset problem described in #33523

Working around this double offset did lead to successful flashing and no more USB resetting.

**Comment by carlescufi** [comment] 2021-05-06 09:09
Closing as duplicate of #33523

**Closed by carlescufi** 2021-05-06 09:09 UTC
Labels: bug, priority: low
