### ISSUE TITLE
tests/drivers/watchdog/wdt_basic_api/: Watchdog setup error

### ISSUE THREAD

**Issue by cinlyooi-intel** [zephyrproject-rtos/zephyr#12803] opened 2019-01-29 02:01 UTC
**Describe the bug**
For same_70_xplained and arduino_due, we see a "Watchdog setup error" 

**To Reproduce**
1. mkdir build; cd build
2. cmake -GNinja -DBOARD=same_70_xplained -Darm
3. ninja
4. ninja run

for ardruino2 replace step 2 with
2. cmake -GNinja -DBOARD=adruino_due -Darm

**Screenshots or console output**
```
Running test suite wdt_basic_test
===================================================================
starting test - test_wdt
Testcase: test_wdt_no_callback
Watchdog setup error
Waiting to restart MCU**Environment 


```
**Environment (please complete the following information):**
 - OS:Linux
 - Toolchain : Zephyr
 - Commit SHA or Version used: aabaa4fab98c46429ac202268b3ed8cebd257bcd (for both boards)

**Comment by nashif** [comment] 2019-02-11 02:31
duplicate of #8097

**Closed by nashif** 2019-02-11 02:31 UTC
Labels: area: Watchdog, bug
