### ISSUE TITLE
UP² broken (git bisect findings inside)

### ISSUE THREAD

**Issue by tbursztyka** [zephyrproject-rtos/zephyr#31517] opened 2021-01-22 08:46 UTC
**Describe the bug**
Any samples running on UP² that has a console output should work, but it does not anymore.

**To Reproduce**

I tried the tests/arch/x86/info sample
up_squared board  (so x86_64) on multiboot (zephyr.strip)

**Expected behavior**
A lot of output on the multiboot, acpi and RTC

**Impact**
I cannot test my work on UP² atm, and I am using it extensively

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain:Zephyr SDK
 - Commit SHA: ef1b4d45b0ae1fe3cfd9e85d45acdf595a23a3b1

**Additional context**

I ran a git bisect, and it finds the commit 5c47bbc5010d98c6f6d795aa6d268138c3463bbd

It previously was commit 3660040e22042e0e67005da0a7229fc224e089d0 which was the same before it got reverted.

**Comment by tbursztyka** [comment] 2021-01-22 08:50
@andrewboie @nashif @dcpleung @andyross  Please have a look

@jhedberg Is the console still working properly on EHL on latest master? Perhaps, the issue could affect more that just the UP².

**Comment by jhedberg** [comment] 2021-01-22 09:33
@andrewboie @tbursztyka I just discovered that the same commit 3660040 also breaks zephyr.efi creation (the resulting file is too small (some 86k) and not a valid EFI binary according to EFI BIOS. @andyross FYI

**Comment by finikorg** [comment] 2021-01-22 10:30
Cannot boot any of EHLs

**Comment by jhedberg** [comment] 2021-01-22 11:24
@jenmwms FYI

**Comment by nashif** [comment] 2021-01-22 12:38
> Cannot boot any of EHLs, commit that broke seems to be [513b9f5](https://github.com/zephyrproject-rtos/zephyr/commit/513b9f598fc1135219d555013e8aa821447662d9)

this most likely would be a different issue, unrelated to paging

**Comment by nashif** [comment] 2021-01-22 14:12
paging commits reverted now, wrt to EFI, this should be filed as its own bug if this is really a problem.

**Comment by tbursztyka** [comment] 2021-01-25 08:23
EHL issue was definitely another one. 

UP² issue is still there.

**Comment by nashif** [comment] 2021-01-25 13:01
duplicate of #31566

**Closed by nashif** 2021-01-25 13:01 UTC
Labels: area: Boards, area: Console, bug, priority: high
