### ISSUE TITLE
Bluetooth: ISO: samples/bluetooth/broadcast_audio_source error -122

### ISSUE THREAD

**Issue by carlst** [zephyrproject-rtos/zephyr#49493] opened 2022-08-24 21:54 UTC
**Describe the bug**
samples/bluetooth/broadcast_audio_source displays log error -122

**To Reproduce**
1. build sample for nRF52840DK
2. run sample. console log displays: Unable to broadcast data on 0x20003ae4: -122

**Expected behavior**
sample should broadcast LE audio data

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain: Zephyr SDK, Segger Embedded Studio
 - Commit 7b1a8f4b8969648c598d7cfe796710b9f49be8a4

**Additional context**
May be related to the first of 3 commits in #48068:
https://github.com/zephyrproject-rtos/zephyr/pull/48068/commits/dc97b248f6317b5ab97f9281a320dfe42200f631

`iso_chan_max_data_len` reduces `max_data_len` below the requested SDU length (`buf->len`)

**Comment by Thalley** [comment] 2022-08-29 13:37
Duplicate of https://github.com/zephyrproject-rtos/zephyr/issues/49629

**Closed by Thalley** 2022-08-29 13:37 UTC
Labels: bug, area: Bluetooth, area: Bluetooth Host, area: Bluetooth ISO
