### ISSUE TITLE
Build STM32 : generate hex file fail

### ISSUE THREAD

**Issue by Benichou34** [zephyrproject-rtos/zephyr#16204] opened 2019-05-16 12:42 UTC
**Describe the bug**
Build displays the following errors messages:
```
C:\Program Files (x86)\GNU Tools ARM Embedded\8 2018-q4-major\bin\arm-none-eabi-objcopy.exe: zephyr.hex 64-bit address 0x4b4fa308000000 out of range for Intel Hex file
C:\Program Files (x86)\GNU Tools ARM Embedded\8 2018-q4-major\bin\arm-none-eabi-objcopy.exe:zephyr.hex: bad value
```
**To Reproduce**
Steps to reproduce the behavior: Build "Hello world" sample with nucleo_F413zh board.

**Expected behavior**
Generate hex file.

**Environment:**
 - OS: Windows 10 x64
 - Toolchain: GNU ARM toolchain 8-2018-q4-major
- Ninja 1.9.0.20190208
- CMake 3.14.4

**Comment by SebastianBoe** [comment] 2019-05-16 12:55
Duplicate of https://github.com/zephyrproject-rtos/zephyr/issues/12257

**Closed by SebastianBoe** 2019-05-16 12:55 UTC
Labels: bug

**Comment by Benichou34** [comment] 2019-05-16 15:07
Hello @SebastianBoe,
Please note that since PR #16022, generation of hex file for STM32 is activated by default.
So, this issue appears all the time, for each build.

**Comment by SebastianBoe** [comment] 2019-05-20 09:46
Noted.
