### ISSUE TITLE
MCU bootloader not take effective

### ISSUE THREAD

**Issue by ilyhcg** [zephyrproject-rtos/zephyr#56452] opened 2023-04-03 02:13 UTC
zephyr version：3.3.0
target platform ：nrf52840dk_nrf52840 or sparkfun_pro_micro_rp2040
test sample path：zephyr\samples\subsys\usb\dfu

  It  not have zephyr.signed.bin and app_signed.hex create.

**Comment by nordicjm** [comment] 2023-04-03 07:26
Works fine here, closing as user workflow issue, not a bug.

> It not have zephyr.signed.bin and app_signed.hex create.

app_signed.hex is unrelated to zephyr.

The reason you do not get a zephyr.signed.bin file is you are not setting the mcuboot signing key, `CONFIG_MCUBOOT_SIGNATURE_KEY_FILE`, so no signed image can be generated. You can either set it when you configure the application (or after), or use sysbuild to automatically have a bootloader built and have both bootloader and application use the default mcuboot key.

**Closed by nordicjm** 2023-04-03 07:26 UTC
Labels: bug
