### ISSUE TITLE
Up Squared serial console character output corrupted

### ISSUE THREAD

**Issue by fulong82** [zephyrproject-rtos/zephyr#12810] opened 2019-01-29 08:36 UTC
**Describe the bug**
After rebased to latest master branch, observe serial console character output has corrupted.
Tried to revert commit below and found issue no longer there:
f0db0b8815 driver: uart_ns16550.c: necessary changes for arc iot soc

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=up_squared ../
3. make menuconfig
4. select CONFIG_SHELL_BACKEND_SERIAL, CONFIG_LOG
5. make
6. copy newly build zephyr.strip image to usb boot drive
7. boot up Up Squared with the boot drive
8. Observing console printing corrupted

**Expected behavior**
Console printing correctly.

**Impact**
Unable to interact with shell terminal.

**Screenshots or console output**
![image](https://user-images.githubusercontent.com/19462849/51894887-eb13c300-23e3-11e9-9847-2abd08915f29.png)

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 14.04
 - Toolchain: Zephyr SDK
 - Commit: 5bd5e4e4406a56c61b4ad0609e3fe238e8ab6864

**Comment by fulong82** [comment] 2019-01-29 09:16
[config.txt](https://github.com/zephyrproject-rtos/zephyr/files/2806906/config.txt)

Forgot to attach the config file for reference.

Regards,
Wilson

**Comment by nashif** [comment] 2019-01-30 15:45
duplicate of #12652

**Closed by nashif** 2019-01-30 15:45 UTC
Labels: bug, priority: medium
