### ISSUE TITLE
samples: boards/stm32/backup_sram : needs backup sram enabled in DT to properly display memory region 

### ISSUE THREAD

**Issue by manoj153** [zephyrproject-rtos/zephyr#37658] opened 2021-08-13 07:36 UTC
**Describe the bug**
A clean build of boards/stm32/backup_sram shows some sign of bug:
Displaying wrong info:
-  region name, falls back to `*default*: `
- size gibberish val

**To Reproduce**
1. west build -b nucleo_h723zg samples/boards/stm32/backup_sram/

**Expected behaviour**
Suppose to be 4KB 

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**
```
Memory region         Used Size  Region Size  %age Used
           FLASH:       15756 B         1 MB      1.50%
            SRAM:        4288 B       128 KB      3.27%
            DTCM:          0 GB       128 KB      0.00%
        IDT_LIST:          0 GB         2 KB      0.00%
       *default*:        4952 B 18446744073709551615 B      0.00%
```

Solution:
Have a generic overlay file with enabled `backup_sram`
PR : #37659 

**Environment (please complete the following information):**
 - OS: (Ubuntu 20.04.2 LTS)
 - Toolchain (zephyr-sdk-0.13.0)
 - Commit SHA or Version used (zephyr: 7b9fbcd3b7e932996)

**Comment by gmarull** [comment] 2021-08-17 15:02
Closing as this was not a bug but rather a board without backup_sram enabled in DT. Related PR https://github.com/zephyrproject-rtos/zephyr/pull/37666

**Closed by gmarull** 2021-08-17 15:02 UTC
Labels: bug, platform: STM32
