### ISSUE TITLE
there is no network interface to work with for  wifi sample for esp32 board

### ISSUE THREAD

**Issue by houssine97** [zephyrproject-rtos/zephyr#33557] opened 2021-03-22 10:10 UTC
Describe the bug
When running the wifi sample on ESP32 , it reports that there is no network interface to work with:

*** Booting Zephyr OS version 2.5.99  ***ource...

[00:00:00.515,000] <err> net_if: There is no network interface to work with!

To Reproduce

cd zephyr/samples/net/wifi
west build -b esp32
west flash
See error
Expected behavior
The sample should get to displaying the wifi shell's prompt without error.

**Comment by sylvioalves** [comment] 2021-03-22 11:21
@houssine97 ESP32 has yet no support regarding zephyr's wifi subsystem due to it's non-offloaded implementation. For now, to get ESP32 wifi running you have the option to use the board specific sample as in `samples/boards/esp32/wifi_station`.

**Comment by houssine97** [comment] 2021-03-22 13:37
@sylvioalves i used the board specific samples wifi_station and i get this error :
<wrn> net_if: iface 0x3ffb00e8 is down
[00:00:02.933,000] <err> esp_event: SYSTEM_EVENT_STA_DISCONNECTED
[00:00:04.981,000] <err> esp_event: SYSTEM_EVENT_STA_DISCONNECTED

**Comment by nashif** [comment] 2021-03-22 15:22
IMO if that is expected behavior, we should close this as a non-bug :)

**Closed by nashif** 2021-03-22 15:22 UTC
Labels: Enhancement, priority: low
