### ISSUE TITLE
gen_isr_table@mimxrt1050_evk runs failure on R1.13_RC1.

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#9652] opened 2018-08-27 02:37 UTC
build the application tests/kernel/gen_isr_table  with below command line 
`cmake -DBOARD=mimxrt1050_evk  ..`
download to board, the console output is

> start application at 0x2d5d !!!

***** Booting Zephyr OS v1.13.0-rc1-36-g4a0d8af *****

starting test - Test gen_isr_tables

IRQ configuration (total lines 160):

isr1 isr=0x00000add irq=159

isr2 isr=0x00000b09 irq=158

Checking _irq_vector_table entry 159 for irq 159

triggering irq 159

interrupt 159 didn't run once, ran 0 times

FAIL - main

**Comment by hakehuang** [comment] 2018-08-27 02:37
cc @MaureenHelm

**Comment by nashif** [comment] 2018-08-27 14:48
duplicate of #9441

**Closed by nashif** 2018-08-27 14:48 UTC
Labels: area: ARM, area: Kernel, area: Tests, bug, priority: medium
