### ISSUE TITLE
[Coverity CID: 183068] Incorrect expression in /tests/kernel/fatal/src/main.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#6663] opened 2018-03-19 10:38 UTC
Static code scan issues seen in File: /tests/kernel/fatal/src/main.c
 Category: Incorrect expression
 Function: test_fatal
 Component: Tests
 CID: 183068
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by spoorthik** [comment] 2018-05-30 06:26
The issue is already marked as false positive. We can close this issue.

**Closed** 2018-06-01 09:27 UTC
Labels: Coverity, area: Tests, bug, priority: low
