### ISSUE TITLE
tests: net: socket: reuseaddr: some board don't work

### ISSUE THREAD

**Issue by Desvauxm-st** [zephyrproject-rtos/zephyr#63979] opened 2023-10-16 10:54 UTC
Describe the bug

tests: net: socket: reuseaddr: some board don't work

boards nucleo_f429zi, nucleo_f746zg, nucleo_h743zi don't work

To Reproduce
west build -p always -b   nucleo_f746zg  tests/net/socket/reuseaddr_reuseport/

and after west build

and in the console you can see:

Booting Zephyr OS build v3.5.0-rc2-183-g9ebacf07a6a0 

START - test_ipv4_tcp_time_wait_specified
    Assertion failed at WEST_TOPDIR/zephyr/tests/net/socket/reuseaddr_reuseport/src/main.c:170: test_connect_success: (connect(sock, addr, addrlen) not equal to 0)
connect() failed with error 116
 FAIL - test_ipv4_tcp_time_wait_specified in 0.503 seconds

------ TESTSUITE SUMMARY START ------
SUITE FAIL -  60.00% [socket_reuseaddr_test_suite]: pass = 9, fail = 6, skip = 0, total = 15 duration = 1.279 seconds
 - PASS - [socket_reuseaddr_test_suite.test_enable_disable] duration = 0.001 seconds
 - PASS - [socket_reuseaddr_test_suite.test_ipv4_both_unspecified] duration = 0.001 seconds
 - PASS - [socket_reuseaddr_test_suite.test_ipv4_first_unspecified] duration = 0.001 seconds
 - PASS - [socket_reuseaddr_test_suite.test_ipv4_second_unspecified] duration = 0.001 seconds
 - PASS - [socket_reuseaddr_test_suite.test_ipv4_tcp_specified_listening] duration = 0.001 seconds
 - FAIL - [socket_reuseaddr_test_suite.test_ipv4_tcp_time_wait_specified] duration = 0.503 seconds
 - FAIL - [socket_reuseaddr_test_suite.test_ipv4_tcp_time_wait_unspecified] duration = 0.017 seconds
 - FAIL - [socket_reuseaddr_test_suite.test_ipv4_tcp_unspecified_listening] duration = 0.017 seconds
 - PASS - [socket_reuseaddr_test_suite.test_ipv6_both_unspecified] duration = 0.001 seconds
 - PASS - [socket_reuseaddr_test_suite.test_ipv6_first_unspecified] duration = 0.001 seconds
 - PASS - [socket_reuseaddr_test_suite.test_ipv6_second_unspecified] duration = 0.001 seconds
 - PASS - [socket_reuseaddr_test_suite.test_ipv6_tcp_specified_listening] duration = 0.001 seconds
 - FAIL - [socket_reuseaddr_test_suite.test_ipv6_tcp_time_wait_specified] duration = 0.707 seconds
 - FAIL - [socket_reuseaddr_test_suite.test_ipv6_tcp_time_wait_unspecified] duration = 0.013 seconds
 - FAIL - [socket_reuseaddr_test_suite.test_ipv6_tcp_unspecified_listening] duration = 0.013 secon

SUITE FAIL -   0.00% [socket_reuseport_test_suite]: pass = 0, fail = 27, skip = 0, total = 27 duration = 0.356 seconds
 - FAIL - [socket_reuseport_test_suite.test_enable_disable] duration = 0.018 seconds
 - FAIL - [socket_reuseport_test_suite.test_ipv4_both_specified_bad] duration = 0.013 seconds
 - FAIL - [socket_reuseport_test_suite.test_ipv4_both_specified_good] duration = 0.013 seconds
 - FAIL - [socket_reuseport_test_suite.test_ipv4_both_unspecified_bad] duration = 0.013 seconds
 - FAIL - [socket_reuseport_test_suite.test_ipv4_both_unspecified_good] duration = 0.013 seconds
 - FAIL - [socket_reuseport_test_suite.test_ipv4_first_unspecified_bad] duration = 0.013 seconds
 - FAIL - [socket_reuseport_test_suite.test_ipv4_first_unspecified_good] duration = 0.013 seconds
 - FAIL - [socket_reuseport_test_suite.test_ipv4_second_unspecified_bad] duration = 0.013 seconds
 - FAIL - [socket_reuseport_test_suite.test_ipv4_second_unspecified_good] duration = 0.013 seconds
 - FAIL - [socket_reuseport_test_suite.test_ipv4_tcp_identical_clients] duration = 0.013 seconds
 - FAIL - [socket_reuseport_test_suite.test_ipv4_udp_bad_both_not_set] duration = 0.013 seconds
 - FAIL - [socket_reuseport_test_suite.test_ipv4_udp_bad_first_not_set] duration = 0.013 seconds
 - FAIL - [socket_reuseport_test_suite.test_ipv4_udp_bad_second_not_set] duration = 0.013 seconds
 - FAIL - [socket_reuseport_test_suite.test_ipv4_udp_good] duration = 0.013 seconds
 - FAIL - [socket_reuseport_test_suite.test_ipv6_both_specified_bad] duration = 0.013 seconds
 - FAIL - [socket_reuseport_test_suite.test_ipv6_both_specified_good] duration = 0.013 seconds
 - FAIL - [socket_reuseport_test_suite.test_ipv6_both_unspecified_bad] duration = 0.013 seconds
 - FAIL - [socket_reuseport_test_suite.test_ipv6_both_unspecified_good] duration = 0.013 seconds
 - FAIL - [socket_reuseport_test_suite.test_ipv6_first_unspecified_bad] duration = 0.013 seconds
 - FAIL - [socket_reuseport_test_suite.test_ipv6_first_unspecified_good] duration = 0.013 seconds
 - FAIL - [socket_reuseport_test_suite.test_ipv6_second_unspecified_bad] duration = 0.013 seconds
 - FAIL - [socket_reuseport_test_suite.test_ipv6_second_unspecified_good] duration = 0.013 seconds
 - FAIL - [socket_reuseport_test_suite.test_ipv6_tcp_identical_clients] duration = 0.013 seconds
 - FAIL - [socket_reuseport_test_suite.test_ipv6_udp_bad_both_not_set] duration = 0.013 seconds
 - FAIL - [socket_reuseport_test_suite.test_ipv6_udp_bad_first_not_set] duration = 0.013 seconds
 - FAIL - [socket_reuseport_test_suite.test_ipv6_udp_bad_second_not_set] duration = 0.013 seconds
 - FAIL - [socket_reuseport_test_suite.test_ipv6_udp_good] duration = 0.013 seconds
------ TESTSUITE SUMMARY END ------
===================================================================

PROJECT EXECUTION FAILED

Expected behavior

Impact
twister tests failed .

Environment (please complete the following information):
 - OS: (Windows)

**Comment by dleach02** [comment] 2023-10-24 16:45
Also reported on NXP platforms: #64061

**Comment by dleach02** [comment] 2023-10-24 16:46
@hakehuang did a bisect down to #61885 from @Frauschi

**Comment by jukkar** [comment] 2023-10-24 17:12
@Desvauxm-st could you try if this works with the current main as https://github.com/zephyrproject-rtos/zephyr/pull/64180 is merged.

**Comment by Frauschi** [comment] 2023-10-25 07:23
With the current main, I cannot reproduce the issues anymore (I tested with a nucleo_h743zi and a stm32h573i_dk). I'm pretty sure the issues have been related to #64180 as the logs of the failing tests indicate incorrect behavior of socket operations unrelated to SO_REUSEADDR/SO_REUSEPORT specifically.

**Comment by carlescufi** [comment] 2023-10-25 09:09
@Desvauxm-st is this still an issue? @Frauschi doesn't seem to be able to reproduce anymore.

**Comment by Desvauxm-st** [comment] 2023-10-26 08:09
@jukkar
I try this works with the current main as https://github.com/zephyrproject-rtos/zephyr/pull/64180 is merged.
and now it's works

**Comment by Desvauxm-st** [comment] 2023-10-26 08:10
thanks you

**Closed** 2023-10-26 08:46 UTC
Labels: bug, priority: medium, area: Networking, area: Ethernet, area: Sockets
