### ISSUE TITLE
samples/shields/x_nucleo_iks01a3 test is stucking due to dca45cb commit

### ISSUE THREAD

**Issue by avisconti** [zephyrproject-rtos/zephyr#18031] opened 2019-08-06 07:58 UTC
The samples/shields/x_nucleo_iks01a3 is a sample to test the x_nucleo_iks01a3 shield. It outputs the sensor data forever.
After dca45cb commit has been merged it stucks after few iterations
(dca45cb drivers: i2c: Add STM32F10X slave support)
Help on this commit is required.
(see #17568)

If I remove it everything works:
git revert dca45cb

(it requires a nucleo F401RE + x_nucleo_iks01a3 shield)
1. samples/shields/x_nucleo_iks01a3/standard
2. mkdir build && cd build
3. cmake -DBOARD=nucleo_f401re ..
4. make

**Screenshots or console output**
X-NUCLEO-IKS01A3 sensor dashboard

HTS221: Temperature: 26.4 C
HTS221: Relative Humidity: 30.0%
LPS22HH: Temperature: 0.0 C
LPS22HH: Pressure:0.000 kpa
STTS751: Temperature: 0.0 C
LIS2MDL: Magn (gauss): x: -0.660, y: -0.351, z: -0.804
LIS2DW12: Accel (m.s-2): x: 43.109, y: -1.838, z: 69.296
LSM6DSO: Accel (m.s-2): x: 0.000, y: 0.000, z: 0.000
LSM6DSO: GYro (dps): x: 0.000, y: 0.000, z: 0.000
1:: lps22hh trig 4
1:: lsm6dso acc trig 8
1:: lsm6dso gyr trig 8
1:: lsm6dso temp trig 0
[00:00:00.004,000] <dbg> LIS2DW12.lis2dw12_set_power_mode: Apply default Power Mode
[00:00:00.008,000] <inf> LSM6DSO: chip id 0x6c

**Comment by avisconti** [comment] 2019-08-06 08:01
@erwango @ydamigos 
I put you as owner of this bug as you reviewed #17568.
I have actually been requested by @ydamigos to review it as well, but I was in vacation. Sorry for
that. I think that we should put @pavlohamov in a condition to debug it.

**Comment by ydamigos** [comment] 2019-08-06 16:12
I will take a look at it the following days. Unfortunately, I don't have the hardware to test it.
@avisconti Did you test the sample in polling mode?

**Comment by pavlohamov** [comment] 2019-08-06 20:41
@avisconti Thank you for pointing this issue. Seems like i've managed to reproduce it on stm32f429 disco with 100% probability. 
The issue is NOT reproduced if:
`CONFIG_I2C_STM32_INTERRUPT=n`
or
`CONFIG_I2C_SLAVE=y`
Also with https://github.com/zephyrproject-rtos/zephyr/pull/18061 - works fine.

Unfortunate i have no nucleo shield, nor F401. @avisconti Could you be so kind to verify these 3 individual options?

**Comment by avisconti** [comment] 2019-08-07 07:33
> I will take a look at it the following days. Unfortunately, I don't have the hardware to test it.
> @avisconti Did you test the sample in polling mode?

No, interrupt mode.

**Comment by avisconti** [comment] 2019-08-07 07:55
> @avisconti Thank you for pointing this issue. Seems like i've managed to reproduce it on stm32f429 disco with 100% probability.
> The issue is NOT reproduced if:
> `CONFIG_I2C_STM32_INTERRUPT=n`
> or
> `CONFIG_I2C_SLAVE=y`
> Also with #18061 - works fine.
> 
> Unfortunate i have no nucleo shield, nor F401. @avisconti Could you be so kind to verify these 3 individual options?

@pavlohamov 
I tried #18061 and it seems to fix my issue!!
I will take a deeper look to what it does, and maybe @ydamigos can also review it.
Thanks for the quick solution.

**Comment by dleach02** [comment] 2019-10-15 17:45
@avisconti , can you confirm that the #18061 fixes this issue and you want to have it backported to 2.0.1?

**Comment by avisconti** [comment] 2019-10-16 08:02
> @avisconti , can you confirm that the #18061 fixes this issue and you want to have it backported to 2.0.1?

@dleach02 
David, yes it fixes the issue and I believe it must be backported to v2.0.1.
Thanks!

**Comment by erwango** [comment] 2019-11-21 14:37
@avisconti, can we close this bug ? It is counting in V2.1.0 maturity while it is actually closed on this branch

**Comment by dleach02** [comment] 2019-11-26 14:51
@avisconti, please open an issue item for your backport request. We are going to close this particular issue.

**Closed by dleach02** 2019-11-26 14:51 UTC
Labels: area: Drivers, area: I2C, bug, priority: medium

**Comment by avisconti** [comment] 2019-11-26 16:51
> @avisconti, please open an issue item for your backport request. We are going to close this particular issue.

@erwango @dleach02 
Sorry, I missed your comments.
Sure I will open a new request for v2.0.1
