### ISSUE TITLE
Not able to display "°C" in console terminal

### ISSUE THREAD

**Issue by Niranjan-eaton** [zephyrproject-rtos/zephyr#56451] opened 2023-04-02 18:10 UTC
**Describe the bug**
void Calc_Internal_Temp( double Sensed_Voltage )
{
	// Temperature (in �C) = {(VSENSE � V25) / Avg_Slope} + 25
	double V25 = ( 0.76 * 1000 );	// in mV
	double Avg_Slope = 2.5;		// mV per �C
	double SensedTemp = 0;

	SensedTemp = ( ( Sensed_Voltage - V25 ) / Avg_Slope ) + 25;

	printk( "Current temperature: %.1f °C\n", SensedTemp );
}

 - ...

**To Reproduce**
examples\drivers\ADC\ADC_STM32_Die_Temp_Read
west build -b nucleo_f429zi ./ --pristine

**Expected behavior**
Need to Display °C as in terminal.

**Impact**
Good to display temperature in °C

**Logs and console output**
![image](https://user-images.githubusercontent.com/114387272/229370773-0f208ae1-84fa-457a-b8d4-db70eb272bf5.png)

**Environment (please complete the following information):**
 - OS: Zephyr 3.2.0
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Additional context**
west build -b nucleo_f429zi ./ --pristine

**Comment by nordicjm** [comment] 2023-04-03 07:30
Closing as user issue, not a bug.

The degrees symbol is unicode, you are using a terminal that does not support unicode, so it displays either a unicode unknown replacement character code or tries to interpret it as e.g. ascii.

**Closed by nordicjm** 2023-04-03 07:30 UTC
Labels: bug
