### ISSUE TITLE
Upgrade LVGL to v8

### ISSUE THREAD

**Issue by brgl** [zephyrproject-rtos/zephyr#40729] opened 2021-11-29 13:22 UTC
Current stable lvgl release is v8.1.0, but zephyr still only supports v7. These two versions are not source compatible, in fact v8 introduces *a lot* of breaking changes but also improves the library significantly. We're interested in making zephyr support v8 and want to put in the needed time.

Zephyr's lvgl support is split into two parts: the lvgl module (in its separate repo) and glue code in the main zephyr repository. This glue code would need to be heavily reworked and of course lvgl v7 apps would stop working and would need to be upgraded to v8.

The question is: what would be the best approach for this? Can we simply merge interface breaking changes into the master branch and say that from this and that version we only support v8? Should we support v7 and v8 at the same time?

I think it's worth discussing this during the dev-review.

**Comment by gmarull** [comment] 2021-11-29 15:50
Duplicate of #38305

**Closed** 2021-11-29 15:51 UTC
Labels: Enhancement, dev-review, manifest-lvgl
