### ISSUE TITLE
intel_adsp : tests/kernel/queue/kernel.queue* fails

### ISSUE THREAD

**Issue by majunkier** [zephyrproject-rtos/zephyr#70490] opened 2024-03-20 12:44 UTC
**Describe the bug**
tested on intel_adsp/ boards (cavs25, ace15_mtpm ,ace20_lnl)

```
tests/kernel/queue/kernel.queue
tests/kernel/queue/kernel.queue.minimallibc
```

tests hangs despite initially promising results. Result is timeout.

**To Reproduce**
` twister --device-testing --hardware-map PATH-TO-HWMAP -s tests/kernel/queue/kernel.queue`

**Expected behavior**
Test should pass

**Logs and console output**
handler.log

```
*** Booting Zephyr OS build v3.6.0-1236-g8f4ac0d4ab45 ***
Running TESTSUITE queue_api
===================================================================
START - test_access_kernel_obj_with_priv_data
PASS - test_access_kernel_obj_with_priv_data in 0.001 seconds
===================================================================
START - test_multiple_queues
PASS - test_multiple_queues in 0.001 seconds
===================================================================
START - test_queue_alloc
PASS - test_queue_alloc in 0.001 seconds
===================================================================
START - test_queue_append_list_error
PASS - test_queue_append_list_error in 0.001 seconds
===================================================================
START - test_queue_isr2thread
PASS - test_queue_isr2thread in 0.001 seconds
===================================================================
START - test_queue_merge_list_error
PASS - test_queue_merge_list_error in 0.001 seconds
===================================================================
START - test_queue_thread2isr
PASS - test_queue_thread2isr in 0.001 seconds
===================================================================
START - test_queue_unique_append
PASS - test_queue_unique_append in 0.001 seconds
===================================================================
TESTSUITE queue_api succeeded
Running TESTSUITE queue_api_1cpu
===================================================================
START - test_queue_get_2threads

```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Version used: v3.6.0-1236-g8f4ac0d4ab45

**Comment by nashif** [comment] 2024-03-20 13:28
duplicate of #70494

**Closed by nashif** 2024-03-20 13:28 UTC
Labels: bug, platform: Intel ADSP
