### ISSUE TITLE
qemu_xtensa cannot be debugged with SDK

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#7308] opened 2018-05-02 16:37 UTC
I ran a test case with "make debugserver".

I then tried to connect to it with GDB:

```
$ $ZEPHYR_SDK_INSTALL_DIR/sysroots/x86_64-pokysdk-linux/usr/bin/xtensa-zephyr-elf/xtensa-zephyr-elf-gdb zephyr/zephyr.elf 
GNU gdb (GDB) 7.11.0.20160511-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-pokysdk-linux --target=xtensa-zephyr-elf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from zephyr/zephyr.elf...done.
(gdb) target remote :1234
Remote debugging using :1234
Remote 'g' packet reply is too long: 000000500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000feda80c2474d06211f000000000000000000000000000000000000002800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
(gdb) c
The program is not being run.
(gdb) 
```

This is pretty bad, if I am doing new feature development and something only crashes on Xtensa, it will be very difficult to figure out what is going on.

**Comment by nashif** [comment] 2018-05-05 13:51
This is a duplicate of #4309. It is an SDK bug and not something we can fix in Zephyr. This has been resolved meanwhile and we are waiting for the fix to be verified.

**Closed by nashif** 2018-05-05 13:51 UTC
Labels: area: Debugging, area: Xtensa, bug, priority: high
