### ISSUE TITLE
[west] Only install HALs/modules on demand

### ISSUE THREAD

**Issue by mrx23dot** [zephyrproject-rtos/zephyr#64686] opened 2023-11-01 11:42 UTC
Following the tutorial 
https://docs.zephyrproject.org/latest/develop/getting_started/index.html

`west update`
installs every possible HAL/module, which are **82,360  (3.8GB) files**

I'm no expert, but device tree defines the required HALs/modules **at a given checkpoint**, so can we download them only on demand?

Otherwise we are back to a situation where it takes 10GB of space to write a tiny blinky.

**Comment by nordicjm** [comment] 2023-11-01 14:16
Duplicate of https://github.com/zephyrproject-rtos/zephyr/issues/54276

**Closed by nordicjm** 2023-11-01 14:16 UTC
Labels: Feature Request
