### ISSUE TITLE
tests/kernel/stack/stack/kernel.stack.usage fails on intel_adsp_cavs25.

### ISSUE THREAD

**Issue by gbarkadiusz** [zephyrproject-rtos/zephyr#62488] opened 2023-09-11 11:09 UTC
**Describe the bug**
Test fails sporadically, hard to reproduce.

**To Reproduce**
` scripts/twister -W -p intel_adsp_cavs25 --device-testing --hardware-map <path_to>/cavs/cavs.map -s tests/kernel/stack/stack/kernel.stack.usage -v`

**Expected behavior**
Test should pass.

**Impact**
Annoyance, affects our CI.

**Logs and console output**
Twister output: `tests/kernel/stack/stack/kernel.stack.usage         FAILED Timeout (60.588s)`
and `<path_to>/handler.log` contains.
```
ERROR   - INFO:cavs-client:REMOTE HOST: <host_ip> PORT: <host_port>
INFO:cavs-client:Monitor process
INFO:cavs-client:Sent:     start_log
INFO:cavs-client:Receive: start_log
INFO:cavs-client:Start to monitor log output...
```
**Environment :**
 - OS: Linux
 - Toolchain: Zephyr SDK v16.1
 - Zephyr version: zephyr-v3.4.0-3031-g81e28a4f1bef.

**Comment by dcpleung** [comment] 2023-10-30 18:39
Unable to reproduce it by running it over 20000+ times locally on UP board, and they were all successful. So it is highly probable that it's a local CI issue. Closing for now. Reopening if needed.

**Closed by dcpleung** 2023-10-30 18:39 UTC
Labels: bug, priority: low, platform: Intel ADSP
