### ISSUE TITLE
lpcxpresso55s69_ns: build failure

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#67777] opened 2024-01-18 11:08 UTC
**Describe the bug**

build failure for lpcxpresso55s69_ns

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
 lpcxpresso55s69_ns
 - What have you tried to diagnose or workaround this issue?
 git bisect found it is 
```
commit 917bec37d0849932c122d355ded690697a5bf812
Author: Markus Swarowsky <markus.swarowsky@nordicsemi.no>
Date:   Thu Dec 7 18:26:01 2023 +0100

    manifest: TF-M v2.0.0 update
    
    Update TF-M to version 2.0.0 including
    MbedTLS to v3.5.0
    TF-M-Tests to v2.0.0
    PSA-Arch_Tests to v23.06_API1.5_ADAC_EAC
    
    Signed-off-by: Markus Swarowsky <markus.swarowsky@nordicsemi.no>

 submanifests/optional.yaml | 4 ++--
 west.yml                   | 4 ++--
 2 files changed, 4 insertions(+), 4 deletions(-)
```

**To Reproduce**
scripts/twister -p lpcxpresso55s69_ns -T tests/arch/common/timing --build-only

**Expected behavior**
build pass

**Impact**
lpcxpresso55s69_ns  platform support

**Logs and console output**

```
[396/409] Linking C static library platform/libplatform_bl2.a
[397/409] Linking C static library bl2/ext/mcuboot/bootutil/libbootutil.a
[398/409] Linking C executable bin/tfm_s.axf
FAILED: bin/tfm_s.axf 
: && /home/ubuntu/zephyr-sdk/zephyr-sdk-0.16.4/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc -mcpu=cortex-m33 -Os -DNDEBUG -mcpu=cortex-m33 --entry=Reset_Handler -specs=nano.specs -Wl,-check-sections -Wl,-fatal-warnings -Wl,--gc-sections -Wl,--no-wchar-size-warning -Wl,--print-memory-usage -Wl,-Map=/home/shared/disk/zephyr_project/zephyr_test/zephyr/twister-out/lpcxpresso55s69_ns/tests/arch/common/timing/arch.common.timing/tfm/bin/tfm_s.map -mfloat-abi=hard -mfpu=fpv5-sp-d16 -Wl,--cmse-implib,--out-implib=/home/shared/disk/zephyr_project/zephyr_test/zephyr/twister-out/lpcxpresso55s69_ns/tests/arch/common/timing/arch.common.timing/tfm/secure_fw/s_veneers.o -T /home/shared/disk/zephyr_project/zephyr_test/zephyr/twister-out/lpcxpresso55s69_ns/tests/arch/common/timing/arch.common.timing/tfm/platform/target/CMakeFiles/tfm_s_scatter.dir/./__/__/__/common/gcc/tfm_common_s.ld secure_fw/CMakeFiles/tfm_s.dir/partitions/ns_agent_tz/psa_api_veneers_v80m.o secure_fw/CMakeFiles/tfm_s.dir/__/platform/ext/target/nxp/lpcxpresso55s69/Device/Source/startup_lpcxpresso55s69.o secure_fw/CMakeFiles/tfm_s.dir/__/platform/ext/target/nxp/lpcxpresso55s69/project_template/s/hardware_init.o secure_fw/CMakeFiles/tfm_s.dir/__/platform/ext/common/faults.o secure_fw/CMakeFiles/tfm_s.dir/__/generated/secure_fw/partitions/crypto/auto_generated/load_info_tfm_crypto.o secure_fw/CMakeFiles/tfm_s.dir/__/generated/secure_fw/partitions/protected_storage/auto_generated/load_info_tfm_protected_storage.o secure_fw/CMakeFiles/tfm_s.dir/__/generated/secure_fw/partitions/internal_trusted_storage/auto_generated/load_info_tfm_internal_trusted_storage.o secure_fw/CMakeFiles/tfm_s.dir/__/generated/secure_fw/partitions/platform/auto_generated/load_info_tfm_platform.o secure_fw/CMakeFiles/tfm_s.dir/partitions/ns_agent_tz/load_info_ns_agent_tz.o secure_fw/CMakeFiles/tfm_s.dir/__/platform/ext/common/syscalls_stub.o -o bin/tfm_s.axf  platform/libplatform_s.a  secure_fw/partitions/lib/runtime/libtfm_sprt.a  secure_fw/spm/libtfm_spm.a  platform/libplatform_crypto_keys.a  secure_fw/partitions/crypto/mbedcrypto/library/libmbedcrypto.a  secure_fw/partitions/crypto/libtfm_psa_rot_partition_crypto.a  secure_fw/partitions/protected_storage/libtfm_app_rot_partition_ps.a  secure_fw/partitions/internal_trusted_storage/libtfm_psa_rot_partition_its.a  secure_fw/partitions/platform/libtfm_psa_rot_partition_platform.a  platform/libplatform_s.a  secure_fw/partitions/lib/runtime/libtfm_sprt.a  secure_fw/spm/libtfm_spm.a  platform/libplatform_crypto_keys.a  secure_fw/partitions/crypto/mbedcrypto/library/libmbedcrypto.a  secure_fw/partitions/crypto/libtfm_psa_rot_partition_crypto.a  secure_fw/partitions/protected_storage/libtfm_app_rot_partition_ps.a  secure_fw/partitions/internal_trusted_storage/libtfm_psa_rot_partition_its.a  secure_fw/partitions/platform/libtfm_psa_rot_partition_platform.a  platform/libplatform_s.a  secure_fw/partitions/lib/runtime/libtfm_sprt.a  secure_fw/spm/libtfm_spm.a  platform/libplatform_crypto_keys.a  secure_fw/partitions/crypto/mbedcrypto/library/libmbedcrypto.a  secure_fw/partitions/crypto/libtfm_psa_rot_partition_crypto.a  secure_fw/partitions/protected_storage/libtfm_app_rot_partition_ps.a  secure_fw/partitions/internal_trusted_storage/libtfm_psa_rot_partition_its.a  secure_fw/partitions/platform/libtfm_psa_rot_partition_platform.a  secure_fw/partitions/crypto/mbedcrypto/3rdparty/everest/libcrypto_service_everest.a  secure_fw/partitions/crypto/mbedcrypto/3rdparty/p256-m/libcrypto_service_p256m.a && :
/home/ubuntu/zephyr-sdk/zephyr-sdk-0.16.4/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld: error: bin/tfm_s.axf uses VFP register arguments, secure_fw/partitions/crypto/mbedcrypto/3rdparty/p256-m/libcrypto_service_p256m.a(p256-m_driver_entrypoints.o) does not
/home/ubuntu/zephyr-sdk/zephyr-sdk-0.16.4/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld: failed to merge target specific data of file secure_fw/partitions/crypto/mbedcrypto/3rdparty/p256-m/libcrypto_service_p256m.a(p256-m_driver_entrypoints.o)
/home/ubuntu/zephyr-sdk/zephyr-sdk-0.16.4/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld: error: bin/tfm_s.axf uses VFP register arguments, secure_fw/partitions/crypto/mbedcrypto/3rdparty/p256-m/libcrypto_service_p256m.a(p256-m.o) does not
/home/ubuntu/zephyr-sdk/zephyr-sdk-0.16.4/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld: failed to merge target specific data of file secure_fw/partitions/crypto/mbedcrypto/3rdparty/p256-m/libcrypto_service_p256m.a(p256-m.o)
Memory region         Used Size  Region Size  %age Used
           FLASH:       69512 B       158 KB     42.96%
             RAM:       43996 B       136 KB     31.59%
        CODE_RAM:          0 GB        32 KB      0.00%
collect2: error: ld returned 1 exit status
[399/409] Linking C executable bin/bl2.axf
Memory region         Used Size  Region Size  %age Used
           FLASH:       28016 B        32 KB     85.50%
             RAM:       32032 B       272 KB     11.50%
ninja: build stopped: subcommand failed.
FAILED: modules/trusted-firmware-m/tfm-prefix/src/tfm-stamp/tfm-build tfm/bin/bl2.elf tfm/bin/bl2.bin tfm/bin/bl2.hex tfm/bin/tfm_s.elf tfm/bin/tfm_s.bin tfm/bin/tfm_s.hex tfm/bin/tfm_s_signed.bin tfm/bin/tfm_s_ns_signed.bin tfm/api_ns/interface/lib/s_veneers.o tfm/api_ns/interface/src/tfm_attest_api.c tfm/api_ns/interface/src/tfm_crypto_api.c tfm/api_ns/interface/src/tfm_fwu_api.c tfm/api_ns/interface/src/tfm_its_api.c tfm/api_ns/interface/src/tfm_platform_api.c tfm/api_ns/interface/src/tfm_ps_api.c tfm/api_ns/interface/src/tfm_tz_psa_ns_api.c tfm/api_ns/interface/src/tfm_ioctl_core_ns_api.c /home/shared/disk/zephyr_project/zephyr_test/zephyr/twister-out/lpcxpresso55s69_ns/tests/arch/common/timing/ar

```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, , )
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: zephyr-v3.5.0-4318-g9569e4410475

**Comment by nordicjm** [comment] 2024-01-18 11:38
Duplicate of https://github.com/zephyrproject-rtos/zephyr/issues/67751

**Closed** 2024-01-19 03:03 UTC
Labels: bug, area: TF-M
