### ISSUE TITLE
STM32WBA52 bootloader cannot jump to application code.

### ISSUE THREAD

**Issue by lnhao** [zephyrproject-rtos/zephyr#69510] opened 2024-02-27 10:00 UTC
Why can't STM32WBA jump to the APP while STM32F429 can jump and run normally with the same MCUboot and application code?

STM32WBA is aligned according to its own flash sector size - 8K.

Have you ever encountered a similar problem?

Thank you!

**Comment by nordicjm** [comment] 2024-02-27 10:04
duplicate of #69509

**Closed by nordicjm** 2024-02-27 10:04 UTC
Labels: bug
