### ISSUE TITLE
Catch all bug for build issues with SDK 0.10.0-rc2

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#13272] opened 2019-02-11 16:15 UTC
Seeing the following build issues with SDK 0.10.0-beta, though some may not be limited to that SDK version.

```
15 tests selected, 85710 tests discarded due to filters
total complete:    0/  15   0%  failed:    0

altera_max10              tests/kernel/stack/stack_api/kernel.stack          FAILED: build_error
	see: sanity-out/altera_max10/tests/kernel/stack/stack_api/kernel.stack/build.log

total complete:    3/  15  20%  failed:    3

qemu_nios2                tests/kernel/stack/stack_api/kernel.stack          FAILED: build_error
	see: sanity-out/qemu_nios2/tests/kernel/stack/stack_api/kernel.stack/build.log

total complete:    6/  15  40%  failed:    6

mimxrt1050_evk_qspi       samples/cpp_synchronization/test                   FAILED: build_error
	see: sanity-out/mimxrt1050_evk_qspi/samples/cpp_synchronization/test/build.log

total complete:    9/  15  60%  failed:    9

imxrt1050_evk            samples/cpp_synchronization/test                   FAILED: build_error
	see: sanity-out/mimxrt1050_evk/samples/cpp_synchronization/test/build.log

total complete:   11/  15  73%  failed:   11

mimxrt1050_evk_qspi       tests/application_development/cpp/test             FAILED: build_error
	see: sanity-out/mimxrt1050_evk_qspi/tests/application_development/cpp/test/build.log

total complete:   12/  15  80%  failed:   12

mimxrt1050_evk            tests/application_development/cpp/test             FAILED: build_error
	see: sanity-out/mimxrt1050_evk/tests/application_development/cpp/test/build.log

total complete:   13/  15  86%  failed:   13

minnowboard               tests/kernel/mem_protect/mem_protect/kernel.memory_protection FAILED: build_error
	see: sanity-out/minnowboard/tests/kernel/mem_protect/mem_protect/kernel.memory_protection/build.log

total complete:   14/  15  93%  failed:   14

minnowboard               tests/kernel/fifo/fifo_timeout/kernel.fifo.timeout.poll FAILED: build_error
	see: sanity-out/minnowboard/tests/kernel/fifo/fifo_timeout/kernel.fifo.timeout.poll/build.log

total complete:   15/  15  100%  failed:   15
0 of 15 tests passed with 0 warnings in 10 seconds
```

**Comment by galak** [comment] 2019-02-14 16:20
altera_max10              tests/kernel/stack/stack_api/kernel.stack          FAILED: build_error


```
/opt/zephyr-sdk-0.10.0-rc2/nios2-zephyr-elf/bin/../lib/gcc/nios2-zephyr-elf/8.2.0/../../../../nios2-zephyr-elf/bin/ld: ../app/libapp.a(test_stack_contexts.c.obj): in function `tstack_pop':
/home/galak/git/zephyr/tests/kernel/stack/stack_api/src/test_stack_contexts.c:31: warning: unable to reach (null) (at 0x004002f4) from the global pointer (at 0x004082fc) because the offset (-32776) is out of the allowed range, -32678 to 32767

```

**Comment by galak** [comment] 2019-02-14 16:21
minowboard:

```
/opt/zephyr-sdk-0.10.0-rc2/i586-zephyr-elf/bin/../lib/gcc/i586-zephyr-elf/8.2.0/../../../../i586-zephyr-elf/bin/ld:linker_pass_final.cmd:64 cannot move location counter backwards (from 000000000010afaf to 000000000010afae)
```

**Comment by nashif** [comment] 2019-02-14 16:23
@andrewboie you have an idea what the issue is with minnowboard and new toolchain?

**Comment by nashif** [comment] 2019-02-20 20:27
on minnowboard:

```
[100%] Linking C executable zephyr.elf
/home/nashif/Work/SDK/0.10.0-rc2-pr-43/i586-zephyr-elf/bin/../lib/gcc/i586-zephyr-elf/8.2.0/../../../../i586-zephyr-elf/bin/ld:linker_pass_final.cmd:64 cannot move location counter backwards (from 000000000010be4e to 000000000010be4d)
```

**Comment by nashif** [comment] 2019-02-20 20:29
on nios2:

```
[ 94%] Linking C executable zephyr_prebuilt.elf
/home/nashif/Work/SDK/0.10.0-rc2-pr-43/nios2-zephyr-elf/bin/../lib/gcc/nios2-zephyr-elf/8.2.0/../../../../nios2-zephyr-elf/bin/ld: ../app/libapp.a(test_stack_contexts.c.obj): in function `tstack_pop':
/home/nashif/Work/zephyrproject/zephyr/tests/kernel/stack/stack_api/src/test_stack_contexts.c:31: warning: unable to reach (null) (at 0x00400300) from the global pointer (at 0x00408308) because the offset (-32776) is out of the allowed range, -32678 to 32767
```

**Comment by nashif** [comment] 2019-02-20 20:44
just noticed @galak already provided the trace :)

**Comment by MaureenHelm** [comment] 2019-02-22 13:14
@galak which issues are still outstanding? the nxp issues are resolved, so can we reassign this bug to the appropriate person?

**Comment by nashif** [comment] 2019-02-22 14:51
closing this now in favor of dedicated issue for the nios2 issue, I think I have a fix

**Closed by nashif** 2019-02-22 14:51 UTC
Labels: area: X86, bug, platform: NXP, priority: medium
