### ISSUE TITLE
[Coverity CID :203443]Memory - corruptions in /subsys/bluetooth/host/rfcomm.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#18386] opened 2019-08-17 20:39 UTC
Static code scan issues seen in File: /subsys/bluetooth/host/rfcomm.c
 Category: Memory - corruptions
 Function: bt_rfcomm_dlc_send
 Component: Bluetooth
 CID: 203443
 Please fix or provide comments to square it off in coverity in the link: ~https://scan9.coverity.com/reports.htm#v32951/p12996~
https://scan9.coverity.com/reports.htm#v34747/p12996/

**Comment by jhedberg** [comment] 2019-08-18 14:16
There are several things that look messed up with this code. I don't have time to go digging through the RFCOMM spec to figure out what exactly is the right thing. Maybe this is the final straw and we should just remove BR/EDR support from the tree. Downgrading to low priority however since this is considered experimental code.

**Comment by joerchan** [comment] 2020-01-03 13:16
@aasthagr Could you possibly check if this issue has been resolved with the fix that was recently submitted to RFCOMM?

**Comment by joerchan** [comment] 2020-01-21 12:57
> aasthagr Could you possibly check if this issue has been resolved with the fix that was recently submitted to RFCOMM?

Answering my own question. No it does not.

**Comment by nashif** [comment] 2020-03-11 15:36
this is marked fixed in coverity with comment

"Source code is not available because it has been purged."

**Comment by nashif** [comment] 2021-03-05 00:41
the issue is still there in coverity

**Comment by joerchan** [comment] 2021-03-05 12:06
This is intentional, rfcomm has a variable length length field, which is confusing when we cast the uint8_t field to an uint16_t field instead, but the extra byte has been pushed to the net_buf.

**Comment by carlescufi** [comment] 2021-05-20 11:12
@MaureenHelm assigning this to you since @MarkWangChinese is not yet part of the org, and this is BR/EDR with which you've shown an interest in keeping alive.

**Comment by MaureenHelm** [comment] 2021-05-24 23:29
@MarkWangChinese can you take a look this week?

**Comment by MarkWangChinese** [comment] 2021-05-27 07:09
I created one PR https://github.com/zephyrproject-rtos/zephyr/pull/35706

**Closed** 2021-06-24 08:57 UTC
Labels: Coverity, area: Bluetooth, bug, priority: low
