### ISSUE TITLE
tests/misc/test_build fails to build on esp32

### ISSUE THREAD

**Issue by inakypg** [zephyrproject-rtos/zephyr#8087] opened 2018-06-01 05:00 UTC
Toolchain: ZEPHYR_GCC_VARIANT=espressif

Commit 43553da9b2bb9e537185695899fb5184c3b17ebe

link fails with:

```
...
[ 93%] Linking C executable zephyr_prebuilt.elf
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-assert.o):(.literal+0xc): undefined reference to `__getreent'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-assert.o): In function `__assert_func':
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdlib/assert.c:59: undefined reference to `__getreent'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-fiprintf.o): In function `fiprintf':
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdio/fiprintf.c:49: undefined reference to `__getreent'
....
```

Full build steps and error output:

```
$ mkdir -p outdir-epos-sv8a-esp32; rm -f outdir-epos-sv8a-esp32/.config
$ cmake -DPREBUILT_HOST_TOOLS=/opt/zephyr-sdk-0.9.2/sysroots/x86_64-pokysdk-linux/usr/bin -DBOARD=esp32 -DARCH=xtensa -DEXTRA_CPPFLAGS="-DTC_RUNID=ci-180531-1931-1708:sv8a" -DEXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" -DEXTRA_AFLAGS=-Wa,--fatal-warnings -DEXTRA_LDFLAGS=-Wl,--fatal-warnings -DCONF_FILE=newlib.conf -B"outdir-epos-sv8a-esp32" -H"zephyr.git/tests/misc/test_build"
CMake Deprecation Warning at zephyr.git/cmake/app/boilerplate.cmake:38 (cmake_policy):
  The OLD behavior for policy CMP0000 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  CMakeLists.txt:1 (include)


-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.5.2", minimum required is "3.4")
-- Selected BOARD esp32
Zephyr version: 1.12.0
Parsing Kconfig tree in zephyr.git/Kconfig
Using zephyr.git/boards/xtensa/esp32/esp32_defconfig as base
Merging newlib.conf
warning: ENTROPY_ESP32_RNG (defined at drivers/entropy/Kconfig.esp32:7) was assigned the value "y" but got the value "n" -- check dependencies
CMake Warning at zephyr.git/cmake/toolchain.cmake:13 (message):
  ZEPHYR_GCC_VARIANT is deprecated, please use ZEPHYR_TOOLCHAIN_VARIANT
  instead
Call Stack (most recent call first):
  zephyr.git/cmake/app/boilerplate.cmake:242 (include)
  CMakeLists.txt:1 (include)


fatal: No tags can describe '43553da9b2bb9e537185695899fb5184c3b17ebe'.
Try --always, or create some tags.
-- Generating zephyr/include/generated/generated_dts_board.h
-- Cache files will be written to: /home/jenkins/.cache/zephyr
CMake Warning at zephyr.git/boards/common/esp32.board.cmake:5 (message):
  Setting ESP_IDF_PATH in the environment is deprecated.  Use cmake
  -DESP_IDF_PATH=...  instead.
Call Stack (most recent call first):
  zephyr.git/boards/xtensa/esp32/board.cmake:1 (include)
  zephyr.git/cmake/app/boilerplate.cmake:289 (include)
  CMakeLists.txt:1 (include)


-- The C compiler identification is GNU 5.2.0
-- The CXX compiler identification is GNU 5.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /opt/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
-- Performing Test toolchain_is_ok
-- Performing Test toolchain_is_ok - Success
CMake Warning at ../../../CMakeLists.txt:1123 (message):


        ------------------------------------------------------------
        --- WARNING:  __ASSERT() statements are globally ENABLED ---
        --- The kernel will run more slowly and use more memory  ---
        ------------------------------------------------------------


-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    PREBUILT_HOST_TOOLS


-- Build files have been written to: outdir-epos-sv8a-esp32
$ make -C outdir-epos-sv8a-esp32 config-sanitycheck
Scanning dependencies of target config-sanitycheck
Built target config-sanitycheck
exit code 2 from 'make -C outdir-epos-sv8a-esp32' @tcf.git/tcfl/app_zephyr.py:358
Scanning dependencies of target syscall_list_h_target
Scanning dependencies of target syscall_macros_h_target
Scanning dependencies of target kobj_types_h_target
Scanning dependencies of target driver_validation_h_target
[  1%] Generating always_rebuild
[  2%] Generating include/generated/syscall_macros.h
Building for board esp32
[  4%] Generating include/generated/kobj-types-enum.h, include/generated/otype-to-str.h
[  5%] Generating include/generated/driver-validation.h
[  6%] Generating misc/generated/syscalls.json
[  8%] Generating include/generated/syscall_dispatch.c, include/generated/syscall_list.h
[  8%] Built target syscall_macros_h_target
[  8%] Built target syscall_list_h_target
[  8%] Built target driver_validation_h_target
[  8%] Built target kobj_types_h_target
Scanning dependencies of target offsets
[  9%] Building C object zephyr/CMakeFiles/offsets.dir/arch/xtensa/core/offsets/offsets.c.obj
[ 11%] Linking C static library liboffsets.a
[ 11%] Built target offsets
Scanning dependencies of target offsets_h
[ 12%] Generating include/generated/offsets.h
[ 12%] Built target offsets_h
Scanning dependencies of target linker_script
[ 13%] Generating linker.cmd
Scanning dependencies of target drivers__i2c
[ 13%] Built target linker_script
[ 15%] Building C object zephyr/drivers/i2c/CMakeFiles/drivers__i2c.dir/i2c_esp32.c.obj
Scanning dependencies of target app
Scanning dependencies of target lib__libc__newlib
Scanning dependencies of target drivers__serial
Scanning dependencies of target drivers__gpio
[ 16%] Building C object CMakeFiles/app.dir/src/main.c.obj
[ 18%] Building C object zephyr/drivers/serial/CMakeFiles/drivers__serial.dir/uart_esp32.c.obj
[ 19%] Building C object zephyr/lib/libc/newlib/CMakeFiles/lib__libc__newlib.dir/libc-hooks.c.obj
[ 20%] Building C object zephyr/drivers/gpio/CMakeFiles/drivers__gpio.dir/gpio_esp32.c.obj
[ 22%] Linking C static library libapp.a
[ 23%] Linking C static library libdrivers__serial.a
Scanning dependencies of target zephyr
[ 23%] Built target app
[ 23%] Built target drivers__serial
[ 25%] Building C object zephyr/CMakeFiles/zephyr.dir/arch/common/isr_tables.c.obj
[ 27%] Building C object zephyr/CMakeFiles/zephyr.dir/arch/xtensa/core/cpu_idle.c.obj
[ 27%] Building C object zephyr/CMakeFiles/zephyr.dir/arch/xtensa/soc/esp32/esp32-mp.c.obj
[ 29%] Building ASM object zephyr/CMakeFiles/zephyr.dir/arch/xtensa/core/xtensa-asm2-util.S.obj
[ 30%] Building C object zephyr/CMakeFiles/zephyr.dir/lib/thread_entry.c.obj
[ 31%] Linking C static library liblib__libc__newlib.a
[ 33%] Building ASM object zephyr/CMakeFiles/zephyr.dir/arch/xtensa/core/atomic.S.obj
[ 38%] Building C object zephyr/CMakeFiles/zephyr.dir/arch/xtensa/soc/esp32/soc.c.obj
[ 38%] Building C object zephyr/CMakeFiles/zephyr.dir/arch/xtensa/core/xtensa-asm2.c.obj
[ 38%] Building C object zephyr/CMakeFiles/zephyr.dir/lib/crc/crc16_sw.c.obj
[ 40%] Building ASM object zephyr/CMakeFiles/zephyr.dir/arch/xtensa/core/window_vectors.S.obj
[ 38%] Building C object zephyr/CMakeFiles/zephyr.dir/arch/xtensa/core/fatal.c.obj
[ 41%] Building C object zephyr/CMakeFiles/zephyr.dir/lib/crc/crc8_sw.c.obj
Scanning dependencies of target kernel
[ 43%] Building C object zephyr/CMakeFiles/zephyr.dir/lib/mempool/mempool.c.obj
[ 44%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/alert.c.obj
[ 44%] Built target lib__libc__newlib
[ 45%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/idle.c.obj
[ 47%] Linking C static library libdrivers__gpio.a
[ 48%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/errno.c.obj
[ 50%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/init.c.obj
[ 51%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/device.c.obj
[ 52%] Linking C static library libdrivers__i2c.a
[ 54%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/mailbox.c.obj
[ 55%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/mem_slab.c.obj
[ 56%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/mempool.c.obj
[ 56%] Built target drivers__gpio
[ 58%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/mutex.c.obj
[ 59%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/msg_q.c.obj
[ 61%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/pipes.c.obj
[ 62%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/queue.c.obj
[ 62%] Built target drivers__i2c
[ 63%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/sched.c.obj
[ 65%] Building C object zephyr/CMakeFiles/zephyr.dir/misc/generated/configs.c.obj
[ 66%] Building C object zephyr/CMakeFiles/zephyr.dir/misc/printk.c.obj
[ 68%] Building C object zephyr/CMakeFiles/zephyr.dir/lib/rbtree/rb.c.obj
[ 69%] Building C object zephyr/CMakeFiles/zephyr.dir/drivers/console/uart_console.c.obj
[ 70%] Building C object zephyr/CMakeFiles/zephyr.dir/drivers/pinmux/pinmux_esp32.c.obj
[ 72%] Building C object zephyr/CMakeFiles/zephyr.dir/drivers/timer/sys_clock_init.c.obj
[ 73%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/sem.c.obj
[ 75%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/stack.c.obj
[ 76%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/sys_clock.c.obj
[ 77%] Building C object zephyr/CMakeFiles/zephyr.dir/drivers/timer/xtensa_sys_timer.c.obj
[ 79%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/system_work_q.c.obj
[ 80%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/thread.c.obj
[ 81%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/version.c.obj
[ 83%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/thread_abort.c.obj
[ 84%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/smp.c.obj
[ 86%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/work_q.c.obj
[ 87%] Building C object zephyr/kernel/CMakeFiles/kernel.dir/timer.c.obj
[ 88%] Linking C static library libzephyr.a
[ 88%] Built target zephyr
[ 90%] Linking C static library libkernel.a
[ 90%] Built target kernel
Scanning dependencies of target zephyr_prebuilt
[ 91%] Building C object zephyr/CMakeFiles/zephyr_prebuilt.dir/misc/empty_file.c.obj
[ 93%] Linking C executable zephyr_prebuilt.elf
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-assert.o):(.literal+0xc): undefined reference to `__getreent'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-assert.o): In function `__assert_func':
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdlib/assert.c:59: undefined reference to `__getreent'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-fiprintf.o): In function `fiprintf':
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdio/fiprintf.c:49: undefined reference to `__getreent'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-vfiprintf.o): In function `_vfiprintf_r':
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdio/vfprintf.c:1791: undefined reference to `__getreent'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-wsetup.o): In function `__swsetup_r':
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdio/wsetup.c:39: undefined reference to `__getreent'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-fflush.o):/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdio/fflush.c:293: more undefined references to `__getreent' follow
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-freer.o):(.literal+0x14): undefined reference to `_sbrk_r'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-freer.o): In function `_malloc_trim_r':
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdlib/mallocr.c:3331: undefined reference to `_sbrk_r'
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdlib/mallocr.c:3340: undefined reference to `_sbrk_r'
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdlib/mallocr.c:3345: undefined reference to `_sbrk_r'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-locale.o): In function `_localeconv_r':
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/locale/locale.c:1023: undefined reference to `__getreent'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-locale.o): In function `setlocale':
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/locale/locale.c:1035: undefined reference to `__getreent'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-makebuf.o):(.literal+0x4): undefined reference to `_fstat_r'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-makebuf.o): In function `__smakebuf_r':
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdio/makebuf.c:59: undefined reference to `_fstat_r'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-mallocr.o): In function `malloc_extend_top':
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdlib/mallocr.c:2165: undefined reference to `_sbrk_r'
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdlib/mallocr.c:2202: undefined reference to `_sbrk_r'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-signal.o):(.literal+0x0): undefined reference to `_getpid_r'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-signal.o):(.literal+0x4): undefined reference to `_kill_r'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-signal.o): In function `_raise_r':
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/signal/signal.c:163: undefined reference to `_getpid_r'
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/signal/signal.c:163: undefined reference to `_kill_r'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-signal.o): In function `raise':
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/signal/signal.c:215: undefined reference to `__getreent'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-signal.o): In function `signal':
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/signal/signal.c:223: undefined reference to `__getreent'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-signal.o): In function `_init_signal':
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/signal/signal.c:229: undefined reference to `__getreent'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-signal.o): In function `__sigtramp':
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/signal/signal.c:235: undefined reference to `__getreent'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-stdio.o):(.literal+0x4): undefined reference to `_read_r'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-stdio.o):(.literal+0x8): undefined reference to `_lseek_r'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-stdio.o):(.literal+0xc): undefined reference to `_write_r'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-stdio.o):(.literal+0x10): undefined reference to `_close_r'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-stdio.o): In function `__sread':
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdio/stdio.c:48: undefined reference to `_read_r'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-stdio.o): In function `__swrite':
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdio/stdio.c:89: undefined reference to `_lseek_r'
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdio/stdio.c:97: undefined reference to `_write_r'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-stdio.o): In function `__sseek':
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdio/stdio.c:117: undefined reference to `_lseek_r'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-stdio.o): In function `__sclose':
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdio/stdio.c:135: undefined reference to `_close_r'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-wbuf.o): In function `__swbuf_r':
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdio/wbuf.c:82: undefined reference to `__getreent'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-wcrtomb.o): In function `_wcrtomb_r':
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdlib/wcrtomb.c:40: undefined reference to `__getreent'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(isatty.o): In function `_isatty_r':
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/sys/xtensa/isatty.c:13: undefined reference to `_fstat_r'
/opt/xtensa-esp32-elf/xtensa-esp32-elf/lib/./libc.a(lib_a-fclose.o): In function `_fclose_r':
/home/ivan/e/crosstool-NG/.build/src/newlib-2.2.0/newlib/libc/stdio/fclose.c:114: undefined reference to `__getreent'
collect2: error: ld returned 1 exit status
zephyr/CMakeFiles/zephyr_prebuilt.dir/build.make:104: recipe for target 'zephyr/zephyr_prebuilt.elf' failed
make[3]: *** [zephyr/zephyr_prebuilt.elf] Error 1
CMakeFiles/Makefile2:582: recipe for target 'zephyr/CMakeFiles/zephyr_prebuilt.dir/all' failed
make[2]: *** [zephyr/CMakeFiles/zephyr_prebuilt.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
```

**Comment by lpereira** [comment] 2018-06-01 23:14
Closing as duplicate of #1495.

**Closed by lpereira** 2018-06-01 23:14 UTC
Labels: area: Xtensa, bug, priority: medium
