### ISSUE TITLE
Bluetooth: Mesh: initialisation delay after disabling CONFIG_BT_DEBUG_LOG

### ISSUE THREAD

**Issue by vikrant8051** [zephyrproject-rtos/zephyr#11780] opened 2018-11-30 19:16 UTC
It is found that we have to have enable CONFIG_BT_DEBUG_LOG=y
then only Mesh initialization happens within second otherwise it takes around 10+ seconds. This bug has introduced after latest new logging subsystem.

**To Reproduce**
1) flash samples/boards/nrf52/mesh/onoff_level_lighting_vnd_app in nRF52840_pca10056 
   with CONFIG_BT_DEBUG_LOG=n (it is by default disable as per current prj.conf)
2) Provision & configure it using nRFMesh App
3) Reset the Board & see device serial terminal

Here NODE takes 10+ seconds to print "Mesh initialized"

It will be good if we could avoid all type of DEBUG LOGs, so that we could avoid that 1 seconds delay as well as to improve the performance. DEBUG log is important only for development with actual product developers may want to disable it.

**Comment by jhedberg** [comment] 2018-12-04 09:45
Looks like this is caused by commit 4d94257162b22f37104e9f85238ed7c3486c5a1c. @vikrant8051 could you try reverting that (`git revert 4d94257162b22f37104e9f85238ed7c3486c5a1c`) and see if the issue goes away for you?

**Comment by vikrant8051** [comment] 2018-12-04 11:33
OK

**Comment by vikrant8051** [comment] 2018-12-04 11:48
@jhedberg 
I think 
> git revert 4d94257162b22f37104e9f85238ed7c3486c5a1c

has no effect....still Mesh initialization takes some time.

**Comment by jhedberg** [comment] 2018-12-04 14:05
@vikrant8051 you also need #11842 . Both PRs should hopefully be merged soon.

**Closed** 2018-12-04 14:43 UTC
Labels: area: Logging, bug, priority: medium

**Comment by jhedberg** [comment] 2018-12-04 14:48
@vikrant8051 both PRs are in master now, so you can just rebase on top of that to see if the issue is now solved.

**Comment by vikrant8051** [comment] 2018-12-04 16:09
@nordic-krch  @jhedberg @carlescufi 
Issue has resolved !!
Thanks for solving it.
