### ISSUE TITLE
Bluetooth: USB Audio Starvation in BAP Broadcast Sink Sample 

### ISSUE THREAD

**Issue by smaerup** [zephyrproject-rtos/zephyr#76551] opened 2024-07-31 13:27 UTC
**Describe the bug**
The bap_broadcast_sink sample app will not send any audio frames over USB if no audio is received from the broadcast source.
This can cause issues on USB host side as some audio implementations does not like to be starved of audio frames. Particularly the Java audio implementation fails when trying to stop an audio recording from a device that has not yet provided any audio frames.

**To Reproduce**
1. Build the bap_broadcast_sink sample app and download to a nRF5340 Audio DK board
2. Connect to a Linux Host and start a recording using the Java Audio framework.
3. Stop the recording without having received any audio frames from a broadcast source.
4. The Java Audio framework will then hang as it has not yet received any USB audio frames.

**Expected behavior**
When stopping a recording from a device which has not yet received any audio, the recording should be successfully stopped and an audio file containing only silence should be produced.

**Environment**
    OS: (Linux)
    Toolchain (Zephyr SDK, Java SDK)
    Commit origin/main https://github.com/zephyrproject-rtos/zephyr/commit/36940db938a8f4a1e919496793ed439850a221c2

**Comment by aescolar** [comment] 2024-07-31 14:38
@smaerup would you be so kind as to elaborate a bit more :)

**Comment by Thalley** [comment] 2024-07-31 15:47
> @smaerup would you be so kind as to elaborate a bit more :)

@smaerup Please follow the bug template and properly describe the issue

**Comment by smaerup** [comment] 2024-08-29 07:05
Sorry for the delay, just came back from vacation.

**Comment by Thalley** [comment] 2024-09-10 06:45
@smaerup Any updates on this?

**Comment by smaerup** [comment] 2024-09-10 07:56
@Thalley I updated the bug description 2 weeks ago, anything else required?

**Comment by Thalley** [comment] 2024-09-10 08:06
> @Thalley I updated the bug description 2 weeks ago, anything else required?

Ah, sorry, didn't notice that :)

**Comment by smaerup** [comment] 2024-09-10 12:27
Yes, tried it with both plain Linux & Windows, and there the failure to stop an audio recording does not occur.
But not sending "silent" USB audio frames causes another issue on plain Linux/Windows that at first confused me a bit.
If I start a recording on the USB host and then some time later start/stop a BIS stream a few times, I would then expect the resulting recording to contain:
Silence, Audio, Silence Audio, Silence
But since no USB frames where sent, the resulting recording ended up being:
Audio, Audio

**Comment by smaerup** [comment] 2024-10-15 11:32
Sorry, was away on vacation.
Yes, that describes the issue very well.

**Comment by Thalley** [comment] 2024-10-16 11:48
Great, then we have a pretty good idea of what the issue is and where to look for at fix. 

Could you provide the steps to use the Java Audio framework to reproduce the issue? I'm unfamiliar with that framework, and I don't want to spend too much time with that framework to replicate the issue and to verify it.

**Comment by smaerup** [comment] 2024-10-21 12:04
The problem as such is already fixed by PR https://github.com/zephyrproject-rtos/zephyr/pull/76270
So this bug report is just for linking to the 3.7 backport.

**Comment by Thalley** [comment] 2024-10-21 12:24
This was fixed by https://github.com/zephyrproject-rtos/zephyr/pull/76270 and backported by https://github.com/zephyrproject-rtos/zephyr/pull/76548

**Closed by Thalley** 2024-10-21 12:24 UTC
Labels: bug, priority: low, area: Bluetooth, area: Bluetooth Audio
