### ISSUE TITLE
BLE Mesh On Net Buffer free issue

### ISSUE THREAD

**Issue by menglingao1997** [zephyrproject-rtos/zephyr#18013] opened 2019-08-05 10:11 UTC
**FUNCTION1**
https://github.com/zephyrproject-rtos/zephyr/blob/2b84c726c8893eaaa1bf26dfddf2798b159cd47d/subsys/bluetooth/mesh/friend.c#L90-L111

**FUNCTION2**
https://github.com/zephyrproject-rtos/zephyr/blob/2b84c726c8893eaaa1bf26dfddf2798b159cd47d/subsys/bluetooth/mesh/adv.c#L242-L252

**FUNCTION3**
https://github.com/zephyrproject-rtos/zephyr/blob/2b84c726c8893eaaa1bf26dfddf2798b159cd47d/subsys/bluetooth/mesh/friend.c#L166-L205

**FUNCTION4**
https://github.com/zephyrproject-rtos/zephyr/blob/2b84c726c8893eaaa1bf26dfddf2798b159cd47d/subsys/bluetooth/mesh/adv.c#L159-L196

when the buffer create from **FUNCTION1**, then the buf `ref=1`, we send this buffer use **FUNCTION2**, this time the buf `ref=2`, when the friend terminated and buf also in `adv_queue`, the **FUNCTION3** will be call, in this function unref the last_buf, and set BUSY=0, so buf `ref=1`,when **FUNCTION4** get cpu times, will get buffer from `adv_queue`, but the BUSY flag we already cleared, so this buffer not send, and the buf also `ref=1`. so at this time the **memory leak** occurs.

**If I infer that it is correct, Can be modified like this:**
``` C
 	if (BT_MESH_ADV(buf)->busy) { 
 		BT_MESH_ADV(buf)->busy = 0U; 
 		adv_send(buf); 
 	} 
        else{
                net_buf_unref(buf);
        }

```

**Comment by menglingao1997** [comment] 2019-08-05 10:14
@jhedberg

**Comment by jhedberg** [comment] 2019-08-05 13:18
@menglingao1997 your suggested fix looks correct. Do you want to try creating a pull request for it? I'm still on vacation, so I'll be able to do it earliest next week.

**Comment by jhedberg** [comment] 2019-08-05 13:23
Isn't this a duplicate of #17936 ?

**Comment by menglingao1997** [comment] 2019-08-06 00:42
look like this, and may be able to solve in the same way.

**Closed** 2019-08-14 12:51 UTC
Labels: area: Bluetooth, bug
