### ISSUE TITLE
Problem pairing/bonding 2nd device, whilst the first device is still connected using sample project (bluetooth\peripheral)

### ISSUE THREAD

**Issue by faisalSaleemSetec** [zephyrproject-rtos/zephyr#13083] opened 2019-02-06 05:21 UTC
**Describe the bug""
Failed to bond the second device, while 1st device is paired and connected, running the sample project bluetooth\peripheral on nrf52_pca10040 development board. Have added (CONFIG_BT_MAX_CONN=4, CONFIG_BT_MAX_PAIRED=4) to allow for up to 4 devices to bond.
 
 
**To Reproduce**
1. Modify the prj.conf file in the sample project bluetooth\peripheral with the following changes,
CONFIG_BT_MAX_CONN=4 
CONFIG_BT_MAX_PAIRED=4
optional, for debugging
CONFIG_DEBUG_INFO=y
CONFIG_BT_DEBUG=y
CONFIG_BT_DEBUG_SMP=y
CONFIG_BT_DEBUG_KEYS=n
CONFIG_BT_DEBUG_GATT=y
CONFIG_BT_DEBUG_CONN=n

2. project_build> cmake -GNinja -DBOARD=nrf52_pca10040 ..\project\zephyr\samples\bluetooth\peripheral

3. Ninja flash
4. Use NRFConnect to connect multiple devices.
1st device always bonds correctly but the second one never bonds while the 1st one is bonded (paired and connected)..
used iphone xs and iphone 7 plus... whichever device i use first, gets paired but the second one fails to bond..
With the debug report on console, the first device will display smp_pairing_complete with status 0x0, (successful) and finally bt_smp_connected whereas the second device will always get Disconnected (reason 8), i.e., unspecified error.. the sequence of failure is as follows, which is also given in the snapshots below,
bt_smp_encrypt_change:
bt_gatt_disconnected:
ccc_save:
bt_gatt_store_ccc:
bt_smp_disconnected:
Disconnected (reason 8)

**Expected behaviour**
Since CONFIG_BT_MAX_CONN=4 and CONFIG_BT_MAX_PAIRED=4, is added, I was expecting 4 devices to get paired and connected. Not sure what other configurations need to be changed.

**Impact**
We are using multiple device pairing ability in one of our projects which has a final delivery within a month time. Still struggling to get the second device getting paired up with 1st device already paired and connected.

**Environment (please complete the following information):**
 - OS: (Windows)
 - Toolchain (arm-none-eabi-gcc-7.3.1)
 - hardware - PCA10040 development kit
 - Commit SHA-1: 84ae2f11ed07335d188af0d302954dc54de14746

**Screenshots or console output**

**_1st device pairing successfully_**

![image](https://user-images.githubusercontent.com/47340640/52320937-2470b200-2a26-11e9-88bb-b224aac085ec.png)

![image](https://user-images.githubusercontent.com/47340640/52320970-4f5b0600-2a26-11e9-8634-68b8779b95ef.png)

![image](https://user-images.githubusercontent.com/47340640/52321009-6d286b00-2a26-11e9-98aa-eb8e0260279e.png)

![image](https://user-images.githubusercontent.com/47340640/52321039-a1039080-2a26-11e9-8ba0-4f642f297a92.png)

**_2nd device pairing failed_**

![image](https://user-images.githubusercontent.com/47340640/52321085-f50e7500-2a26-11e9-8f4f-47f8530261e8.png)

![image](https://user-images.githubusercontent.com/47340640/52321101-0bb4cc00-2a27-11e9-8beb-f916047e4cd8.png)

![image](https://user-images.githubusercontent.com/47340640/52321114-1d966f00-2a27-11e9-91b9-8bbdfb957ffc.png)

![image](https://user-images.githubusercontent.com/47340640/52321126-31da6c00-2a27-11e9-9d95-39e5fe5891d2.png)

**Additional context**
duplicate of "Zephyr/BLE stack: Problem pairing/bonding more than one device, whilst the first device is still connected".

**Comment by faisalSaleemSetec** [comment] 2019-02-07 03:05
** Problem **
Upon bonding the 1st device successfully and while it is connected, when I try to bond the 2nd device, I get Disconnected (reason 8). (BTW, a few times the connection/bonding of the 2nd device was successful as well). Anyways, the case where the 2nd device fails to bond and if I reset the development board running the sample code. Now I can straight away connect the 1st device without it asking for pairing key, since it is bonded but when I try to pair the 2nd device, I get a hardware exception given below

```
Connected
[bt] [DBG] sc_process: (0x20003138) start 0x000c end 0x002b
[bt] [DBG] gatt_indicate: (0x20003138) conn 0x2000079c handle 0x0003
[bt] [DBG] gatt_indicate: (0x20003138) conn 0x200006fc handle 0x0003
[bt] [DBG] sc_indicate_rsp: (0x20002fc4) err 0x00
***** USAGE FAULT *****
  Illegal use of the EPSR
***** Hardware exception *****
Current thread ID = 0x20002fc4
Faulting instruction address = 0x0
Fatal fault in thread 0x20002fc4! Aborting.
```

**To reproduce the issue**

1. With the configuration changes in sample bluetooth\peripheral given above in the first report, flash the code in the nrf52_pca10040 development kit.

2. Using nrfConnect, Pair/connect the 1st device (I used iphone 7 plus), it should successfully bond/connect with the development kit.
3. Using nrfConnect pair/connect the 2nd device (i used iphone 7 plus as well, tried android as well), 90% of the times it is unsuccessful with Disconnection (reason 8).
4. If the 2nd device is unsuccessful in connecting/bonding, then restart the development kit.
5. Using nrfConnect connect the 1st device, since it is already paired it will straight away get connected.
6. Using nrfConnect connect the 2nd device, it should give the hardware exception given in the console output attachement. On 1 occassion, it did try to ask for the pairing key, thus no hardware exception came, but when i restarted the development kit again and followed steps 5 and 6, same hardware exception came back.

**Console Output for the hardware exception **
[hardwareException.txt](https://github.com/zephyrproject-rtos/zephyr/files/2839120/hardwareException.txt)

**Comment by faisalSaleemSetec** [comment] 2019-02-07 05:24
tried the bluetooth sample peripheral using Zephyr commit: SHA-1: 31503a868b889413ed27180e8799188802fedca1 
Same issue, second 2nd device disconnects (reason 8) if the 1st device is bonded and connected...

prj.conf is modified as follows..
   CONFIG_BT_MAX_CONN=4
   CONFIG_BT_MAX_PAIRED=4

**Comment by jhedberg** [comment] 2019-02-08 07:53
This sounds like it could be a duplicate of #12946

**Comment by faisalSaleemSetec** [comment] 2019-02-10 23:48
it is actually the duplicate of #12946 as my colleague posted that issue.. since cvinayak asked for further details in regards to the zephyr hash, configuration etc, I simply reproduced the same issue using the sample bluetooth (peripheral) with our modified changes... I created this new post and tried to link #12946 as a duplicate.. you can close off issue #12946 and update the details here as its the same issue...

**Comment by cvinayak** [comment] 2019-02-11 10:02
Acknowledge the issue, the second connection is stable until encryption change on the second connection. I am analyzing the cause, will comment here once I have something.

**Comment by DeclanTraill** [comment] 2019-02-13 02:39
I don't know if this is relevant or not, but might be worth considering:

The TODO comment in the file ctrl.c, function isr_radio_state_tx():

static inline void isr_radio_state_tx(void)
{
	u32_t hcto;

	_radio.state = STATE_RX;

     ```````````````````````````````````````
      Other Code.......
     ```````````````````````````````````````
		/* Route the tx packet to respective connections */
		/* TODO: use timebox for tx enqueue (instead of 1 packet
		 * that is routed, which may not be for the current connection)
		 * try to route as much tx packet in queue into corresponding
		 * connection's tx list.
		 */
		packet_tx_enqueue(1);

		break;

	case ROLE_NONE:
	default:
		LL_ASSERT(0);
		break;
	}
}

Could there be a timeout occurring on a packet for the 2nd connection due to packets from the first connection being processed in preference (as the individual connections Tx queues are not yet Timeboxed)?

**Comment by nwsetec** [comment] 2019-02-20 21:52
Hi @cvinayak, any updates on this issue?  Thanks

**Comment by carlescufi** [comment] 2019-03-15 14:37
@faisalSaleemSetec @nwsetec sorry for the long delay. A fix has been identified by @joerchan and will be posted shortly

**Closed** 2019-03-15 19:56 UTC
Labels: area: Bluetooth, bug, priority: high
