### ISSUE TITLE
Adding CONFIG_PM=y to prj.conf containing CONFIG_LORA=y causes the device to not boot up

### ISSUE THREAD

**Issue by jpro-tt** [zephyrproject-rtos/zephyr#62935] opened 2023-09-21 13:24 UTC
**Describe the bug**
Hello, I've recently found an issue related to adding `CONFIG_PM=y` to `prj.conf` containing `CONFIG_LORA=y`.  Whenever I combine these two configs in `prj.conf`, my device doesn't boot. I use Wio-E5 Development Kit (LoRa_E5_Dev_Board).

**To Reproduce**
1. Add `CONFIG_PM=y` to `prj.conf` in sample `drivers/lora/send` 
2. `west build -p always -b lora_e5_dev_board samples/drivers/lora/send`
3. `west flash`

Other samples may be used, but they also fail to work.

**Expected behavior**
A device boots and prints logs to UART console.

**Impact**
I cannot use power management in my applications using LoRaWAN.

**Logs and console output**
There is no output in console.

**Additional context**
I use default devicetree in these samples.

**Comment by knthm** [comment] 2023-09-25 14:04
This is a duplicate of #59194.

The STM32WL SoC will have entered STOP2 before the UART boot splash prints and the LoRa message transmission has been attempted.

The UART and SPI drivers don't yet have a mechanism to recover from their configuration loss after the SoC enters STOP2. UART simply won't work, but SPI will deadlock the system when it attempts a bus transaction.

See #59200 for fixes to both *(note you need to add the required `reinit-power-states` DT property for the respective USART and SPI peripherals)*.

**Closed by knthm** 2023-09-25 14:04 UTC
Labels: bug, Duplicate, area: Power Management, platform: STM32, area: LoRa
