### ISSUE TITLE
intermittent tests/kernel/workq/work_queue failure

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#13044] opened 2019-02-04 22:04 UTC
Seen with both regular and polling implementations

```
----------sanity-out/qemu_nios2/tests/kernel/workq/work_queue/kernel.workqueue/handler.log----------
***** Booting Zephyr OS zephyr-v1.13.0-4051-g44906b118f *****
Running test suite workqueue
===================================================================
starting test - test_sequence
 - Initializing test items
 - Submitting test items
 - Submitting work 1 from preempt thread
 - Running test item 1
 - Submitting work 2 from coop thread
 - Submitting work 3 from preempt thread
 - Submitting work 4 from coop thread
 - Running test item 2
 - Submitting work 5 from preempt thread
 - Submitting work 6 from coop thread
 - Waiting for work to finish
 - Running test item 3
 - Running test item 4
 - Running test item 5
 - Running test item 6
PASS - test_sequence
===================================================================
starting test - test_resubmit
Starting resubmit test
 - Submitting work
 - Waiting for work to finish
 - Resubmitting work
 - Resubmitting work
 - Resubmitting work
 - Resubmitting work
 - Resubmitting work
 - Checking results

    Assertion failed at /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/tests/kernel/workq/work_queue/src/main.c:119: check_results: (num_results not equal to num_tests)
*** work items finished: 5 (expected: 6)

FAIL - test_resubmit
===================================================================
starting test - test_delayed
Starting delayed test
 - Initializing delayed test items
 - Submitting delayed test items
 - Submitting delayed work 1 from preempt thread
 - Submitting delayed work 3 from preempt thread
 - Submitting delayed work 5 from preempt thread
 - Waiting for delayed work to finish
 - Submitting delayed work 2 from coop thread
 - Submitting delayed work 4 from coop thread
 - Submitting delayed work 6 from coop thread
 - Running delayed test item 1
 - Running delayed test item 2
 - Running delayed test item 3
 - Running delayed test item 4
 - Running delayed test item 5
 - Running delayed test item 6
 - Checking results

    Assertion failed at /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/tests/kernel/workq/work_queue/src/main.c:119: check_results: (num_results not equal to num_tests)
*** work items finished: 12 (expected: 6)

FAIL - test_delayed
===================================================================
starting test - test_delayed_resubmit
Starting delayed resubmit test
 - Submitting delayed work
 - Waiting for work to finish
 - Resubmitting delayed work
 - Resubmitting delayed work
 - Resubmitting delayed work
 - Checking results

    Assertion failed at /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/tests/kernel/workq/work_queue/src/main.c:119: check_results: (num_results not equal to num_tests)
*** work items finished: 15 (expected: 6)

FAIL - test_delayed_resubmit
===================================================================
starting test - test_delayed_resubmit_thread
Starting delayed resubmit from coop thread test
 - Waiting for work to finish
 - Resubmitting delayed work with 1 ms
 - Resubmitting delayed work with 1 ms
 - Resubmitting delayed work with 1 ms
 - Resubmitting delayed work with 1 ms
 - Resubmitting delayed work with 1 ms
 - Resubmitting delayed work with 1 ms
 - Running delayed test item 1
 - Checking results

    Assertion failed at /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/tests/kernel/workq/work_queue/src/main.c:119: check_results: (num_results not equal to num_tests)
*** work items finished: 16 (expected: 1)

FAIL - test_delayed_resubmit_thread
===================================================================
starting test - test_delayed_cancel
Starting delayed cancel test
 - Cancel delayed work from preempt thread
 - Waiting for work to finish
 - Cancel delayed work from coop thread
 - Checking results

    Assertion failed at /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/tests/kernel/workq/work_queue/src/main.c:119: check_results: (num_results not equal to num_tests)
*** work items finished: 16 (expected: 0)

FAIL - test_delayed_cancel
===================================================================
Test suite workqueue failed.
===================================================================
PROJECT EXECUTION FAILED
----------sanity-out/qemu_nios2/tests/kernel/workq/work_queue/kernel.workqueue/handler.log----------
```

```
--------sanity-out/qemu_x86/tests/kernel/workq/work_queue/kernel.workqueue.poll/handler.log---------
cSeaBIOS (version rel-1.11.2-0-gf9626ccb91-prebuilt.qemu-project.org)
Booting from ROM..***** Booting Zephyr OS zephyr-v1.13.0-4051-g44906b118f *****
Running test suite workqueue
===================================================================
starting test - test_sequence
 - Initializing test items
 - Submitting test items
 - Submitting work 1 from preempt thread
 - Running test item 1
 - Submitting work 2 from coop thread
 - Submitting work 3 from preempt thread
 - Submitting work 4 from coop thread
 - Running test item 2
 - Submitting work 5 from preempt thread
 - Submitting work 6 from coop thread
 - Waiting for work to finish
 - Running test item 3
 - Running test item 4
 - Running test item 5
 - Running test item 6
PASS - test_sequence
===================================================================
starting test - test_resubmit
Starting resubmit test
 - Submitting work
 - Waiting for work to finish
 - Resubmitting work
 - Resubmitting work
 - Resubmitting work
 - Resubmitting work
 - Resubmitting work
 - Checking results
PASS - test_resubmit
===================================================================
starting test - test_delayed
Starting delayed test
 - Initializing delayed test items
 - Submitting delayed test items
 - Submitting delayed work 1 from preempt thread
 - Submitting delayed work 3 from preempt thread
 - Submitting delayed work 5 from preempt thread
 - Waiting for delayed work to finish
 - Submitting delayed work 2 from coop thread
 - Submitting delayed work 4 from coop thread
 - Submitting delayed work 6 from coop thread
 - Running delayed test item 1
 - Running delayed test item 2
 - Running delayed test item 3
 - Running delayed test item 4
 - Running delayed test item 5
 - Running delayed test item 6
 - Checking results
PASS - test_delayed
===================================================================
starting test - test_delayed_resubmit
Starting delayed resubmit test
 - Submitting delayed work
 - Waiting for work to finish
 - Resubmitting delayed work
 - Resubmitting delayed work
 - Resubmitting delayed work
 - Resubmitting delayed work
 - Resubmitting delayed work
 - Checking results

    Assertion failed at /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/tests/kernel/workq/work_queue/src/main.c:119: check_results: (num_results not equal to num_tests)
*** work items finished: 5 (expected: 6)

FAIL - test_delayed_resubmit
===================================================================
starting test - test_delayed_resubmit_thread
Starting delayed resubmit from coop thread test
 - Waiting for work to finish
 - Resubmitting delayed work with 1 ms
 - Resubmitting delayed work with 1 ms
 - Resubmitting delayed work with 1 ms
 - Resubmitting delayed work with 1 ms
 - Resubmitting delayed work with 1 ms
 - Resubmitting delayed work with 1 ms
 - Running delayed test item 1
 - Checking results

    Assertion failed at /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/tests/kernel/workq/work_queue/src/main.c:119: check_results: (num_results not equal to num_tests)
*** work items finished: 7 (expected: 1)

FAIL - test_delayed_resubmit_thread
===================================================================
starting test - test_delayed_cancel
Starting delayed cancel test
 - Cancel delayed work from preempt thread
 - Waiting for work to finish
 - Cancel delayed work from coop thread
 - Cancel pending delayed work from coop thread
 - Checking results

    Assertion failed at /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/tests/kernel/workq/work_queue/src/main.c:119: check_results: (num_results not equal to num_tests)
*** work items finished: 7 (expected: 0)

FAIL - test_delayed_cancel
===================================================================
Test suite workqueue failed.
===================================================================
PROJECT EXECUTION FAILED
--------sanity-out/qemu_x86/tests/kernel/workq/work_queue/kernel.workqueue.poll/handler.log---------
```

**Comment by andyross** [comment] 2019-03-06 16:29
Going to close this one as IMHO the issue is well captured by #12553, it's nothing specific to this bug, and this bug works very reliably on unloaded systems (it **is**, however, the single most seen failing case on loaded runs, but I think that's down to the fact that it does more loops with sleeping and scheduling interactions than other tests, which usually test one thing and move on).

**Closed by andyross** 2019-03-06 16:29 UTC
Labels: bug, priority: low
