### ISSUE TITLE
sam_e70_xplained: running samples/net/sockets/civetweb/ failed

### ISSUE THREAD

**Issue by Zhaoningx** [zephyrproject-rtos/zephyr#29773] opened 2020-11-04 02:58 UTC
Describe the bug
running samples/net/sockets/civetweb/ failed, it might be timeout.

To Reproduce
sanitycheck -p sam_e70_xplained --device-testing --device-serial /dev/ttyACM0  -T samples/net/sockets/civetweb/ -vv
see error

*** Booting Zephyr OS build zephyr-v2.4.0-1226-g0d4dca10b2ac  ***
[00:00:00.000,000] <wrn> soc: CIDR mismatch: chip = 0xa1020e01 vs HAL = 0xa1020e00
[00:00:00.000,000] <inf> eth_sam: MAC: 00:00:00:00:00:00
[00:00:00.000,000] <inf> eth_sam: Queue 0 activated
[00:00:00.000,000] <inf> eth_sam: Queue 1 set to idle
[00:00:00.000,000] <inf> eth_sam: Queue 2 set to idle
[00:00:00.000,000] <inf> eth_sam_phy: Soft Reset of ETH PHY
*** Booting Zephyr OS build zephyr-v2.4.0-1226-g0d4dca10b2ac  ***
[00:00:00.090,000] <inf> eth_sam_phy: PHYID: 0x221561 at addr: 0
[00:00:00.096,000] <inf> net_config: Initializing network
[00:00:00.096,000] <inf> net_config: Waiting interface 1 (0x2040482c) to be up...

Environment (please complete the following information):
OS: Fedora28
Toolchain: Zephyr-sdk-0.11.3
Commit ID: g0d4dca10b2ac

**Comment by nashif** [comment] 2020-12-16 17:12
duplicate of #30472

**Closed by nashif** 2020-12-16 17:12 UTC
Labels: bug, priority: low
