### ISSUE TITLE
tests/kernel/fifo/fifo_timeout fails on cc3220sf_launchxl

### ISSUE THREAD

**Issue by vanti** [zephyrproject-rtos/zephyr#18599] opened 2019-08-23 01:14 UTC
**Describe the bug**
The test fails with the following output:

```
***** Booting Zephyr OS build v2.0.0-rc1-144-g048b0359bcd2 *****
Running test suite test_fifo_timeout
===================================================================
starting test - test_timeout_empty_fifo
PASS - test_timeout_empty_fifo
===================================================================
starting test - test_timeout_non_empty_fifo
PASS - test_timeout_non_empty_fifo
===================================================================
starting test - test_timeout_fifo_thread
PASS - test_timeout_fifo_thread
===================================================================
starting test - test_timeout_threads_pend_on_fifo
 thread (q order: 2, t/o: 0, fifo 0x20000008)
 thread (q order: 3, t/o: 10, fifo 0x20000008)
 thread (q order: 0, t/o: 20, fifo 0x20000008)
 thread (q order: 4, t/o: 30, fifo 0x20000008)
 thread (q order: 1, t/o: 40, fifo 0x20000008)
PASS - test_timeout_threads_pend_on_fifo
===================================================================
starting test - test_timeout_threads_pend_on_dual_fifos
 thread (q order: 0, t/o: 0, fifo 0x2000001c)
FAIL - test_multiple_threads_pending@188.  *** thread 3 woke up, expected 1

    Assertion failed at ZEPHYR_BASE/tests/kernel/fifo/fifo_timeout/src/main.c:467: test_timeout_threads_pend_on_dual_fifos: rv not equal to TC_PASS

FAIL - test_timeout_threads_pend_on_dual_fifos
===================================================================
starting test - test_timeout_threads_pend_fail_on_fifo
FAIL - test_multiple_threads_get_data@240.  *** thread 5 woke up, expected 0

    Assertion failed at ZEPHYR_BASE/tests/kernel/fifo/fifo_timeout/src/main.c:488: test_timeout_threads_pend_fail_on_fifo: rv not equal to TC_PASS


    Assertion failed at ZEPHYR_BASE/tests/kernel/fifo/fifo_timeout/src/main.c:131: test_thread_pend_and_timeout: packet == N
```

**To Reproduce**
0. cd tests/kernel/fifo/fifo_timeout
1. mkdir build; cd build
2. cmake .. -DBOARD=cc3220sf_launchxl
3. make flash

**Expected behavior**
The test should pass.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain: Zephyr SDK 0.10.3
 - Commit SHA tested: 1751648db02258d6c56c4ca1e6fea591bf5bc806

**Comment by nashif** [comment] 2019-08-29 12:33
duplicate of #18591

**Closed by nashif** 2019-08-29 12:33 UTC
Labels: area: Kernel, bug, priority: medium
