### ISSUE TITLE
Ethernet network management interface additions for MAC filtering

### ISSUE THREAD

**Issue by laperie** [zephyrproject-rtos/zephyr#7042] opened 2018-04-12 14:02 UTC
It should be possible to pass a set of MAC addresses to the Ethernet driver so that they are whitelisted.  It should be possile to drop any traffic with destination other than the whitelisted

**Comment by jukkar** [comment] 2018-07-12 09:46
Duplicate of #7596

**Closed by jukkar** 2018-07-12 09:46 UTC
Labels: area: Ethernet, area: Networking, enhancement
