### ISSUE TITLE
west update fails on `hal_espressif`

### ISSUE THREAD

**Issue by rexut** [zephyrproject-rtos/zephyr#72207] opened 2024-05-02 06:19 UTC
**Describe the bug**

Actually, with the detached SHA1 `e554857` from Zephyr's west manifest, `west update` runs into the following error:
```
ERROR: update failed for project hal_espressif
```

Isn't that the wrong SHA1 https://github.com/zephyrproject-rtos/hal_espressif/commit/e554857b07d54e2152c6f1a9b39da6d6c13fe7f7 ?:

https://github.com/zephyrproject-rtos/zephyr/blob/ea995f6378f7f6a6f8b6b1f7df29e0af7437f7a1/west.yml#L155

In the `hal_espressif` [branch `zephyr` on head](https://github.com/zephyrproject-rtos/hal_espressif/commits/zephyr) is SHA1 https://github.com/zephyrproject-rtos/hal_espressif/commit/c49581173bab8625d1f08d5c41d5a186afc240b3. Both SHA1 refer to the commit:
```
driver: sdhc: ESP32 pinctrl config for SDHC

Additional LL files for SDHC driver, as well as pinctrl configuration

Signed-off-by: Raffael Rostagno <raffael.rostagno@espressif.com>
```

**To Reproduce**

1. have a out-of-tree or downstream project with Zephyr as module
2. have a local west workspace for at least unchanged since 29. April
3. run `west update`

**Expected behavior**

`west update` without any error. Sane update the references in `hal_espressif`.

**Impact**

Can't participate from last fixes / changes on Espressif HAL.

**Environment (please complete the following information):**

 - OS: Linux (Ubuntu 20.04)
 - Toolchain: Zephyr SDK v0.16.5
 - Source: Zephyr v3.6.99 (main) Commit SHA ea995f6378f7f6a6f8b6b1f7df29e0af7437f7a1
 - West: v1.2.0

**Additional context**

Simple change the SHA1 in Zephyr's west manifest from `e554857b07d54e2152c6f1a9b39da6d6c13fe7f7` to `c49581173bab8625d1f08d5c41d5a186afc240b3` that was committed yesterday.

**Comment by jvermillard** [comment] 2024-05-02 06:44
duplicate of #72196

**Closed** 2024-05-02 07:18 UTC
