### ISSUE TITLE
stm32f407 flash erase error sometimes

### ISSUE THREAD

**Issue by maweicoltsmart** [zephyrproject-rtos/zephyr#16041] opened 2019-05-09 15:13 UTC
```
int flash_stm32_wait_flash_idle(struct device *dev)
{
	s64_t timeout_time = k_uptime_get() + STM32_FLASH_TIMEOUT;
	int rc;

	rc = flash_stm32_check_status(dev);
	if (rc < 0) {
		printk("%s, %d\r\n",__func__,__LINE__);
		return -EIO;
	}

	while ((FLASH_STM32_REGS(dev)->sr & FLASH_SR_BSY)) {
		if (k_uptime_get() > timeout_time) {
			return -EIO;
		}
	}

	return 0;
}
```
stm32f407vet6 flash erase error sometimes，program run to line printk above

**Comment by maweicoltsmart** [comment] 2019-05-09 15:33
I erase address 0x8060000

**Comment by erwango** [comment] 2019-07-03 08:17
@maweicoltsmart do you still face this issue?
If yes, can you try to increase STM32_FLASH_TIMEOUT?

**Comment by erwango** [comment] 2019-07-26 09:23
@maweicoltsmart , we've increased STM32_FLASH_TIMEOUT since it was seen to be too tight in some cases. The change is available in current master.
Can you try to see if you still see the issue with this change?

**Comment by erwango** [comment] 2019-11-01 11:35
@maweicoltsmart, is this issue still valid?

**Comment by erwango** [comment] 2019-11-21 15:06
No update, can't be reproduced. Likely fixed by STM32_FLASH_TIMEOUT increased flashed some months ago.
I'm closing the point. Please feel free to re-open if seen again

**Closed by erwango** 2019-11-21 15:06 UTC
Labels: area: Flash, bug, platform: STM32, priority: low
