### ISSUE TITLE
USB device not recognized on PCA10056 preview-DK

### ISSUE THREAD

**Issue by Qbicz** [zephyrproject-rtos/zephyr#14988] opened 2019-03-28 14:55 UTC
**Describe the bug**
nrf52840_pca10056, USB DFU sample. USB device used to be recognized in the past, with recent Zephyr it's unusable with following message on Windows:

`USB Device Not Recognized. One of the USB devices attached to this computer has malfunctioned and Windows does not recognize it. For assistance in solving this problem, click this message.`

![image](https://user-images.githubusercontent.com/5618209/55157981-19045200-515e-11e9-95ea-ed58fa672519.png)

**To Reproduce**
1. Erase the board
2. Flash MCUBoot built for DBOARD=nrf52840_pca10056
2. Compile USB DFU sample
3. Sign sample with imgtool
4. Flash signed sample next to bootloader
5. Attach USB cable

**Environment (please complete the following information):**
 - built on Ubuntu 16.04 LTS
 - Toolchain (e.g Zephyr SDK 0.10.0)
 - Commit SHA 373a42b861
 - nrf52840_pca10056 v0.9.0 or v0.10.0

**Comment by Qbicz** [comment] 2019-03-28 14:55
@nvlsianpu FYI

**Comment by Qbicz** [comment] 2019-03-28 15:05
I tried going back in history with bisect, but all old revisions resulted in the same problem. Toolchain issue? Tried on a few different kits.

**Comment by carlescufi** [comment] 2019-03-28 15:44
This sounds like it needs an `.inf` file. @masz-nordic?

**Comment by masz-nordic** [comment] 2019-03-28 15:50
No, this message appears when the device fails during enumeration.
I was actually unable to reproduce with Zephyr 373a42b and MCUBoot ebd0503 - device is enumerated properly.

**Comment by carlescufi** [comment] 2019-03-28 16:56
Setting prio as low since this impacts a single sample, not a single board.

**Comment by Qbicz** [comment] 2019-03-29 10:25
This issue occurs on PCA10056 preview DKs, version 0.9.0 and 0.10.0. These are engineering samples which are obsolete anyway.

On PCA10056 0.12.0 and 1.0.0 problem cannot be reproduced.

**Comment by carlescufi** [comment] 2019-03-29 11:11
Closing since this is a hardware problem

**Closed by carlescufi** 2019-03-29 11:11 UTC
Labels: area: USB, bug, platform: nRF, priority: low
