### ISSUE TITLE
net: socket: Add dependency to mbedtls

### ISSUE THREAD

**Issue by DenvE** [zephyrproject-rtos/zephyr#21837] opened 2020-01-10 18:55 UTC
Add dependency to MBEDTLS for NET_SOCKETS_SOCKOPT_TLS] 

Socket_tls.c is depending on mbedtls. If mbedtls is not configured, socket_tls gives
compile issues

**Comment by jukkar** [comment] 2020-01-12 12:10
Duplicate of #21768 so closing this.

**Closed by jukkar** 2020-01-12 12:10 UTC
Labels: area: Networking, bug, has-pr, priority: low
