### ISSUE TITLE
west spdx TypeError: 'NoneType' object is not iterable 

### ISSUE THREAD

**Issue by hellesvik-nordic** [zephyrproject-rtos/zephyr#44070] opened 2022-03-22 10:02 UTC
**Describe the bug**
I have tested this for both tag: v2.7.99-ncs1-1 and main. 

When using the command "west spdx", I get an error. Log is in pasted below.
After this error, build/spdx/app.spdx and build/spdx/zephyr.spdx are generated. BUILD_DIR/spdx/build.spdx is missing.

The following change seems to fix the issue, suggested to me by a colleague. However, I do not know if it is a good fix or not as I have little Zephyr developing experience.
```
diff --git a/scripts/west_commands/zspdx/writer.py b/scripts/west_commands/zspdx/writer.py
index f357acf180..7ffa9d1bac 100644                                                       
--- a/scripts/west_commands/zspdx/writer.py                                               
+++ b/scripts/west_commands/zspdx/writer.py                                               
@@ -125,7 +125,7 @@ Created: {datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")}           
                                                                                          
     # write other license info, if any                                                   
     if len(doc.customLicenseIDs) > 0:                                                    
-        for lic in list(doc.customLicenseIDs).sort():                                    
+        for lic in sorted(list(doc.customLicenseIDs)):                                   
             writeOtherLicenseSPDX(f, lic)
```

**To Reproduce**
Follow steps explained in https://docs.zephyrproject.org/latest/guides/west/zephyr-cmds.html.
Built for board nrf52840dk_nrf52840, sample zephyr/hello_world. I also tried other samples, which showed the same bug.

**Expected behavior**
It should not print the error message, and generate BUILD_DIR/spdx/build.spdx

**Impact**
Until I had the workaround, I were not able to generate complete Software bill of materials. 

**Logs and console output**
Log from issue:
```
/home/username/ncs/zephyr/samples/hello_world$ west spdx -d BUILD_DIR
parsing CMake Cache file
parsing CMake Codemodel files
setting up SPDX documents
walking through targets
walking through pending sources files
walking through pending relationships
scanning files in package app-sources in document app-sources
scanning files in package zephyr-sources in document zephyr-sources
scanning files in package ..__nrf__drivers__hw_cc310 in document build
scanning files in package ..__nrf__lib__fatal_error in document build
scanning files in package app in document build
scanning files in package app_subimage in document build
scanning files in package arch__arm__core__aarch32 in document build
scanning files in package arch__arm__core__aarch32__cortex_m in document build
scanning files in package arch__arm__core__aarch32__mpu in document build
scanning files in package arch__common in document build
scanning files in package asm in document build
scanning files in package attach in document build
scanning files in package bintools in document build
scanning files in package boards in document build
scanning files in package code_data_relocation_target in document build
scanning files in package compiler in document build
scanning files in package compiler-cpp in document build
scanning files in package config-twister in document build
scanning files in package debug in document build
scanning files in package debugserver in document build
scanning files in package devicetree_target in document build
scanning files in package driver_validation_h_target in document build
scanning files in package drivers__clock_control in document build
scanning files in package drivers__console in document build
scanning files in package drivers__gpio in document build
scanning files in package drivers__interrupt_controller in document build
WARNING: unable to get hashes for file {f.abspath}; skipping
scanning files in package drivers__serial in document build
scanning files in package drivers__timer in document build
scanning files in package flash in document build
scanning files in package footprint in document build
scanning files in package guiconfig in document build
scanning files in package hardenconfig in document build
scanning files in package isr_tables in document build
scanning files in package kernel in document build
scanning files in package kobj_types_h_target in document build
scanning files in package lib__libc__minimal in document build
scanning files in package lib__posix in document build
scanning files in package linker in document build
scanning files in package linker_zephyr_final_script_target in document build
scanning files in package linker_zephyr_pre0_script in document build
scanning files in package linker_zephyr_prebuilt_script_target in document build
scanning files in package menuconfig in document build
scanning files in package modules__hal_nordic__nrfx in document build
scanning files in package modules__segger in document build
scanning files in package offsets in document build
scanning files in package offsets_h in document build
scanning files in package parse_syscalls_target in document build
scanning files in package pristine in document build
scanning files in package ram_report in document build
scanning files in package rom_report in document build
scanning files in package run in document build
scanning files in package runners_yaml_props_target in document build
scanning files in package shields in document build
scanning files in package soc__arm__common__cortex_m in document build
scanning files in package soc__arm__nordic_nrf__nrf52 in document build
scanning files in package syscall_list_h_target in document build
scanning files in package usage in document build
scanning files in package zephyr in document build
scanning files in package zephyr_final in document build
scanning files in package zephyr_generated_headers in document build
scanning files in package zephyr_pre0 in document build
scanning files in package zephyr_pre1 in document build
scanning files in package zephyr_property_target in document build
Writing SPDX document app-sources to BUILD_DIR/spdx/app.spdx
Writing SPDX document zephyr-sources to BUILD_DIR/spdx/zephyr.spdx
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/username/.local/lib/python3.8/site-packages/west/__main__.py", line 3, in <module>
    main()
  File "/home/username/.local/lib/python3.8/site-packages/west/app/main.py", line 781, in main
    app.run(argv or sys.argv[1:])
  File "/home/username/.local/lib/python3.8/site-packages/west/app/main.py", line 106, in run
    self.run_command(argv)
  File "/home/username/.local/lib/python3.8/site-packages/west/app/main.py", line 338, in run_command
    self.run_extension(args.command, argv)
  File "/home/username/.local/lib/python3.8/site-packages/west/app/main.py", line 410, in run_extension
    command.run(args, unknown, self.topdir, manifest=self.manifest)
  File "/home/username/.local/lib/python3.8/site-packages/west/commands.py", line 140, in run
    self.do_run(args, unknown)
  File "/home/username/ncs/zephyr/scripts/west_commands/spdx.py", line 65, in do_run
    do_run_spdx(args)
  File "/home/username/ncs/zephyr/scripts/west_commands/spdx.py", line 114, in do_run_spdx
    makeSPDX(cfg)
  File "/home/username/ncs/zephyr/scripts/west_commands/zspdx/sbom.py", line 113, in makeSPDX
    writeSPDX(os.path.join(cfg.spdxDir, "zephyr.spdx"), w.docZephyr)
  File "/home/username/ncs/zephyr/scripts/west_commands/zspdx/writer.py", line 141, in writeSPDX
    writeDocumentSPDX(f, doc)
  File "/home/username/ncs/zephyr/scripts/west_commands/zspdx/writer.py", line 128, in writeDocumentSPDX
    for lic in list(doc.customLicenseIDs).sort():
TypeError: 'NoneType' object is not iterable
```

**Environment:**
 - OS: Ubuntu 20.04 LTS, Windows 10
 - Toolchain: Using Zephyr in the nRF Connect SDK.
 - v2.7.99-ncs1-1, main
 (only tested for Linux on main)

**Comment by mbolivar-nordic** [comment] 2022-03-22 15:03
Following offline discussion with @hellesvik-nordic , it looks like this doesn't reproduce upstream, so I'm going to close this one for now. @hellesvik-nordic -- please reopen if https://github.com/zephyrproject-rtos/zephyr/commit/e12d9385c6e7cc3a3b36e7f9e4190b2605cd874c doesn't fix it for you.

**Closed** 2022-03-22 15:03 UTC
Labels: bug

**Comment by rettichschnidi** [comment] 2022-07-06 09:40
Having the same error here, proposed fix helped. Do not understand (yet) the root cause.

**Comment by dkalowsk** [comment] 2022-09-28 18:44
@swinslow since Discord is pointing back towards you, figure I'll tag you here in the issue as well

**Comment by dkalowsk** [comment] 2022-09-29 21:32
Connecting the MR that applied said patch: https://github.com/zephyrproject-rtos/zephyr/pull/45815
