### ISSUE TITLE
Update canopennode to v2/master

### ISSUE THREAD

**Issue by tobiasjaster** [zephyrproject-rtos/zephyr#82481] opened 2024-12-03 11:22 UTC
The active development of canopennode has been on version 2 since 2020. New features and bugfixes are only rolled out there. An update to version 2 (better: the current master) updates compatibility with the current EDS tooling and fixes various issues

**Comment by henrikbrixandersen** [comment] 2024-12-04 10:00
Duplicate of #70285.

**Closed by henrikbrixandersen** 2024-12-04 10:00 UTC
Labels: Enhancement, area: CAN
