### ISSUE TITLE
Redundant flash shell commands

### ISSUE THREAD

**Issue by nordic-krch** [zephyrproject-rtos/zephyr#25055] opened 2020-05-07 05:31 UTC
**Describe the bug**
It's rather "bad impression" bug. `samples/drivers/flash_shell` implements commands to handle flash and there are already generic commands in `drivers/flash/flash_shell.c` which are not enabled in that example (because they overlap). It would be good to merge those two and clean up the example or even remove it and just enable flash commands in generic shell example.

**Comment by nordic-krch** [comment] 2020-05-07 05:32
@nvlsianpu fyi

**Comment by eugmes** [comment] 2020-09-29 12:03
It seems that something has changed since this issue was reported. Right now I see two entries for 'flash' when I run the `flash_shell` sample. `CONFIG_FLASH_SHELL` is enabled for that sample.

**Comment by erwango** [comment] 2022-11-30 15:06
Duplicate of https://github.com/zephyrproject-rtos/zephyr/issues/14260.
Closing this one as the other one is the most commented

**Closed by erwango** 2022-11-30 15:06 UTC
Labels: Enhancement, priority: low, area: Flash, area: Shell, Good first issue
