### ISSUE TITLE
TCP Connected Change the window size to 1/3/ff fail

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#47683] opened 2022-07-11 11:11 UTC
Describe the bug
This test changes the window size field in all TCP packets to 1. This test is intended to exercise boundary conditions on the window size field.	Assumes the DUT is sending a TCP data stream to a data sink. DUT must be able to complete transmission of its reply in under 60 seconds.	The DUT must throttle back its transmissions to only one-octet-long data segments.	

References

RFC 793: section 3.7
RFC 1122: section 4.2.2.16 {Robust against shrinking window}

Results

FAIL: tcp.v4 got fewer bytes than expected, which is not an expected result.

Environment (please complete the following information):

OS: (e.g. Linux )
Toolchain (e.g Zephyr SDK)
Commit SHA or Version used: Zephyr3.1.0-1882-gb161554ee8

**Comment by rlubos** [comment] 2022-07-12 13:10
Any chance for a Wireshark pcap from the test?

**Comment by hakehuang** [comment] 2022-07-13 03:51
[pcap_window_1.zip](https://github.com/zephyrproject-rtos/zephyr/files/9098754/pcap_window_1.zip)
I am using the qemu_x86 and with overlay-e1000.config, from target console there is 
eth_e1000: out of buffers error
looks like the changes on the window size will cause sides effects on buffer limited devices

**Comment by rlubos** [comment] 2022-07-14 15:09
@hakehuang @dleach02 I've identified a potential deadlock situation, in case both ends are transferring data. I'm not 100% certain that this is the reason of the test failure, but for sure I hit this problem where I've tested similar scenario on my side. I've opened a draft PR for now - please check the commit description for the details about the scenario where the deadlock can occur:
https://github.com/zephyrproject-rtos/zephyr/pull/47793
Could you give it a try and see if it helps with the regression?

Now, I saw 2 possible solutions to avoid the deadlock, none of them great really. I don't think it's possible to remove the mutex protection from the receive callback, due to https://github.com/zephyrproject-rtos/zephyr/pull/35466, it was added for a reason. What could be done to avoid the deadlock is:
1. Do not notify new data directly from the TCP RX thread, but rather defer it to the TCP work queue instead. This should prevent blocking of the TCP RX thread and thus allow to process consecutive TCP packets - i. e. incoming ACKs that would unblock the `send()` call.
2. Or simply unlock the socket mutex for the time `send()` call is idle, either waiting for buffer or for the TX window semaphore.

Now, I've decided to implement option 2, because:
1. There might be some other corner cases, where a blocked TCP work queue could be an issue,
2. Option 1 would affect every single incoming data packet, which could have a negative impact on the throughput.

Unlocking the mutex is not great either, as one could chip in with some other socket call in between, but overall given it's such a rare condition to hit the issue, I think it's a better option after all. 

Please let me know if the PR helps - or perhaps if you have a better idea on how to prevent the deadlock from happening.

**Comment by hakehuang** [comment] 2022-07-15 06:02
> #47793
> Could you give it a try and see if it helps with the regression?

this fix works for window size with 1/3/0xff, now the test can pass. @rlubos

**Closed** 2022-07-18 15:36 UTC
Labels: bug, priority: medium, area: Networking, Regression
