### ISSUE TITLE
tests: tests/subsys/shell/shell test case fail in daily test on many platforms

### ISSUE THREAD

**Issue by hunterhu3000** [zephyrproject-rtos/zephyr#50065] opened 2022-09-09 00:47 UTC
**Describe the bug**
tests/subsys/shell/shell test case fail in daily test on it8xxx2_evb, mec15xxevb_assy6853, mec172xevb_assy6906, intel_adsp_cavs* and etc.
including the following tests:
```
shell.core.shell.core.cmd_select
shell.core.shell.core.cmd_clear
shell.core.shell.core.shell_wildcards_dynamic
shell.core.shell.core.cmd_mand_1_opt_raw
shell.core.shell.core.mand_2_opt_raw
shell.core.shell.core.set_root_cmd
shell.core.shell.core.cmd_history
shell.core.shell.core.shell_module
shell.core.shell.core.cmd_shell
shell.core.shell.core.max_argc
shell.core.shell.core.cmd_dict
shell.core.shell.core.section_cmd
shell.core.shell.core.shell_fprintf
shell.core.shell.core.shell_wildcards_static
shell.core.shell.core.cmd_resize
shell.core.shell.core.cmd_help
```

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? it8xxx2_evb, mec15xxevb_assy6853, mec172xevb_assy6906, intel_adsp_cavs* and etc.
 - Is this a regression? Yes
   specific commit? 491f4dd7

**To Reproduce**
1. twister -p it8xxx2_evb --device-testing --west-flash="../../itetool/loader.sh" --device-serial=/dev/ttyUSB0 -T tests/subsys/shell/shell -vv
2. west build -p always -b it8xxx2_evb tests/subsys/shell/shell 

**Expected behavior**
The tests should pass

**Impact**
16 test cases fail in daily test under tests/subsys/shell/shell

**Logs and console output**
```
DEBUG   - DEVICE: *** Booting Zephyr OS build zephyr-v3.1.0-4834-g491f4dd701b0  (delayed boot 1ms) ***
DEBUG   - DEVICE: Running TESTSUITE shell
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_cmd_clear
DEBUG   - DEVICE: shell_execute_cmd(clear): 0
DEBUG   - DEVICE: shell_execute_cmd(clear -h): 1
DEBUG   - DEVICE: shell_execute_cmd(clear --help): 1
DEBUG   - DEVICE: shell_execute_cmd(clear dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(clear dummy dummy): -22
DEBUG   - DEVICE: PASS - test_cmd_clear in 0.024 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_cmd_dict
DEBUG   - DEVICE: shell_execute_cmd(dict1 one): 1
DEBUG   - DEVICE: shell_execute_cmd(dict1 two): 2
DEBUG   - DEVICE: shell_execute_cmd(dict2 one): 2
DEBUG   - DEVICE: shell_execute_cmd(dict2 two): 4
DEBUG   - DEVICE: PASS - test_cmd_dict in 0.015 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_cmd_history
DEBUG   - DEVICE: shell_execute_cmd(history): 0
DEBUG   - DEVICE: shell_execute_cmd(history -h): 1
DEBUG   - DEVICE: shell_execute_cmd(history --help): 1
DEBUG   - DEVICE: shell_execute_cmd(history dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(history dummy dummy): -22
DEBUG   - DEVICE: PASS - test_cmd_history in 0.026 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_cmd_mand_1_opt_raw
DEBUG   - DEVICE: shell_execute_cmd(cmd_mand_1_opt_raw aaa "" bbb): 0
DEBUG   - DEVICE: shell_execute_cmd(cmd_mand_1_opt_raw): 0
DEBUG   - DEVICE: shell_execute_cmd(select cmd_mand_1_opt_raw): 0
DEBUG   - DEVICE: shell_execute_cmd(aaa "" bbb): 0
DEBUG   - DEVICE: PASS - test_cmd_mand_1_opt_raw in 0.018 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_cmd_resize
DEBUG   - DEVICE: shell_execute_cmd(resize -h): 1
DEBUG   - DEVICE: shell_execute_cmd(resize --help): 1
DEBUG   - DEVICE: shell_execute_cmd(resize dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(resize dummy dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(resize default): 0
DEBUG   - DEVICE: shell_execute_cmd(resize default -h): 1
DEBUG   - DEVICE: shell_execute_cmd(resize default --help): 1
DEBUG   - DEVICE: shell_execute_cmd(resize default dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(resize default dummy dummy): -22
DEBUG   - DEVICE: PASS - test_cmd_resize in 0.061 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_cmd_select
DEBUG   - DEVICE: shell_execute_cmd(select -h): 1
DEBUG   - DEVICE: shell_execute_cmd(select clear): -22
DEBUG   - DEVICE: shell_execute_cmd(off): -8
DEBUG   - DEVICE: shell_execute_cmd(on): -8
DEBUG   - DEVICE: shell_execute_cmd(select shell colors): 0
DEBUG   - DEVICE: shell_execute_cmd(off): 0
DEBUG   - DEVICE: shell_execute_cmd(on): 0
DEBUG   - DEVICE: shell_execute_cmd(off): -8
DEBUG   - DEVICE: shell_execute_cmd(on): -8
DEBUG   - DEVICE: PASS - test_cmd_select in 0.038 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_cmd_shell
DEBUG   - DEVICE: shell_execute_cmd(shell -h): 1
DEBUG   - DEVICE: shell_execute_cmd(shell --help): 1
DEBUG   - DEVICE: shell_execute_cmd(shell dummy): 1
DEBUG   - DEVICE: shell_execute_cmd(shell dummy dummy): 1
DEBUG   - DEVICE: shell_execute_cmd(shell backspace_mode -h): 1
DEBUG   - DEVICE: shell_execute_cmd(shell backspace_mode --help): 1
DEBUG   - DEVICE: shell_execute_cmd(shell backspace_mode dummy): 1
DEBUG   - DEVICE: shell_execute_cmd(shell backspace_mode backspace): 0
DEBUG   - DEVICE: shell_execute_cmd(shell backspace_mode backspace -h): 1
DEBUG   - DEVICE: shell_execute_cmd(shell backspace_mode backspace --help): 1
DEBUG   - DEVICE: shell_execute_cmd(shell backspace_mode backspace dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(shell backspace_mode backspace dummy dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(shell backspace_mode delete): 0
DEBUG   - DEVICE: shell_execute_cmd(shell backspace_mode delete -h): 1
DEBUG   - DEVICE: shell_execute_cmd(shell backspace_mode delete --help): 1
DEBUG   - DEVICE: shell_execute_cmd(shell backspace_mode delete dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(shell backspace_mode delete dummy dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(shell colors -h): 1
DEBUG   - DEVICE: shell_execute_cmd(shell colors --help): 1
DEBUG   - DEVICE: shell_execute_cmd(shell colors dummy): 1
DEBUG   - DEVICE: shell_execute_cmd(shell colors dummy dummy): 1
DEBUG   - DEVICE: shell_execute_cmd(shell colors off): 0
DEBUG   - DEVICE: shell_execute_cmd(shell colors off -h): 1
DEBUG   - DEVICE: shell_execute_cmd(shell colors off --help): 1
DEBUG   - DEVICE: shell_execute_cmd(shell colors off dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(shell colors off dummy dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(shell colors on): 0
DEBUG   - DEVICE: shell_execute_cmd(shell colors on -h): 1
DEBUG   - DEVICE: shell_execute_cmd(shell colors on --help): 1
DEBUG   - DEVICE: shell_execute_cmd(shell colors on dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(shell colors on dummy dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(shell echo): 0
DEBUG   - DEVICE: shell_execute_cmd(shell echo -h): 1
DEBUG   - DEVICE: shell_execute_cmd(shell echo --help): 1
DEBUG   - DEVICE: shell_execute_cmd(shell echo dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(shell echo dummy dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(shell echo off): 0
DEBUG   - DEVICE: shell_execute_cmd(shell echo off -h): 1
DEBUG   - DEVICE: shell_execute_cmd(shell echo off --help): 1
DEBUG   - DEVICE: shell_execute_cmd(shell echo off dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(shell echo off dummy dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(shell echo on): 0
DEBUG   - DEVICE: shell_execute_cmd(shell echo on -h): 1
DEBUG   - DEVICE: shell_execute_cmd(shell echo on --help): 1
DEBUG   - DEVICE: shell_execute_cmd(shell echo on dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(shell echo on dummy dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(shell stats): 1
DEBUG   - DEVICE: shell_execute_cmd(shell stats -h): 1
DEBUG   - DEVICE: shell_execute_cmd(shell stats --help): 1
DEBUG   - DEVICE: shell_execute_cmd(shell stats dummy): 1
DEBUG   - DEVICE: shell_execute_cmd(shell stats dummy dummy): 1
DEBUG   - DEVICE: shell_execute_cmd(shell stats reset): 0
DEBUG   - DEVICE: shell_execute_cmd(shell stats reset -h): 1
DEBUG   - DEVICE: shell_execute_cmd(shell stats reset --help): 1
DEBUG   - DEVICE: shell_execute_cmd(shell stats reset dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(shell stats reset dummy dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(shell stats show): 0
DEBUG   - DEVICE: shell_execute_cmd(shell stats show -h): 1
DEBUG   - DEVICE: shell_execute_cmd(shell stats show --help): 1
DEBUG   - DEVICE: shell_execute_cmd(shell stats show dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(shell stats show dummy dummy): -22
DEBUG   - DEVICE: PASS - test_cmd_shell in 0.456 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_mand_2_opt_raw
DEBUG   - DEVICE: shell_execute_cmd(cmd_mand_2_opt_raw): -22
DEBUG   - DEVICE: shell_execute_cmd(cmd_mand_2_opt_raw mandatory): 0
DEBUG   - DEVICE: shell_execute_cmd(cmd_mand_2_opt_raw mandatory aaa "" bbb): 0
DEBUG   - DEVICE: shell_execute_cmd(select cmd_mand_2_opt_raw): 0
DEBUG   - DEVICE: shell_execute_cmd(): -8
DEBUG   - DEVICE: shell_execute_cmd(mandatory): 0
DEBUG   - DEVICE: shell_execute_cmd(mandatory aaa "" bbb): 0
DEBUG   - DEVICE: PASS - test_mand_2_opt_raw in 0.034 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_max_argc
DEBUG   - DEVICE: shell_execute_cmd(dummy 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19): 0
DEBUG   - DEVICE: shell_execute_cmd(dummy 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20): -8
DEBUG   - DEVICE: PASS - test_max_argc in 0.018 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_section_cmd
DEBUG   - DEVICE: shell_execute_cmd(section_cmd): 1
DEBUG   - DEVICE: shell_execute_cmd(section_cmd cmd1): 10
DEBUG   - DEVICE: shell_execute_cmd(section_cmd cmd2): 20
DEBUG   - DEVICE: shell_execute_cmd(section_cmd cmd1 sub_cmd1): 11
DEBUG   - DEVICE: shell_execute_cmd(section_cmd cmd1 sub_cmd2): -22
DEBUG   - DEVICE: PASS - test_section_cmd in 0.031 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_set_root_cmd
DEBUG   - DEVICE: shell_execute_cmd(shell colors on): 0
DEBUG   - DEVICE: shell_execute_cmd(shell colors): 1
DEBUG   - DEVICE: shell_execute_cmd(colors on): 0
DEBUG   - DEVICE: shell_execute_cmd(colors): -8
DEBUG   - DEVICE: shell_execute_cmd(shell colors on): 0
DEBUG   - DEVICE: PASS - test_set_root_cmd in 0.031 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_shell_fprintf
DEBUG   - DEVICE:
DEBUG   - DEVICE: Assertion failed at WEST_TOPDIR/zephyr/tests/subsys/shell/shell/src/main.c:336: shell_test_shell_fprintf: (size >= sizeof(expect) is false)
DEBUG   - DEVICE: Expected size > 14, got 0
DEBUG   - DEVICE: FAIL - test_shell_fprintf in 0.016 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_shell_module
DEBUG   - DEVICE: shell_execute_cmd(test_shell_cmd): 0
DEBUG   - DEVICE: shell_execute_cmd(test_shell_cmd -h): 1
DEBUG   - DEVICE: shell_execute_cmd(test_shell_cmd --help): 1
DEBUG   - DEVICE: shell_execute_cmd(test_shell_cmd dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(test_shell_cmd dummy dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(): -8
DEBUG   - DEVICE: shell_execute_cmd(not existing command): -8
DEBUG   - DEVICE: PASS - test_shell_module in 0.037 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_shell_wildcards_dynamic
DEBUG   - DEVICE: shell_execute_cmd(test_dynamic): 0
DEBUG   - DEVICE: shell_execute_cmd(test_dynamic d*): 1
DEBUG   - DEVICE: shell_execute_cmd(test_dynamic c*): 1
DEBUG   - DEVICE: shell_execute_cmd(test_dynamic d* c*): 2
DEBUG   - DEVICE: PASS - test_shell_wildcards_dynamic in 0.018 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_shell_wildcards_static
DEBUG   - DEVICE: shell_execute_cmd(test_wildcard): 0
DEBUG   - DEVICE: shell_execute_cmd(test_wildcard argument_1): 1
DEBUG   - DEVICE: shell_execute_cmd(test_wildcard argument?1): 1
DEBUG   - -- west flash: using runner misc-flasher
/home/ztest/zephyrproject/zephyr/twister-out/it8xxx2_evb/tests/subsys/shell/shell/shell.core
/home/ztest/itetool/ite /home/ztest/zephyrproject/zephyr/twister-out/it8xxx2_evb/tests/subsys/shell/shell/shell.core/zephyr/zephyr.bin

DEBUG   - DEVICE: shell_execute_cmd(test_wildcard argu?ent?1): 1
DEBUG   - DEVICE: shell_execute_cmd(test_wildcard a*1): 1
DEBUG   - DEVICE: shell_execute_cmd(test_wildcard ar?u*1): 1
DEBUG   - DEVICE: shell_execute_cmd(test_wildcard *): 3
DEBUG   - DEVICE: shell_execute_cmd(test_wildcard a*): 2
DEBUG   - DEVICE: PASS - test_shell_wildcards_static in 0.038 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: TESTSUITE shell failed.
DEBUG   - DEVICE: Running TESTSUITE shell_1cpu
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_cmd_help
DEBUG   - DEVICE: shell_execute_cmd(help): 0
DEBUG   - DEVICE: shell_execute_cmd(help -h): 1
DEBUG   - DEVICE: shell_execute_cmd(help --help): 1
DEBUG   - DEVICE: shell_execute_cmd(help dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(help dummy dummy): -22
DEBUG   - DEVICE: PASS - test_cmd_help in 0.051 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: TESTSUITE shell_1cpu succeeded
DEBUG   - DEVICE:
DEBUG   - DEVICE: ------ TESTSUITE SUMMARY START ------
DEBUG   - DEVICE:
DEBUG   - DEVICE: SUITE FAIL -  93.33% [shell]: pass = 14, fail = 1, skip = 0, total = 15 duration = 0.861 seconds
DEBUG   - DEVICE: - PASS - [shell.test_cmd_clear] duration = 0.024 seconds
DEBUG   - DEVICE: - PASS - [shell.test_cmd_dict] duration = 0.015 seconds
DEBUG   - DEVICE: - PASS - [shell.test_cmd_history] duration = 0.026 seconds
DEBUG   - DEVICE: - PASS - [shell.test_cmd_mand_1_opt_raw] duration = 0.018 seconds
DEBUG   - DEVICE: - PASS - [shell.test_cmd_resize] duration = 0.061 seconds
DEBUG   - DEVICE: - PASS - [shell.test_cmd_select] duration = 0.038 seconds
DEBUG   - DEVICE: - PASS - [shell.test_cmd_shell] duration = 0.456 seconds
DEBUG   - DEVICE: - PASS - [shell.test_mand_2_opt_raw] duration = 0.034 seconds
DEBUG   - DEVICE: - PASS - [shell.test_max_argc] duration = 0.018 seconds
DEBUG   - DEVICE: - PASS - [shell.test_section_cmd] duration = 0.031 seconds
DEBUG   - DEVICE: - PASS - [shell.test_set_root_cmd] duration = 0.031 seconds
DEBUG   - DEVICE: - FAIL - [shell.test_shell_fprintf] duration = 0.016 seconds
DEBUG   - DEVICE: - PASS - [shell.test_shell_module] duration = 0.037 seconds
DEBUG   - DEVICE: - PASS - [shell.test_shell_wildcards_dynamic] duration = 0.018 seconds
DEBUG   - DEVICE: - PASS - [shell.test_shell_wildcards_static] duration = 0.038 seconds
DEBUG   - DEVICE:
DEBUG   - DEVICE: SUITE PASS - 100.00% [shell_1cpu]: pass = 1, fail = 0, skip = 0, total = 1 duration = 0.051 seconds
DEBUG   - DEVICE: - PASS - [shell_1cpu.test_cmd_help] duration = 0.051 seconds
DEBUG   - DEVICE:
DEBUG   - DEVICE: ------ TESTSUITE SUMMARY END ------
DEBUG   - DEVICE:
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: RunID: 0ce9bdcbd2453c3b0b166b957bb213e8
DEBUG   - DEVICE: PROJECT EXECUTION FAILED
DEBUG   - run status: it8xxx2_evb/tests/subsys/shell/shell/shell.core failed
INFO    - 15/15 it8xxx2_evb               tests/subsys/shell/shell/shell.core                FAILED Failed (device 10.585s)
ERROR   - see: /home/ztest/zephyrproject/zephyr/twister-out/it8xxx2_evb/tests/subsys/shell/shell/shell.core/handler.log
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows) Ubuntu20.04
 - Toolchain (e.g Zephyr SDK, ...) 0.15.0
 - Commit SHA or Version used 491f4dd7

**Comment by hunterhu3000** [comment] 2022-09-09 03:14
@jakub-uC Could you please help to check this problem? Probably caused by the following commit. Thanks

commit 491f4dd701b043639b2ab680353249c8e151d2ca
Author: Jakub Rzeszutko <jakub.rzeszutko@nordicsemi.no>
Date:   Tue Sep 6 09:50:52 2022 +0200

    shell: update shell tests
    
    Replace hard fixed delay with function shell_ready to wait
    for shell readiness.
    
    Signed-off-by: Jakub Rzeszutko <jakub.rzeszutko@nordicsemi.no>

**Comment by jakub-uC** [comment] 2022-09-09 05:09
@hunterhu3000 
This issue is already investigated. It seems that the problem is with the `WAIT_FOR` macro that needs to be fixed:

https://github.com/zephyrproject-rtos/zephyr/pull/50058#pullrequestreview-1101349518

**Comment by henrikbrixandersen** [comment] 2022-09-09 08:47
Duplicate of #50066 (which is a duplicate of #50032).

**Closed by henrikbrixandersen** 2022-09-09 08:47 UTC
Labels: bug, platform: Microchip MEC, platform: ITE
