### ISSUE TITLE
(BLE) Dynamic TX Power Control

### ISSUE THREAD

**Issue by Trubochkin** [zephyrproject-rtos/zephyr#18923] opened 2019-09-05 08:44 UTC
**Is your feature request related to a problem? Please describe.**
I could not find anywhere how to dynamically change the TX power of the bluetooth transmitter. I found only static definitions that are set in the configuration file:
`CONFIG_BT_CTLR_TX_PWR_PLUS_8`
`CONFIG_BT_CTLR_TX_PWR_PLUS_7`
`CONFIG_BT_CTLR_TX_PWR_PLUS_6`
`CONFIG_BT_CTLR_TX_PWR_PLUS_5`
`CONFIG_BT_CTLR_TX_PWR_PLUS_4`
`CONFIG_BT_CTLR_TX_PWR_PLUS_3`
`CONFIG_BT_CTLR_TX_PWR_PLUS_2`
`CONFIG_BT_CTLR_TX_PWR_0`
`CONFIG_BT_CTLR_TX_PWR_MINUS_4`
`CONFIG_BT_CTLR_TX_PWR_MINUS_8`
`CONFIG_BT_CTLR_TX_PWR_MINUS_12`
`CONFIG_BT_CTLR_TX_PWR_MINUS_16`
`CONFIG_BT_CTLR_TX_PWR_MINUS_20`
`CONFIG_BT_CTLR_TX_PWR_MINUS_40`

**Describe the solution you'd like**
I would like to change the transmitter power in my code (dynamically). If there is such an opportunity, can someone tell me how to do this? I would be grateful for your help.

**Comment by aescolar** [comment] 2019-09-05 09:19
Closing as duplicate of #17731

**Closed by aescolar** 2019-09-05 09:19 UTC
Labels: area: Bluetooth, question
