### ISSUE TITLE
reel_board:running tests/kernel/workq/work_queue_api/ failed

### ISSUE THREAD

**Issue by Zhaoningx** [zephyrproject-rtos/zephyr#29534] opened 2020-10-26 02:27 UTC
Describe the bug
running tests/kernel/workq/work_queue_api/ failed due to the condition is not our expected(assert failed)

To Reproduce
sanitycheck -p reel_board --device-testing --device-serial /dev/ttyACM0 -T  tests/kernel/workq/work_queue_api/ -vv
west flash
see error

*** Booting Zephyr OS build zephyr-v2.4.0-983-g3c79b565fe7e ***
DEBUG   - DEVICE: START - test_user_workq_granted_access
DEBUG   - DEVICE: PASS - test_user_workq_granted_access
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_work_submit_to_multipleq
DEBUG   - DEVICE: 
DEBUG   - DEVICE: Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/workq/work_queue_api/src/main.c:277: twork_submit_multipleq: k_delayed_work_pending(&new_work) is false
DEBUG   - DEVICE: 
DEBUG   - DEVICE: FAIL - test_work_submit_to_multipleq
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_work_resubmit_to_queue
DEBUG   - DEVICE: PASS - test_work_resubmit_to_queue
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_work_resubmit_nowait_to_queue
DEBUG   - DEVICE: PASS - test_work_resubmit_nowait_to_queue

Environment (please complete the following information):
OS: Fedora28
Toolchain: Zephyr-sdk-0.11.3
Commit ID: g3c79b565fe7e

**Comment by pabigot** [comment] 2020-10-26 10:53
Duplicate of #29329

**Closed by pabigot** 2020-10-26 10:53 UTC
Labels: area: Kernel, bug
