### ISSUE TITLE
tests/net/ieee802154/crypto fails with assertion failure in subsys/net/ip/net_if.c

### ISSUE THREAD

**Issue by arun1joshi** [zephyrproject-rtos/zephyr#14247] opened 2019-03-11 06:31 UTC
tests/net/ieee802154/crypto fails with assertion failure in subsys/net/ip/net_if.c:241
Note: seems like we get kernel panic before the test case starts and looks similar to #10657 

The test is failing in this commit: [7967829]

Arch: x86
Platforms: quark_se_c1000_devboard

Error on console log:
```
ASSERTION FAIL [api && api->init] @ /home/joshiaru/zephyr.git/subsys/net/ip/net_if.c:241
***** Kernel Panic! *****
Current thread ID = 0xa80081e0
eax: 0x4004d621, ebx: 0x00000000, ecx: 0x00000000, edx: 0x000000f1
esi: 0xa800da40, edi: 0x00000000, ebp: 0xa800c4e0, esp: 0xa800c4dc
eflags: 0x00000286 cs: 0x0008
eip: 0x40031966

**Comment by jukkar** [comment] 2019-03-11 09:23
Duplicate of #10657

**Closed by jukkar** 2019-03-11 09:23 UTC
Labels: area: Networking, bug
