### ISSUE TITLE
samples/tfm_integration/tfm_ipc/sample.tfm_ipc build failure on multiple patforms

### ISSUE THREAD

**Issue by fabiobaltieri** [zephyrproject-rtos/zephyr#61503] opened 2023-08-15 12:43 UTC
**Describe the bug**

Hi, spotted few build errors in the weekly run for the tfm samples:

https://github.com/zephyrproject-rtos/zephyr/runs/15850879425

```
/__w/zephyr/modules/tee/tf-m/trusted-firmware-m/bl2/src/shared_data.c:167:5: error: conflicting types for 'boot_save_shared_data'; have 'int(const struct image_header *, const struct flash_area *)'
  167 | int boot_save_shared_data(const struct image_header *hdr,
      |     ^~~~~~~~~~~~~~~~~~~~~
In file included from /__w/zephyr/modules/tee/tf-m/trusted-firmware-m/bl2/src/shared_data.c:8:
/__w/zephyr/bootloader/mcuboot/boot/bootutil/include/bootutil/boot_record.h:79:5: note: previous declaration of 'boot_save_shared_data' with type 'int(const struct image_header *, const struct flash_area *, const uint8_t,  const int)' {aka 'int(const struct image_header *, const struct flash_area *, const unsigned char,  const int)'}
   79 | int boot_save_shared_data(const struct image_header *hdr,
      |     ^~~~~~~~~~~~~~~~~~~~~
```

(and a bunch of other warnings)

Could you look into this?

Thanks!

**To Reproduce**
`west build -p -b b_u585i_iot02a_ns -T samples/tfm_integration/tfm_ipc/sample.tfm_ipc`

**Expected behavior**
Build, no warnings.

**Impact**
CI breakage.

**Comment by nordicjm** [comment] 2023-09-01 09:30
Duplicate of #61953

**Closed by nordicjm** 2023-09-01 09:30 UTC
Labels: bug, priority: medium, area: Samples, area: TF-M
