### ISSUE TITLE
west flash ignores --bin-file parameter and uses hex file when nrfjprog is used internally

### ISSUE THREAD

**Issue by caco3** [zephyrproject-rtos/zephyr#27353] opened 2020-08-03 14:07 UTC
**Describe the bug**
I tried to follow the example https://docs.zephyrproject.org/latest/samples/subsys/mgmt/mcumgr/smp_svr/README.html#flashing-the-sample-image for a `nrf52840dongle_nrf52840` and a SEGGER J-Link.

**To Reproduce**
1. Build a sample
1. Try to flash it with providing the bin file, eg. `west flash --bin-file build/zephyr/zephyr.signed.bin`

**Expected behavior**
The **signed** (bin) image gets written into slot 0

**Impact**
The **unsigned** (hex) image gets written to slot 0

**Logs and console output**
```
west -v flash --bin-file build/zephyr/zephyr.signed.bin 
ZEPHYR_BASE=/home/<user>/zephyrproject/zephyr (origin: configfile)
-- west flash: rebuilding
cmake version 3.16.3 is OK; minimum version is 3.13.1
Running CMake: /usr/bin/cmake --build /home/<user>/zephyrproject/build --target west_flash_depends
[0/1] cd /home/<user>/zephyrproject/build/zephyr/cmake/flash && /usr/bin/cmake -E echo

-- west flash: using runner nrfjprog
runners.nrfjprog: nrfjprog --ids
-- runners.nrfjprog: Flashing file: /home/<user>/zephyrproject/build/zephyr/zephyr.hex
runners.nrfjprog: nrfjprog --program /home/<user>/zephyrproject/build/zephyr/zephyr.hex -f NRF52 --snr 50117086 --sectoranduicrerase
Parsing hex file.
Erasing page at address 0x12000.
[..]
Erasing page at address 0x3F000.
Applying system reset.
Checking that the area to write is not protected.
Programming device.
runners.nrfjprog: nrfjprog --pinresetenable -f NRF52 --snr 50117086
Enabling pin reset.
runners.nrfjprog: nrfjprog --pinreset -f NRF52 --snr 50117086
Applying pin reset.
-- runners.nrfjprog: Board with serial number 50117086 flashed successfully.
```
`nrfjprog` seems not to support `bin` files, at least the documentation only indicates support for `hex` files.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Toolchain: zephyr-sdk-0.11.3
 - Commit SHA or Version used: 2.3.99 (zephyr-v2.3.0-1533-gdc48999ee163)

**Additional context**

Calling `nrfjprog` directly with the signed hex image works fine:
```
nrfjprog --program /home/<user>/zephyrproject/build/zephyr/zephyr.signed.hex -f NRF52 --snr 50117086 --sectoranduicrerase
Parsing hex file.
Erasing page at address 0x12000.
[..]
Erasing page at address 0x3F000.
Applying system reset.
Checking that the area to write is not protected.
Programming device.
```

**Comment by mbolivar-nordic** [comment] 2020-09-08 17:40
The signed application is now flashable by default since 003d30b6f028705e7eefe7cec29669da1594d6c7 was merged.

Please see updated west sign documentation for an example workflow:

https://docs.zephyrproject.org/latest/guides/west/sign.html#mcuboot-imgtool

The `--bin-file` behavior described in the issue report is a not a bug. This is how the tool is documented to behave. In particular, `west flash -h` says:

````
Not all runners respect --elf-file / --hex-file / --bin-file
````

**Closed by mbolivar-nordic** 2020-09-08 17:40 UTC
Labels: area: Flashing, bug, priority: low
