### ISSUE TITLE
[bluetooth][PTS] Getting Connection failed to be established ocasionally

### ISSUE THREAD

**Issue by MariuszSkamra** [zephyrproject-rtos/zephyr#10146] opened 2018-09-21 12:26 UTC
Trying to connect to PTS, Im getting connection failed to be established occasionally. 

Reproducible 2/10
TestCase: GATT/CL/GAD/BV-03-C
IUT: Zephyr, nRF52840PDK

Reproduce with bt shell:
> connect 00:1b:dc:08:e6:83 (public)
> gatt-discover-include
> disconnect

Procedure repeats few times

**Comment by MariuszSkamra** [comment] 2018-09-21 12:28
[conn_failed_to_be_estab_filtered.zip](https://github.com/zephyrproject-rtos/zephyr/files/2405298/conn_failed_to_be_estab_filtered.zip)

**Comment by joerchan** [comment] 2018-10-03 07:53
The sniffer trace that has been uploaded does not show a connection that disconnected with that error code, but there is a hole in the sniffer trace , so it might be that the sniffer missed it. Can we get a new sniffer trace?

Also could you provide some more information to help me reproduce the issue?

- Which device is central.
- which device is peripheral.
- a specific commit
- Any special configuration

So far I haven't been able to reproduce the frequency of connection failed that you describe. But in a noisy environment this behaviour is expected. A CRC error on the connect request could be the cause.

**Comment by galak** [comment] 2018-12-13 16:41
@MariuszSkamra Are you still seeing this with recent runs of PTS?

**Comment by cvinayak** [comment] 2019-03-14 10:24
we should close this, as there has been no follow up on reproducing it since Sept 21 and I have run conformance tests as part of v1.14.0-rc1 testing that passes all conformance tests.

**Comment by carlescufi** [comment] 2019-03-14 14:39
Closing as non-applicable anymore.

**Closed by carlescufi** 2019-03-14 14:39 UTC
Labels: area: Bluetooth, bug, priority: medium
