### ISSUE TITLE
sanitycheck doesn't work on Windows (mkfifo not supported)

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/zephyr#5718] opened 2018-01-17 21:03 UTC
The instructions to invoke ``sanitycheck`` (in CONTRIBUTING) are Linux-specific.  Running ``python .\scripts\sanitycheck`` (as a workaround), produces errors such as "AttributeError: module 'os' has no attribute 'mkfifo'"  (mkfifo is not available on Windows)

**Comment by carlescufi** [comment] 2018-03-14 15:39
duplicate of #2664

**Closed** 2018-03-14 15:39 UTC
Labels: bug, priority: low
