### ISSUE TITLE
bluetooth: Resume peripheral's advertising after disconnection when using new bt_le_ext_adv_* API

### ISSUE THREAD

**Issue by lukasbrchl** [zephyrproject-rtos/zephyr#31086] opened 2021-01-04 08:38 UTC
Hello,
There was a feature in Bluetooth legacy API `bt_le_adv_*` that when advertising connectable advertisements and central connects to peripheral, the advertisements get paused. When central disconnects, the advertisements get again resumed. This was a convenient feature because one doesn't need to rely on the disconnect callback to resume the advertisements manually.

However, in the new Bluetooth API `bt_le_ext_adv_*`, the functionality for resuming the advertisements is not implemented. There is an option `BT_LE_ADV_OPT_ONE_TIME `which indicates "If Advertising directed or the advertiser was started with bt_le_ext_adv_start then this behavior is the default behavior and this flag has no effect.". I would suggest disabling this default behavior or add an option that will allow automatically to resume while using `bt_le_ext_adv_* `

What are your thoughts about this?

**Comment by joerchan** [comment] 2021-01-11 08:47
@lukasbrchl Thank you, this looks to me like a duplicate of https://github.com/zephyrproject-rtos/zephyr/issues/30699, so I'll close this issue in favour of that.

**Closed by joerchan** 2021-01-11 08:47 UTC
Labels: Enhancement, area: Bluetooth, area: Bluetooth Host
