### ISSUE TITLE
Meta-IRQ documentation references

### ISSUE THREAD

**Issue by shuegr-personal** [zephyrproject-rtos/zephyr#26941] opened 2020-07-17 19:47 UTC
Extend the Thread Priorities and Interrupts documentation to at least mention and reference meta-IRQs related to preemption priorities in the system.

**Comment by shuegr-personal** [comment] 2020-07-17 19:48
In a private email prompting this issue, @carlescufi requested this be assigned to @andyross.

**Comment by nashif** [comment] 2020-08-14 15:48
duplicate of #21648

**Closed by nashif** 2020-08-14 15:48 UTC
Labels: Enhancement, area: Documentation
