### ISSUE TITLE
up_squared and ehl_crb: test fails from timeout in application_development.cpp.libcxx.exceptions

### ISSUE THREAD

**Issue by yerabolu** [zephyrproject-rtos/zephyr#34503] opened 2021-04-22 23:32 UTC
**Describe the bug**
tests/application_development/libcxx/application_development.cpp.libcxx.exceptions Failed Timeout.
and test also fails on Upsquare board.

**To Reproduce**
1. twister -W -p ehl_crb --device-testing --device-serial /dev/ttyUSB0 -T  tests/application_development/libcxx/ --west-flash="/home/ztest/EHL_X86_PXE.sh" -j 1
2. device timeout error in device.log

**Expected behavior**
Test is expected to Pass 

**Logs and console output**
```  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M100   100    0   100    0     0   1851      0 --:--:-- --:--:-- --:--:--  1851
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M100   100    0   100    0     0   1886      0 --:--:-- --:--:-- --:--:--  1886
```

**Environment (please complete the following information):**
 - OS: Fedora 29
 - Toolchain: SDK 12.4
 - Commit SHA e1a6820e4c470ad5693eef469a0f4b61f868d8ec

**Comment by galak** [comment] 2021-04-27 14:17
The output looks like an issue with flashing the test and not the test itself.

**Comment by nashif** [comment] 2021-04-28 13:06
duplicate of #32448

**Closed by nashif** 2021-04-28 13:06 UTC
Labels: area: C++, bug, priority: low
