### ISSUE TITLE
tests/kernel/threads/no-multithreading/testcase.yam: Not Booting

### ISSUE THREAD

**Issue by chiachuanwu** [zephyrproject-rtos/zephyr#14462] opened 2019-03-13 08:51 UTC
**Describe the bug**
Failed to boot up on altera_max10 board

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=altera_max10
3. make
4. make run

**Expected behavior**
Should able to boot zephyr and show log on console output.

**Screenshots or console output**
no console output.

OS: fedora29
Toolchain: zephyr
Commit SHA or Version used: 6368ed4

**Comment by rljordan** [comment] 2019-03-15 00:30
@ramakrishnapallala  Do you have the hardware to test this?

**Comment by rljordan** [comment] 2019-03-15 00:30
@ramakrishnapallala  You can use the internal pool for this.

**Comment by ramakrishnapallala** [comment] 2019-03-19 05:09
I see that test works:

***** Booting Zephyr OS v1.7.99-16394-g3a8767c1f269 *****
It works
===================================================================
PROJECT EXECUTION SUCCESSFUL
===================================================================
PROJECT EXECUTION SUCCESSFUL

Here are the steps I followed:

mkdir build; cd build
cmake -DBOARD=altera_max10 ..
make flash

Check the logs on the serial console.

**Comment by ManojSubbarao** [comment] 2019-03-21 04:50
@chiachuanwu can you close if this is not an issue anymore?

**Comment by chiachuanwu** [comment] 2019-03-21 06:33
hi @ManojSubbarao  , this issued might be similar with #14454.

**Comment by ManojSubbarao** [comment] 2019-03-21 06:37
Thanks @chiachuanwu . Closing this issue since it's duplicate of #14454

**Closed by ManojSubbarao** 2019-03-21 06:37 UTC
Labels: area: NIOS2, bug, priority: medium
