### ISSUE TITLE
Bluetooth: bt_conn_foreach() reports unstable conn ref before the connection is completed

### ISSUE THREAD

**Issue by ahmedmoheb-nordic** [zephyrproject-rtos/zephyr#53254] opened 2022-12-21 11:40 UTC
**Describe the bug**
Calling bt_conn_foreach() in a loop to loop over active connection doesn't grantee that reported connection reference is usable.
bt_conn_foreach() reports unstable connection reference before reporting that connection reference by the 'connected' callback.

**To Reproduce**
1. Checkout this commit 364267a7037abc2bad840f5e1bc20c35827c85f2
2. Run ~/zephyrproject/zephyr/tests/bluetooth/bsim_bt/bsim_test_conn_stress/tests_scripts/conn_stress.sh

**Expected behavior**
Please find the execution log

```
d_01: @00:00:00.114719  [Peripheral] : Updated MTU: TX: 23 RX: 23 bytes
d_01: @00:00:00.114719  [Peripheral] : Connection 0x80d1f40 established : 60:5D:FC:C7:1A:F4 (random)
d_00: @00:00:00.114716  [Central] : Updated MTU: TX: 23 RX: 23 bytes
d_00: @00:00:00.114716  [Central] : Connection 0x80d1f40 established : 7A:7C:28:1F:71:40 (random)
d_00: @00:00:00.114716  [Central] : Active connections count : 1
d_00: @00:00:00.114716  [Central] : Connection reference store index 0
d_00: @00:00:00.115924  [Central] : Security level for connection 0x80d1f40 with peer 7A:7C:28:1F:71:40 (random) is set to : 2
d_00: @00:00:00.119751  [Central] : Scanning successfully started
d_00: @00:00:00.422994  [Central] : ------------------------------------------------------
d_00: @00:00:00.422994  [Central] : [DEVICE]: 68:11:15:89:AB:56 (random), AD evt type 0, AD data len 3, RSSI -35
d_00: @00:00:00.422994  [Central] : ------------------------------------------------------
d_00: @00:00:00.423750  [Central] : ------------------------------------------------------
d_00: @00:00:00.423750  [Central] : [DEVICE]: 68:11:15:89:AB:56 (random), AD evt type 4, AD data len 19, RSSI -35
d_00: @00:00:00.423750  [Central] : ------------------------------------------------------
d_00: @00:00:00.423750  [Central] : Device name : Zephyr Peripheral
d_00: @00:00:00.423751  [Central] : Scanning successfully stopped
d_00: @00:00:00.423751  [Central] : Connecting to 68:11:15:89:AB:56 (random)
d_00: @00:00:00.439087  [Central] get_conn_info_ref:84 : Couldn't find a reference for conn 0x80d1ff8
d_00: @00:00:00.459046  [Central] get_conn_info_ref:84 : Couldn't find a reference for conn 0x80d1ff8
d_00: @00:00:00.479004  [Central] get_conn_info_ref:84 : Couldn't find a reference for conn 0x80d1ff8
d_00: @00:00:00.498963  [Central] get_conn_info_ref:84 : Couldn't find a reference for conn 0x80d1ff8
d_00: @00:00:00.518921  [Central] get_conn_info_ref:84 : Couldn't find a reference for conn 0x80d1ff8
d_02: @00:00:00.531314  [Peripheral] : Updated MTU: TX: 23 RX: 23 bytes
d_02: @00:00:00.531314  [Peripheral] : Connection 0x80d1f40 established : 60:5D:FC:C7:1A:F4 (random)
d_00: @00:00:00.531311  [Central] : Updated MTU: TX: 23 RX: 23 bytes
d_00: @00:00:00.531311  [Central] : Connection 0x80d1ff8 established : 68:11:15:89:AB:56 (random)
d_00: @00:00:00.531311  [Central] : Active connections count : 2
d_00: @00:00:00.531311  [Central] : Connection reference store index 1
d_00: @00:00:00.532519  [Central] : Security level for connection 0x80d1ff8 with peer 68:11:15:89:AB:56 (random) is set to : 2
d_01: @00:00:00.766047  [Peripheral] : Security for 0x80d1f40 changed: 60:5D:FC:C7:1A:F4 (random) level 2
d_01: @00:00:00.778382  [Peripheral] : Discovering peer 60:5D:FC:C7:1A:F4 (random) primary service
d_00: @00:00:00.816240  [Central] : Security for conn (0) @ 0x80d1f40 changed: 7A:7C:28:1F:71:40 (random) level 2
d_00: @00:00:00.818299  [Central] : Discovering peer 7A:7C:28:1F:71:40 (random) primary service
d_00: @00:00:00.966371  [Central] : Primary Service Found
d_01: @00:00:01.016078  [Peripheral] : Primary Service Found
d_01: @00:00:01.066149  [Peripheral] : Service Characteristic Found
d_00: @00:00:01.066467  [Central] : Service Characteristic Found
d_02: @00:00:01.067218  [Peripheral] : Security for 0x80d1f40 changed: 60:5D:FC:C7:1A:F4 (random) level 2
d_02: @00:00:01.077759  [Peripheral] : Discovering peer 60:5D:FC:C7:1A:F4 (random) primary service
d_00: @00:00:01.117412  [Central] : Security for conn (1) @ 0x80d1ff8 changed: 68:11:15:89:AB:56 (random) level 2
d_00: @00:00:01.117676  [Central] : Discovering peer 68:11:15:89:AB:56 (random) primary service
d_01: @00:00:01.166082  [Peripheral] : [SUBSCRIBED] addr DE:CD:A2:21:EE:22 (random)
d_00: @00:00:01.166332  [Central] : [SUBSCRIBED] addr CB:04:A6:15:1F:50 (random) conn 0
d_00: @00:00:01.218121  [Central] : Primary Service Found
d_02: @00:00:01.267249  [Peripheral] : Primary Service Found
d_02: @00:00:01.317321  [Peripheral] : Service Characteristic Found
d_00: @00:00:01.317640  [Central] : Service Characteristic Found
d_02: @00:00:01.417253  [Peripheral] : [SUBSCRIBED] addr DE:CD:A2:21:EE:22 (random)
d_00: @00:00:01.417504  [Central] : [SUBSCRIBED] addr DD:D1:7D:F0:5F:33 (random) conn 1
```

Connection reference was reported by `bt_conn_foreach()`
```
d_00: @00:00:00.439087  [Central] get_conn_info_ref:84 : Couldn't find a reference for conn 0x80d1ff8
d_00: @00:00:00.459046  [Central] get_conn_info_ref:84 : Couldn't find a reference for conn 0x80d1ff8
d_00: @00:00:00.479004  [Central] get_conn_info_ref:84 : Couldn't find a reference for conn 0x80d1ff8
d_00: @00:00:00.498963  [Central] get_conn_info_ref:84 : Couldn't find a reference for conn 0x80d1ff8
d_00: @00:00:00.518921  [Central] get_conn_info_ref:84 : Couldn't find a reference for conn 0x80d1ff8
```
before being reported by the `connected` callback
```
d_00: @00:00:00.531311  [Central] : Connection 0x80d1ff8 established : 68:11:15:89:AB:56 (random)
```

**Comment by jhedberg** [comment] 2023-01-04 15:34
`bt_conn_foerach()` ensures that there's a valid reference before calling the callback, and then releases the reference after the callback. So I doubt the issue is with `bt_conn_foreach()`. @ahmedmoheb-nordic could you study the code a bit further to figure out where the issue is? (it could also be in the test app)

**Comment by carlescufi** [comment] 2023-02-09 12:28
Closing as duplicate of https://github.com/zephyrproject-rtos/zephyr/issues/53996

**Closed by carlescufi** 2023-02-09 12:28 UTC
Labels: bug, priority: low, area: Bluetooth
