### ISSUE TITLE
Read out heap space used and unallocated

### ISSUE THREAD

**Issue by kristoftjonck** [zephyrproject-rtos/zephyr#21033] opened 2019-11-27 10:17 UTC
**Is your feature request related to a problem? Please describe.**
I need to know how much heap size is allocated, how much is used and how much is left. Like the "xPortGetFreeHeapSize()" in freeRTOS.

**Describe the solution you'd like**
Function to read out the total heap size, used allocated heap space / unallocated heap space left.

Not sure if it is implemented, but could not find it in the documentation.

**Comment by aescolar** [comment] 2019-11-28 15:43
CC @andyross @andrewboie

**Comment by carlescufi** [comment] 2020-03-31 17:49
@andyross could you consider adding this to your new heap allocator?

**Comment by andyross** [comment] 2021-02-13 01:18
Duplicate of #23076

**Closed by andyross** 2021-02-13 01:18 UTC
Labels: Feature Request, area: Kernel
