### ISSUE TITLE
[v2.7] Connection error with Android 13

### ISSUE THREAD

**Issue by xeanhort** [zephyrproject-rtos/zephyr#54555] opened 2023-02-07 14:57 UTC
**Describe the bug**
Hello, I am writing because we have BLE connection problems in some Android 13 devices. I want to emphasize that these problems are only occurring since the release of android version 13 and that only occur in some models of cell phones, in most models everything works correctly.

As you can see in the attached log, these mobiles only manage to connect once in two times (some of them fail to connect the first time, the second time works, the third doesn't work, etc.; and other devices connect the 1st, 3rd, ... and fail to connect the 2nd, 4th, ...). When they don't connect, they show the error bt_att: Invalid len 2 for code 0x0e continously until a disconnection is made.

We are working with nordic nrf52840 and zephyr 2.7.3 but it is not working either with 2.7.99 or 2.5.0 and we can not move to the last version for now.

I also added a sniffer trace when this occur.

Thank you

**Expected behavior**
The device connects through BLE.

**Impact**
Uncertainty about how many devices are affected.

**Logs and console output**
<img width="542" alt="image" src="https://user-images.githubusercontent.com/6896906/217276989-4e3bbef1-19f4-4794-b301-4908a7d55f72.png">
<img width="538" alt="image" src="https://user-images.githubusercontent.com/6896906/217277049-99d28c31-d7ec-4508-911e-7c12f6c0b0e7.png">

[connection_error.pcapng (remove the leading `.log`)](https://github.com/zephyrproject-rtos/zephyr/files/10676306/connection_error.pcapng.log)

**Environment (please complete the following information):**
 - Zephyr 2.7.3 (also 2.7.99 and 2.5.0)

**Comment by carlescufi** [comment] 2023-02-07 15:09
@xeanhort could you please try to reproduce with the latest `main` branch?

**Comment by carlescufi** [comment] 2023-02-07 15:10
Also @xeanhort, what platform/board are you running Zephyr on?

**Comment by xeanhort** [comment] 2023-02-07 20:52
@carlescufi we sre using a custom board, with the nrf52840.

This board worked for a long time (~june) with several phones, but we are finding that lately some Android 13 are failing with this strange behaviour. In fact, we first detected the issue with a OnePlus 8T that was working for several months and, right after its update to Android 13, it started to fail (also with older FW versions it keet failing).

We have the test with the main branch scheduled, but it might take some time to migrate everything.

**Comment by jori-nordic** [comment] 2023-02-08 07:25
@xeanhort can you try disabling `CONFIG_BT_GATT_READ_MULTIPLE`? The failing opcode is `BT_ATT_OP_READ_MULT_REQ` which is a new feature (so it makes sense it starts failling only on recent android stack versions).

**Comment by xeanhort** [comment] 2023-02-08 11:42
@jori-nordic We disabled this flag but it keeps failing. Nevertheless, now we are having different behavior.

- The project configuration:
![image](https://user-images.githubusercontent.com/6896906/217518700-603378c6-0364-4e2c-8a16-268866b22298.png)
- Now we are receiving different messages when the connection fails: 
![image](https://user-images.githubusercontent.com/6896906/217519392-f7a724c5-bb29-4c11-bb38-f44c21aa98f8.png)
- Phone 1 (Realme GT Neo2):
    - This phone keeps the same behavior: when it connects it shows the new log messages (Unhandled ATT), and the odd connection it works (like before).
    - Attached sniffer file with the new connection process: 
[connection_error_config_multiple_disabled.pcapng (remove the leading `.log`)](https://github.com/zephyrproject-rtos/zephyr/files/10685078/connection_error_config_multiple_disabled.pcapng.log)
- Phone 2 (OnePlus 8T):
    - This phone was working half of the times, but now it always fails (it never connects). The log messages are the same (Unhandled ATT).

Thank you

**Comment by nordicjm** [comment] 2023-02-15 14:49
@Thalley any thoughts on this?

**Comment by Thalley** [comment] 2023-02-16 09:54
Hmm, the unhandled request is still `BT_ATT_OP_READ_MULT_REQ`. Weird that it continues to attempt to read using that, since we clearly respond with `BT_ATT_ERR_NOT_SUPPORTED`.

For the first issue, it is Android being incorrect, as it uses `BT_ATT_OP_READ_MULT_REQ` with a single handle (thus len = 2). The core spec clearly states that at least 2 handles shall be used: 
![image](https://user-images.githubusercontent.com/2520413/219331476-06942ba8-9a35-4b9e-bee1-d6bc4a26c127.png)


This is clearly a bug in Android, and we should close it here

**Closed** 2023-02-16 11:45 UTC
Labels: bug, priority: low, area: Bluetooth, area: Bluetooth Host
