### ISSUE TITLE
Bluetooth: Crash in bt_gatt_dm_attr_chrc_val when BLE device is disconnected during discovery process

### ISSUE THREAD

**Issue by gpuzio** [zephyrproject-rtos/zephyr#35686] opened 2021-05-26 17:37 UTC
In certain situation when BLE device is disconnected during service discovery process sw can crash in bt_gatt_dm_char_by_uuid due to BUS FAULT (dereference of pointer showing non accessible memory). Scenario is following,:
1. scanning is started
2. connection with BLE device is established during filter match callback. 
3. Gatt discovery is started with bt_gatt_dm_start.
4. 3 services are discovered correctly
5. BLE device is disconnected (this is pulse oximeter, it have so good timings that very often disconnect right in this moment) 
6. 4th service is discovered
7. In "completed" callback for 4th service  I'm assigning handlers for one of the characteristics calling bt_gatt_dm_char_by_uuid function. 
8. Crash happen in bt_uuid_cmp function as second argument points to wrong memory 

**Describe the bug**
The bug is that during service discovery none of the characteristics is discovered. discovery_callback with BT_GATT_DISCOVER_CHARACTERISTIC is called only once with attr=NULL, so this basically ends service discovery and cause calling discovery_complete callback. I believe this situation should end with discovery_complete_error. In discovery_complete callback my application tries to assign handlers, but bt_gatt_dm_char_next() is returning pointer to memory that was used for storing characteristic for service 3. 

**To Reproduce**
You need assign handlers during gatt discovery procedure and disconnect device in right moment, which is not easy, when I tried this with different BLE devices I couldn't reproduce issue. One device (pulse oximeter) have so "good" timing that problem can be reproduce in around 50% cases. 

**Expected behavior**
bt_gatt_dm_char_by_uuid should not crash, discovery error callback should be called. 

**Impact**
showstopper

**Logs and console output**
[discovery_crash.txt](https://github.com/zephyrproject-rtos/zephyr/files/6548630/discovery_crash.txt)
[debug_printk_diff.txt](https://github.com/zephyrproject-rtos/zephyr/files/6548636/debug_printk_diff.txt)

[17:56:50:065] bt_gatt_dm_char_by_uuid chrc->uuid 0x20005034 
this is first characteristic checked in bt_gatt_dm_attr_chrc_val function. This address was previously used for storing characteristics from service number 3 (180a), but this memory was released in svc_attr_memory_release

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK 
 - nrf tag: v1.4.2 (a61d43c681eb7e2609a01c1929ae6e2113d7f9a2)

**Additional context**
I developed workaround for problem. I'm counting discovered characteristics in discovery_process_characteristic - if counter is 0 when att=NULL (in discovery_process_characteristic) I'm calling discovery_error callback. Looks that this works, at least for devices that I'm working with. Not sure it this can be problem with different devices - can we have no characteristics in Service?

**Comment by joerchan** [comment] 2021-05-27 14:04
@gpuzio Thank you for the bug-report. This is however reported in the wrong place as the issue is in the nrf repository as part of the nRF Connect SDK, and not related to zephyr itself.
The correct place to report these types of bugs is through https://devzone.nordicsemi.com/.
If you don't mind could you please open a ticket there so that we can continue any dialog there. I've already created an internal ticket so you can refer to that as NCSDK-9811.

I'll close this as it is not a zephyr issue.

**Closed by joerchan** 2021-05-27 14:04 UTC
Labels: area: Bluetooth, area: Bluetooth Host, bug, priority: high
