### ISSUE TITLE
MCUBoot with multi-image support on Zephyr project for i.MX RT1165 EVK

### ISSUE THREAD

**Issue by vishnusudhan** [zephyrproject-rtos/zephyr#45761] opened 2022-05-18 11:04 UTC
I am trying to build the MCUBoot with multi-image support (2 images) with Zephyr on i.MX RT1165 EVK.

I can able to build & flash the MCUBoot with single application.  

Now trying to find the steps to check the multi-image (2 images) with MCUBoot & place the image over each SLOT 0 & SLOT1 and also need to the check the image upgrade mode with scratch/ without scratch possibilities.  

Please refer where need to find the steps to try for the multi-image support with MCUBoot?

**Comment by pepe2k** [comment] 2022-05-18 12:48
I found this short tutorial very useful: https://github.com/zephyrproject-rtos/zephyr/discussions/45252

**Comment by mbolivar-nordic** [comment] 2022-05-18 20:46
I'm closing this as not a bug. If you think you have found a bug, please fill out the correct template in a new issue: https://github.com/zephyrproject-rtos/zephyr/issues/new?assignees=&labels=bug&template=bug_report.md&title=

**Closed by mbolivar-nordic** 2022-05-18 20:46 UTC
Labels: bug
