### ISSUE TITLE
intel_adsp: tests/kernel/workq/work/kernel.workqueue.api fails

### ISSUE THREAD

**Issue by majunkier** [zephyrproject-rtos/zephyr#70492] opened 2024-03-20 12:48 UTC
**Describe the bug**
tested on intel_adsp/ boards (cavs25, ace15_mtpm ,ace20_lnl)

```
tests/kernel/workq/work/kernel.workqueue.api
```

test hangs despite initially promising results. Result is timeout.

**To Reproduce**
` twister --device-testing --hardware-map PATH-TO-HWMAP -s tests/kernel/workq/work/kernel.workqueue.api`

**Expected behavior**
Test should pass

**Logs and console output**
handler.log

```
*** Booting Zephyr OS build v3.6.0-1236-g8f4ac0d4ab45 ***
Running TESTSUITE work
===================================================================
START - test_drain_empty
PASS - test_drain_empty in 0.001 seconds
===================================================================
START - test_nop
SKIP - test_nop in 0.001 seconds
===================================================================
START - test_null_queue
PASS - test_null_queue in 0.001 seconds
===================================================================
START - test_smp_running_cancel
PASS - test_smp_running_cancel in 0.101 seconds
===================================================================
START - test_smp_simple_queue
PASS - test_smp_simple_queue in 0.001 seconds
===================================================================
START - test_unstarted
PASS - test_unstarted in 0.001 seconds
===================================================================
TESTSUITE work succeeded
Running TESTSUITE work_1cpu
===================================================================
START - test_1cpu_basic_reschedule
PASS - test_1cpu_basic_reschedule in 0.102 seconds
===================================================================
START - test_1cpu_basic_schedule

```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Version used: v3.6.0-1236-g8f4ac0d4ab45

**Comment by nashif** [comment] 2024-03-20 13:28
duplicate of #70494

**Closed by nashif** 2024-03-20 13:28 UTC
Labels: bug, platform: Intel ADSP
