### ISSUE TITLE
test: tests/lib/sprintf/ build fail

### ISSUE THREAD

**Issue by hunterhu3000** [zephyrproject-rtos/zephyr#47714] opened 2022-07-13 01:50 UTC
**Describe the bug**
tests/lib/sprintf/ build fail due to warning treated as error in twister

Please also mention any information which could help others to understand
the problem you're facing:
 - on platform: mec17
 - What have you tried to diagnose or workaround this issue? Submit https://github.com/zephyrproject-rtos/zephyr/pull/47715

**To Reproduce**
1. west:
    west build -p always -b mec172xevb_assy6906 tests/lib/sprintf/
2. twister
    twister -p mec172xevb_assy6906 --device-testing --device-serial /dev/ttyUSB0 -vv -T tests/lib/sprintf/

**Expected behavior**
The build can pass

**Impact**
blocks all the tests under tests/lib/sprintf/

**Logs and console output**
```
-- Generating done
-- Build files have been written to: /home/ztest/zephyrproject/zephyr/build
-- west build: building application
[1/157] Preparing syscall dependency handling

[2/157] Generating include/generated/version.h
-- Zephyr version: 3.1.99 (/home/ztest/zephyrproject/zephyr), build: zephyr-v3.1.0-2059-g1eeae7762140
[71/157] Building C object CMakeFiles/app.dir/src/main.c.obj
/home/ztest/zephyrproject/zephyr/tests/lib/sprintf/src/main.c: In function 'test_print':
/home/ztest/zephyrproject/zephyr/tests/lib/sprintf/src/main.c:760:15: warning: zero-length gnu_printf format string [-Wformat-zero-length]
  760 |  ret = printf("");
      |               ^~
/home/ztest/zephyrproject/zephyr/tests/lib/sprintf/src/main.c: In function 'test_fprintf':
/home/ztest/zephyrproject/zephyr/tests/lib/sprintf/src/main.c:778:24: warning: zero-length gnu_printf format string [-Wformat-zero-length]
  778 |  ret = fprintf(stdout, "");
      |                        ^~
[147/157] Linking C executable zephyr/zephyr_pre0.elf
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows): Ubuntu 20.04
 - Toolchain (e.g Zephyr SDK, ...): 0.14.1
 - Commit SHA or Version used: 1eeae77621403ebea45943673c9732541db70ef9

**Additional context**
printf a NULL string will generate a warning in the build, but the warning is treated as error recently. If we remove the printf(""), we are unable to test the function. So we can only set "-Wno-format-zero-length" for this case.

**Comment by stephanosio** [comment] 2022-07-13 02:48
Duplicate of #47588

**Closed by stephanosio** 2022-07-13 02:48 UTC
Labels: bug
