### ISSUE TITLE
Suggestion: Turn warnings into errors in extract_dts_includes.py

### ISSUE THREAD

**Issue by ulfalizer** [zephyrproject-rtos/zephyr#9701] opened 2018-08-28 20:31 UTC
Would get rid of stuff like this, which has been there for a long time now:

    quark_se_c1000_devboard.dts_compiled: Warning (unit_address_vs_reg): Node /soc/virtualcom@0 has a unit name, but no reg property
    extract_dts_includes.py: 'id' property missing in 'Intel I/O Advanced Programmable Interrupt Controller' binding. Using '<unknown id>'.

Could check if tests are being run somehow too. The brute-force approach is effective at least...

**Comment by ulfalizer** [comment] 2018-08-28 20:32
CC @b0661

**Comment by SebastianBoe** [comment] 2018-08-29 10:35
This is a duplicate of the (until now accidentally closed) issue #8360 .

**Closed by SebastianBoe** 2018-08-29 10:35 UTC
Labels: enhancement
