### ISSUE TITLE
make usb power settings in "Configuration Descriptor" setable

### ISSUE THREAD

**Issue by StefJar** [zephyrproject-rtos/zephyr#19544] opened 2019-10-02 08:27 UTC
In some cases the USB port is not only used for communication. If it used for charging it is necessary to set the maximum current via "Configuration Descriptor".

state of the art:

in https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/usb/usb_descriptor.c#L91 it is set fixed to 100mA

approach:

- Find a way to set the "Configuration Descriptor" to 500mA (0xFA or MAX_HIGH_POWER(https://github.com/zephyrproject-rtos/zephyr/blob/master/include/usb/usb_common.h#L88)) as demo for usb2.0 devices

- discuss if the power is set via device tree or via (menu)config

**Comment by carlescufi** [comment] 2019-10-02 09:05
Duplicate of #19545. Please follow-up there.

**Closed by carlescufi** 2019-10-02 09:05 UTC
Labels: enhancement
