### ISSUE TITLE
zefi.py assumes host GCC is x86 

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#27047] opened 2020-07-22 10:59 UTC
zefi.py will fail if this assumption isn't meet.  Which may be the case on either an arm64 host environment or on something like MacOS X.

Is it possible to use the x86 cross compiler that build zephyr here?

**Comment by jhedberg** [comment] 2020-07-22 14:43
AFAIK the plan is to eventually move to using the same build environment as for the rest of Zephyr, as per #26737

I'll let @andyross comment if there's some quick/simple intermediate fix we could do to zefi.py to eliminate the x86 dependency.

**Comment by andyross** [comment] 2020-07-22 14:55
We could pass the compiler to the script via the environment or the command line for a quick fix.  But note that there's been absolutely no thought given to non-x86 EFI environments.  It's very much an arch-specific feature right now.  The framework is there, I guess, but I'd expect significant changes would be needed to get the COFF linkage working on other platforms, etc...

I'd mostly view this as a duplicate of #26737, yeah.

**Comment by jenmwms** [comment] 2020-11-18 22:35
> We could pass the compiler to the script via the environment or the command line for a quick fix. But note that there's been absolutely no thought given to non-x86 EFI environments. It's very much an arch-specific feature right now. The framework is there, I guess, but I'd expect significant changes would be needed to get the COFF linkage working on other platforms, etc...
> 
> I'd mostly view this as a duplicate of #26737, yeah.

@andyross I'll follow-up with you about this bug. @nashif clarified this is not a duplicate. I'll update this bug as I learn more.

**Comment by galak** [comment] 2021-01-23 15:40
Re-open this issue since we need an update to the SDK to enable EFI binary targets in binutils.

**Closed** 2021-01-25 18:17 UTC
Labels: area: X86, bug, priority: low
