### ISSUE TITLE
Bluetooth: LL assertion fail with peripherals connect/disconnect rounds

### ISSUE THREAD

**Issue by ahmedmoheb-nordic** [zephyrproject-rtos/zephyr#53049] opened 2022-12-14 09:34 UTC
**Describe the bug**
When central is connected to multiple peripherals and the MTU is increased to 247 bytes, central gets notifications only from the last connected peripheral

Central connects to 4 peripherals, exchange MTU to be increased to 247 bytes, then notifications should go in both directions for a minute before the peripherals disconnect and so on.

After several rounds, one of the LL assertions fails and operations stops

**To Reproduce**
1. Central connects to more than one peripheral
2. For each connection, set the connection interval to be 37 ms
3. Send notifications in both directions

Please checkout this commit f591f4116b2575017fc84bcdbd2182fc89b11584 and run the script ~/zephyrproject/zephyr/tests/bluetooth/bsim_bt/bsim_test_conn_stress/tests_scripts/conn_stress.sh

![image](https://user-images.githubusercontent.com/109019690/204889194-9997711c-dd83-42a3-8fbe-f809cb96de4f.png)

**Comment by cvinayak** [comment] 2023-02-11 06:20
The issue is no longer reproducible in v3.3.0-rc2, possibly fixed by #52012. The rebased tests used to verify is here: https://github.com/zephyrproject-rtos/zephyr/pull/54736

And the resulting log: 
[conn_stress.log](https://github.com/zephyrproject-rtos/zephyr/files/10712753/conn_stress.log)

**Closed by cvinayak** 2023-02-11 06:20 UTC
Labels: bug, priority: medium, area: Bluetooth, area: Bluetooth Controller
