### ISSUE TITLE
devicetree: phandles cross dependencies

### ISSUE THREAD

**Issue by bbilas** [zephyrproject-rtos/zephyr#76245] opened 2024-07-23 19:45 UTC
**Describe the bug**
Unable to create a cross-phandle dependency.

**To Reproduce**
A bug should be reproducible on any sample where devicetree is used, just add the following changes:

dts:
<pre>
xyz0: xyz0 {
    compatible = "zephyr,foo";
    bar = <&xyz1>;
};

xyz1: xyz1 {
    compatible = "zephyr,foo";
    bar = <&xyz0>;
};
</pre>

foo yaml:

<pre>
compatible: "zephyr,foo"

include: base.yaml

properties:
  bar:
    type: phandle
</pre>

**Expected behavior**
No errors.

**Impact**
Showstopper for the custom interlocking mechanism.

**Logs and console output**
<pre>
zephyr/include/generated/zephyr/devicetree_generated.h:279:25: error: expected '=', ',', ';', 'asm' or '__attribute__' before '-' token
  279 | #define DT_N_S_xyz1_ORD -1
</pre>

**Environment (please complete the following information):**

 - OS: Arch Linux
 - Toolchain Zephyr SDK
 - Zephyr 3.7.0-rc3

**Comment by gmarull** [comment] 2024-07-24 07:17
Duplicate of https://github.com/zephyrproject-rtos/zephyr/issues/57708

**Closed by gmarull** 2024-07-24 07:17 UTC
Labels: bug, area: Devicetree
