### ISSUE TITLE
Failed llvm build asks to view non existent CMakeError.log for details

### ISSUE THREAD

**Issue by de-nordic** [zephyrproject-rtos/zephyr#61803] opened 2023-08-23 16:44 UTC
**Describe the bug**

Outside of zephyr repo, done this:
```
export ZEPHYR_TOOLCHAIN_VARIANT=llvm
west build -d hello -b nrf52840dk_nrf52840 zephyr/samples/hello_world/
```

got this:
```
$$ west build -d hello -b nrf52840dk_nrf52840 zephyr/samples/hello_world/
-- west build: generating a build system
Loading Zephyr default modules (Zephyr base).
-- Application: <redacted>/mcuboot-xip/zephyr/samples/hello_world
-- CMake version: 3.27.2
-- Found Python3: /usr/bin/python3 (found suitable version "3.10.12", minimum required is "3.8") found components: Interpreter
-- Cache files will be written to: /home/doer/.cache/zephyr
-- Zephyr version: 3.4.99 (<redacted>/mcuboot-xip/zephyr)
-- Found west (found suitable version "1.0.0", minimum required is "0.14.0")
-- Board: nrf52840dk_nrf52840
-- Found host-tools: zephyr 0.16.1 (/home/doer/zephyr-sdk)
-- Found toolchain: host (clang/ld)
-- Found Dtc: /usr/bin/dtc (found suitable version "1.6.1", minimum required is "1.4.6")
-- Found BOARD.dts: <redacted>/mcuboot-xip/zephyr/boards/arm/nrf52840dk_nrf52840/nrf52840dk_nrf52840.dts
-- Generated zephyr.dts: <redacted>/mcuboot-xip/hello/zephyr/zephyr.dts
-- Generated devicetree_generated.h: <redacted>/mcuboot-xip/hello/zephyr/include/generated/devicetree_generated.h
-- Including generated dts.cmake file: <redacted>/mcuboot-xip/hello/zephyr/dts.cmake
Parsing <redacted>/mcuboot-xip/zephyr/Kconfig
Loaded configuration '<redacted>/mcuboot-xip/zephyr/boards/arm/nrf52840dk_nrf52840/nrf52840dk_nrf52840_defconfig'
Merged configuration '<redacted>/mcuboot-xip/zephyr/samples/hello_world/prj.conf'
Configuration saved to '<redacted>/mcuboot-xip/hello/zephyr/.config'
Kconfig header saved to '<redacted>/mcuboot-xip/hello/zephyr/include/generated/autoconf.h'
-- Found GnuLd: /usr/bin/ld.bfd (found version "2.38")
-- The C compiler identification is Clang 14.0.0
-- The CXX compiler identification is Clang 14.0.0
-- The ASM compiler identification is Clang with GNU-like command-line
-- Found assembler: /usr/bin/clang
CMake Error at <redacted>/mcuboot-xip/zephyr/cmake/modules/extensions.cmake:2243 (message):
  Assertion failed: The toolchain is unable to build a dummy C file.  See
  CMakeError.log.
Call Stack (most recent call first):
  <redacted>/mcuboot-xip/zephyr/cmake/modules/kernel.cmake:145 (assert)
  <redacted>/mcuboot-xip/zephyr/cmake/modules/zephyr_default.cmake:138 (include)
  <redacted>/mcuboot-xip/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
  <redacted>/mcuboot-xip/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)
  CMakeLists.txt:5 (find_package)


-- Configuring incomplete, errors occurred!
FATAL ERROR: command exited with status 1: /home/doer/.local/bin/cmake -DWEST_PYTHON=/usr/bin/python3 -B<redacted>/mcuboot-xip/hello -GNinja -DBOARD=nrf52840dk_nrf52840 -S<redacted>/mcuboot-xip/zephyr/samples/hello_world
```

Using:
```
find hello -type f -name CMakeError.log
```
found nothing.

**To Reproduce**
Above

**Expected behavior**
Want build error log.

**Impact**
It is harder to investigate problems with build. Getting annoyed while trying to figure out how to build stuff with llvm.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr sdk 0.16.1, some llvm
 - Commit dac864bba379bc9d00b7e7d8bf5bea651b71713b is the newest Zephyr main used.

**Comment by jhedberg** [comment] 2023-08-29 16:11
Release meeting: this is not supported right now (not a bug). Closing as not planned for now.

**Closed by jhedberg** 2023-08-29 16:11 UTC
Labels: bug, priority: low
