### ISSUE TITLE
Ztest becomes unresponsive while running SMP tests

### ISSUE THREAD

**Issue by spoorthik** [zephyrproject-rtos/zephyr#9506] opened 2018-08-17 14:58 UTC
Issue: The tests in tests/kernel/smp when executed becomes unresponsive.

Sample log:

```
Running test suite smp
===================================================================
starting test - test_smp_coop_threads
PASS - test_smp_coop_threads
===================================================================
starting test - test_cpu_id_threads
```

Same set of tests when executed individually by commenting rest of the tests in testsuite like below:

```
 ztest_test_suite(smp,
/*           ztest_unit_test(test_smp_coop_threads),
*/
             ztest_unit_test(test_cpu_id_threads)
/*,
             ztest_unit_test(test_coop_resched_threads),
             ztest_unit_test(test_preempt_resched_threads),
             ztest_unit_test(test_yield_threads),
             ztest_unit_test(test_sleep_threads),
             ztest_unit_test(test_wakeup_threads),
             ztest_unit_test(test_wakeup_pending_threads)
*/
             );
    ztest_run_test_suite(smp);
```
the test case executes successfully.

Sample log:

```
Running test suite smp
===================================================================
starting test - test_cpu_id_threads
PASS - test_cpu_id_threads
===================================================================
===================================================================
PROJECT EXECUTION SUCCESSFUL
```
It is the same case for all the test cases in smp. Cleanup of threads created is handled in test case already.
```
 ztest_test_suite(smp,
/*           ztest_unit_test(test_smp_coop_threads),
             ztest_unit_test(test_cpu_id_threads),
*/
             ztest_unit_test(test_coop_resched_threads)

/*,
             ztest_unit_test(test_preempt_resched_threads),
             ztest_unit_test(test_yield_threads),
             ztest_unit_test(test_sleep_threads),
             ztest_unit_test(test_wakeup_threads),
             ztest_unit_test(test_wakeup_pending_threads)
*/
             );
    ztest_run_test_suite(smp);

Execution log:

Running test suite smp
===================================================================
starting test - test_coop_resched_threads
PASS - test_coop_resched_threads
===================================================================
===================================================================

PROJECT EXECUTION SUCCESSFUL
```

Steps to reproduce:

```
cd tests/kernel/smp
mkdir build && cd build
cmake -DBOARD=esp32 ..
make flash
```

**Comment by aescolar** [comment] 2018-08-19 16:50
@spoorthik : When compiled for which target?

**Comment by spoorthik** [comment] 2018-08-19 16:53
@aescolar : Compiled for esp32.

**Comment by rljordan** [comment] 2019-03-07 01:26
@nashif Can we resolve this in future?

**Comment by gnuless** [comment] 2019-03-22 16:36
This is a can of worms that is a bit over my head at this point.  I think there are problems with races in either the xtensa code and/or the scheduler.

**Comment by gnuless** [comment] 2019-03-22 16:40
I've discovered that k_sleep() is broken on SMP, which affects this test. I'm not sure if my fix for that issue is correct, which leaves me wondering if continuing issues are created by my fix, or are actual symptoms. I have to punt this back to someone with more knowledge of the scheduler and xtensa arch.

**Comment by gnuless** [comment] 2019-03-22 16:53
FWIW, my k_sleep() fix was:

```
--- a/kernel/sched.c
+++ b/kernel/sched.c
@@ -945,6 +945,16 @@ s32_t z_impl_k_sleep(s32_t duration)
        z_remove_thread_from_ready_q(_current);
        z_add_thread_timeout(_current, ticks);

+#if defined(CONFIG_SMP)
+       /*
+        * when running SMP, we must mark the thread queued
+        * to prevent the path through z_swap() from putting
+        * it right back in a ready queue, resulting in no sleep.
+        */
+
+       z_mark_thread_as_queued(_current);
+#endif
+
        (void)z_swap(&local_lock, key);

        ticks = expected_wakeup_time - z_tick_get_32();
```

**Comment by gnuless** [comment] 2019-03-27 17:19
This bug should not have been closed, as #14846 addressed some issues related to this bug, but not all.

**Comment by dleach02** [comment] 2019-12-10 20:03
@andyross , you mentioned that you can't reproduce this anymore after #18531. Do you think we can close this issue then?

**Comment by andyross** [comment] 2019-12-11 19:19
Yes, this is working in all CI builds and has been for months. Closing.

**Closed by andyross** 2019-12-11 19:19 UTC
Labels: area: Testing Suite, bug, priority: low
