### ISSUE TITLE
mec15xxevb_assy6853:running tests/kernel/workq/work_queue_api/ failed

### ISSUE THREAD

**Issue by maksimmasalski** [zephyrproject-rtos/zephyr#29328] opened 2020-10-19 09:28 UTC
**Describe the bug**
During run tests/kernel/workq/work_queue_api/ in test `test_work_submit_to_multipleq` assertion failed.

**To Reproduce**
1.  west build -p -b mec15xxevb_assy6853 tests/kernel/workq/work_queue_api/
2. west flash
3. See the error in the console output
or
1. `sanitycheck --hardware-map ~/mec1.file --device-testing -T tests/kernel/workq/work_queue_api/ -vv`
2. See the error

**Expected behavior**
Test should pass

**Impact**
Test suite fails

**Logs and console output**
```
DEBUG   - DEVICE: *** Booting Zephyr OS build zephyr-v2.4.0-634-g53cc090c39a5  ***
DEBUG   - DEVICE: Running test suite workqueue_api
~~~
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_work_submit_to_multipleq
DEBUG   - DEVICE:
DEBUG   - DEVICE: Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/workq/work_queue_api/src/main.c:277: twork_submit_multipleq: k_delayed_work_pending(&new_work) is false
DEBUG   - DEVICE:
DEBUG   - DEVICE: FAIL - test_work_submit_to_multipleq
~~~
```

**Environment (please complete the following information):**
 - OS: Linux Ubuntu 18.04.4 LTS
 - Toolchain Zephyr SDK 0.11.4
 - Commit SHA or Version used 53cc090

**Comment by nashif** [comment] 2020-10-19 13:20
close as possible duplicate of  #29329

**Closed by nashif** 2020-10-19 13:20 UTC
Labels: bug, priority: low
