### ISSUE TITLE
undefined reference to `bt_le_per_adv_sync_transfer_subscribe' when trying to build samples/bluetooth/periodic_sync_rsp

### ISSUE THREAD

**Issue by TimWei888** [zephyrproject-rtos/zephyr#68606] opened 2024-02-06 09:49 UTC
**Describe the bug**
I tried to build samples/bluetooth/periodic_sync_rsp and got a undefined reference error.

**To Reproduce**
west build -p always -b nrf52840dk_nrf52840 samples/bluetooth/periodic_sync_rsp

**Expected behavior**
Build successfully.

**Impact**
showstopper

**Logs and console output**
C:\Users\tw\zephyrproject\zephyr>west build -p always -b nrf52840dk_nrf52840 samples/bluetooth/periodic_sync_rsp
-- west build: making build dir C:\Users\tw\zephyrproject\zephyr\build pristine
-- west build: generating a build system
Loading Zephyr default modules (Zephyr base).
-- Application: C:/Users/tw/zephyrproject/zephyr/samples/bluetooth/periodic_sync_rsp
-- CMake version: 3.28.3
-- Found Python3: C:/Users/tw/AppData/Local/Programs/Python/Python311/python.exe (found suitable version "3.11.7", minimum required is "3.8") found components: Interpreter
-- Cache files will be written to: C:/Users/tw/zephyrproject/zephyr/.cache
-- Zephyr version: 3.6.0-rc1 (C:/Users/tw/zephyrproject/zephyr)
-- Found west (found suitable version "1.2.0", minimum required is "0.14.0")
-- Board: nrf52840dk_nrf52840
-- ZEPHYR_TOOLCHAIN_VARIANT not set, trying to locate Zephyr SDK
-- Found host-tools: zephyr 0.16.5 (C:/Users/tw/zephyr-sdk-0.16.5)
-- Found toolchain: zephyr 0.16.5 (C:/Users/tw/zephyr-sdk-0.16.5)
-- Found Dtc: C:/ProgramData/chocolatey/bin/dtc.exe (found suitable version "1.5.0", minimum required is "1.4.6")
-- Found BOARD.dts: C:/Users/tw/zephyrproject/zephyr/boards/arm/nrf52840dk_nrf52840/nrf52840dk_nrf52840.dts
-- Generated zephyr.dts: C:/Users/tw/zephyrproject/zephyr/build/zephyr/zephyr.dts
-- Generated devicetree_generated.h: C:/Users/tw/zephyrproject/zephyr/build/zephyr/include/generated/devicetree_generated.h
-- Including generated dts.cmake file: C:/Users/tw/zephyrproject/zephyr/build/zephyr/dts.cmake

warning: BT_PER_ADV_SYNC_TRANSFER_RECEIVER (defined at subsys/bluetooth/Kconfig:164) was assigned
the value 'y' but got the value 'n'. Check these unsatisfied dependencies: (!BT_CTLR ||
BT_CTLR_SYNC_TRANSFER_RECEIVER_SUPPORT) (=n). See
http://docs.zephyrproject.org/latest/kconfig.html#CONFIG_BT_PER_ADV_SYNC_TRANSFER_RECEIVER and/or
look up BT_PER_ADV_SYNC_TRANSFER_RECEIVER in the menuconfig/guiconfig interface. The Application
Development Primer, Setting Configuration Values, and Kconfig - Tips and Best Practices sections of
the manual might be helpful too.

warning: BT_PER_ADV_SYNC_TRANSFER_SENDER (defined at subsys/bluetooth/Kconfig:168) was assigned the
value 'y' but got the value 'n'. Check these unsatisfied dependencies: (!BT_CTLR ||
BT_CTLR_SYNC_TRANSFER_SENDER_SUPPORT) (=n). See
http://docs.zephyrproject.org/latest/kconfig.html#CONFIG_BT_PER_ADV_SYNC_TRANSFER_SENDER and/or look
up BT_PER_ADV_SYNC_TRANSFER_SENDER in the menuconfig/guiconfig interface. The Application
Development Primer, Setting Configuration Values, and Kconfig - Tips and Best Practices sections of
the manual might be helpful too.

Parsing C:/Users/tw/zephyrproject/zephyr/Kconfig
Loaded configuration 'C:/Users/tw/zephyrproject/zephyr/boards/arm/nrf52840dk_nrf52840/nrf52840dk_nrf52840_defconfig'
Merged configuration 'C:/Users/tw/zephyrproject/zephyr/samples/bluetooth/periodic_sync_rsp/prj.conf'
Configuration saved to 'C:/Users/tw/zephyrproject/zephyr/build/zephyr/.config'
Kconfig header saved to 'C:/Users/tw/zephyrproject/zephyr/build/zephyr/include/generated/autoconf.h'
-- Found GnuLd: c:/users/tw/zephyr-sdk-0.16.5/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd.exe (found version "2.38")
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- The ASM compiler identification is GNU
-- Found assembler: C:/Users/tw/zephyr-sdk-0.16.5/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc.exe
-- Configuring done (6.8s)
-- Generating done (0.4s)
-- Build files have been written to: C:/Users/tw/zephyrproject/zephyr/build
←[92m-- west build: building application
[1/224] Generating include/generated/version.h
-- Zephyr version: 3.6.0-rc1 (C:/Users/tw/zephyrproject/zephyr), build: v3.6.0-rc1
[218/224] Linking C executable zephyr\zephyr_pre0.elf
FAILED: zephyr/zephyr_pre0.elf zephyr/zephyr_pre0.map C:/Users/tw/zephyrproject/zephyr/build/zephyr/zephyr_pre0.map
C:\WINDOWS\system32\cmd.exe /C "cd . && C:\Users\tw\zephyr-sdk-0.16.5\arm-zephyr-eabi\bin\arm-zephyr-eabi-gcc.exe  -gdwarf-4 zephyr/CMakeFiles/zephyr_pre0.dir/misc/empty_file.c.obj -o zephyr\zephyr_pre0.elf  zephyr
/CMakeFiles/offsets.dir/./arch/arm/core/offsets/offsets.c.obj  -fuse-ld=bfd  -T  zephyr/linker_zephyr_pre0.cmd  -Wl,-Map=C:/Users/tw/zephyrproject/zephyr/build/zephyr/zephyr_pre0.map  -Wl,--whole-archive  app/libap
p.a  zephyr/libzephyr.a  zephyr/arch/common/libarch__common.a  zephyr/arch/arch/arm/core/libarch__arm__core.a  zephyr/arch/arch/arm/core/cortex_m/libarch__arm__core__cortex_m.a  zephyr/arch/arch/arm/core/mpu/libarc
h__arm__core__mpu.a  zephyr/lib/libc/picolibc/liblib__libc__picolibc.a  zephyr/lib/libc/common/liblib__libc__common.a  zephyr/soc/soc/arm/nordic_nrf/libsoc__arm__nordic_nrf.a  zephyr/subsys/random/libsubsys__random
.a  zephyr/subsys/bluetooth/common/libsubsys__bluetooth__common.a  zephyr/subsys/bluetooth/host/libsubsys__bluetooth__host.a  zephyr/subsys/bluetooth/controller/libsubsys__bluetooth__controller.a  zephyr/subsys/net
/libsubsys__net.a  zephyr/drivers/clock_control/libdrivers__clock_control.a  zephyr/drivers/console/libdrivers__console.a  zephyr/drivers/entropy/libdrivers__entropy.a  zephyr/drivers/gpio/libdrivers__gpio.a  zephy
r/drivers/pinctrl/libdrivers__pinctrl.a  zephyr/drivers/serial/libdrivers__serial.a  zephyr/drivers/timer/libdrivers__timer.a  modules/hal_nordic/nrfx/libmodules__hal_nordic__nrfx.a  modules/segger/libmodules__segg
er.a  -Wl,--no-whole-archive  zephyr/kernel/libkernel.a  -L"c:/users/tw/zephyr-sdk-0.16.5/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/thumb/v7e-m/nofp"  -LC:/Users/tw/zephyrproject/zephyr/build/zephyr  -l
gcc  zephyr/arch/common/libisr_tables.a  -mcpu=cortex-m4  -mthumb  -mabi=aapcs  -mfp16-format=ieee  -mtp=soft  -Wl,--gc-sections  -Wl,--build-id=none  -Wl,--sort-common=descending  -Wl,--sort-section=alignment  -Wl
,-u,_OffsetAbsSyms  -Wl,-u,_ConfigAbsSyms  -nostdlib  -static  -Wl,-X  -Wl,-N  -Wl,--orphan-handling=warn  -Wl,-no-pie  -DPICOLIBC_LONG_LONG_PRINTF_SCANF  --specs=picolibc.specs  -lc  -lgcc && C:\WINDOWS\system32\c
md.exe /C "cd /D C:\Users\tw\zephyrproject\zephyr\build\zephyr && "C:\Program Files\CMake\bin\cmake.exe" -E true""
c:/users/tw/zephyr-sdk-0.16.5/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd.exe: app/libapp.a(main.c.obj): in function `main':
C:/Users/tw/zephyrproject/zephyr/samples/bluetooth/periodic_sync_rsp/src/main.c:217: undefined reference to `bt_le_per_adv_sync_transfer_subscribe'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: 'C:\Program Files\CMake\bin\cmake.EXE' --build 'C:\Users\tw\zephyrproject\zephyr\build'

**Environment (please complete the following information):**
 - OS:  Windows 10
 - Toolchain Zephyr SDK 0.16.5
 - Zephyr version: 3.6.0-rc1

**Comment by hermabe** [comment] 2024-02-07 06:22
Closing as duplicate of https://github.com/zephyrproject-rtos/zephyr/issues/68604

**Closed** 2024-02-07 07:48 UTC
Labels: bug, priority: medium, area: Bluetooth
