### ISSUE TITLE
NFFS does not work with STM32L4 devices due to flash restrictions

### ISSUE THREAD

**Issue by vanwinkeljan** [zephyrproject-rtos/zephyr#5493] opened 2017-12-27 23:55 UTC
NFFS assumes that it can write at byte granularity to a flash device but STM32L4 family expects 64-bit writes to flash. Further STM32L4 family assumes that an entry has not been written before preventing a read-modify-write workaround.

Note that this issue possibly impacts more STM32 families.

**Comment by miyatsu** [comment] 2018-01-03 03:41
NFFS does not work with STM32F4 too.

**Comment by nashif** [comment] 2018-02-20 18:29
duplicate of #1583

**Closed by nashif** 2018-02-20 18:29 UTC
Labels: STM32, bug, priority: medium
