### ISSUE TITLE
Intel CAVS18: tests/subsys/dsp/basicmath fails

### ISSUE THREAD

**Issue by majunkier** [zephyrproject-rtos/zephyr#54417] opened 2023-02-03 11:20 UTC
**Describe the bug**
zdsp.basicmath.zdsp.basicmath.zdsp_* tests configurations from tests/subsys/dsp/basicmath fails.  Problem could be connected with  #54399.

**To Reproduce**
Build and run test on CAVS 18. Twister options given in our CI:

```
-W --hardware-map /home/ztest/cavs/cavs.map
--device-testing
-x=CONFIG_BOOT_DELAY=500
-v --no-skipped-report
```

**Expected behavior**
Passes.

**Logs and console output**
```
--
Running TESTSUITE user_data
 
START - test_channel_user_data
PASS - test_channel_user_data in 0.001 seconds
 
START - test_user_data_regression
Assertion failed at WEST_TOPDIR/zephyr/tests/subsys/zbus/user_data/src/main.c:106: user_data_test_user_data_regression: *count not equal to 2
FAIL - test_user_data_regression in 1.001 seconds

TESTSUITE user_data failed.
------ TESTSUITE SUMMARY START ------
SUITE FAIL -  50.00% [user_data]: pass = 1, fail = 1, skip = 0, total = 2 duration = 1.002 seconds
- PASS - [user_data.test_channel_user_data] duration = 0.001 seconds
- FAIL - [user_data.test_user_data_regression] duration = 1.001 seconds
------ TESTSUITE SUMMARY END ------

RunID: d18461e3ecd96f02f6d07b085ae46521
PROJECT EXECUTION FAILED
```

**Environment**
 - Linux
 - Zephyr SDK
 - 60a20471b561

Works fine 25. On Cavs15 error similar tests failing #54122

**Comment by laurenmurphyx64** [comment] 2023-02-03 17:09
Duplicate of https://github.com/zephyrproject-rtos/zephyr/issues/54122

**Closed by laurenmurphyx64** 2023-02-03 17:09 UTC
Labels: bug
