### ISSUE TITLE
tests/net/utils failed on multiple arm platforms.

### ISSUE THREAD

**Issue by chen-png** [zephyrproject-rtos/zephyr#26625] opened 2020-07-03 03:28 UTC
**Describe the bug**
tests/net/utils failed on frdm_k64f, mimxrt1050_evk, sam_e70_xplained boards.

**To Reproduce**
1. west build -b frdm_k64f  -p auto  tests/net/utils
2. west flash
3. see error

**Logs and console output**
*** Booting Zephyr OS build zephyr-v2.3.0-720-gab3e778f47d8  ***
Running test suite test_utils_fn

START - test_net_addr
START - test_ipv4_pton_1
Failed to verify 
failed
START - test_ipv4_pton_2
Failed to verify 
failed
START - test_ipv4_pton_3
Failed to verify 
failed
START - test_ipv4_pton_4
Failed to verify 255.255.255
failed
START - test_ipv4_pton_5
passed
START - test_ipv4_pton_6
Failed to verify 
failed
START - test_ipv4_pton_7
Failed to verify 
failed
START - test_ipv4_pton_8
Failed to verify 
failed
**START - test_ipv6_pton_1
E: ***** BUS FAULT *****
E:   Precise data bus error**
E:   BFAR Address: 0x20002788
E:   NXP MPU error, port 3
E:     Mode: User, Data Address: 0x20002788
E:     Type: Read, Master: 0, Regions: 0x8800
E: r0/a1:  0x00000002  r1/a2:  0x20000d3c  r2/a3:  0x00000000
E: r3/a4:  0x20002788 r12/ip:  0x00011137 r14/lr:  0x00000b41
E:  xpsr:  0xa1000000
E: Faulting instruction address (r15/pc): 0x00005632
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x200021f8 (unknown)
E: Halting system

**Environment (please complete the following information):**
 - OS: fedora28
 - Toolchain: zephyr-sdk-0.11.4
 - Commit ID: ab3e778f47d8

**Comment by stephanosio** [comment] 2020-07-03 10:25
Duplicate of #26600

**Closed** 2020-07-03 10:25 UTC
Labels: area: Tests, bug
