### ISSUE TITLE
SAM GMAC should support PHY link status detection

### ISSUE THREAD

**Issue by stephanosio** [zephyrproject-rtos/zephyr#23386] opened 2020-03-11 08:30 UTC
**Is your enhancement proposal related to a problem? Please describe.**
The SAM GMAC driver does not currently support detecting and reporting changes in the Ethernet link status (carrier detection).

**Describe the solution you'd like**
Poll link status from the PHY and report changes through `net_eth_carrier_on` and `net_eth_carrier_off`.

NOTE: We are not using interrupts for link status change detection, as PHY IRQ to the CPU is not part of the standard interface (i.e. MII).

**Comment by mrfuchs** [comment] 2020-03-11 14:59
Is this a duplicate of #16096?

**Comment by stephanosio** [comment] 2020-03-11 16:14
> Is this a duplicate of #16096?

It is indeed a duplicate of #16096 🤦‍♂

**Closed** 2020-03-21 13:38 UTC
Labels: Duplicate, area: Drivers, area: Ethernet, area: Networking, enhancement, has-pr, platform: ATMEL
