### ISSUE TITLE
Add support for FVP in CI / SDK

### ISSUE THREAD

**Issue by carlocaione** [zephyrproject-rtos/zephyr#34256] opened 2021-04-13 18:29 UTC
With #33905 just landed and #34252 almost there we should start thinking about adding FVP to the CI / SDK for testing the ARM platforms. Besides the technical issue I'm not sure if the licenses allow that. Anyway, opening this feature request to track this.

**Comment by stephanosio** [comment] 2022-04-27 15:52
Didn't realise this existed.

Although #43852 came later, I will close this since most of the discussions happened there.

**Comment by stephanosio** [comment] 2022-04-27 15:52
Duplicate of #43852

**Closed by stephanosio** 2022-04-27 15:52 UTC
Labels: Enhancement, Feature Request, area: Testsuite
