### ISSUE TITLE
zephyr stm32wb55_ble sample not working 

### ISSUE THREAD

**Issue by athulksriod** [zephyrproject-rtos/zephyr#82394] opened 2024-12-02 07:39 UTC
Hi all , this is i got when running the stm32wb_ble sample code  #zephyr #stm32wb55 #ble
*** BStarting Beacon Demo

[00:00:03.127,000] �[1;31m os: ***** USAGE FAULT *****�[0m

[00:00:03.127,000] �[1;31m os: Illegal use of the EPSR�[0m

[00:00:03.127,000] �[1;31m os: r0/a1: 0x0800c69c r1/a2: 0x20003108 r2/a
3: 0x00080000�[0m

[00:00:03.127,000] �[1;31m os: r3/a4: 0x00000000 r12/ip: 0x200002e0 r14/l
r: 0x08005b21�[0m

[00:00:03.127,000] �[1;31m os: xpsr: 0x20000000�[0m

[00:00:03.127,000] �[1;31m os: Faulting instruction address (r15/pc): 0x000
00000�[0m

[00:00:03.127,000] �[1;31m os: >>> ZEPHYR FATAL ERROR 35: Unknown error on
CPU 0�[0m

[00:00:03.127,000] �[1;31m os: Current thread: 0x20000a80 (unknown)�[0m

[00:00:03.186,000] �[1;31m os: Halting system�[0m

i update the m0 core with stm32wb5x_BLE_HCILayer_fw V1.15.0 but the code getting stuck in FUNC_NORETURN __weak void arch_system_halt(unsigned int reason) function the reason is 35 

/* LCOV_EXCL_START */
FUNC_NORETURN __weak void arch_system_halt(unsigned int reason)
{
	ARG_UNUSED(reason);

	/* TODO: What's the best way to totally halt the system if SMP
	 * is enabled?
	 */

	(void)arch_irq_lock();
	for (;;) {
		/* Spin endlessly */
	}
}

in this infinte for loop @erwango

**Comment by erwango** [comment] 2024-12-02 08:07
Duplicate of #82395

**Closed by erwango** 2024-12-02 08:07 UTC
