### ISSUE TITLE
tests/lib/c_lib/thrd/ fails on multiple platforms

### ISSUE THREAD

**Issue by gbarkadiusz** [zephyrproject-rtos/zephyr#65472] opened 2023-11-20 13:43 UTC
**Describe the bug**
This test fails on a several platforms with different symptoms.
```
CAVS 25
tests/lib/c_lib/thrd/libraries.libc.c11_threads.minimal  ( Failed )
tests/lib/c_lib/thrd/libraries.libc.c11_threads.picolibc   ( Timeout )
tests/lib/c_lib/thrd/libraries.libc.c11_threads.picolibc.module  ( Timeout )
tests/lib/c_lib/thrd/libraries.libc.c11_threads.picolibc.notls  ( Failed )
```

```
ACE 15 MTL 
tests/lib/c_lib/thrd/libraries.libc.c11_threads.minimal ( Failed )
tests/lib/c_lib/thrd/libraries.libc.c11_threads.picolibc ( Failed )
tests/lib/c_lib/thrd/libraries.libc.c11_threads.picolibc.module ( Failed )
tests/lib/c_lib/thrd/libraries.libc.c11_threads.picolibc.notls ( Failed )
tests/lib/c_lib/thrd/libraries.libc.c11_threads.newlib ( Failed )
```
```
UP SQUARED 
tests/lib/c_lib/thrd/libraries.libc.c11_threads.minimal ( Failed )
tests/lib/c_lib/thrd/libraries.libc.c11_threads.picolibc.notls ( Failed )
```

**To Reproduce**
The different steps for different platforms:
In general:
` twister --device-testing  --hardware-map <path_to>/map.yml -p <platform> -T tests/lib/c_lib/thrd -vv`

**Logs and console output**
`/twister-out/up_squared/tests/lib/c_lib/thrd/libraries.libc.c11_threads.minimal/handler.log`
```
***** delaying boot 500ms (per build configuration) *****
*** Booting Zephyr OS build zephyr-v3.5.0-2033-gde63da0081dd (delayed boot 500ms) ***
Running TESTSUITE libc_cnd
===================================================================
START - test_cnd_broadcast_wait
PASS - test_cnd_broadcast_wait in 0.101 seconds
===================================================================
START - test_cnd_errors
PASS - test_cnd_errors in 0.001 seconds
===================================================================
START - test_cnd_init_destroy
PASS - test_cnd_init_destroy in 0.001 seconds
===================================================================
START - test_cnd_signal_timedwait
PASS - test_cnd_signal_timedwait in 0.051 seconds
===================================================================
START - test_cnd_signal_wait
PASS - test_cnd_signal_wait in 0.051 seconds
===================================================================
START - test_cnd_timedwait_timeout
E: Timeout waiting on cond 0x128140
PASS - test_cnd_timedwait_timeout in 0.204 seconds
===================================================================
TESTSUITE libc_cnd succeeded
Running TESTSUITE libc_mtx
===================================================================
START - test_mtx_destroy
PASS - test_mtx_destroy in 0.001 seconds
===================================================================
START - test_mtx_init
PASS - test_mtx_init in 0.001 seconds
===================================================================
START - test_mtx_lock
PASS - test_mtx_lock in 0.001 seconds
===================================================================
START - test_mtx_timedlock
Expecting timedlock with timeout of 200 ms to fail
E: Timeout locking mutex 0x128220
Expecting timedlock with timeout of 200 ms to succeed after 100ms
PASS - test_mtx_timedlock in 0.316 seconds
===================================================================
START - test_mtx_trylock
E: k_mutex_unlock() failed: -16
PASS - test_mtx_trylock in 0.004 seconds
===================================================================
START - test_mtx_unlock
E: Mutex is invalid (b105f00d)
PASS - test_mtx_unlock in 0.004 seconds
===================================================================
TESTSUITE libc_mtx succeeded
Running TESTSUITE libc_once
===================================================================
START - test_call_once
PASS - test_call_once in 0.001 seconds
===================================================================
TESTSUITE libc_once succeeded
Running TESTSUITE libc_thrd
===================================================================
START - test_thrd_create_join
PASS - test_thrd_create_join in 0.001 seconds
===================================================================
START - test_thrd_current_equal
PASS - test_thrd_current_equal in 0.001 seconds
===================================================================
START - test_thrd_detach
E: Pthread 0x1286c0 is not a joinable
E: Pthread claims to be initialized (80000001)
PASS - test_thrd_detach in 0.109 seconds
===================================================================
START - test_thrd_exit
PASS - test_thrd_exit in 0.001 seconds
===================================================================
START - test_thrd_reuse
PASS - test_thrd_reuse in 0.002 seconds
===================================================================
START - test_thrd_sleep
sleeping 0 ms
sleeping 100 ms
Assertion failed at WEST_TOPDIR/os.rtos.zephyr.zephyr/tests/lib/c_lib/thrd/src/thrd.c:37: libc_thrd_test_thrd_sleep: end - start >= delay_ms[i] is false
FAIL - test_thrd_sleep in 0.019 seconds
===================================================================
START - test_thrd_yield
PASS - test_thrd_yield in 0.001 seconds
===================================================================
TESTSUITE libc_thrd failed.
Running TESTSUITE libc_tss
===================================================================
START - test_tss_create_delete
PASS - test_tss_create_delete in 0.001 seconds
===================================================================
START - test_tss_get_set
E: Invalid pthread (80000006)
E: Invalid pthread (80000006)
E: Invalid pthread (80000006)
PASS - test_tss_get_set in 0.010 seconds
===================================================================
TESTSUITE libc_tss succeeded
------ TESTSUITE SUMMARY START ------
SUITE PASS - 100.00% [libc_cnd]: pass = 6, fail = 0, skip = 0, total = 6 duration = 0.409 seconds
- PASS - [libc_cnd.test_cnd_broadcast_wait] duration = 0.101 seconds
- PASS - [libc_cnd.test_cnd_errors] duration = 0.001 seconds
- PASS - [libc_cnd.test_cnd_init_destroy] duration = 0.001 seconds
- PASS - [libc_cnd.test_cnd_signal_timedwait] duration = 0.051 seconds
- PASS - [libc_cnd.test_cnd_signal_wait] duration = 0.051 seconds
- PASS - [libc_cnd.test_cnd_timedwait_timeout] duration = 0.204 seconds
SUITE PASS - 100.00% [libc_mtx]: pass = 6, fail = 0, skip = 0, total = 6 duration = 0.327 seconds
- PASS - [libc_mtx.test_mtx_destroy] duration = 0.001 seconds
- PASS - [libc_mtx.test_mtx_init] duration = 0.001 seconds
- PASS - [libc_mtx.test_mtx_lock] duration = 0.001 seconds
- PASS - [libc_mtx.test_mtx_timedlock] duration = 0.316 seconds
- PASS - [libc_mtx.test_mtx_trylock] duration = 0.004 seconds
- PASS - [libc_mtx.test_mtx_unlock] duration = 0.004 seconds
SUITE PASS - 100.00% [libc_once]: pass = 1, fail = 0, skip = 0, total = 1 duration = 0.001 seconds
- PASS - [libc_once.test_call_once] duration = 0.001 seconds
SUITE FAIL -  85.71% [libc_thrd]: pass = 6, fail = 1, skip = 0, total = 7 duration = 0.134 seconds
- PASS - [libc_thrd.test_thrd_create_join] duration = 0.001 seconds
- PASS - [libc_thrd.test_thrd_current_equal] duration = 0.001 seconds
- PASS - [libc_thrd.test_thrd_detach] duration = 0.109 seconds
- PASS - [libc_thrd.test_thrd_exit] duration = 0.001 seconds
- PASS - [libc_thrd.test_thrd_reuse] duration = 0.002 seconds
- FAIL - [libc_thrd.test_thrd_sleep] duration = 0.019 seconds
- PASS - [libc_thrd.test_thrd_yield] duration = 0.001 seconds
SUITE PASS - 100.00% [libc_tss]: pass = 2, fail = 0, skip = 0, total = 2 duration = 0.011 seconds
- PASS - [libc_tss.test_tss_create_delete] duration = 0.001 seconds
- PASS - [libc_tss.test_tss_get_set] duration = 0.010 seconds
------ TESTSUITE SUMMARY END ------
===================================================================
RunID: 8c65313215d86c1a1da52a982b123bdf
PROJECT EXECUTION FAILED
```

`/twister-out/intel_adsp_cavs25/tests/lib/c_lib/thrd/libraries.libc.c11_threads.newlib/handler.log`
```
***** delaying boot 500ms (per build configuration) *****
*** Booting Zephyr OS build zephyr-v3.5.0-2033-gde63da0081dd (delayed boot 500ms) ***
Running TESTSUITE libc_cnd
===================================================================
START - test_cnd_broadcast_wait
PASS - test_cnd_broadcast_wait in 0.101 seconds
===================================================================
START - test_cnd_errors
PASS - test_cnd_errors in 0.001 seconds
===================================================================
START - test_cnd_init_destroy
PASS - test_cnd_init_destroy in 0.001 seconds
===================================================================
START - test_cnd_signal_timedwait
PASS - test_cnd_signal_timedwait in 0.051 seconds
===================================================================
START - test_cnd_signal_wait
PASS - test_cnd_signal_wait in 0.051 seconds
===================================================================
START - test_cnd_timedwait_timeout
E: Timeout waiting on cond 0x9e028b74
PASS - test_cnd_timedwait_timeout in 0.201 seconds
===================================================================
TESTSUITE libc_cnd succeeded
Running TESTSUITE libc_mtx
===================================================================
START - test_mtx_destroy
PASS - test_mtx_destroy in 0.001 seconds
===================================================================
START - test_mtx_init
PASS - test_mtx_init in 0.001 seconds
===================================================================
START - test_mtx_lock
PASS - test_mtx_lock in 0.001 seconds
===================================================================
START - test_mtx_timedlock
Expecting timedlock with timeout of 200 ms to fail
E: Mutex is invalid (be012d48)
Assertion failed at WEST_TOPDIR/os.rtos.zephyr.zephyr/tests/lib/c_lib/thrd/src/mtx.c:124: libc_mtx_test_mtx_timedlock: thrd_timedout not equal to ret
FAIL - test_mtx_timedlock in 0.001 seconds
===================================================================
START - test_mtx_trylock
E: k_mutex_unlock() failed: -16
PASS - test_mtx_trylock in 0.001 seconds
===================================================================
START - test_mtx_unlock
E: Mutex is invalid (b105f00d)
PASS - test_mtx_unlock in 0.001 seconds
===================================================================
TESTSUITE libc_mtx failed.
Running TESTSUITE libc_once
===================================================================
START - test_call_once
PASS - test_call_once in 0.001 seconds
===================================================================
TESTSUITE libc_once succeeded
Running TESTSUITE libc_thrd
===================================================================
START - test_thrd_create_join
Assertion failed at WEST_TOPDIR/os.rtos.zephyr.zephyr/tests/lib/c_lib/thrd/src/thrd.c:74: libc_thrd_test_thrd_create_join: (BIOS_FOOD not equal to x)
expected: -1325010931 actual: 0
FAIL - test_thrd_create_join in 0.001 seconds
===================================================================
START - test_thrd_current_equal
PASS - test_thrd_current_equal in 0.001 seconds
===================================================================
START - test_thrd_detach
E: Pthread 0x9e028040 is not a joinable
E: Pthread claims to be initialized (80000000)
PASS - test_thrd_detach in 0.101 seconds
===================================================================
START - test_thrd_exit
Assertion failed at WEST_TOPDIR/os.rtos.zephyr.zephyr/tests/lib/c_lib/thrd/src/thrd.c:99: libc_thrd_test_thrd_exit: BIOS_FOOD not equal to x
FAIL - test_thrd_exit in 0.001 seconds
===================================================================
START - test_thrd_reuse
PASS - test_thrd_reuse in 0.004 seconds
===================================================================
START - test_thrd_sleep
sleeping 0 ms
sleeping 100 ms
sleeping 200 ms
sleeping 400 ms
PASS - test_thrd_sleep in 3.854 seconds
===================================================================
START - test_thrd_yield
PASS - test_thrd_yield in 0.001 seconds
===================================================================
TESTSUITE libc_thrd failed.
Running TESTSUITE libc_tss
===================================================================
START - test_tss_create_delete
PASS - test_tss_create_delete in 0.001 seconds
===================================================================
START - test_tss_get_set
E: Invalid pthread (80000005)
E: Invalid pthread (80000005)
E: Invalid pthread (80000005)
PASS - test_tss_get_set in 0.001 seconds
===================================================================
TESTSUITE libc_tss succeeded
------ TESTSUITE SUMMARY START ------
SUITE PASS - 100.00% [libc_cnd]: pass = 6, fail = 0, skip = 0, total = 6 duration = 0.406 seconds
- PASS - [libc_cnd.test_cnd_broadcast_wait] duration = 0.101 seconds
- PASS - [libc_cnd.test_cnd_errors] duration = 0.001 seconds
- PASS - [libc_cnd.test_cnd_init_destroy] duration = 0.001 seconds
- PASS - [libc_cnd.test_cnd_signal_timedwait] duration = 0.051 seconds
- PASS - [libc_cnd.test_cnd_signal_wait] duration = 0.051 seconds
- PASS - [libc_cnd.test_cnd_timedwait_timeout] duration = 0.201 seconds
SUITE FAIL -  83.33% [libc_mtx]: pass = 5, fail = 1, skip = 0, total = 6 duration = 0.006 seconds
- PASS - [libc_mtx.test_mtx_destroy] duration = 0.001 seconds
- PASS - [libc_mtx.test_mtx_init] duration = 0.001 seconds
- PASS - [libc_mtx.test_mtx_lock] duration = 0.001 seconds
- FAIL - [libc_mtx.test_mtx_timedlock] duration = 0.001 seconds
- PASS - [libc_mtx.test_mtx_trylock] duration = 0.001 seconds
- PASS - [libc_mtx.test_mtx_unlock] duration = 0.001 seconds
SUITE PASS - 100.00% [libc_once]: pass = 1, fail = 0, skip = 0, total = 1 duration = 0.001 seconds
- PASS - [libc_once.test_call_once] duration = 0.001 seconds
SUITE FAIL -  71.43% [libc_thrd]: pass = 5, fail = 2, skip = 0, total = 7 duration = 3.963 seconds
- FAIL - [libc_thrd.test_thrd_create_join] duration = 0.001 seconds
- PASS - [libc_thrd.test_thrd_current_equal] duration = 0.001 seconds
- PASS - [libc_thrd.test_thrd_detach] duration = 0.101 seconds
- FAIL - [libc_thrd.test_thrd_exit] duration = 0.001 seconds
- PASS - [libc_thrd.test_thrd_reuse] duration = 0.004 seconds
- PASS - [libc_thrd.test_thrd_sleep] duration = 3.854 seconds
- PASS - [libc_thrd.test_thrd_yield] duration = 0.001 seconds
SUITE PASS - 100.00% [libc_tss]: pass = 2, fail = 0, skip = 0, total = 2 duration = 0.002 seconds
- PASS - [libc_tss.test_tss_create_delete] duration = 0.001 seconds
- PASS - [libc_tss.test_tss_get_set] duration = 0.001 seconds
------ TESTSUITE SUMMARY END ------
===================================================================
RunID: 632b6d0ba6e8b65f618c8df94ee23093
PROJECT EXECUTION FAILED
```

`/twister-out/intel_adsp_ace15_mtpm/tests/lib/c_lib/thrd/libraries.libc.c11_threads.picolibc.notls/handler.log`
```
*** Booting Zephyr OS build zephyr-v3.5.0-2033-gde63da0081dd (delayed boot 500ms) ***
Running TESTSUITE libc_cnd
===================================================================
START - test_cnd_broadcast_wait
PASS - test_cnd_broadcast_wait in 0.101 seconds
===================================================================
START - test_cnd_errors
PASS - test_cnd_errors in 0.001 seconds
===================================================================
START - test_cnd_init_destroy
PASS - test_cnd_init_destroy in 0.001 seconds
===================================================================
START - test_cnd_signal_timedwait
PASS - test_cnd_signal_timedwait in 0.051 seconds
===================================================================
START - test_cnd_signal_wait
PASS - test_cnd_signal_wait in 0.051 seconds
===================================================================
START - test_cnd_timedwait_timeout
E: Timeout waiting on cond 0x40047c84
PASS - test_cnd_timedwait_timeout in 0.201 seconds
===================================================================
TESTSUITE libc_cnd succeeded
Running TESTSUITE libc_mtx
===================================================================
START - test_mtx_destroy
PASS - test_mtx_destroy in 0.001 seconds
===================================================================
START - test_mtx_init
PASS - test_mtx_init in 0.001 seconds
===================================================================
START - test_mtx_lock
PASS - test_mtx_lock in 0.001 seconds
===================================================================
START - test_mtx_timedlock
Expecting timedlock with timeout of 200 ms to fail
E: Mutex is invalid (a0033c58)
Assertion failed at WEST_TOPDIR/os.rtos.zephyr.zephyr/tests/lib/c_lib/thrd/src/mtx.c:124: libc_mtx_test_mtx_timedlock: thrd_timedout not equal to ret
FAIL - test_mtx_timedlock in 0.001 seconds
===================================================================
START - test_mtx_trylock
E: Mutex is invalid (a0033c52)
Assertion failed at WEST_TOPDIR/os.rtos.zephyr.zephyr/tests/lib/c_lib/thrd/src/mtx.c:159: libc_mtx_test_mtx_trylock: thrd_busy not equal to ret
FAIL - test_mtx_trylock in 0.001 seconds
===================================================================
START - test_mtx_unlock
E: Mutex is invalid (b105f00d)
PASS - test_mtx_unlock in 0.001 seconds
===================================================================
TESTSUITE libc_mtx failed.
Running TESTSUITE libc_once
===================================================================
START - test_call_once
PASS - test_call_once in 0.001 seconds
===================================================================
TESTSUITE libc_once succeeded
Running TESTSUITE libc_thrd
===================================================================
START - test_thrd_create_join
Assertion failed at WEST_TOPDIR/os.rtos.zephyr.zephyr/tests/lib/c_lib/thrd/src/thrd.c:74: libc_thrd_test_thrd_create_join: (BIOS_FOOD not equal to x)
expected: -1325010931 actual: 0
FAIL - test_thrd_create_join in 0.001 seconds
===================================================================
START - test_thrd_current_equal
PASS - test_thrd_current_equal in 0.001 seconds
===================================================================
START - test_thrd_detach
E: Pthread 0x40047040 is not a joinable
E: Pthread claims to be initialized (80000000)
PASS - test_thrd_detach in 0.101 seconds
===================================================================
START - test_thrd_exit
Assertion failed at WEST_TOPDIR/os.rtos.zephyr.zephyr/tests/lib/c_lib/thrd/src/thrd.c:99: libc_thrd_test_thrd_exit: BIOS_FOOD not equal to x
FAIL - test_thrd_exit in 0.001 seconds
===================================================================
START - test_thrd_reuse
PASS - test_thrd_reuse in 0.003 seconds
===================================================================
START - test_thrd_sleep
sleeping 0 ms
sleeping 100 ms
sleeping 200 ms
sleeping 400 ms
PASS - test_thrd_sleep in 0.877 seconds
===================================================================
START - test_thrd_yield
PASS - test_thrd_yield in 0.001 seconds
===================================================================
TESTSUITE libc_thrd failed.
Running TESTSUITE libc_tss
===================================================================
START - test_tss_create_delete
PASS - test_tss_create_delete in 0.001 seconds
===================================================================
START - test_tss_get_set
E: Invalid pthread (80000005)
E: Invalid pthread (80000005)
E: Invalid pthread (80000005)
PASS - test_tss_get_set in 0.001 seconds
===================================================================
TESTSUITE libc_tss succeeded
------ TESTSUITE SUMMARY START ------
SUITE PASS - 100.00% [libc_cnd]: pass = 6, fail = 0, skip = 0, total = 6 duration = 0.406 seconds
- PASS - [libc_cnd.test_cnd_broadcast_wait] duration = 0.101 seconds
- PASS - [libc_cnd.test_cnd_errors] duration = 0.001 seconds
- PASS - [libc_cnd.test_cnd_init_destroy] duration = 0.001 seconds
- PASS - [libc_cnd.test_cnd_signal_timedwait] duration = 0.051 seconds
- PASS - [libc_cnd.test_cnd_signal_wait] duration = 0.051 seconds
- PASS - [libc_cnd.test_cnd_timedwait_timeout] duration = 0.201 seconds
SUITE FAIL -  66.67% [libc_mtx]: pass = 4, fail = 2, skip = 0, total = 6 duration = 0.006 seconds
- PASS - [libc_mtx.test_mtx_destroy] duration = 0.001 seconds
- PASS - [libc_mtx.test_mtx_init] duration = 0.001 seconds
- PASS - [libc_mtx.test_mtx_lock] duration = 0.001 seconds
- FAIL - [libc_mtx.test_mtx_timedlock] duration = 0.001 seconds
- FAIL - [libc_mtx.test_mtx_trylock] duration = 0.001 seconds
- PASS - [libc_mtx.test_mtx_unlock] duration = 0.001 seconds
SUITE PASS - 100.00% [libc_once]: pass = 1, fail = 0, skip = 0, total = 1 duration = 0.001 seconds
- PASS - [libc_once.test_call_once] duration = 0.001 seconds
SUITE FAIL -  71.43% [libc_thrd]: pass = 5, fail = 2, skip = 0, total = 7 duration = 0.985 seconds
- FAIL - [libc_thrd.test_thrd_create_join] duration = 0.001 seconds
- PASS - [libc_thrd.test_thrd_current_equal] duration = 0.001 seconds
- PASS - [libc_thrd.test_thrd_detach] duration = 0.101 seconds
- FAIL - [libc_thrd.test_thrd_exit] duration = 0.001 seconds
- PASS - [libc_thrd.test_thrd_reuse] duration = 0.003 seconds
- PASS - [libc_thrd.test_thrd_sleep] duration = 0.877 seconds
- PASS - [libc_thrd.test_thrd_yield] duration = 0.001 seconds
SUITE PASS - 100.00% [libc_tss]: pass = 2, fail = 0, skip = 0, total = 2 duration = 0.002 seconds
- PASS - [libc_tss.test_tss_create_delete] duration = 0.001 seconds
- PASS - [libc_tss.test_tss_get_set] duration = 0.001 seconds
------ TESTSUITE SUMMARY END ------
===================================================================
RunID: ae16559e6dc6c32cd229b2b0caa26312
PROJECT EXECUTION FAILED
```
**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK 0.16.3

**Comment by nashif** [comment] 2023-11-21 23:36
This is suspected to be SMP related, i.e. it passes on some of those platforms with CONFIG_SMP=n

**Comment by nashif** [comment] 2023-11-21 23:36
@peter-mitsis  FYI

**Comment by peter-mitsis** [comment] 2023-11-22 21:02
FWIW, I have reproduced the failures on the intel_adsp_ace15_mtpm. Those, failures _could_ be SMP related, however the output is raising an eyebrow ...

```
E: Timeout locking mutex 0xnnnnnnnn  # Passing case
vs
E: Mutex is invalid (nnnnnnnn)           # Failing case
```

Why would we be getting an invalid mutex message? I could be wrong, but my spidey-sense suspects that an incoherent cache is coming into play--that is, one CPU is attempting to access the stack of a thread running on another CPU. (That problem does not exist on uniprocessor xtensa systems).

Digging into this ....

**Comment by peter-mitsis** [comment] 2023-11-22 21:22
The xtensa cache thing is coming into play again. Take test_mtx_timedlock() for example. It creates a mutex on the stack of one thread, and then accesses it from another. Since on an Xtensa SMP system, that is likely to be on another CPU we have the not-so-good scenario of a thread on one CPU accessing stack memory of a thread running on another CPU (not so good because that memory is guaranteed to be kept in sync in that circumstance).

To get around this, either we would need to fix the tests so that the objects being tested are global objects (and thus not on the stack), or prevent this set of tests from being executed on xtensa platforms (which would arguably leave a testing hole).

As for the up_squared failure ... I have not delved into that one.

**Comment by cfriedt** [comment] 2023-11-23 02:10
> To get around this, either we would need to fix the tests so that the objects being tested are global objects (and thus not on the stack), or

That's exactly what I was thinking. I kind of suspected it was something like that. Not an extensive xtensa user unfortunately.

@peter-mitsis - Do you want to go for it, or should I?

**Comment by peter-mitsis** [comment] 2023-11-28 21:01
Closing.

**Closed by peter-mitsis** 2023-11-28 21:01 UTC
Labels: bug, priority: medium, area: C Library
