### ISSUE TITLE
Mesh Friend does not reply within ReceiveWindow

### ISSUE THREAD

**Issue by thomasstenersen** [zephyrproject-rtos/zephyr#11681] opened 2018-11-27 11:25 UTC
When using (for example) a receive window of 40ms (`CONFIG_BT_MESH_FRIEND_RECV_WIN=40`) the Friend is not able to reply to the LPN's poll within the receive window. Measuring over multiple polls, with a receive window of 40ms the friend replies between 20-60ms _after_ the receive window has ended.

This behavior is observed with the `samples/bluetooth/mesh` example (at `v1.13.0`) using `CONFIG_BT_MESH_FRIEND_RECV_WIN=40` and the friend feature enabled. 

In the screenshot below, the second channel indicates the TX of the Friend Poll from the LPN, the first channel is the Radio RX and the last channel the TX of the Friend. From the timing marker pair, the Friend responds to the Poll >40ms too late.
![image](https://user-images.githubusercontent.com/14885384/49078687-f3fae380-f23e-11e8-9541-bf691a5b9db3.png)

**Comment by jhedberg** [comment] 2018-11-27 11:32
As discussed in Slack, this is largely because standard HCI doesn't give us good enough timing control for scanning and advertising. You're lucky that you're using a combined build, since having split host & controller with a physical HCI in between (e.g. over USB or UART) will likely make this even worse.

I think what we should do is to introduce a similar Kconfig variable for Friend as we have for LPN in the form of BT_MESH_LPN_SCAN_LATENCY, i.e. something to specify the expected latency of requesting advertising to the advertising actually happening. This might be a bit trickier and inherently unreliable however, since advertising happens through a queue, i.e. if there are other advertising packets in the queue the Friend Update will need to wait for those.

**Comment by jhedberg** [comment] 2018-11-27 12:19
@thomasstenersen are you able to experiment to see if a fixed delay (let's call it e.g. CONFIG_BT_MESH_FRIEND_SEND_LATENCY) solves this for you, or if the latency you can see with sending the responses varies too much?

**Comment by jhedberg** [comment] 2018-11-27 12:21
@thomasstenersen btw, I think we'd also need to have some code to ignore Friend requests if the LPN is requesting a ReceiveDelay that's smaller than the configured CONFIG_BT_MESH_FRIEND_SEND_LATENCY.

**Comment by thomasstenersen** [comment] 2018-11-27 12:32
@jhedberg Not able to do any experimentation on it right now, unfortunately, but it sounds like something that might help. The core underlying issue is, as you point out, the limitations of the HCI interface. In addition, the Friend needs to be able to essentially preempt the outgoing packet queue to be able to always meet the deadline of the ReceiveWindow. Otherwise the ability of the Friend to meet its deadline is going to be completely arbitrary. The CONFIG_BT_MESH_FRIEND_SEND_LATENCY is not going to fix that. It's mostly not a problem on the LPN side because it won't have much else going on (it is supposed to be sleeping).

**Comment by jhedberg** [comment] 2018-11-27 12:41
@thomasstenersen it's not a problem for LPN or any other Mesh messaging since I think Friend is the only one with very strict requirements on when a packet should be going out over the advertising bearer. An LPN can send a packet at any time, as long as it doesn't do it too close to the Friend Timeout expiring (e.g. Zephyr starts sending Friend Updates well in advance because of this).

**Comment by jhedberg** [comment] 2018-11-27 12:42
@thomasstenersen this is also why I'd make the new Kconfig option Friend-specific rather than having something more generic.

**Comment by thomasstenersen** [comment] 2018-11-27 13:09
@jhedberg I might have been a bit unclear. I don't see a real problem for the LPN or normal mesh transmissions. But for the Friend, the problems are
- poor control over advertisement timing, e.g., "I want to send packed `PDU` at time `X`"
- lack of preemption for Friend PDUs. If you receive a Friend Poll, you need to be able to transmit a PDU at a given point in time, but you don't know what else might be in the packet queue at that point

The last point is not super-critical unless you always miss the receive window because of other packets filling up the outgoing queue. Alas, it is not straight forward to solve any of these "properly", but using CONFIG_BT_MESH_FRIEND_SEND_LATENCY to control the average case could certainly help :)

Perhaps I've got some misconceptions about the architecture and inner workings here, so let me know if so.

**Comment by jhedberg** [comment] 2018-11-30 11:32
I've hooked up a logic analyzer to an nRF52840 PDK, enabled `CONFIG_BT_CTLR_DEBUG_PINS=y`, and modified some of the debug pins to map to host-side behavior. My findings are as follows:

 - It takes 40-60ms from the host issuing a bt_le_adv_start() until the controller actually transmits the first advertising packet. This implies that if we introduce a FRIEND_SEND_LATENCY Kconfig option the default value for this board should be 40ms.
 - The mapping of "X transmissions wanted" to what the controller actually does is not very accurate. Requesting 3 transmissions gives me 2, requesting 1 gives me 2 as well. This is due to the host having to "guess" how long to let the controller advertise in order to get the right number of advertising packets.
 - Due to the 30ms scan window, even though we request a 20ms advertising interval it may in reality sometimes be close to 70ms.

CC @cvinayak

**Comment by jhedberg** [comment] 2018-11-30 11:35
One other note: the Friend PDUs are defined to be transmitted only once (see FRIEND_XMIT in the beginning of mesh/friend.c), however based on my findings you'll at least sometimes get two transmissions by the controller, perhaps your worst-case was your receiver catching the second one?

**Comment by jhedberg** [comment] 2018-11-30 14:43
Added @cvinayak as a second assignee, since based on my analysis this may need tweaking both on the controller and host side.

@thomasstenersen one thing I discovered is that I can reduce the time it takes for the controller to get an advertising packet transmitted by enabling the following in prj.cont:
```
CONFIG_BT_CTLR_ADVANCED_FEATURES=y
CONFIG_BT_CTLR_JOB_PRIO=1
```

With that change the time to transmit gets reduced roughly by a scan window (which with current master is 30ms).

**Comment by carlescufi** [comment] 2019-08-22 11:22
@trond-snekvik @thomasstenersen can you please retest this with the split controller?

**Comment by trond-snekvik** [comment] 2019-08-26 13:48
Retested this with the new link layer, and it's no longer reproducible. 

I think the performance still has some room for improvement, but the friend responds to every poll it gets (within the assigned window). I think this can be closed as fixed.

**Comment by jhedberg** [comment] 2019-08-26 14:21
@trond-snekvik ok, thanks. I'll close it then. @thomasstenersen please reopen if you disagree.

**Closed by jhedberg** 2019-08-26 14:21 UTC
Labels: area: Bluetooth, area: Bluetooth Mesh, enhancement
