### ISSUE TITLE
tests: tests/crypto/secp256r1: lpcxpresso55s69/lpc55s69/cpu0/ns : build error

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#75835] opened 2024-07-13 03:31 UTC
**Describe the bug**

tests/crypto/secp256r1 crypto.secp256r1.p256-m_raw build error on lpcxpresso55s69/lpc55s69/cpu0/ns

**To Reproduce**

```
scripts/twister -p lpcxpresso55s69/lpc55s69/cpu0/ns -T tests/crypto/secp256r1 -s crypto.secp256r1.p256-m_raw
```

**Expected behavior**

build pass

**Impact**

mbedtls

**Logs and console output**

```
warning: MBEDTLS_PSA_CRYPTO_C (defined at modules/mbedtls/Kconfig.tls-generic:485,
modules/mbedtls/Kconfig.tls-generic:485) was assigned the value 'y' but got the value 'n'. Check
these unsatisfied dependencies: ((!BUILD_WITH_TFM && MBEDTLS_BUILTIN && MBEDTLS_CFG_FILE = "config-
tls-generic.h" && MBEDTLS) || (!BUILD_WITH_TFM && MBEDTLS_BUILTIN && MBEDTLS_CFG_FILE = "config-tls-
generic.h" && MBEDTLS && 0)) (=n). See
http://docs.zephyrproject.org/latest/kconfig.html#CONFIG_MBEDTLS_PSA_CRYPTO_C and/or look up
MBEDTLS_PSA_CRYPTO_C in the menuconfig/guiconfig interface. The Application Development Primer,
Setting Configuration Values, and Kconfig - Tips and Best Practices sections of the manual might be
helpful too.


warning: The choice symbol MBEDTLS_PSA_CRYPTO_EXTERNAL_RNG (defined at modules/mbedtls/Kconfig.tls-
generic:468, modules/mbedtls/Kconfig.tls-generic:468) was selected (set =y), but no symbol ended up
as the choice selection. See
http://docs.zephyrproject.org/latest/kconfig.html#CONFIG_MBEDTLS_PSA_CRYPTO_EXTERNAL_RNG and/or look
up MBEDTLS_PSA_CRYPTO_EXTERNAL_RNG in the menuconfig/guiconfig interface. The Application
Development Primer, Setting Configuration Values, and Kconfig - Tips and Best Practices sections of
the manual might be helpful too.


warning: MBEDTLS_PSA_P256M_DRIVER_ENABLED (defined at modules/mbedtls/Kconfig.tls-generic:509, modules/mbedtls/Kconfig.tls-generic:509) has direct dependencies (MBEDTLS_PSA_CRYPTO_C && MBEDTLS_BUILTIN && MBEDTLS_CFG_FILE = "config-tls-generic.h" && MBEDTLS) || (MBEDTLS_PSA_CRYPTO_C && MBEDTLS_BUILTIN && MBEDTLS_CFG_FILE = "config-tls-generic.h" && MBEDTLS && 0) with value n, but is currently being y-selected by the following symbols:
 - MBEDTLS_PSA_P256M_DRIVER_RAW (defined at modules/mbedtls/Kconfig.tls-generic:517, modules/mbedtls/Kconfig.tls-generic:517), with value y, direct dependencies (MBEDTLS_BUILTIN && MBEDTLS_CFG_FILE = "config-tls-generic.h" && MBEDTLS) || (MBEDTLS_BUILTIN && MBEDTLS_CFG_FILE = "config-tls-generic.h" && MBEDTLS && 0) (value: y), and select condition MBEDTLS_BUILTIN && MBEDTLS_CFG_FILE = "config-tls-generic.h" && MBEDTLS (value: y)
Parsing /home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/Kconfig
Loaded configuration '/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/boards/nxp/lpcxpresso55s69/lpcxpresso55s69_lpc55s69_cpu0_ns_defconfig'
Merged configuration '/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/tests/crypto/secp256r1/prj.conf'
Merged configuration '/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/tests/crypto/secp256r1/p256-m_raw.conf'
Merged configuration '/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/twister-out/lpcxpresso55s69_lpc55s69_cpu0_ns/tests/crypto/secp256r1/crypto.secp256r1.p256-m_raw/zephyr/misc/generated/extra_kconfig_options.conf'

error: Aborting due to Kconfig warnings

CMake Error at cmake/modules/kconfig.cmake:389 (message):
  command failed with return code: 1
Call Stack (most recent call first):
  cmake/modules/zephyr_default.cmake:132 (include)
  share/zephyr-package/cmake/ZephyrConfig.cmake:75 (include)
  share/zephyr-package/cmake/ZephyrConfig.cmake:97 (include_boilerplate)
  cmake/package_helper.cmake:126 (find_package)
```

**Environment (please complete the following information):**

 - OS: (e.g. Linux, )
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: v3.7.0-rc2-465-g488426208876

** Analysis

git bisect find below commit introduces this issue

```
commit 83cd9f5a01664e82d3a0cb062b356b9a4de3e755
Author: Tomi Fontanilles <tomi.fontanilles@nordicsemi.no>
Date:   Thu Jul 4 14:18:26 2024 +0300

    modules: mbedtls: properly guard PSA_CRYPTO_C
    
    Instead of silently `#undef`ing PSA_CRYPTO_C when TF-M is in use,
    enforce that rule at the Kconfig level.
    
    Signed-off-by: Tomi Fontanilles <tomi.fontanilles@nordicsemi.no>

 modules/mbedtls/Kconfig.tls-generic          | 1 +
 modules/mbedtls/configs/config-tls-generic.h | 4 ----
 2 files changed, 1 insertion(+), 4 deletions(-)
```

**Comment by henrikbrixandersen** [comment] 2024-07-13 11:04
Duplicate of #75710?

**Closed** 2024-07-13 14:09 UTC
Labels: bug, platform: NXP
