### ISSUE TITLE
Unable to view PR #6391

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/zephyr#7460] opened 2018-05-10 19:11 UTC
https://github.com/zephyrproject-rtos/zephyr/pull/6391 fails to open and shows the "unicorn" page (page taking too long to load).  I reported this to the GitHub folks.  Are others having the same problem?

**Comment by dbkinder** [comment] 2018-05-10 19:53
GitHub replied: "We've got an issue open internally for our engineers to check out that PR to see what might be going on. We'll update you as soon as we know more.  Cheers, Alex"

**Comment by nashif** [comment] 2018-05-11 01:59
it just has too many comments and content, this has been very common with PRs that have >100 comments

**Comment by dbkinder** [comment] 2018-05-11 05:05
If we can't view it we can't review it and it's stuck open?

**Comment by nashif** [comment] 2018-05-11 13:09
yes, this needs to be fixed on github side, but I can see it an review it by not using the browser.

**Comment by henrikbrixandersen** [comment] 2018-05-13 10:46
FWIW, I can view #6391 fine using Safari on macOS.

**Comment by pswarnak** [comment] 2018-05-14 10:41
I can view it using chrome browser. Possibly, the issue is fixed now. Please check.

**Comment by MaureenHelm** [comment] 2018-05-14 14:28
I got the unicorn too. Chrome and IE11 on Win10.

**Comment by MaureenHelm** [comment] 2018-05-14 14:33
Tagged the priority as low so it doesn't block the zephyr 1.12 release. In reality it's a higher priority than that, but it's not something we can fix ourselves.

**Comment by nashif** [comment] 2018-05-15 08:29
PR is now merged.

**Closed by nashif** 2018-05-15 08:29 UTC
Labels: bug, priority: low
