### ISSUE TITLE
Does not respect python virtualenv

### ISSUE THREAD

**Issue by benjizhai** [zephyrproject-rtos/zephyr#28723] opened 2020-09-28 08:52 UTC
**Describe the bug**
When I run west build from virtualenv, it still detects system python instead of the virtualenv one.

**To Reproduce**
1. activate python venv
2. `west build -b auto -b nrf52840dongle_nrf52840 samples/basic/blinky`

**Logs and console output**
[1/125] Generating include/generated/kobj-types-enum.h, include/generated/otype-to-str.h FAILED: zephyr/include/generated/kobj-types-enum.h zephyr/include/generated/otype-to-str.h cd /home/benji/proj/zephyr/zephyr/build/zephyr && **/usr/bin/python3.8** /home/benji/proj/zephyr/zephyr/scripts/gen_kobject_list.py --kobj-types-output /home/benji/proj/zephyr/zephyr/build/zephyr/include/generated/kobj-types-enum.h --kobj-otype-output /home/benji/proj/zephyr/zephyr/build/zephyr/include/generated/otype-to-str.h --kobj-size-output /home/benji/proj/zephyr/zephyr/build/zephyr/include/generated/otype-to-size.h --include /home/benji/proj/zephyr/zephyr/build/zephyr/misc/generated/struct_tags.json Traceback (most recent call last): File "/home/benji/proj/zephyr/zephyr/scripts/gen_kobject_list.py", line 62, in <module> import elftools ModuleNotFoundError: No module named 'elftools'

**Environment (please complete the following information):**
 - Ubuntu 20.04

**Comment by galak** [comment] 2020-09-29 17:06
@tejlmand / @mbolivar-nordic thoughts?

**Comment by mbolivar-nordic** [comment] 2020-09-29 20:28
dupe of https://github.com/zephyrproject-rtos/west/issues/443

**Closed by mbolivar-nordic** 2020-09-29 20:28 UTC
Labels: area: Build System, bug, priority: low
