### ISSUE TITLE
docs: Search ordering has worsened

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#60624] opened 2023-07-20 10:17 UTC
**Describe the bug**
The doc search system has gone to pot recently, comparing the current `latest` and `3.3` when searching for GPIO yields very different results.
Latest: https://docs.zephyrproject.org/latest/search.html?q=gpio&check_keywords=yes&area=default
3.3: https://docs.zephyrproject.org/3.3.0/search.html?q=gpio&check_keywords=yes&area=default

The correct result, for the GPIO page, is 20th in the latest (and 3.4) results, it is 2nd in the 3.3 docs.

**To Reproduce**
Search

**Expected behavior**
The relevant (in this case GPIO) page to be near the top

**Impact**
Annoyance

**Comment by gmarull** [comment] 2023-07-20 11:32
I think there's an important point to make here:

The GPIO page title changed from `GPIO` to `General-Purpose Input/Output (GPIO)`:

https://docs.zephyrproject.org/latest/hardware/peripherals/gpio.html
https://docs.zephyrproject.org/3.3.0/hardware/peripherals/gpio.html

So this is likely not a new issue.

**Comment by gmarull** [comment] 2023-07-20 11:37
Also, FYI https://github.com/zephyrproject-rtos/zephyr/pull/60018

**Comment by kartben** [comment] 2023-07-20 16:55
> So this is likely not a new issue.

+1. @nordicjm unless you are seeing other examples of regressions like this one, I think we can close this.

**Comment by nordicjm** [comment] 2023-07-21 06:35
> > So this is likely not a new issue.
> 
> +1. @nordicjm unless you are seeing other examples of regressions like this one, I think we can close this.

It's an issue, I don't see why it should be closed, regardless if it's one search item or multiple.

> Also, FYI #60018

Having an absolutely invasive company's search engine is not a solution to anything

**Comment by kartben** [comment] 2023-07-21 06:37
> > > So this is likely not a new issue.
> > 
> > +1. @nordicjm unless you are seeing other examples of regressions like this one, I think we can close this.
> 
> It's an issue, I don't see why it should be closed, regardless if it's one search item or multiple.

At least can we agree it's a dupe of #55173? :)

**Comment by nordicjm** [comment] 2023-07-21 06:38
> > > > So this is likely not a new issue.
> > > 
> > > 
> > > +1. @nordicjm unless you are seeing other examples of regressions like this one, I think we can close this.
> > 
> > 
> > It's an issue, I don't see why it should be closed, regardless if it's one search item or multiple.
> 
> At least can we agree it's a dupe of #55173? :)

Yes, dupe of that

**Closed** 2023-07-21 08:43 UTC
Labels: bug, priority: low, area: Documentation
