### ISSUE TITLE
is there some code snap show how to enum multi usb hid interface in one device?

### ISSUE THREAD

**Issue by chopin1998** [zephyrproject-rtos/zephyr#12060] opened 2018-12-13 07:25 UTC
i wanna use my cortex m4 as a usb device, i hope it has several(3-4) USB hid interface i can send sensor data to computer? 

Is ther some example to show that?

**Comment by carlescufi** [comment] 2019-01-14 10:08
Duplicate of #12432

**Closed by carlescufi** 2019-01-14 10:08 UTC
Labels: area: USB, feature request
