### ISSUE TITLE
sdk: failed to run tests/subsys/logging/log_core_additional

### ISSUE THREAD

**Issue by shaoanxli** [zephyrproject-rtos/zephyr#49609] opened 2022-08-29 06:50 UTC
**Describe the bug**
Failed to run tests/subsys/logging/log_core_additional, only when the sdk version is 0.15.0.
The error occurs on LOG_INF(), but if the CONFIG_LOG_RUNTIME_FILTERING=y in tests/subsys/logging/log_core_additional/log_user.conf file is removed, the test passes. 
The test fails on nsim_em, up_squared, frdm_k64f, the log below is on frdm_k64f.

**To Reproduce**
1. source zephyr-env.sh
2. twister -p frdm_k64f --hardware-map map.yml --device-testing -T tests/subsys/logging/log_core_additional/  -v
3. See error.

**Expected behavior**
Test case should pass as expected.

**Impact**
The test tests/subsys/logging/log_core_additional failed.

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v3.1.0-3953-gdd69eede4353  ***
Running TESTSUITE test_log_core_additional
===================================================================
START - test_log_filter_set
PASS - test_log_filter_set in 0.001 seconds
===================================================================
START - test_log_from_user
[00:00:00.000,000] ^[[1;31m<err> os: ***** BUS FAULT *****^[[0m^M
[00:00:00.000,000] ^[[1;31m<err> os:   Precise data bus error^[[0m^M
[00:00:00.000,000] ^[[1;31m<err> os:   BFAR Address: 0x200025a0^[[0m^M
[00:00:00.000,000] ^[[1;31m<err> os:   NXP MPU error, port 3^[[0m^M
[00:00:00.000,000] ^[[1;31m<err> os:     Mode: User, Data Address: 0x200025a0^[[0m^M
[00:00:00.000,000] ^[[1;31m<err> os:     Type: Read, Master: 0, Regions: 0x8100^[[0m^M
[00:00:00.000,000] ^[[1;31m<err> os: r0/a1:  0x00000001  r1/a2:  0x00000002  r2/a3:  0x20000014^[[0m^M
[00:00:00.000,000] ^[[1;31m<err> os: r3/a4:  0x00000000 r12/ip:  0x0000f283 r14/lr:  0x00000c6f^[[0m^M
[00:00:00.000,000] ^[[1;31m<err> os:  xpsr:  0x21000000^[[0m^M
[00:00:00.000,000] ^[[1;31m<err> os: Faulting instruction address (r15/pc): 0x00000c70^[[0m^M
[00:00:00.000,000] ^[[1;31m<err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0^[[0m^M
[00:00:00.000,000] ^[[1;31m<err> os: Current thread: 0x20000478 (test_log_from_user)^[[0m^M
[00:00:00.114,000] ^[[1;31m<err> os: Halting system^[[0m^M

```

**Environment :**
OS: Linux
Toolchain Zephyr SDK 0.15.0
Commit SHA or Version: ccfe9513ecee

**Comment by stephanosio** [comment] 2022-08-30 16:19
Duplicate of https://github.com/zephyrproject-rtos/zephyr/issues/49213

**Closed by stephanosio** 2022-08-30 16:19 UTC
Labels: bug, platform: NXP, platform: X86, platform: Synopsys
