### ISSUE TITLE
stm32 octospi flash driver

### ISSUE THREAD

**Issue by aradenac** [zephyrproject-rtos/zephyr#48175] opened 2022-07-22 15:23 UTC
**Describe the bug**
Hello, in Zephyr v3.1.0 the sample zephyr/samples/drivers/spi_flash was working fine on b_u585i_iot02a board (MX25LM51245 octospi flash), providing the following output:
![image](https://user-images.githubusercontent.com/22891063/180468982-3cd63a46-9ce5-47d1-8277-b28fb1499e53.png)

But in the current main Zephyr version (commit 5432cac806b4e479a2da55afa30ead927eef3e2b) the sample program seems to be broken. This is the sample new output:
![image](https://user-images.githubusercontent.com/22891063/180469368-d580ac16-dd28-4cd6-bfc7-b4f37cfc8971.png)

While debugging I found out that the flash driver flash_stm32_ospi.c was failing in the function stm32_ospi_config_mem at driver initialization:
![image](https://user-images.githubusercontent.com/22891063/180471212-e081b572-fe52-4501-8e5b-ff7d7e1e2033.png)

Is there a known reason for this regression (a work in progress maybe) ?

Note: In b_u585i_iot02a-common.dtsi changing OSPI_OSPI_MODE to OSPI_SPI_MODE for the "mx25lm51245" node allows the sample to work.

**Comment by galak** [comment] 2022-07-23 04:04
This could be because of device init ordering.  Worth checking the priorities of the flash device, ospi driver, etc to make sure the init ordering is happening correctly.

**Comment by fabiobaltieri** [comment] 2022-07-26 16:18
cc @erwango

**Comment by erwango** [comment] 2022-07-27 10:00
Duplicate of https://github.com/zephyrproject-rtos/zephyr/issues/46740
Should be fixed by https://github.com/zephyrproject-rtos/zephyr/pull/46794.

**Closed by erwango** 2022-07-27 10:00 UTC
Labels: bug, priority: low, platform: STM32
