### ISSUE TITLE
tests/kernel/threads/tls/kernel.threads.tls.userspace failing

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#31262] opened 2021-01-12 16:19 UTC
**Describe the bug**
tests/kernel/threads/tls/kernel.threads.tls.userspace is failed on following targets:
- frdm_k64f
- disco_l475_iot1, nucleo_f429zi (and more STM32 targets)

**To Reproduce**

$ twister  -T tests/kernel/threads/tls/

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v2.4.0-2965-gadb2e982e840  ***
Running test suite thread_tls
===================================================================
START - test_tls
thread 0: result 0 (expecting 0)
thread 1: result 0 (expecting 0)
thread 2: result 0 (expecting 0)
PASS - test_tls
===================================================================
Test suite thread_tls succeeded
Running test suite thread_tls_userspace
===================================================================
START - test_tls_userspace
E: 0x200 is not a valid z_thread_stack_element
E: address is not a known kernel object
E: syscall z_vrfy_k_thread_create failed check: bad stack object
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00000000
E:  xpsr:  0x00000000
E: Faulting instruction address (r15/pc): 0x00000000
E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
E: Current thread: 0x20000318 (unknown)
E: Halting system
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.12.0
 - Commit SHA: zephyr-v2.4.0-2952-g86e98f0894

**Additional context**

**Comment by nashif** [comment] 2021-01-12 18:17
duplicate of #30393

**Closed by nashif** 2021-01-12 18:17 UTC
Labels: area: Kernel, area: Tests, bug, priority: low
