### ISSUE TITLE
nRF52840 DevKit generates USB TX timeout when using HCI_USB

### ISSUE THREAD

**Issue by mike-scott** [zephyrproject-rtos/zephyr#10899] opened 2018-10-29 10:26 UTC
After compiling and flashing samples/bluetooth/hci_usb to the Nordic nRF52840 DevKit I'm seeing a TX timeout when plugging in the USB port.  hciconfig also fails to bring up the interface.

```
[ 9543.906212] usb 2-1: new full-speed USB device number 18 using xhci_hcd
[ 9544.056741] usb 2-1: New USB device found, idVendor=2fe3, idProduct=0100
[ 9544.056744] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 9544.056746] usb 2-1: Product: USB-DEV
[ 9544.056748] usb 2-1: Manufacturer: ZEPHYR
[ 9544.056750] usb 2-1: SerialNumber: 0.01
[ 9546.086129] Bluetooth: hci1: command 0x1002 tx timeout
```

**Comment by mike-scott** [comment] 2018-10-29 10:35
NOTE: Host PC is running Ubuntu 18.04

**Comment by carlescufi** [comment] 2018-10-29 10:53
@mike-scott is this a duplicate of https://github.com/zephyrproject-rtos/zephyr/issues/10678? If so can you close it?

**Comment by mike-scott** [comment] 2018-10-29 11:09
@carlescufi perfect!  will close here.

**Closed** 2018-10-29 11:09 UTC
Labels: area: Bluetooth, bug
