### ISSUE TITLE
testing.ztest.error_hook: fails on lpcxpresso55s16_ns

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#35102] opened 2021-05-11 10:26 UTC
**Describe the bug**
assert error

**To Reproduce**
1. cd tests/ztest/error_hook;mkdir build; cd build
2. cmake -DBOARD=lpcxpresso55s16_ns ..
3. make; make flash

**Expected behavior**
tes pass

**Impact**
ztest error_hook support

**Logs and console output**

testing.ztest.error_hook

```
    *** Booting Zephyr OS build zephyr-v2.5.0-3761-g730acbd6ed85  ***
    Running test suite error_hook_tests
    ===================================================================
    START - test_catch_assert_fail
    ASSERTION FAIL [a != ((void *)0)] @ WEST_TOPDIR/zephyr/tests/ztest/error_hook/src/main.c:41
    	parameter a should not be NULL!
    Caught assert failed
    Assert error expected as part of test case.
     PASS - test_catch_assert_fail in 0.17 seconds
    ===================================================================
    START - test_catch_fatal_error
    case type is 0
    ASSERTION FAIL [esf != ((void *)0)] @ WEST_TOPDIR/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:993
    	ESF could not be retrieved successfully. Shall never occur.
    Caught assert failed
    Assert failed was unexpected, aborting...
    ASSERTION FAIL [esf != ((void *)0)] @ WEST_TOPDIR/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:993
    	ESF could not be retrieved successfully. Shall never occur.
    Caught assert failed
    Assert failed was unexpected, aborting...
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: v2.6.0-rc1

**Comment by hakehuang** [comment] 2021-05-11 10:27
@MaureenHelm , @dleach02 , @mmahadevan108

**Comment by galak** [comment] 2021-05-11 17:11
@hakehuang are you seeing this on lpcxpresso55s69_ns?

**Comment by hakehuang** [comment] 2021-05-12 03:15
> lpcxpresso55s69_ns

@galak  55s69_ns platform does not have required CONFIG_ARCH_HAS_USERSPACE, so I do not test it.

**Comment by henrikbrixandersen** [comment] 2021-05-18 19:51
I cannot reproduce this with the changes in #35416.

**Comment by galak** [comment] 2021-05-19 13:25
Closing this, @hakehuang re-open if you still have an issue since we merged #35416.

**Comment by ABOSTM** [comment] 2021-05-21 12:02
This test is still failed on nucleo_g071rb and nucleo_l073rz despite #35416.
SHA1: 5f61d89233

**Comment by henrikbrixandersen** [comment] 2021-05-21 12:37
> This test is still failed on nucleo_g071rb and nucleo_l073rz despite #35416.
> 
> SHA1: 5f61d89233

Please update the PR (or open a new one?) to reflect which board it is failing on. The problem was fixed for the lpcxpresso55s16.

**Comment by ABOSTM** [comment] 2021-05-21 12:56
OK, I close this issue and opened a new issue: #35540

**Closed by ABOSTM** 2021-05-21 12:56 UTC
Labels: bug, platform: NXP, platform: STM32, priority: low
