### ISSUE TITLE
k_delayed_work_submit_to_queue returns error code when resubmitting previously completed work.

### ISSUE THREAD

**Issue by LuxLuthor** [zephyrproject-rtos/zephyr#22933] opened 2020-02-19 10:58 UTC
**Describe the bug**
k_delayed_work_submit_to_queue returns error code -EALREADY when submitting previously completed task. Tak is submitted successfully. This response is not covered in doc. This should probably be changed to 0 since error code is propagated from k_delayed_work_cancel. 

**Expected behavior**
0 result - work was submitted to queue. 
OR
response described in doc

**Comment by carlescufi** [comment] 2020-02-19 11:06
was this fixed by https://github.com/zephyrproject-rtos/zephyr/pull/22810?
@Vudentz @joerchan @pabigot

**Comment by joerchan** [comment] 2020-02-19 11:18
@LuxLuthor Can you specify which commit you are on?
Maybe it is a regression from #22810?

**Comment by LuxLuthor** [comment] 2020-02-19 11:41
I observe issue on 28298fa06a 
It seems that it is regression from #22810 
Code below causes setting err to -EALREADY although work is send to queue
`	
/* Cancel if work has been submitted */
	if (work->work_q == work_q) {
		err = work_cancel(work);
		/* -EALREADY indicates the work has already completed so this
		 * is likely a recurring work.
		 */
		if (err < 0 && err != -EALREADY) {
			goto done;
		}
	}
`

**Comment by pabigot** [comment] 2020-02-19 12:09
I propose we should revert #22810, fix #22803 by changing the documentation to reflect what the API actually does, and fixing #22756 with the alternative solution from #22769.

**Comment by pabigot** [comment] 2020-02-19 13:45
Clarification: I'm assuming that the bug here is a direct result of the change in API to match documentation by now returning an error from `k_delayed_work_cancel()` where before it returned success.  I take that as a sign that we shouldn't have changed the API in #22810, certainly not at this stage of the release cycle.  @jhedberg 

This particular problem might be fixed by overriding the error return in this case and make it return success value; I don't know, haven't looked closely.  But that won't address any other cases that are going to be discovered.

**Comment by joerchan** [comment] 2020-02-19 15:49
I think using the function added here in #22826 (we could just have it internal) is the way to solve it.
I cannot see a way to reset work->work_q to NULL. work_timeout would not be the right place it seems.

Tested using this approach and that solves it. Thoughts @pabigot @Vudentz ?

```
diff --git a/kernel/work_q.c b/kernel/work_q.c
index 845a2670c8..fba3f36a34 100644
--- a/kernel/work_q.c
+++ b/kernel/work_q.c
@@ -80,6 +80,12 @@ static int work_cancel(struct k_delayed_work *work)
        return 0;
 }
 
+static inline bool k_delayed_work_pending(struct k_delayed_work *work)
+{
+       return !z_is_inactive_timeout(&work->timeout) ||
+              k_work_pending(&work->work);
+}
+
 int k_delayed_work_submit_to_queue(struct k_work_q *work_q,
                                   struct k_delayed_work *work,
                                   s32_t delay)
@@ -94,7 +100,7 @@ int k_delayed_work_submit_to_queue(struct k_work_q *work_q,
        }
 
        /* Cancel if work has been submitted */
-       if (work->work_q == work_q) {
+       if (k_delayed_work_pending(work)) {
                err = work_cancel(work);
                /* -EALREADY indicates the work has already completed so this
                 * is likely a recurring work.
```

**Comment by pabigot** [comment] 2020-02-19 15:53
If we want a quick fix something like this might do it @Vudentz since #22810 left the non-zero `err` value to fall through causing the misbehavior:

```
diff --git a/kernel/work_q.c b/kernel/work_q.c
index 845a2670c8..96cd2f644f 100644
--- a/kernel/work_q.c
+++ b/kernel/work_q.c
@@ -99,7 +99,9 @@ int k_delayed_work_submit_to_queue(struct k_work_q *work_q,
                /* -EALREADY indicates the work has already completed so this
                 * is likely a recurring work.
                 */
-               if (err < 0 && err != -EALREADY) {
+               if (err == -EALREADY) {
+                       err = 0;
+               } else if (err < 0) {
                        goto done;
                }
        }
```

But I'm still not really happy about changing the return value of `k_delayed_work_cancel()` from success to error in this case.  We have no idea who else depends on the existing behavior.

**Closed** 2020-02-20 15:50 UTC
Labels: bug, has-pr, priority: high
