### ISSUE TITLE
Cmake ignores setting CONFIG_ETH_MCUX_0=n in prj.conf

### ISSUE THREAD

**Issue by vakulgarg** [zephyrproject-rtos/zephyr#5143] opened 2017-11-24 05:04 UTC
I am compiling samples/bluetooth/ipsp for frdm_k64f board with following modifications in prj.conf.
The following two lines are added.

+CONFIG_BT=y
+CONFIG_NET_L2_BT=y
+CONFIG_ETH_MCUX_0=n
+CONFIG_NET_L2_ETHERNET=n

In the  zephyr configuration generated ipsp/build/zephyr/.config, I still see CONFIG_ETH_MCUX_0=y.
Thus CONFIG_ETH_MCUX_0 does not get turned off.

**Comment by SebastianBoe** [comment] 2017-11-24 11:33
That is weird, I see that the board's kconfig defaults it to y.

config ETH_MCUX_0
	def_bool y

But CONF_FILE is passed to merge_config.sh after the board's kconfig, so merge_config should override the board's settings. I can't explain this behaviour.

**Comment by vakulgarg** [comment] 2017-11-25 06:34
Thanks for looking into this. Does the problem reproduce at your end?

Regards
Vakul

**Comment by nashif** [comment] 2017-11-25 22:36
this config is being set in the board when networking is enabled, looks like it is not overridable, which is a problem.

**Comment by carlescufi** [comment] 2018-02-06 15:37
I tried to reproduce this but `CONFIG_ETH_MCUX_0` is disabled in my `.config`. Will close this unless someone can reproduce this.

**Comment by nashif** [comment] 2018-02-06 22:53
tried here as well, works as expected, so closing.

**Closed by nashif** 2018-02-06 22:53 UTC
Labels: area: Configuration System, bug, priority: medium
