### ISSUE TITLE
Bluetooth: Extended advertising with one advertising set fails after the first time

### ISSUE THREAD

**Issue by StevenGhe** [zephyrproject-rtos/zephyr#31254] opened 2021-01-12 12:38 UTC
**Describe the bug**
I'm using an extended advertising set with one event (BT_LE_EXT_ADV_START_PARAM(0,1)). However if I call "bt_le_ext_adv_start" again with the same parameters, I get an error: (see picture below)

```
<err> bt_hci_core: Failed to start advertiser
[INIT] failed bt_le_ext_adv_start (err -5) ( <-my own printk log)
``` 

Am I supposed to stop advertising or create a new extended advertising set each event?
The .sent callback in the "bt_le_ext_adv_cb" is called the first time, which makes me believe the advertising has stopped. 
Looking at the documentation, I see nothing else I can do?
I use an Adafruit Feather with a Nordic nRF52840 chip.

What have you tried to diagnose or workaround this issue?
Tried a lot of different methods of triggering this single advertising event. Nothing really changed
Multiple devices have the same behaviour

**To Reproduce**
I've supplied a main.c with some configuration files to test the problem in a .zip below.
The output generated on my device(s) is in the picture below.

**Expected behavior**
Advertising should happen each time. Not just the first time.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)
I'm quite sure I could use (BT_LE_EXT_ADV_START_PARAM(0,0) and stop the advertising myself given I stop it before the second event happened. So not too bad, but I think it could be more efficient using the provided function.

**Logs and console output**
![image](https://user-images.githubusercontent.com/24386096/104320275-65ab4f80-54e2-11eb-81cc-628c1c698c0e.png)
[snippet.zip](https://github.com/zephyrproject-rtos/zephyr/files/5802316/snippet.zip)

Edit: The main.c file is quite messy, I threw everythign related from my own project into the single file. The most interesting parts are at the bottom (main function and BLE advertising method)
Edit2: changed some things requested by Joakim Andersson on Slack

**Environment (please complete the following information):**
 - OS: Win10
 - Toolchain: Zephyr
 - Commit SHA or Version used:
 1e61d3e

**Comment by joerchan** [comment] 2021-01-12 14:24
@cvinayak This seems to be an issue with the controller. The advertiser cannot be restarted after it has been terminated in the controller by a timeout or number of events limit.
The advertising set terminated event has been given to the host.

A simple test in the shell:
```
uart:~$ bt init
Bluetooth initialized
uart:~$ bt adv-create conn-nscan ext-adv
Created adv id: 0, adv: 0x20002800
uart:~$ bt adv-start
Advertiser[0] 0x20002800 set started
uart:~$ bt adv-stop
Advertiser set stopped
uart:~$ bt adv-start num-events 4
Advertiser[0] 0x20002800 set started
Advertiser[0] 0x20002800 sent 4
uart:~$ bt adv-start
Failed to start advertising set (-5)
[00:00:53.906,311] <wrn> bt_hci_core: opcode 0x2039 status 0x0c
[00:00:53.906,341] <err> bt_hci_core: Failed to start advertiser
```

**Comment by cvinayak** [comment] 2021-01-12 14:31
@joerchan Is the issue with non-connectable non-scannable extended advertising too?

**Comment by joerchan** [comment] 2021-01-12 14:33
@cvinayak No, that seems to work:
```
uart:~$ bt adv-create nconn-nscan ext-adv
Created adv id: 0, adv: 0x20002800
uart:~$ bt adv-start num-events 4
Advertiser[0] 0x20002800 set started
Advertiser[0] 0x20002800 sent 4
uart:~$ bt adv-start
Advertiser[0] 0x20002800 set started
```

**Comment by cvinayak** [comment] 2021-01-12 14:38
@joerchan ok. Thank you. Connectable was added recently, will add a connectable advertising test, investigate and send  a PR.

**Comment by StevenGhe** [comment] 2021-01-12 14:58
I'm sorry but I wasn't using connectable advertising? Only Identity and Extended options are set.

**Comment by cvinayak** [comment] 2021-01-12 16:27
@joerchan There is already a bsim test that covers starting connectable advertising after the terminate due to max events. (https://github.com/zephyrproject-rtos/zephyr/blob/master/tests/bluetooth/bsim_bt/bsim_test_advx/src/main.c#L236) The test is passing in CI. I also added another start advertising with max events, advertising start without duration/max events and the test still passed for me.

updated test patch file: 
[0001-tests-Bluetooth-bsim-Added-advertising-start-after-t.zip](https://github.com/zephyrproject-rtos/zephyr/files/5803388/0001-tests-Bluetooth-bsim-Added-advertising-start-after-t.zip)

There must be something wrong running on target, will continue investigation...

**Comment by cvinayak** [comment] 2021-01-13 01:53
This is a bug in the controller, the implementation to release auxiliary channel PDU resources is missing when advertising terminates due to max events or duration. Relates to https://github.com/zephyrproject-rtos/zephyr/pull/26338

**Comment by carlescufi** [comment] 2021-01-14 12:53
Setting priority as low since this is a WIP feature in the controller.

**Comment by carlescufi** [comment] 2021-01-21 12:53
@StevenGhe this is caused by the current implementation of Extended Adv missing parts of it, it will be fixed as part of the ongoing Ext Adv work, but not in time for Zephyr 2.5.

**Comment by StevenGhe** [comment] 2021-01-21 14:24
Any ETA? Are we speaking of weeks/months?

My thesis is due +- May so not having such key BLE feature is pretty huge for me.

**Comment by joerchan** [comment] 2021-01-21 15:09
@StevenGhe I don't know the ETA, but in the meantime you could use the SoftDevice controller in nRF Connect SDK, which has support for this feature.

**Comment by legoabram** [comment] 2021-02-16 21:04
I have a similar problem which I believe is related. An advertising set will also fail to restart if a connection was made through that set. In that instance, BT_HCI_ERR_MEM_CAPACITY_EXCEEDED is returned instead. The error starts in `ull_adv.c` at line 978 when calling `ll_rx_alloc`. It looks like extended advertising sets don't always cleanup after themselves.
[prj.zip](https://github.com/zephyrproject-rtos/zephyr/files/5991628/prj.zip)

**Closed** 2021-03-10 20:08 UTC
Labels: area: Bluetooth, area: Bluetooth Controller, bug, priority: low
