### ISSUE TITLE
menuconfig target aborts when Kconfig warnings are present

### ISSUE THREAD

**Issue by aport** [zephyrproject-rtos/zephyr#26034] opened 2020-06-07 19:38 UTC
**Describe the bug**
`west build -t menuconfig` aborts when Kconfig warnings are present. This prevents the user from resolving the Kconfig warnings.

**To Reproduce**
For this purpose I'll use an exising Kconfig conflict. Any existing Kconfig symbol conflict will work to reproduce.
1. Enable CONFIG_POSIX_API=y
2. Enable CONFIG_NET_SOCKETS_POSIX_NAMES=y (this symbol conflicts with the previous)
3. Save configuration
4. Attempt to build, see build fails due to Kconfig warning
5. Issue `west build -t menuconfig` to resolve the Kconfig warning
6. See that the Kconfig warning prevents `menuconfig` from running

**Expected behavior**
Kconfig warnings should not prevent `menuconfig` from executing. A user would expect to use `menuconfig` as the primary strategy for resolving Kconfig warnings.

**Impact**
I must delete .config and start over

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain gnuarmemb
 - v2.3.0

**Comment by tejlmand** [comment] 2020-06-08 14:43
This is another variant of this existing bug: https://github.com/zephyrproject-rtos/zephyr/issues/9573

**Comment by carlescufi** [comment] 2020-06-08 15:09
Closing as duplicate of #9573

**Closed by carlescufi** 2020-06-08 15:09 UTC
Labels: area: Build System, bug
