### ISSUE TITLE
Missing documentation for fcb and nffs

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#13574] opened 2019-02-20 14:33 UTC
There is no documentation on fcb or nffs.
Specially how it behaves vs flash supported write-block-size...

**Comment by ramakrishnapallala** [comment] 2019-03-05 09:27
@nvlsianpu  can you look into this issue as fcb and nffs are owned by you.

**Comment by nashif** [comment] 2019-03-05 13:34
@ramakrishnapallala this is less about the specific filesystems and more about the virtual file system interface and fs support in general.

**Comment by nvlsianpu** [comment] 2019-03-05 14:41
- fcb doc is missing - can be take form mynewt.
- NFFS is external project as well - currently not well documented, can consider documentation making but, for sure no now.

@nashif  Can we consider this as lack of documentation, not a bug. I would create separate issue for both subjects.

**Comment by nashif** [comment] 2019-03-05 15:06
lack of documentation is a BUG :)

I would start here: https://docs.zephyrproject.org/latest/reference/file_system/index.html
This is currently the API only need more content to the file system feature in general. Probably a quick into about the supported filesystems with details to be added later.

**Comment by ramakrishnapallala** [comment] 2019-03-12 07:16
I will start on adding more documentation to the API's

**Comment by ramakrishnapallala** [comment] 2019-03-26 06:07
Pushed PR: https://github.com/zephyrproject-rtos/zephyr/pull/14796/

**Comment by nashif** [comment] 2019-03-29 13:43
@nvlsianpu what about documenting fcb and nffs?

**Comment by nvlsianpu** [comment] 2019-03-29 13:59
FCB doc I can copy form MyNewt.
NFFS is under fixing now - expects that It will change a lot. I would only refer to its design.txt file and describe its limitation.

**Comment by nashif** [comment] 2019-04-02 17:19
@nvlsianpu any updates?

**Comment by nashif** [comment] 2019-06-01 00:29
@nvlsianpu ping

**Comment by nvlsianpu** [comment] 2019-07-08 12:02
I'm Preparing FCB doc right now.

**Comment by nvlsianpu** [comment] 2019-07-09 14:21
FCB documentation: https://github.com/zephyrproject-rtos/zephyr/pull/17425

**Comment by carlescufi** [comment] 2019-08-19 09:11
FCB is now documented and NFFS is on the path to deprecation, so closing this.

**Closed by carlescufi** 2019-08-19 09:11 UTC
Labels: area: Documentation, area: File System, bug, priority: medium
