### ISSUE TITLE
intel_adsp: tests/lib/p4workq/libraries.p4wq fails

### ISSUE THREAD

**Issue by majunkier** [zephyrproject-rtos/zephyr#70493] opened 2024-03-20 12:49 UTC
**Describe the bug**
tested on intel_adsp/ boards (cavs25, ace15_mtpm)

```
tests/lib/p4workq/libraries.p4wq
```

test hangs despite initially promising results. Result is timeout.

**To Reproduce**
` twister --device-testing --hardware-map PATH-TO-HWMAP -s tests/lib/p4workq/libraries.p4wq`

**Expected behavior**
Test should pass

**Logs and console output**
handler.log

```
*** Booting Zephyr OS build v3.6.0-1236-g8f4ac0d4ab45 ***
Running TESTSUITE lib_p4wq
===================================================================
START - test_fill_queue
PASS - test_fill_queue in 0.004 seconds
===================================================================
START - test_resubmit
PASS - test_resubmit in 0.101 seconds
===================================================================
START - test_stress
PASS - test_stress in 0.111 seconds
===================================================================
TESTSUITE lib_p4wq succeeded
Running TESTSUITE lib_p4wq_1cpu
===================================================================
START - test_p4wq_simple

```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Version used: v3.6.0-1236-g8f4ac0d4ab45

**Comment by nashif** [comment] 2024-03-20 14:01
duplicate of #70494

**Closed by nashif** 2024-03-20 14:01 UTC
Labels: bug
