### ISSUE TITLE
it8xxx2_evb: k_busy_wait is not working accurately for ITE RISC-V

### ISSUE THREAD

**Issue by Asthachavda** [zephyrproject-rtos/zephyr#43757] opened 2022-03-14 11:38 UTC
**Describe the bug**
**k_busy_wait** is not give accurate delay for **ITE (RISC V).**  Give the delay while toggling the gpio pin using k_busy_wait. later check the output using Saleae logic analyzer for measuring delay. Got **less delay** compare to expected delay.

**To Reproduce**

1. Wrote a sample code to toggle GPIO pin.
2. Apply microsecond delay using k_busy_wait.
3. used Saleae logic analyzer to measure delay.

**Expected behavior**
k_busy_wait should gives proper delay. Deviation should not >~3%

**Impact**
Application code doesn't get correct delay while using k_busy_wait. 

**Logs and console output**
**Expected delay** **==**  **output  delay**
10               ==========                                  18.84
100             ==========                                 90.992
200             ==========                                 182.49
500             ==========                              486.94
2000           ==========                            1975.56

**Check the Saleae output waveform image in below document.**
[Saleae_Output.docx](https://github.com/zephyrproject-rtos/zephyr/files/8244299/Saleae_Output.docx)

**Environment (please complete the following information):**
 - OS: Linux (Ubuntu 18.04.5)
 - Toolchain: Zephyr SDK 12.04
 - Board used: ITE IT8XXX2 (RISC-V 32)
 - Zephyr Version: zephyr-v3.0.0

**Comment by Dino-Li** [comment] 2022-04-06 02:50
The implementation of CONFIG_ARCH_HAS_CUSTOM_BUSY_WAIT config option had been merged:
https://github.com/zephyrproject-rtos/zephyr/pull/44060

**Comment by Asthachavda** [comment] 2022-04-08 04:51
Hi Dino,
I have seen above PR (#44060) and used all the changed file to check the microseconds delay accuracy using k_busy_wait API. Here is the output for the same.

**Logs and console output**
Expected delay == output delay
10 ========== **5.48**
100 ========== **35.48**
200 ========== **68.61**
500 ========== **167.968**
2000 ========== **666.312**

**Output delay is very less compare to the expected delay.**

**Comment by Dino-Li** [comment] 2022-04-08 07:09
Hi Astha,
The symptom seems to be caused by changing PLL sequence failed.
Does the below patch make microseconds delay more accurate?
https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3578493/1/soc/riscv/riscv-ite/it8xxx2/soc.c

**Comment by Dino-Li** [comment] 2022-04-08 09:38
Also, is chip's VCC always up to 1.8v?

**Comment by Asthachavda** [comment] 2022-04-11 10:02
1. We used above patch but code itself not compiled. It showing below errors.
![image](https://user-images.githubusercontent.com/91449305/162714507-7490bd05-40d6-464c-b8fe-4b70190bb723.png)

2. Chip's VCC is approx. 3.3V

**Comment by Dino-Li** [comment] 2022-04-12 06:29
I verified busy wait of 500 microsecond on the top:
https://github.com/Dino-Li/zephyr/commit/1ad1a3c6fdf42827d3b9ae536a50d70cda13e20f
The accuracy looks good.

There are two conditions will break PLL sequence:
1. On eSPI platform, the GPM5 (#CS) is at level low during changing PLL sequence.
The workaroud had been impeleted here:
https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/riscv/riscv-ite/it8xxx2/soc.c#L137
2. One of the below i2c port (pinmux) is enabled before changing PLL sequence and its clock and data pins aren't all at level high:
i2c3, i2c4, and i2c5
Have you enable the above i2c port before changing the sequence?

Loop @RuibinChang in.

**Comment by Asthachavda** [comment] 2022-04-12 09:58
1. We used same file (https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/riscv/riscv-ite/it8xxx2/soc.c#L137)
2. No, we haven't enable any I2C port.

**However, We have  below questions.,** 

1. How many microseconds you got as a output for 500us delay?
2.  Which test case you checked to verified the accuracy? 
3. The patch which you provided in above comments its not works, can you give solution for the same?

**Comment by Dino-Li** [comment] 2022-04-12 10:46
Please comment chip_run_pll_sequence() out from chip_configure_pll().
If that makes busy wait more accurate, we need to figure out why changing PLL failed on your system.

@RuibinChang, can you provide delay output?

**Comment by RuibinChang** [comment] 2022-04-15 06:14
I test by samples/hello_world on board it8xxx2_evb in here:
https://github.com/zephyrproject-rtos/zephyr/compare/main...RuibinChang:timer_busywait_verify?expand=1

And the result is:
Expected delay====output delay
    10================12
    100===============101
    200===============201
    500===============498
    2000==============1988

**Comment by Asthachavda** [comment] 2022-04-28 16:01
Hi Ruibin, 
We used your patch & we also got some what similar results. I am closed the issue. Thanks.

**Closed** 2022-04-28 16:02 UTC
Labels: bug, priority: low, area: RISCV, platform: ITE
