### ISSUE TITLE
tests/kernel/sched/schedule_api/testcase.yaml#kernel.sched.slice_reset fails on nrf52840_pca10056, nrf52_pca10040, nrf51_pca10028

### ISSUE THREAD

**Issue by arun1joshi** [zephyrproject-rtos/zephyr#15996] opened 2019-05-08 06:00 UTC
**Describe the bug**
tests/kernel/sched/schedule_api/testcase.yaml#kernel.sched.slice_reset fails on nrf boards - nrf52840_pca10056, nrf52_pca10040, nrf51_pca10028

- Last checked ok commit on 7/may/19 [3696eccc1a]
- Looks same to #9611

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=nrf51_pca10028
3. make

**Expected behavior**
The test case should pass

**Impact**
Regression

**Screenshots or console output**
```
***** delaying boot 1000ms (per build configuration) *****
***** Booting Zephyr OS zephyr-v1.14.0-605-ge9ed63465426 (delayed boot 1000ms) *****
Running test suite threads_scheduling
===================================================================
starting test - test_priority_cooperative
PASS - test_priority_cooperative
===================================================================
starting test - test_priority_preemptible
PASS - test_priority_preemptible
===================================================================
starting test - test_yield_cooperative
PASS - test_yield_cooperative
===================================================================
starting test - test_sleep_cooperative
PASS - test_sleep_cooperative
===================================================================
starting test - test_sleep_wakeup_preemptible
PASS - test_sleep_wakeup_preemptible
===================================================================
starting test - test_pending_thread_wakeup
PASS - test_pending_thread_wakeup
===================================================================
starting test - test_time_slicing_preemptible
PASS - test_time_slicing_preemptible
===================================================================
starting test - test_time_slicing_disable_preemptible
PASS - test_time_slicing_disable_preemptible
===================================================================
starting test - test_lock_preemptible
PASS - test_lock_preemptible
===================================================================
starting test - test_unlock_preemptible
PASS - test_unlock_preemptible
===================================================================
starting test - test_sched_is_preempt_thread
PASS - test_sched_is_preempt_thread
===================================================================
starting test - test_slice_reset
    Assertion failed at ./tests/kernel/sched/schedule_api/src/test_sched_timeslice_reset.c:50: thread_tslice: t <= expected_slice_max is false
    Assertion failed at ./tests/kernel/sched/schedule_api/src/test_sched_timeslice_reset.c:49: thread_tslice: t >= expected_slice_min is false
    Assertion failed at ./tests/kernel/sched/schedule_api/src/test_sched_timeslice_reset.c:49: thread_tslice: t >= expected_slice_min is false
FAIL - test_slice_reset
===================================================================
starting test - test_slice_scheduling
PASS - test_slice_scheduling
===================================================================
starting test - test_priority_scheduling
AB
AB
AB
AB
AB
PASS - test_priority_scheduling
===================================================================
starting test - test_wakeup_expired_timer_thread
PASS - test_wakeup_expired_timer_thread
===================================================================
Test suite threads_scheduling failed.
===================================================================
RunID: :56sv
PROJECT EXECUTION FAILED
```
**Environment (please complete the following information):**
 - OS: Fedora 29
 - Toolchain: Zephyr SDK v0.10.0
 - Commit: e9ed63465426

**Comment by carlescufi** [comment] 2019-05-08 16:12
duplicate of #15983

**Closed by carlescufi** 2019-05-08 16:12 UTC
Labels: area: Kernel, area: Tests, bug, platform: nRF
