### ISSUE TITLE
Bluetooth: GATT Subscribe does not detect duplicate if new parameters are used.

### ISSUE THREAD

**Issue by paulgavrikov** [zephyrproject-rtos/zephyr#15099] opened 2019-04-01 21:59 UTC
**Describe the bug**
Similar to #15098. It is possible to issue a new subscribe command to previously subscribed handles by using a different subscribe param struct.

**Expected behavior**
Iterare over existing subscriptions and compare handles.

**Comment by Vudentz** [comment] 2019-04-02 10:31
We do support multiple subscription to the same CCC, it does actually iterate to check that:

https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/bluetooth/host/gatt.c#L2733

Im closing it as it is working as intended, if you want to add an API to query existing subscription that is a different API, though Id consider a bug if an application cannot really check its own subscription since the parameters are owned by it.

**Closed by Vudentz** 2019-04-02 10:31 UTC
Labels: area: Bluetooth, bug
