### ISSUE TITLE
dumb_http_server_mt with overlay-tls.conf does not connect

### ISSUE THREAD

**Issue by bran795** [zephyrproject-rtos/zephyr#21744] opened 2020-01-07 13:35 UTC
running dumb_http_server_mt  with overlay-tls.conf does not connect:
The mbded tls hangs : mbedtls_ssl_fetch_input calls ssl->f_recv on line 2714 and waits forever.
Adding 
      net_context_set_accepting(child, false);
in function ztls_accept_ctx() file sockets_tls.c solves the hanging (taken from the master branch)

**To Reproduce**
west build -b frdm_k64f -d build_dhs samples\net\sockets\dumb_http_server_mt
west flash

from browser: https://192.0.2.1

**Expected behavior**
Expected TLS handshake to complete

**Impact**
Showstopper: TLS handskae hangs after Client Hello. All TCP communication is stopped

**Screenshots or console output**

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain: GNU Arm Embedded
 - Commit SHA or Version used: V2.1 branch

**Additional context**
Browser: Chrome

**Comment by rlubos** [comment] 2020-02-13 15:11
It seems that a similar issue was reported in #21335, and it was fixed in #21371 (the same way it was suggested in this issue). I could not reproduce it on current master so I think we can close this issue. Please reopen if you think the problem still persists.

**Closed by rlubos** 2020-02-13 15:11 UTC
Labels: area: Networking, bug, priority: low
