### ISSUE TITLE
[net][net.socket.select][imx-rt series] test fails  (k_uptime_get_32() - tstamp <= FUZZ is false)

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#25991] opened 2020-06-05 03:50 UTC
**Describe the bug**
Assertion failed at WEST_TOPDIR/zephyr/tests/net/socket/select/src/main.c:160: test_select: (k_uptime_get_32() - tstamp <= FUZZ is false)

all rt baords with net support fail:
mimxrt1020_evk
mimxrt1060_evk
mimxrt1064_evk
mimxrt1050_evk

for v2.3.0-rc1 this case is OK.

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=mimxrt1060_evk ..
3. make flash

**Expected behavior**
all test pass.

**Impact**
net socket function

**Screenshots or console output**
'''

*** Booting Zephyr OS version 2.3.0-rc2  ***

I: ETH_0 enabled 100M full-duplex mode.
Running test suite socket_select
===================================================================
starting test - test_fd_set
PASS - test_fd_set
===================================================================
starting test - test_select
E: 0x00000000 is not a valid NET_SOCKET
E: address is not a known kernel object
E: 0x00000000 is not a valid NET_SOCKET
E: address is not a known kernel object

    Assertion failed at WEST_TOPDIR/zephyr/tests/net/socket/select/src/main.c:160: test_select: (k_uptime_get_32() - tstamp <= FUZZ is false)

FAIL - test_select
===================================================================
Test suite socket_select failed.
===================================================================
PROJECT EXECUTION FAILED

'''

**Environment (please complete the following information):**
 - OS: (e.g. Linux)
 - Toolchain (Zephyr SDK, ...)
 - v.2.3.0-rc2

**Comment by hakehuang** [comment] 2020-06-05 03:55
@dleach02 , @MaureenHelm

**Comment by carlescufi** [comment] 2020-06-05 04:43
Probably duplicate of #25990

**Comment by dleach02** [comment] 2020-06-05 13:42
yep... looks like we introduced a bug in the last week... given that it is across multiple (all?) architectures maybe we should fix this before doing final?

**Closed** 2020-06-05 16:34 UTC
Labels: area: Ethernet, area: Sockets, area: Tests, bug, platform: NXP

**Comment by dleach02** [comment] 2020-06-05 17:48
I can confirm that #26001 fixes this problem. I reproduced the problem before and then confirmed that the test passed after applying the patch
