### ISSUE TITLE
sample.drivers.flash.shell: Failed on NXP targets

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#48912] opened 2022-08-11 08:19 UTC
**Describe the bug**
Seen here: https://github.com/zephyrproject-rtos/zephyr/runs/7769981753?check_suite_focus=true

`samples/drivers/flash_shell/sample.drivers.flash.shell ` is failed on following targets:
- hexiwear_kw40z
- lpcxpresso55s28
- lpcxpresso55s16
- lpcxpresso55s69_ns
- lpcxpresso55s69_cpu0
- lpcxpresso54114_m4

**Log Error**
Two types of errors, depending on targets
```
In file included from /local/mcu/zephyrproject/modules/hal/nxp/mcux/mcux-sdk/drivers/flash/fsl_ftfx_features.h:21,
                 from /local/mcu/zephyrproject/modules/hal/nxp/mcux/mcux-sdk/drivers/flash/fsl_ftfx_controller.h:13,
                 from /local/mcu/zephyrproject/modules/hal/nxp/mcux/mcux-sdk/drivers/flash/fsl_ftfx_cache.h:13,
                 from /local/mcu/zephyrproject/modules/hal/nxp/mcux/mcux-sdk/drivers/flash/fsl_flash.h:13,
                 from /local/mcu/zephyrproject/zephyr/drivers/flash/soc_flash_mcux.c:20:
/local/mcu/zephyrproject/modules/hal/nxp/mcux/mcux-sdk/drivers/flash/fsl_ftfx_adapter.h:290: error: "SIM_FCFG1_REG" redefined [-Werror]
  290 | #define SIM_FCFG1_REG           SIM->FCFG1
      | 
In file included from /local/mcu/zephyrproject/modules/hal/nxp/mcux/mcux-sdk/devices/MKW40Z4/fsl_device_registers.h:44,
                 from /local/mcu/zephyrproject/modules/hal/nxp/mcux/mcux-sdk/drivers/common/fsl_common.h:22,
                 from /local/mcu/zephyrproject/zephyr/soc/arm/nxp_kinetis/kwx/soc.h:27,
                 from /local/mcu/zephyrproject/zephyr/drivers/flash/soc_flash_mcux.c:13:
/local/mcu/zephyrproject/modules/hal/nxp/mcux/mcux-sdk/devices/MKW40Z4/MKW40Z4.h:6829: note: this is the location of the previous definition
 6829 | #define SIM_FCFG1_REG(base)                      ((base)->FCFG1)
      |
```
or
```
/local/mcu/zephyrproject/zephyr/drivers/flash/soc_flash_mcux.c:20:10: fatal error: fsl_flash.h: No such file or directory
   20 | #include "fsl_flash.h"
      |          ^~~~~~~~~~~~~
```
**To Reproduce**
`twister -b -s samples/drivers/flash_shell/sample.drivers.flash.shell -p hexiwear_kw40z`

**Impact**
Blocking CI (https://github.com/zephyrproject-rtos/zephyr/pull/45221)

**Environment (please complete the following information):**
zephyr-v3.1.0-3289-gc93361a5bf

**Comment by dleach02** [comment] 2022-08-17 20:20
Duplicate of #49166. I'm going to close this one since the newer one has some comments in the conversation thread to retain.

**Closed by dleach02** 2022-08-17 20:20 UTC
Labels: bug, priority: medium, platform: NXP
