### ISSUE TITLE
simics/qemu_x86_nommu: testscases with CONFIG_BOOT_DELAY !=0 do not boot

### ISSUE THREAD

**Issue by inakypg** [zephyrproject-rtos/zephyr#6511] opened 2018-03-08 05:22 UTC
When running testcases under Simics with the CONFIG_BOOT_DELAY option set to 1000 (ms), testcases do not proceed past the boot delay message:

    ***** delaying boot 1000ms (per build configuration) *****

this was run under the Simics 5.0 configuration:

    $disk_image = "hd0.img"
    $cpu_class = "pentium-pro"
    $text_console = TRUE
    run-command-file "%simics%/targets/x86-440bx/x86-440bx-pci-system.include"
    create-telnet-console-comp $system.serconsole 37825
    connect system.serconsole.serial cnt1 = system.motherboard.sio.com[0]
    instantiate-components
    system.serconsole.con.capture-start "simics-console.read"
    c

where hd0.img is an HD image with a single MSDOS partition, FAT32 formatted and grub2 which multiboots zephyr/zephyr.elf.

This affects all testcases in tests/kernel

**Comment by ramakrishnapallala** [comment] 2018-05-16 18:27
Debugged the issue further and the root cause is that the HPET timer's MAIN_COUNTER_VALUE_REG(0xf0) is not being updated at all if I run test app on Simics platform. I am getting timer interrupts but the MAIN_COUNTER_VALUE_REG contents are always set to 0xffffffff.
 If i run same app on Qemu it run fine.

**Comment by ramakrishnapallala** [comment] 2018-05-17 11:32
Hacked the hpet timer driver interrupt handler code to increment the counter value and ran the test.
It worked with the hack which clearly points to the issue to _HPET_MAIN_COUNTER_VALUE update issue. 

This hardware register value always remains 0xffffffff even if you forcefully change it. Need to check with Simics folks on this behavior.

**Comment by ramakrishnapallala** [comment] 2018-05-21 09:04
checked with Simics team and found out that the existing Simics model we are will  not support HPET timer IP. we need to use QSP-x86 model to that. I will fix it and update the documentation accordingly.

**Comment by ramakrishnapallala** [comment] 2018-06-04 13:10
@inakypg I am closing this issue we have recipe which boots simics with delay.

**Closed by ramakrishnapallala** 2018-06-04 13:10 UTC
Labels: bug, priority: low
