### ISSUE TITLE
Pinctrl for applicable ARC boards

### ISSUE THREAD

**Issue by ruuddw** [zephyrproject-rtos/zephyr#45771] opened 2022-05-18 15:27 UTC
Some ARC development boards support pinmuxing. The HSDK board had a minimal pinmux driver which was removed when pinmux got deprecated. Since the default pinmux setting cover typical use of these boards, pinctrl support is not required but it would be good to support this in a future release.

**Comment by ruuddw** [comment] 2022-06-16 08:39
See also #39740 for Zephyr roadmap for pinctrl.
To be investigated if this also applies to ARC development boards "pmodmux" feature (not pin-level, but connector level pin muxing).

**Comment by gmarull** [comment] 2023-05-30 07:01
Duplicate of https://github.com/zephyrproject-rtos/zephyr/issues/52436

**Closed by gmarull** 2023-05-30 07:01 UTC
Labels: Enhancement, area: ARC, area: Pinctrl
