### ISSUE TITLE
intel_adsp_cavs15: run testcases of queue failed

### ISSUE THREAD

**Issue by KangJianX** [zephyrproject-rtos/zephyr#32512] opened 2021-02-20 07:18 UTC
**Describe the bug**
run testcases of **queue** failed

**To Reproduce**
1. twister -p intel_adsp_cavs15 --device-testing -T tests/kernel/queue/ --west-flash="/home/ztest/work/zephyrproject/zephyr/boards/xtensa/intel_adsp_cavs15/tools/flash.sh,/home/ztest/work/zephyrproject/modules/audio/sof/keys/otc_private_key.pem,/home/ztest/work/zephyrproject/modules/audio/sof/zephyr/ext/rimage/config,/home/ztest/work/zephyrproject/modules/audio/sof/zephyr/ext/rimage/build/rimage" --device-serial-pty="/home/ztest/work/zephyrproject/zephyr/boards/xtensa/intel_adsp_cavs15/tools/adsplog.py,--no-history"
2. See error

**Logs and console output**
START - test_queue_alloc
PASS - test_queue_alloc
......................................................................................................................................................................
START - test_queue_poll_race
**Assertion failed** at WEST_TOPDIR/zephyr/tests/kernel/queue/src/test_queue_contexts.c:367: test_queue_poll_race: low_count + mid_count == 2 is false
FAIL - test_queue_poll_race
......................................................................................................................................................................
START - test_multiple_queues
PASS - test_multiple_queues
......................................................................................................................................................................
START - test_access_kernel_obj_with_priv_data
**ASSERTION FAIL** [old_val != 0x1337C0D3] @ WEST_TOPDIR/zephyr/kernel/thread.c:547
re-use of active thread object 0x9e0181e8 detected
@ WEST_TOPDIR/zephyr/lib/os/assert.c:45
Caught system error -- reason 4 0
Fatal error was unexpected, aborting...

**Environment (please complete the following information):**
- OS: Fedora28
- Toolchain: Zephyr-sdk-0.12.2
- Commit ID: 3fe33fe3883ffabb8a9

**Comment by andyross** [comment] 2021-02-26 16:37
Duplicate of #32705

**Closed by andyross** 2021-02-26 16:37 UTC
Labels: bug, priority: medium
