### ISSUE TITLE
Backport 'boards: bl654_usb: Fix non-mcuboot builds not limiting size' to 2.7

### ISSUE THREAD

**Issue by lairdjm** [zephyrproject-rtos/zephyr#44620] opened 2022-04-07 07:19 UTC
**Describe the bug**
This is a backport request for the upcoming zephyr 2.7 release to fix an issue in the bl654_usb boards file that does not correctly limit the application size with non-mcuboot builds
Original PR: https://github.com/zephyrproject-rtos/zephyr/pull/44532

**Comment by mbolivar-nordic** [comment] 2022-04-12 16:42
Closing as a dupe of https://github.com/zephyrproject-rtos/zephyr/issues/44531

**Closed by mbolivar-nordic** 2022-04-12 16:42 UTC
Labels: bug, backport v2.7-branch
