### ISSUE TITLE
CI: tests/subsys/logging/log_backend_uart tests fail on qemu_cortex_m0

### ISSUE THREAD

**Issue by henrikbrixandersen** [zephyrproject-rtos/zephyr#65511] opened 2023-11-21 10:17 UTC
**Describe the bug**
The following tests fail on `qemu_cortex_m0` in CI on `main`:
- tests/subsys/logging/log_backend_uart/logging.backend.uart.multi on qemu_cortex_m0 failed (Timeout)
- tests/subsys/logging/log_backend_uart/logging.backend.uart.single on qemu_cortex_m0 failed (Timeout)
- tests/subsys/logging/log_output/logging.output.thread_id on qemu_cortex_m0 failed (Timeout)

It appears these failures were introduced in #65150.

**To Reproduce**
1. `west twister -p qemu_cortex_m0 -s tests/subsys/logging/log_backend_uart/logging.backend.uart.multi`
2. See error as on https://github.com/zephyrproject-rtos/zephyr/actions/runs/6933236823/job/18859011016

**Expected behavior**
CI tests pass.

**Impact**
Multiple CI failures on `main`.

**Environment (please complete the following information):**
 - Commit SHA: 934a09550dd17406426ac92aac89761cbe506520

**Comment by ycsin** [comment] 2023-11-21 15:01
I tried one of the test and it was passing in bc08e801c6b1416dcbbc679f5e25f801d438a531, but fails in a43e516ff2f7bc7091835bf9a97c979937a75366

**Comment by nordic-krch** [comment] 2023-11-21 15:03
There is a similar failure reported #65456 for which I opened #65526. But cortex-m0 failures seems to related to https://github.com/zephyrproject-rtos/zephyr/commit/7a5fcb8c60e2e6ba26704fabc28fe2d4e0106513

**Comment by keith-packard** [comment] 2023-11-21 18:08
Could this be caused by CI using SDK version 0.16.3?

**Comment by keith-packard** [comment] 2023-11-21 19:18
Yup, SDK 0.16.3 has the version of picolibc without separate long long support, so making that work has broken several test cases. Fixed in #65539 (which I've added another patch to).

**Closed** 2023-11-21 20:43 UTC
Labels: bug, priority: high, area: Logging
