### ISSUE TITLE
[v2.7] DTLS handshake time out after migration zephyr 2.7.x

### ISSUE THREAD

**Issue by efra-mx-aqua** [zephyrproject-rtos/zephyr#49071] opened 2022-08-15 16:26 UTC
**Describe the bug**
After migration our application from zephyr 1.14.1 to zephyr 2.7.2, the DTLS handshake is timing out.

PPP is working fine, SNTP is working fine.

```
18:26:03.203393 [00:32:37.327,941] <inf> modem_gsm: Attached to packet service!
18:26:03.203433 [00:32:37.453,155] <inf> net_ppp: Initializing PPP to use GSM_1
18:26:03.203472 [00:32:37.460,845] <inf> modem_gsm: AT channel 1 connected to GSM_2
18:26:03.203511 [00:32:37.460,906] <inf> tx_manager: Waiting for network connection...
18:26:03.203564 [00:32:38.071,685] <inf> tx_manager: Network connected
18:26:03.203609 [00:32:38.071,716] <inf> tx_manager: Device IP address: 10.81.165.249
18:26:03.203649 [00:32:38.071,807] <inf> cloud_config: Connecting to Fallback hostname xxxxx.xxx.xx
18:26:03.203697 [00:32:38.072,479] <inf> cloud_config: Connection established!
18:26:03.203742 [00:32:38.072,540] <inf> shared_timers: Radio silent timer has been stopped.
18:26:24.606664 [00:32:54.859,405] <err> tx_manager: txman_send error: -113
18:26:24.606856 [00:32:54.859,405] <err> tx_manager: Verify the device 'barker651' is properly registered
18:26:24.606921 [00:32:54.859,436] <err> tx_manager: upload_logged_errors returned -113
18:26:24.606963 [00:32:54.860,351] <inf> modem_gsm: GSM PPP stop
18:26:24.607017 [00:32:54.860,534] <inf> tx_manager: Network disconnected
18:26:24.607068 [00:32:55.008,911] <inf> modem_gsm: GSM network interface down
```

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? NRF52840 with ublox modem sara-r4, in our custom hardware
 - What have you tried to diagnose or workaround this issue? Yes, I tried to increase the heap size to 12K but no change 
 - It runs with zephyr 1.14.1 with  a ublox driver and socket offloads.

**To Reproduce**
Create a DTLS socket with PSK and try to send data using a GSM PPP modem driver

**Expected behavior**
I am doing the migration of our application and I am having issues with DTLS, the handshakes times out. After analyzing 
logs with wireshark we can see that the client and server communicate but the handshake is never completed.

The handshake must be completed

**Impact**
Showstopper

**Logs and console output**
[log.zip](https://github.com/zephyrproject-rtos/zephyr/files/9338468/log.zip)

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain 
 export GCC_ARM_NAME=gcc-arm-none-eabi-10-2020-q4-major
export CROSS_COMPILE=zephyr
export ZEPHYR_TOOLCHAIN_VARIANT=gnuarmemb
export GNUARMEMB_TOOLCHAIN_PATH=/opt/toolchains/${GCC_ARM_NAME}

DTLS server:
- https://github.com/CreatorDev/DTLS.Net/blob/v1.0.21/src/DTLS.Net/Server.cs

 - Commit SHA or Version used
zephyr 2.7.2

**Additional context**
This is the network configuration used:

```
``
# Overlay to enable networking
CONFIG_NETWORKING=y

# GSM modem support
CONFIG_MODEM=y
CONFIG_MODEM_GSM_PPP=y
CONFIG_MODEM_SHELL=n

CONFIG_MODEM_CONTEXT=y

CONFIG_NET_UDP=y
CONFIG_NET_SOCKETS=y

# Connect to network automatically
CONFIG_GSM_PPP_AUTOSTART=y

# This should be an empty string to enable auto-APN
CONFIG_MODEM_GSM_APN=""

# Enable RSSI, RSRP, RSRQ
CONFIG_MODEM_GSM_ENABLE_CESQ_RSSI=y

# This is needed to communicate with modem via AT commands despite UART line
# being used by PPP
CONFIG_GSM_MUX=y

CONFIG_NET_PPP_UART_BUF_LEN=32

CONFIG_MODEM_GSM_MNOPROF=100
CONFIG_MODEM_SIM_NUMBERS=y
CONFIG_MODEM_CELL_INFO=y



# PPP networking support
CONFIG_NET_DRIVERS=y
CONFIG_NET_PPP=y
CONFIG_NET_L2_PPP=y
CONFIG_NET_NATIVE=y

CONFIG_NET_L2_PPP_TIMEOUT=10000

# IPv4 enables PPP IPCP support
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=n
CONFIG_NET_UDP=y

# Network management events
CONFIG_NET_CONNECTION_MANAGER=y
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_DNS_RESOLVER=y
CONFIG_DNS_SERVER_IP_ADDRESSES=y
CONFIG_DNS_RESOLVER_MAX_SERVERS=1
CONFIG_DNS_SERVER1="8.8.8.8"
# CONFIG_DNS_SERVER1="1.1.1.1"
CONFIG_DNS_SERVER_IP_ADDRESSES=y
CONFIG_DNS_NUM_CONCUR_QUERIES=5
CONFIG_NET_SOCKETS_DNS_TIMEOUT=3000

# Sockets/DTLS
CONFIG_TLS_CREDENTIALS=y
CONFIG_NET_SOCKETS_SOCKOPT_TLS=y
CONFIG_NET_SOCKETS_TLS_MAX_CONTEXTS=1
CONFIG_NET_SOCKETS_ENABLE_DTLS=y
CONFIG_NET_SOCKETS_POSIX_NAMES=y
CONFIG_NET_SOCKETS_DTLS_TIMEOUT=30000
CONFIG_NET_L2_OPENTHREAD=n


CONFIG_MBEDTLS=y
CONFIG_MBEDTLS_DTLS=y
CONFIG_MBEDTLS_BUILTIN=y
CONFIG_MBEDTLS_ENABLE_HEAP=y
CONFIG_MBEDTLS_HEAP_SIZE=12000
CONFIG_MBEDTLS_TLS_VERSION_1_2=y
CONFIG_MBEDTLS_DEBUG=n
CONFIG_MBEDTLS_CFG_FILE="config-tls-generic.h"
CONFIG_MBEDTLS_KEY_EXCHANGE_PSK_ENABLED=y

# CoAP
CONFIG_COAP=y

# Using SNTP for clock sync
CONFIG_SNTP=y
CONFIG_NET_CONFIG_CLOCK_SNTP_INIT=y
CONFIG_NET_CONFIG_SNTP_INIT_SERVER="ntp.se"

CONFIG_MODEM_GSM_INIT_PRIORITY=42
```
I cannot share my code.

**Comment by mmahadevan108** [comment] 2022-08-16 16:21
cc @rerickson1

**Comment by rerickson1** [comment] 2022-08-16 16:42
upping the CONFIG_MBEDTLS_HEAP_SIZE. I would try 32000

**Comment by efra-mx-aqua** [comment] 2022-08-17 07:59
> CONFIG_MBEDTLS_HEAP_SIZE

no i have even tried 64000

**Comment by rerickson1** [comment] 2022-08-17 13:40
Use the following to enable debugging. It should give you a lot of info on whats going wrong.
```
CONFIG_NET_SOCKETS_LOG_LEVEL_DBG=y
CONFIG_NET_DEBUG_NET_PKT_ALLOC=y
CONFIG_NET_BUF_POOL_USAGE=y
CONFIG_MBEDTLS_DEBUG=y
CONFIG_MBEDTLS_DEBUG_LEVEL=1
CONFIG_MBEDTLS_SHELL=y
CONFIG_MBEDTLS_MEMORY_DEBUG=y
```

**Comment by rerickson1** [comment] 2022-08-17 18:41
this is the error you are getting:
`#define MBEDTLS_ERR_SSL_INVALID_RECORD                    -0x7200  /**< An invalid SSL record was received. */`
Make sure you have your zephyr device configure with the right cipher suites that match what is required for the certs and keys your server is using.

**Comment by efra-mx-aqua** [comment] 2022-08-17 22:25
yes that is correct

**Comment by boaks** [comment] 2022-08-18 05:45
In the past 5 years, such errors mainly occurred if different secrets are used.

The culprit is mainly bad documentation about the encoding of that secret. 

According [RFC4279 - Page 5](https://www.rfc-editor.org/rfc/rfc4279#page-5)

```
struct {
             opaque other_secret<0..2^16-1>;
             opaque psk<0..2^16-1>;
};
```

The secret (`psk`) is a binary value.

[RFC4279 - Section 5.4](https://www.rfc-editor.org/rfc/rfc4279#section-5.4) specifies:

> Entering PSKs up to 64 octets in length as ASCII strings and in hexadecimal encoding.

In many cases, one side uses an ASCII string and the other hexadecimal encoding.

PSK (ASCII): "secretPSK"
PSK (HEX): "73656372657450534B"
PSK (Base 64): "c2VjcmV0UFNL"

If someone now passes in the hex "73656372657450534B" to one peer, which uses that hex encoding. and also the same string to a peer, that assumes "ASCII" encoding, the result will be:

"secretPSK" !=  "73656372657450534B"

**Comment by efra-mx-aqua** [comment] 2022-08-19 09:16
I found the problem but i do not know how to solve it the MAC is considered invalid by the server and it send a Fatal alert.

What could be causing this issue? As said before this happens very seldom when using zephyr 1.14

**Comment by boaks** [comment] 2022-08-19 09:32
The MAC error is mainly caused by different PSK secrets.

If you create a [ip-capture](https://github.com/eclipse/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information) you will see, that the `Finish` message is the only encrypted one. And the MAC mismatch there for PSK is in almost every case of the past years caused by different secrets. The root-cause for that is too often the missing documentation. 

See:

[Why does message MAC verification fail with an OpenSSL client but succeed with a python-mbedtls client](https://stackoverflow.com/questions/73030838/why-does-message-mac-verification-fail-with-an-openssl-client-but-succeed-with-a)

[nRF9160 modem_key_mgmt_cmp returns -1](https://devzone.nordicsemi.com/f/nordic-q-a/89820/nrf9160-modem_key_mgmt_cmp-returns--1/378016)

Sure, a update should not change that. But some are even not aware, that they changed the API.

**Comment by efra-mx-aqua** [comment] 2022-08-19 11:35
@boaks thank you for the info.

I have attached a wireshark log in the description. I can see all alert are encrypted, but that is maybe only on DTLS .NET implementation. I will debug more the server in order to see if they have different secrets but i doubt it since we have double checked. 

Note that every now and  it DOES connect.

**Comment by boaks** [comment] 2022-08-19 11:59
Unfortunately, my wireshark 3.6.5 has some issues displaying that capture ...

> I can see all alert are encrypted, but that is maybe only on DTLS .NET implementation.

Strange ... 

Just if you want to check it with an other DTLS 1.2 server, [Eclipse/Californium](https://github.com/eclipse/californium) offers a sandbox `coap://californium.eclipseprojects.io:5684/`, see [Interop Server - (D)TLS Support](https://github.com/eclipse/californium#interop-server---dtls-support) for the credentials. Depending on your environment, you may also run the [cf-plugtest-server](https://repo.eclipse.org/content/repositories/californium-releases/org/eclipse/californium/cf-plugtest-server/3.6.0/cf-plugtest-server-3.6.0.jar) on your own (see [dem-apps/cf-plugtest-server](https://github.com/eclipse/californium/tree/main/demo-apps/cf-plugtest-server) for more information).

**Comment by boaks** [comment] 2022-08-19 12:20
From your device log (last part): 

> 0000:  15 fe fd 00 00 00 00 00 00 00 0c 00 40
> 0010:  f8 b3 a9 8b ba 83 f7 07 cd 34 47 b1 55
> 0020:  ac 71 a6 c7 24 7a 51 aa c4 0b 53 d9 7a
> 0030:  ac 08 dd 50 1a 67 24 3a 11 8e a2 6c 41
> 0040:  bf 17 15 69 24 cd 75 9e fe 21 0c 59 9c

0x15 => Alert 
0xfe 0xfd => DTLS v1.2
0x00 0x00 => epoch 0 **(epoch 0 is not encrypted)**
0x00 0x00 0x00 0x00 0x00 0x0c => record sequence number 12
0x00 0x40 => record length 64 bytes

[RFC5246 Alerts](https://www.rfc-editor.org/rfc/rfc5246#section-7.2) are messages with 2 bytes, not 64 bytes.

**Comment by boaks** [comment] 2022-08-19 13:27
> Note that every now and it DOES connect.

Hm ... there are DTLS server, who [RFC6347 - 4.2.8 - Establishing New Associations with Existing Parameters](https://www.rfc-editor.org/rfc/rfc6347.html#section-4.2.8) go for timeout instead of `SHOULD proceed with a new handshake`. So either try out, if this only occurs, if the client start over too fast. You may also check, if the server receives the messages from the same client-ip-address/port. If that's the case, you may try to use a ephemeral port on the client (that doesn't work to well, but ..).
(I personally don't use such dtls servers, of course, because I'm one of the developers of Eclipse/Californium. But also because in NATed IoT any assumptions about the ports and client-ip-addresses are in my experience not that well working.)

**Comment by efra-mx-aqua** [comment] 2022-08-22 07:44
I will try with sand box, it will be definitely helpful to test with a different server.

> Interesting, that wireshark shows "Encrypted Alert". Epoch 0 is not encrypted. Do you know, which cipher suite is used? AES-CBC? AES-CCM? AES-GCM?

This a server issue, the alert is encrypted. This is generated while processing the `change cipher spec`, i think the behavior should be the alerts are encrypted only when when the `change cipher spec` is processed.
I cannot decrypt the message with the PSK KEY.

**Comment by boaks** [comment] 2022-08-22 07:49
Just as example for issues in that DTLS server, which at least requires more explanation:

[Server.ProcessRecord - Session for ip-address:post available](https://github.com/CreatorDev/DTLS.Net/blob/v1.0.21/src/DTLS.Net/Server.cs#L210)

[RFC6347, 4.1.2.6 Anti-Replay](https://www.rfc-editor.org/rfc/rfc6347.html#section-4.1.2.6)

Describes, how to use the record sequence number to protect against replies. That requires a new  record sequence number even on a retransmission of a message.

In difference to the record sequence number, there is also a (handshake) message sequence number. But that is not incremented on retransmission.

The checks in the code sniped are therefore smelly.

```
if ((session.ClientEpoch == record.Epoch) && (session.ClientSequenceNumber == record.SequenceNumber))
{
     processRecord = true;
}
else if (session.ClientEpoch > record.Epoch)
{
     processRecord = true;
}
else if ((session.ClientEpoch == record.Epoch) && (session.ClientSequenceNumber > record.SequenceNumber))
{
     processRecord = true;
}
```

The first checks, if the message is "expected". That check doesn't work, if a message is dropped and retransmitted.
The second checks, if the message is from future "epoch", OK.
The third check seems to check, if the message is a past one. Without "sliding window of already received record sequence numbers", that opens the replay attack.

My impression:
The implementation has mixed up the rules for the record sequence number with those of the handshake message sequence number.

The first check must be relaxed to `session.ClientSequenceNumber == record.SequenceNumber`, and the third must be replaced by a "sliding window" (or left out at all ... that may be slightly less performant and reliable, but better then no reply protection.

Maybe the developer hast other explanations, but for me, that server is simply a bad implementation.

**Comment by boaks** [comment] 2022-08-22 07:54
>  i think the behavior should be the alerts are encrypted only when when the change cipher spec is processed.

More precise, the received `ChangeCipherSpec` switches the epoch for received records.
The epoch (and encryption) for sent records are switched with sending a `ChangeCipherSpec`.
Retransmissions of Handshake flights the complicates that a little more, so that the most peers must be able to receive and process records for two epochs until the handshake has really succeeded.

But epoch 0 records are simply never encrypted in DTLS 1.2

**Comment by efra-mx-aqua** [comment] 2022-08-22 12:08
@boaks I will talk with my colleagues and look deeper into the server and see how we can improve it.

**Comment by boaks** [comment] 2022-08-22 12:16
Really interesting. This seems to be the first PSK issue within years, where the secret is not the cause.
But I guess, using RPK or x509 would also fail (and may be not supported).  

If you just want to check, if the record-sequence-number processing and maybe some "new drops" are the cause of your trouble, just adapt the `session.ClientSequenceNumber == record.SequenceNumber` to `<=` and see, if that helps.

(Anyway, I would not use a server, if that is not maintained for years.)

**Comment by boaks** [comment] 2022-08-22 15:18
No, I don't think, that something else (mbedtls) is wrong.

The first handshake (from # 38 to # 46) is a handshake without retransmissions. 

The second handshake (from # 77 to # 85) uses one retransmission, the # 82, and the server therefore also retransmit # 83 and # 84.

If you check the time of  the first retransmission (448.515709 ,  448.573592) then this is very fast (looks like 0.06 seconds, or the time is somehow different from my experience). With that, maybe you check the initial dtls retransmission timeout?

**Comment by efra-mx-aqua** [comment] 2022-08-22 15:38
Yes, but i mean #85, #87, #89. They cannot be decrypted and I wonder why

The trasnmission timout are set as zephyrs defaults, so it goes up to 60 secs

**Comment by boaks** [comment] 2022-08-22 15:59
I run DTLS interoperability tests now for more than 2 years, including openssl, mbedtls, tinydtls, and gnutls.
I'm not aware of an issue of mbedtls.

> They cannot be decrypted and I wonder why

I don't know, if they can not be decrypted, or if the [Finish verify_data](https://www.rfc-editor.org/rfc/rfc5246#section-7.4.9) fails. If it's the second, then the server includes accidentally the retransmitted handshake messages in the `verify_data`.

> The trasnmission timout are set as zephyrs defaults, so it goes up to 60 secs

The question is more the initial timeout. And for me the capture shows, that these are very short (0.06s, the default according RFC6347 is 1s).

**Comment by boaks** [comment] 2022-08-22 17:37
I found [TLS_DTLS_HANDSHAKE_TIMEOUT_MIN](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/1.9.1/zephyr/reference/networking/sockets.html#c.TLS_DTLS_HANDSHAKE_TIMEOUT_MIN), which is in milliseconds.

Do you use that?

**Comment by boaks** [comment] 2022-08-23 06:25
For me this looks like somehow a 60 is passed accidentally in as [TLS_DTLS_HANDSHAKE_TIMEOUT_MIN](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/1.9.1/zephyr/reference/networking/sockets.html#c.TLS_DTLS_HANDSHAKE_TIMEOUT_MIN) and that seems for me to be the cause to use fast retransmissions. With a buggy server that's fatal.

So, if possible, just read out that socket option value (maybe together with the MAX), and we will see, if it's 1000ms or 60ms.

**Comment by efra-mx-aqua** [comment] 2022-08-23 09:26
> I found [TLS_DTLS_HANDSHAKE_TIMEOUT_MIN](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/1.9.1/zephyr/reference/networking/sockets.html#c.TLS_DTLS_HANDSHAKE_TIMEOUT_MIN), which is in milliseconds.
>
> Do you use that?

The minimum timeout used is 1000 ms, and I can see in the `net_ppp` layer, that the message are being sent without delay. Nevertheless I must look deeper into the modem driver to see if there is something that causes that behaviour

**Comment by boaks** [comment] 2022-09-01 17:19
Any  update about the fast retransmission?
One idea, but just an idea: if the 60ms initial timeout is somehow caused by a accidentally converted 60000 ms maximum timeout to "60", then a 1000*1000ms (=> "1000000") as maximum timeout would result in "1000" initial timeout. Just a wild guess. This doesn't really solve the issue, but may limit the scope to consider.

**Comment by carlescufi** [comment] 2022-09-21 09:09
@efra-mx-aqua can you please reply to the questions from @boaks so we can continue the analysis.

**Comment by efra-mx-aqua** [comment] 2022-09-28 09:57
@carlescufi @boaks After doing analysis with the server we found that:

* Our Server, based on bouncy castle DTLS (.NET) is not compliant with the handshake re-transmission.
* Increasing the timeout to 12 seconds solved out issue
* Stating with a small timeout (1 sec.) was triggering a FATAL alert due two concurrent handshakes.

I apologize for the late reply. 
Tank you for the support

**Comment by rlubos** [comment] 2022-09-28 09:59
@efra-mx-aqua Thank you for the update. Does that mean we can close the issue then?

**Comment by carlescufi** [comment] 2022-09-29 14:50
Closing based on reporter's feedback.

**Closed by carlescufi** 2022-09-29 14:50 UTC
Labels: bug, priority: low, area: Networking
